Repository DEFRA/water-abstraction-system, pull requests merged in 2022-12, with the labels that each got.

#40 Fix tests for new dev environment
  test/services/service-status.service.test.js
Labels: housekeeping

#41 Amend the supplementary charge version query
  app/presenters/supplementary.presenter.js
  app/services/supplementary-billing/fetch-charge-versions.service.js
  app/services/supplementary-billing/supplementary.service.js
  db/migrations/20221206084612_alter_charge_versions.js
  test/presenters/supplementary.presenter.test.js
  test/services/supplementary-billing/fetch-charge-versions.service.test.js
  test/support/helpers/charge-version.helper.js
Labels: enhancement

#44 Fix Objection model relations
  app/models/charge-version.model.js
  app/models/licence.model.js
  app/models/region.model.js
  test/models/charge-version.model.test.js
  test/models/licence.model.test.js
  test/models/region.model.test.js
Labels: bug

#43 Update licence query to just return SROC
  app/services/supplementary-billing/fetch-licences.service.js
  test/services/supplementary-billing/fetch-licences.service.test.js
  test/support/helpers/charge-version.helper.js
Labels: enhancement

#37 New billing batch record for SROC supplementary bill run
  app/models/billing-batch.model.js
  app/models/region.model.js
  app/services/supplementary-billing/create-billing-batch.service.js
  app/services/supplementary-billing/fetch-charge-versions.service.js
  app/services/supplementary-billing/fetch-licences.service.js
  db/migrations/20221125164859_create_billing_batches.js
  test/models/billing-batch.model.test.js
  test/services/supplementary-billing/create-billing-batch.service.test.js
  test/support/helpers/billing-batch.helper.js
Labels: enhancement

#46 Replacing classes with modules and functions
  app/controllers/health/airbrake.controller.js
  app/controllers/health/database.controller.js
  app/controllers/root.controller.js
  app/controllers/test/supplementary.controller.js
  app/presenters/supplementary.presenter.js
  app/routes/root.routes.js
  app/services/database-health-check.service.js
  app/services/service-status.service.js
  app/services/supplementary-billing/billing-period.service.js
  app/services/supplementary-billing/create-billing-batch.service.js
  app/services/supplementary-billing/fetch-charge-versions.service.js
  app/services/supplementary-billing/fetch-licences.service.js
  app/services/supplementary-billing/fetch-region.service.js
  app/services/supplementary-billing/supplementary.service.js
  test/presenters/supplementary.presenter.test.js
  test/services/supplementary-billing/billing-period.service.test.js
  test/support/helpers/charge-version.helper.js
  test/support/helpers/database.helper.js
  test/support/helpers/licence.helper.js
  test/support/helpers/region.helper.js
Labels: housekeeping

#48 Replacing classes with modules and functions Pt.2
  app/services/plugins/filter-routes.service.js
  app/services/plugins/hapi-pino-ignore-request.service.js
  test/services/service-status.service.test.js
  test/support/helpers/billing-batch.helper.js
Labels: housekeeping

#49 Refactor Hapi-pino logger to clean things up
  app/plugins/hapi-pino.plugin.js
  app/server.js
  app/services/plugins/hapi-pino-ignore-request.service.js
  app/services/plugins/hapi-pino-log-in-test.service.js
  test/services/plugins/hapi-pino-ignore-request.service.test.js
  test/services/plugins/hapi-pino-log-in-test.service.test.js
Labels: housekeeping

#45 Create event record for sroc supplementary bill run
  app/models/event.model.js
  app/services/supplementary-billing/create-event.service.js
  db/migrations/20221209193845_create_events.js
  test/models/event.model.test.js
  test/services/supplementary-billing/create-event.service.test.js
  test/support/helpers/event.helper.js
Labels: enhancement

#50 Fix test licences query
  app/services/supplementary-billing/fetch-licences.service.js
  test/services/supplementary-billing/fetch-licences.service.test.js
Labels: bug

#51 Add Create Sroc Bill Run endpoint
  app/controllers/bill-runs.controller.js
  app/plugins/error-pages.plugin.js
  app/plugins/router.plugin.js
  app/routes/bill-runs.routes.js
  app/validators/bill-runs/create-bill-run.validator.js
  package-lock.json
  package.json
  test/controllers/bill-runs.controller.test.js
  test/validators/bill-runs/create-bill-run.validator.js
Labels: enhancement

#53 Add initial generic http request module
  .env.example
  app/lib/request.lib.js
  config/request.config.js
  package-lock.json
  package.json
  test/lib/request.lib.test.js
Labels: enhancement

#54 New charge element model for SROC supplementary bill run
  app/models/charge-element.model.js
  app/models/charge-version.model.js
  db/migrations/20221215174926_create_charge_elements.js
  test/models/charge-element.model.test.js
  test/models/charge-version.model.test.js
  test/support/helpers/charge-element.helper.js
Labels: enhancement

#58 Move /service-status to /health and tidy up
  app/controllers/health/database.controller.js
  app/controllers/health/info.controller.js
  app/controllers/root.controller.js
  app/plugins/router.plugin.js
  app/routes/airbrake.routes.js
  app/routes/assets.routes.js
  app/routes/database.routes.js
  app/routes/health.routes.js
  app/routes/root.routes.js
  app/services/health/database-health-check.service.js
  app/services/health/info.service.js
  app/views/info.njk
  test/controllers/health/info.controller.test.js
  test/services/health/database-health-check.service.test.js
  test/services/health/info.service.test.js
Labels: housekeeping

#57 New charge category model for SROC supplementary bill run
  app/models/billing-charge-category.model.js
  app/models/charge-element.model.js
  db/migrations/20221216112650_create_billing_charge_categories.js
  test/models/billing-charge-category.model.test.js
  test/models/charge-element.model.test.js
  test/support/helpers/billing-charge-category.helper.js
Labels: enhancement

#59 New charge purpose model for SROC supplementary bill run
  app/models/charge-element.model.js
  app/models/charge-purpose.model.js
  db/migrations/20221216154722_create_charge_purposes.js
  test/models/charge-element.model.test.js
  test/models/charge-purpose.model.test.js
  test/support/helpers/charge-purpose.helper.js
Labels: enhancement

#60 Fix issue with error-pages.plugin
  app/plugins/error-pages.plugin.js
  test/plugins/error-pages.plugin.test.js
Labels: bug

#62 Bump major version of @hapi/hoek
  package-lock.json
  package.json
Labels: housekeeping

#61 Fix missing Objection Id columns
  app/models/billing-batch.model.js
  app/models/billing-charge-category.model.js
  app/models/charge-element.model.js
  app/models/charge-purpose.model.js
  app/models/charge-version.model.js
  app/models/event.model.js
  app/models/licence.model.js
  app/models/region.model.js
Labels: bug

#65 Use RequestLib in InfoService
  app/services/health/info.service.js
  test/services/health/info.service.test.js
Labels: housekeeping

#68 Refactor supplementary test code
  app/controllers/check/supplementary.controller.js
  app/plugins/router.plugin.js
  app/presenters/check/supplementary-data.presenter.js
  app/routes/check.routes.js
  app/routes/test.routes.js
  app/services/check/supplementary-data.service.js
  test/controllers/check/supplementary.controller.test.js
  test/presenters/check/supplementary-data.presenter.test.js
  test/services/check/supplementary-data.service.test.js
Labels: housekeeping

#70 Fix objection models
  app/models/base.model.js
  app/models/billing-batch.model.js
  app/models/billing-charge-category.model.js
  app/models/charge-element.model.js
  app/models/charge-purpose.model.js
  app/models/charge-version.model.js
  app/models/event.model.js
  app/models/licence.model.js
  app/models/region.model.js
  test/models/charge-element.model.test.js
  test/models/charge-version.model.test.js
Labels: bug

#72 Update test helpers to use Objection
  app/services/supplementary-billing/create-billing-batch.service.js
  app/services/supplementary-billing/fetch-licences.service.js
  app/services/supplementary-billing/fetch-region.service.js
  test/services/supplementary-billing/fetch-charge-versions.service.test.js
  test/services/supplementary-billing/fetch-licences.service.test.js
  test/services/supplementary-billing/fetch-region.service.test.js
  test/support/helpers/billing-batch.helper.js
  test/support/helpers/billing-charge-category.helper.js
  test/support/helpers/charge-element.helper.js
  test/support/helpers/charge-purpose.helper.js
  test/support/helpers/charge-version.helper.js
  test/support/helpers/event.helper.js
  test/support/helpers/licence.helper.js
  test/support/helpers/region.helper.js
Labels: housekeeping

#66 Implement abstraction period query using Objection
  app/presenters/check/supplementary-data.presenter.js
  app/services/supplementary-billing/fetch-charge-versions.service.js
  test/presenters/check/supplementary-data.presenter.test.js
  test/services/supplementary-billing/fetch-charge-versions.service.test.js
  test/support/helpers/billing-charge-category.helper.js
Labels: enhancement

#71 Improve model tests
  app/models/billing-charge-category.model.js
  app/models/region.model.js
  test/models/billing-batch.model.test.js
  test/models/billing-charge-category.model.test.js
  test/models/charge-element.model.test.js
  test/models/charge-purpose.model.test.js
  test/models/charge-version.model.test.js
  test/models/event.model.test.js
  test/models/licence.model.test.js
  test/models/region.model.test.js
Labels: housekeeping
