Repository DEFRA/water-abstraction-system, pull requests merged in 2022-11, with the labels that each got.

#13 Create test supplementary end point
  app/controllers/test/supplementary.controller.js
  app/plugins/router.plugin.js
  app/routes/test.routes.js
  app/services/test/supplementary.service.js
  test/controllers/test/supplementary.controller.test.js
  test/services/test/supplementary.service.test.js
Labels: enhancement

#14 Replace node-sass with dart-sass package
  bin/build
  bin/build-css
  package-lock.json
  package.json
Labels: bug

#8 Refactoring summary list for each service
  .env.example
  .github/workflows/ci.yml
  app/services/service_status.service.js
  app/views/service_status.njk
  config/services.config.js
  package-lock.json
  package.json
  test/services/service_status.service.test.js
Labels: enhancement

#10 Refactor dotenv require
  config/airbrake.config.js
  config/database.config.js
  config/server.config.js
  config/services.config.js
  config/test.config.js
  index.js
Labels: housekeeping

#16 Filter asset requests from Hapi-pino logs
  .env.example
  app/plugins/hapi_pino.plugin.js
  app/server.js
  app/services/plugins/hapi_pino_ignore_request.service.js
  config/log.config.js
  test/services/plugins/hapi_pino_ignore_request.service.test.js
Labels: housekeeping

#21 Move location where 'dotenv' is being required
  app/server.js
  index.js
Labels: bug

#17 Standardise naming of request object
  app/controllers/health/airbrake.controller.js
  app/controllers/health/database.controller.js
  app/controllers/root.controller.js
  app/controllers/test/supplementary.controller.js
  app/plugins/airbrake.plugin.js
Labels: housekeeping

#22 Create test database migrations
  .github/workflows/ci.yml
  config/database.config.js
  db/create.database.js
  db/migrations/20221108143017_add_pgcrypto_extension.js
  db/migrations/20221108143106_create_update_timestamp_trigger.js
  db/migrations/20221108143943_create-water-schema.js
  db/migrations/20221108152353_create-charge-versions.js
  package.json
Labels: enhancement

#24 Tidy up environment variables
  .env.example
  .github/workflows/ci.yml
Labels: housekeeping

#25 Add unit test DB cleaning
  test/support/helpers/database.helper.js
Labels: housekeeping

#15 Fetching the charge versions data
  app/controllers/test/supplementary.controller.js
  app/routes/test.routes.js
  app/services/test/supplementary.service.js
  test/controllers/test/supplementary.controller.test.js
  test/services/test/supplementary.service.test.js
  test/support/helpers/charge_version.helper.js
Labels: enhancement

#27 Select SROC supplementary charge versions for real
  app/controllers/test/supplementary.controller.js
  app/services/test/find_region.service.js
  app/services/test/supplementary.service.js
  db/migrations/20221111155222_create_licences.js
  db/migrations/20221111184905_alter_charge_versions.js
  db/migrations/20221114104700_create_regions.js
  db/migrations/20221114155444_alter_licences.js
  test/controllers/test/supplementary.controller.test.js
  test/services/test/supplementary.service.test.js
  test/support/helpers/charge_version.helper.js
  test/support/helpers/database.helper.js
  test/support/helpers/licence.helper.js
  test/support/helpers/region.helper.js
Labels: enhancement

#28 Remove node-sass from dependencies
  package-lock.json
  package.json
Labels: housekeeping

#33 Bump major version of @hapi/hapi
  package-lock.json
  package.json
Labels: housekeeping

#34 Implement objection in water-abstraction-system
  app/models/base.model.js
  app/models/charge_version.model.js
  app/models/licence.model.js
  app/models/region.model.js
  test/models/charge_version.model.test.js
  test/models/licence.model.test.js
  test/models/region.model.test.js
Labels: enhancement

#32 Refactor Supplementary output to test presenter
  app/presenters/supplementary.presenter.js
  app/services/supplementary_billing/fetch_charge_versions.service.js
  app/services/supplementary_billing/supplementary.service.js
  test/presenters/supplementary.presenter.test.js
  test/services/supplementary_billing/supplementary.service.test.js
Labels: enhancement

#35 General housekeeping
  app/controllers/health/airbrake.controller.js
  app/controllers/health/database.controller.js
  app/controllers/root.controller.js
  app/controllers/test/supplementary.controller.js
  app/lib/base-notifier.lib.js
  app/lib/boom-notifier.lib.js
  app/lib/request-notifier.lib.js
  app/models/base.model.js
  app/models/charge-version.model.js
  app/models/licence.model.js
  app/models/region.model.js
  app/plugins/airbrake.plugin.js
  app/plugins/error-pages.plugin.js
  app/plugins/hapi-pino.plugin.js
  app/plugins/request-notifier.plugin.js
  app/plugins/router.plugin.js
  app/plugins/views.plugin.js
  app/presenters/supplementary.presenter.js
  app/routes/test.routes.js
  app/server.js
  app/services/database-health-check.service.js
  app/services/plugins/filter-routes.service.js
  app/services/plugins/hapi-pino-ignore-request.service.js
  app/services/service-status.service.js
  app/services/supplementary-billing/billing-period.service.js
  app/services/supplementary-billing/fetch-charge-versions.service.js
  app/services/supplementary-billing/find-region.service.js
  app/services/supplementary-billing/supplementary.service.js
  config/airbrake.config.js
  config/database.config.js
  config/log.config.js
  config/server.config.js
  config/services.config.js
  test/controllers/health/airbrake.controller.test.js
  test/controllers/health/database.controller.test.js
  test/controllers/root.controller.test.js
  test/controllers/test/supplementary.controller.test.js
  test/lib/base-notifier.lib.test.js
  test/lib/boom-notifier.lib.test.js
  test/lib/request-notifier.lib.test.js
  test/models/charge-version.model.test.js
  test/models/region.model.test.js
  test/services/database-health-check.service.test.js
  test/services/plugins/filter-routes.service.test.js
  test/services/plugins/hapi-pino-ignore-request.service.test.js
  test/services/service-status.service.test.js
  test/services/supplementary-billing/billing-period.service.test.js
  test/services/supplementary-billing/fetch-charge-versions.service.test.js
  test/services/supplementary-billing/supplementary.service.test.js
  test/support/helpers/charge-version.helper.js
  test/support/helpers/licence.helper.js
  test/support/helpers/region.helper.js
Labels: housekeeping

#36 Update licences response in supplementary
  app/controllers/test/supplementary.controller.js
  app/presenters/supplementary.presenter.js
  app/services/supplementary-billing/fetch-licences.service.js
  app/services/supplementary-billing/fetch-region.service.js
  app/services/supplementary-billing/find-region.service.js
  app/services/supplementary-billing/supplementary.service.js
  test/controllers/test/supplementary.controller.test.js
  test/presenters/supplementary.presenter.test.js
  test/services/supplementary-billing/billing-period.service.test.js
  test/services/supplementary-billing/fetch-charge-versions.service.test.js
  test/services/supplementary-billing/fetch-licences.service.test.js
  test/services/supplementary-billing/fetch-region.service.test.js
  test/services/supplementary-billing/supplementary.service.test.js
Labels: enhancement
