Repository DEFRA/water-abstraction-system, pull requests merged in 2022-10, with the labels that each got.

#1 Fix database health check test
  test/controllers/health/database.controller.test.js
  test/services/database_health_check.service.test.js
Labels: testing

#2 Fix sonarcloud test coverage reporting
  sonar-project.properties
Labels: testing

#3 Create `create.database.js` script
  README.md
  db/create.database.js
  package.json
Labels: enhancement

#5 Add .vscode to .gitignore
  .gitignore
Labels: housekeeping

#6 Add pm2 config file
  ecosystem.config.json
Labels: housekeeping

#4 Add views to system
  .gitignore
  app/controllers/root.controller.js
  app/plugins/error_pages.plugin.js
  app/plugins/router.plugin.js
  app/plugins/views.plugin.js
  app/public/static/robots.txt
  app/routes/assets.routes.js
  app/routes/root.routes.js
  app/server.js
  app/views/404.njk
  app/views/500.njk
  app/views/home.njk
  app/views/layout.njk
  bin/build
  bin/build-css
  client/sass/application.scss
  package-lock.json
  package.json
Labels: enhancement
