Repository DEFRA/water-abstraction-system, pull requests merged in 2023-11, with the labels that each got.

#485 Add new format money with commas to presenters
  app/presenters/base.presenter.js
  test/presenters/base.presenter.test.js
Labels: enhancement

#491 Refactor money formatters in base presenter
  app/presenters/base.presenter.js
  app/presenters/data/mock-bill-run.presenter.js
  test/presenters/base.presenter.test.js
Labels: enhancement

#492 Charge periods shown on bills in supplementary billing show all year
  app/presenters/charging-module/create-transaction.presenter.js
  app/services/billing/supplementary/process-billing-period.service.js
  app/services/billing/supplementary/send-transactions.service.js
  test/presenters/charging-module/create-transaction.presenter.test.js
Labels: enhancement

#493 Add new fetch billing account service
  app/models/crm-v2/invoice-account-address.model.js
  app/services/bills/fetch-billing-account.service.js
  test/models/crm-v2/invoice-account-address.model.test.js
  test/services/bills/fetch-billing-account.service.test.js
Labels: enhancement

#495 Add new fetch bill service
  app/services/bills/fetch-bill-service.js
  test/services/bills/fetch-bill.service.test.js
Labels: enhancement

#496 Add new Multi-licence bill presenter
  app/presenters/bills/multi-licence-bill.presenter.js
  app/services/bills/fetch-billing-account.service.js
  test/presenters/bills/multi-licence-bill.presenter.test.js
  test/services/bills/fetch-billing-account.service.test.js
Labels: enhancement

#498 Add new view bill service
  app/services/bills/view-bill.service.js
  test/services/bills/view-bill.service.test.js
Labels: enhancement

#500 Fix missing backlink in view bill page
  app/views/layout.njk
Labels: bug

#502 Amend ChargeReferenceModel for PRESROC
  app/models/water/charge-reference.model.js
  app/models/water/purpose.model.js
  db/migrations/20231104145808_alter-water-charge-elements.js
  test/models/water/charge-reference.model.test.js
  test/models/water/purpose.model.test.js
Labels: housekeeping

#505 Add new Minimum Charge Transaction presenter
  app/presenters/bill-licences/minimum-charge-transaction.presenter.js
  test/presenters/bill-licences/minimum-charge-transaction.presenter.test.js
Labels: enhancement

#506 Add new Compensation Charge Transaction presenter
  app/presenters/bill-licences/compensation-charge-transaction.presenter.js
  test/presenters/bill-licences/compensation-charge-transaction.presenter.test.js
Labels: enhancement

#501 Add new fetch bill licence service
  app/services/bill-licences/fetch-bill-licence.service.js
  test/services/bill-licences/fetch-bill-licence.service.test.js
Labels: enhancement

#508 Add View bill licence presenter
  app/presenters/bill-licences/view-bill-licence.presenter.js
  test/presenters/bill-licences/view-bill-licence.presenter.test.js
Labels: enhancement

#509 Add view bill licence service
  app/services/bill-licences/view-bill-licence.service.js
  test/services/bill-licences/view-bill-licence.service.test.js
Labels: enhancement

#510 Add new view bill licence endpoint and template
  app/controllers/bill-licences.controller.js
  app/plugins/router.plugin.js
  app/routes/bill-licences.routes.js
  app/views/bill-licences/view-presroc.njk
  app/views/bill-licences/view-sroc.njk
  test/controllers/bill-licences.controller.test.js
  test/controllers/bills.controller.test.js
Labels: enhancement

#511 Fix 1st pass issues with bill & bill licence pages
  app/presenters/bills/multi-licence-bill.presenter.js
  app/views/bill-licences/view-presroc.njk
  app/views/bill-licences/view-sroc.njk
  app/views/bills/view.njk
  test/presenters/bills/multi-licence-bill.presenter.test.js
  test/services/bills/view-bill.service.test.js
Labels: bug

#503 Handle create 2PT bill run requests
  app/controllers/bill-runs.controller.js
  app/services/billing/determine-billing-periods.service.js
  app/services/billing/start-bill-run-process.service.js
  app/services/billing/two-part-tariff/process-bill-run.service.js
  app/validators/create-bill-run.validator.js
  test/services/billing/determine-billing-periods.service.test.js
  test/services/billing/two-part-tariff/process-bill-run.service.test.js
  test/validators/create-bill-run.validator.test.js
Labels: enhancement

#504 Linking 2PT SROC review page
  app/controllers/bill-runs.controller.js
  app/routes/bill-runs.routes.js
  app/views/bill-runs/view.njk
  test/controllers/bill-runs.controller.test.js
Labels: enhancement

#513 Split MultiLicencePresenter into 2 new ones
  app/presenters/bills/bill.presenter.js
  app/presenters/bills/licence-summaries.presenter.js
  app/services/bills/view-bill.service.js
  test/presenters/bills/bill.presenter.test.js
  test/presenters/bills/licence-summaries.presenter.test.js
Labels: housekeeping

#514 Add new single licence bill templates
  app/controllers/bills.controller.js
  app/services/bills/view-bill.service.js
  app/views/bills/view-multi-licence.njk
  app/views/bills/view-single-licence-presroc.njk
  app/views/bills/view-single-licence-sroc.njk
  test/controllers/bills.controller.test.js
  test/services/bills/view-bill.service.test.js
Labels: enhancement

#515 Rename Invoice Account to Billing Account
  app/models/crm-v2/address.model.js
  app/models/crm-v2/billing-account-address.model.js
  app/models/crm-v2/billing-account.model.js
  app/models/crm-v2/company.model.js
  app/models/crm-v2/contact.model.js
  app/presenters/bills/bill.presenter.js
  app/presenters/charging-module/create-customer-change.presenter.js
  app/services/billing-accounts/change-address.service.js
  app/services/billing-accounts/send-customer-change.service.js
  app/services/billing/supplementary/fetch-billing-accounts.service.js
  app/services/billing/supplementary/generate-bill.service.js
  app/services/billing/supplementary/pre-generate-billing-data.service.js
  app/services/billing/supplementary/process-transactions.service.js
  app/services/bills/fetch-billing-account.service.js
  test/controllers/billing-accounts.controller.test.js
  test/models/crm-v2/address.model.test.js
  test/models/crm-v2/billing-account-address.model.test.js
  test/models/crm-v2/billing-account.model.test.js
  test/models/crm-v2/company.model.test.js
  test/models/crm-v2/contact.model.test.js
  test/presenters/bills/bill.presenter.test.js
  test/presenters/charging-module/create-customer-change.presenter.test.js
  test/services/billing-accounts/change-address.service.test.js
  test/services/billing-accounts/send-customer-change.service.test.js
  test/services/billing/supplementary/fetch-billing-accounts.service.test.js
  test/services/billing/supplementary/fetch-invoice-account-numbers.service.test.js
  test/services/billing/supplementary/fetch-previous-transactions.service.test.js
  test/services/billing/supplementary/generate-bill.service.test.js
  test/services/billing/supplementary/pre-generate-billing-data.service.test.js
  test/services/billing/supplementary/process-billing-period.service.test.js
  test/services/bills/fetch-billing-account.service.test.js
  test/support/helpers/crm-v2/billing-account-address.helper.js
  test/support/helpers/crm-v2/billing-account.helper.js
  test/support/helpers/water/bill.helper.js
Labels: housekeeping

#520 Fix Airbrake when behind a proxy
  app/plugins/airbrake.plugin.js
  package-lock.json
  package.json
Labels: bug

#522 Fix display of credit transactions in bill views
  app/presenters/base.presenter.js
  app/presenters/bill-licences/view-bill-licence.presenter.js
  app/presenters/bills/bill.presenter.js
  app/presenters/bills/licence-summaries.presenter.js
  client/sass/application.scss
  test/presenters/base.presenter.test.js
  test/presenters/bill-licences/view-bill-licence.presenter.test.js
  test/presenters/bills/bill.presenter.test.js
  test/presenters/bills/licence-summaries.presenter.test.js
Labels: bug

#523 Fix display of financial year in new bill views
  app/presenters/bills/bill.presenter.js
  app/services/bills/fetch-bill-service.js
  test/presenters/bills/bill.presenter.test.js
Labels: bug

#524 Fix bill total in single licence bill page
  app/presenters/bill-licences/view-bill-licence.presenter.js
  app/presenters/bills/bill.presenter.js
  app/views/bill-licences/view-presroc.njk
  app/views/bill-licences/view-sroc.njk
  app/views/bills/view-multi-licence.njk
  app/views/bills/view-single-licence-presroc.njk
  app/views/bills/view-single-licence-sroc.njk
  test/presenters/bill-licences/view-bill-licence.presenter.test.js
  test/presenters/bills/bill.presenter.test.js
Labels: bug

#525 Fix bill total wrapping when a credit
  app/views/bills/view-multi-licence.njk
  app/views/bills/view-single-licence-presroc.njk
  app/views/bills/view-single-licence-sroc.njk
Labels: bug

#521 Remove reporting from /health/info
  .env.example
  app/lib/legacy-request.lib.js
  app/services/health/info.service.js
  config/services.config.js
  test/services/health/info.service.test.js
Labels: housekeeping

#526 Rename custom SCSS class
  app/views/bill-licences/view-presroc.njk
  app/views/bill-licences/view-sroc.njk
  app/views/bills/view-single-licence-presroc.njk
  app/views/bills/view-single-licence-sroc.njk
  client/sass/application.scss
Labels: housekeeping

#529 Refactor existing service to create a new one
  app/services/bill-runs/determine-abstraction-periods.service.js
  app/services/bill-runs/supplementary/calculate-authorised-and-billable-days.service.js
  test/services/bill-runs/determine-abstraction-periods.service.test.js
Labels: enhancement

#531 Make migrations work for real and in test
  .github/workflows/ci.yml
  db/migrations/legacy/20221108143017_add-pgcrypto-extension.js
  db/migrations/legacy/20221108143106_create-update-timestamp-trigger.js
  db/migrations/legacy/20221108143943_create-water-schema.js
  db/migrations/legacy/20221108152353_create-water-charge-versions.js
  db/migrations/legacy/20221111155222_create-water-licences.js
  db/migrations/legacy/20221114104700_create-water-regions.js
  db/migrations/legacy/20221125164859_create-water-billing-batches.js
  db/migrations/legacy/20221209193845_create-water-events.js
  db/migrations/legacy/20221215174926_create-water-charge-elements.js
  db/migrations/legacy/20221216112650_create-water-billing-charge-categories.js
  db/migrations/legacy/20221216154722_create-water-charge-purposes.js
  db/migrations/legacy/20230111152047_alter-water-billing-batches.js
  db/migrations/legacy/20230111160155_create-water-billing-invoices.js
  db/migrations/legacy/20230111160251_create-water-billing-invoice-licences.js
  db/migrations/legacy/20230113180624_alter-water-events.js
  db/migrations/legacy/20230131152030_alter-water-billing-batches.js
  db/migrations/legacy/20230206172349_alter-charge-elements.js
  db/migrations/legacy/20230221135143_create-crm-v2-schema.js
  db/migrations/legacy/20230221140243_create-crm-v2-invoice-accounts.js
  db/migrations/legacy/20230221161454_alter-water-billing-invoices.js
  db/migrations/legacy/20230223124044_alter-water-charge-versions.js
  db/migrations/legacy/20230302110453_create-water-change-reasons.js
  db/migrations/legacy/20230302110745_alter-water-charge-versions.js
  db/migrations/legacy/20230302114546_create-water-billing-transactions.js
  db/migrations/legacy/20230302143311_alter-water-licences.js
  db/migrations/legacy/20230310181716_alter-charge-versions.js
  db/migrations/legacy/20230327095020_create-charge-version-workflows.js
  db/migrations/legacy/20230327211801_alter-licences.js
  db/migrations/legacy/20230802134043_create-returns-schema.js
  db/migrations/legacy/20230802134153_create-returns-returns.js
  db/migrations/legacy/20230803160405_create-water-purposes-uses.js
  db/migrations/legacy/20230818154709_create-crm-v2-addresses.js
  db/migrations/legacy/20230818155314_create-crm-v2-invoice-account-addressses.js
  db/migrations/legacy/20230820170600_create-crm-v2-contacts.js
  db/migrations/legacy/20230821082826_create-crm-v2-companies.js
  db/migrations/legacy/20230823150507_create-idm-schema.js
  db/migrations/legacy/20230823150600_create-idm-users.js
  db/migrations/legacy/20230824092452_create-idm-group-roles.js
  db/migrations/legacy/20230824092657_create-idm-groups.js
  db/migrations/legacy/20230824092939_create-idm-roles.js
  db/migrations/legacy/20230824093122_create-idm-user-groups.js
  db/migrations/legacy/20230824142221_create-idm-user-roles.js
  db/migrations/legacy/20230904125928_alter-crm-v2-addresses.js
  db/migrations/legacy/20230904140538_alter-crm-v2-companies.js
  db/migrations/legacy/20230904140845_alter-crm-v2-invoice-account-addresses.js
  db/migrations/legacy/20230905132524_create-returns-lines.js
  db/migrations/legacy/20230905134836_create-returns-versions.js
  db/migrations/legacy/20230929085159_create-water-billing-volumes.js
  db/migrations/legacy/20231009155523_create-water-licence-versions.js
  db/migrations/legacy/20231104145808_alter-water-charge-elements.js
  db/migrations/public/20231120122556_create-form-logs-view.js
  db/migrations/public/20231120140419_create-return-submissions-view.js
  db/migrations/public/20231120141532_create-return-submission-lines.js
  knexfile.js
  package.json
Labels: housekeeping

#532 Rename `package.json` migration scripts
  .github/workflows/ci.yml
  package.json
Labels: housekeeping

#536 Rename billing presenters to bill-runs
  app/presenters/bill-runs/create-bill-run-event.presenter.js
  app/presenters/bill-runs/create-bill-run.presenter.js
  app/services/bill-runs/create-bill-run-event.service.js
  app/services/bill-runs/start-bill-run-process.service.js
  test/presenters/bill-runs/create-bill-run-event.presenter.test.js
  test/presenters/bill-runs/create-bill-run.presenter.test.js
Labels: housekeeping

#538 Rename bill presenters to match convention
  app/presenters/bill-licences/view-bill-licence.presenter.js
  app/presenters/bill-licences/view-compensation-charge-transaction.presenter.js
  app/presenters/bill-licences/view-minimum-charge-transaction.presenter.js
  app/presenters/bill-licences/view-standard-charge-transaction.presenter.js
  app/presenters/bills/view-bill.presenter.js
  app/presenters/bills/view-licence-summaries.presenter.js
  app/services/bills/view-bill.service.js
  test/presenters/bill-licences/view-bill-licence.presenter.test.js
  test/presenters/bill-licences/view-compensation-charge-transaction.presenter.test.js
  test/presenters/bill-licences/view-minimum-charge-transaction.presenter.test.js
  test/presenters/bill-licences/view-standard-charge-transaction.presenter.test.js
  test/presenters/bills/view-bill.presenter.test.js
  test/presenters/bills/view-licence-summaries.presenter.test.js
  test/services/bills/view-bill.service.test.js
Labels: housekeeping

#545 Rename existing bill-runs template to review.njk
  app/controllers/bill-runs.controller.js
  app/views/bill-runs/review.njk
Labels: housekeeping

#533 Build models for `returns` based on new Views
  app/models/return-log.model.js
  app/models/return-submission-line.model.js
  app/models/return-submission.model.js
  db/migrations/legacy/20231122181918_add-defaults-to-returns-table.js
  db/migrations/legacy/20231122183613_add-defaults-to-lines-table.js
  db/migrations/public/20231120122556_create-return-logs-view.js
  db/migrations/public/20231120140419_create-return-submissions-view.js
  test/models/return-log.model.test.js
  test/models/return-submission-line.model.test.js
  test/models/return-submission.model.test.js
  test/support/helpers/return-log.helper.js
  test/support/helpers/return-submission-line.helper.js
  test/support/helpers/return-submission.helper.js
Labels: housekeeping

#540 Remove back-link nunjucks includes
  app/views/includes/back-link.njk
Labels: housekeeping

#537 Add fetch bill run service for new view bill run page
  app/services/bill-runs/fetch-bill-run.service.js
  test/services/bill-runs/fetch-bill-run.service.test.js
Labels: enhancement

#539 Remove home.template
  app/views/home.njk
Labels: housekeeping

#547 Create `fetch-returns-for-licence` service
  app/services/bill-runs/two-part-tariff/fetch-returns-for-licence.service.js
  test/services/bill-runs/two-part-tariff/fetch-returns-for-licence.service.test.js
Labels: enhancement

#541 Add new view bill run presenter
  app/presenters/bill-runs/view-bill-run.presenter.js
  test/presenters/bill-runs/view-bill-run.presenter.test.js
Labels: enhancement

#548 Adding a periods overlap helper
  app/lib/general.lib.js
  test/lib/general.lib.test.js
Labels: enhancement

#556 Create `crm_v2` schema views
  db/migrations/public/20231128140249_create-billing-accounts-view.js
  db/migrations/public/20231128141428_create-billing-account-addresses-view.js
  db/migrations/public/20231128142558_create-addresses-view.js
  db/migrations/public/20231128143653_create-companies-view.js
  db/migrations/public/20231128143937_create-contacts-view.js
Labels: housekeeping
