Repository DEFRA/water-abstraction-system, pull requests merged in 2023-12, with the labels that each got.

#558 Fix billing acc. address error when town is empty
  app/presenters/charging-module/create-customer-change.presenter.js
  test/presenters/charging-module/create-customer-change.presenter.test.js
Labels: bug

#562 Use absolute paths for relations in legacy models
  app/models/legacy-base.model.js
Labels: bug

#563 Create `idm` schema models and helpers
  app/models/group-role.model.js
  app/models/group.model.js
  app/models/role.model.js
  app/models/user-group.model.js
  app/models/user-role.model.js
  app/models/user.model.js
  test/models/group-role.model.test.js
  test/models/group.model.test.js
  test/models/role.model.test.js
  test/models/user-group.model.test.js
  test/models/user-role.model.test.js
  test/models/user.model.test.js
  test/support/helpers/group-role.helper.js
  test/support/helpers/group.helper.js
  test/support/helpers/role.helper.js
  test/support/helpers/user-group.helper.js
  test/support/helpers/user-role.helper.js
  test/support/helpers/user.helper.js
Labels: housekeeping

#565 Refactor to use new view based IDM models
  app/models/idm/group-role.model.js
  app/models/idm/group.model.js
  app/models/idm/idm-base.model.js
  app/models/idm/role.model.js
  app/models/idm/user-group.model.js
  app/models/idm/user-role.model.js
  app/models/idm/user.model.js
  app/services/idm/fetch-user-roles-and-groups.service.js
  test/models/idm/group-role.model.test.js
  test/models/idm/group.model.test.js
  test/models/idm/role.model.test.js
  test/models/idm/user-group.model.test.js
  test/models/idm/user-role.model.test.js
  test/models/idm/user.model.test.js
  test/services/idm/fetch-user-roles-and-groups.service.test.js
  test/support/helpers/idm/group-role.helper.js
  test/support/helpers/idm/group.helper.js
  test/support/helpers/idm/role.helper.js
  test/support/helpers/idm/user-group.helper.js
  test/support/helpers/idm/user-role.helper.js
  test/support/helpers/idm/user.helper.js
Labels: housekeeping

#560 Create `water` schema models & helpers
  app/models/bill-licence.model.js
  app/models/bill-run-volume.model.js
  app/models/bill-run.model.js
  app/models/bill.model.js
  app/models/change-reason.model.js
  app/models/charge-category.model.js
  app/models/charge-element.model.js
  app/models/charge-reference.model.js
  app/models/charge-version.model.js
  app/models/event.model.js
  app/models/licence-version.model.js
  app/models/licence.model.js
  app/models/purpose.model.js
  app/models/region.model.js
  app/models/transaction.model.js
  app/models/workflow.model.js
  db/migrations/public/20231127202549_create-bill-run-volumes-view.js
  test/models/bill-licence.model.test.js
  test/models/bill-run-volume.model.test.js
  test/models/bill-run.model.test.js
  test/models/bill.model.test.js
  test/models/change-reason.model.test.js
  test/models/charge-category.model.test.js
  test/models/charge-element.model.test.js
  test/models/charge-reference.model.test.js
  test/models/charge-version.model.test.js
  test/models/event.model.test.js
  test/models/licence-version.model.test.js
  test/models/licence.model.test.js
  test/models/purpose.model.test.js
  test/models/region.model.test.js
  test/models/transaction.model.test.js
  test/models/workflow.model.test.js
  test/support/helpers/bill-licence.helper.js
  test/support/helpers/bill-run-volume.helper.js
  test/support/helpers/bill-run.helper.js
  test/support/helpers/bill.helper.js
  test/support/helpers/change-reason.helper.js
  test/support/helpers/charge-category.helper.js
  test/support/helpers/charge-element.helper.js
  test/support/helpers/charge-reference.helper.js
  test/support/helpers/charge-version.helper.js
  test/support/helpers/event.helper.js
  test/support/helpers/licence-version.helper.js
  test/support/helpers/licence.helper.js
  test/support/helpers/purpose.helper.js
  test/support/helpers/region.helper.js
  test/support/helpers/transaction.helper.js
  test/support/helpers/workflow.helper.js
Labels: housekeeping

#566 Refactor to use new view based CRM_V2 models
  app/models/crm-v2/address.model.js
  app/models/crm-v2/billing-account-address.model.js
  app/models/crm-v2/billing-account.model.js
  app/models/crm-v2/company.model.js
  app/models/crm-v2/contact.model.js
  app/models/crm-v2/crm-v2-base.model.js
  app/presenters/bills/view-bill.presenter.js
  app/presenters/charging-module/create-customer-change.presenter.js
  app/services/bill-runs/supplementary/fetch-billing-accounts.service.js
  app/services/bill-runs/supplementary/generate-bill.service.js
  app/services/bill-runs/supplementary/pre-generate-billing-data.service.js
  app/services/billing-accounts/change-address.service.js
  app/services/bills/fetch-billing-account.service.js
  test/models/crm-v2/address.model.test.js
  test/models/crm-v2/billing-account-address.model.test.js
  test/models/crm-v2/billing-account.model.test.js
  test/models/crm-v2/company.model.test.js
  test/models/crm-v2/contact.model.test.js
  test/presenters/bills/view-bill.presenter.test.js
  test/presenters/charging-module/create-customer-change.presenter.test.js
  test/services/bill-runs/fetch-bill-run.service.test.js
  test/services/bill-runs/supplementary/fetch-billing-accounts.service.test.js
  test/services/bill-runs/supplementary/fetch-previous-transactions.service.test.js
  test/services/bill-runs/supplementary/generate-bill.service.test.js
  test/services/bill-runs/supplementary/pre-generate-billing-data.service.test.js
  test/services/bill-runs/supplementary/process-billing-period.service.test.js
  test/services/billing-accounts/change-address.service.test.js
  test/services/bills/fetch-billing-account.service.test.js
  test/support/helpers/bill.helper.js
  test/support/helpers/crm-v2/address.helper.js
  test/support/helpers/crm-v2/billing-account-address.helper.js
  test/support/helpers/crm-v2/billing-account.helper.js
  test/support/helpers/crm-v2/company.helper.js
  test/support/helpers/crm-v2/contact.helper.js
  test/support/helpers/water/bill.helper.js
Labels: housekeeping

#568 Refactor to use new view based RETURNS models
  app/models/legacy-base.model.js
  app/models/returns/line.model.js
  app/models/returns/return.model.js
  app/models/returns/returns-base.model.js
  app/models/returns/version.model.js
  app/services/bill-runs/two-part-tariff/fetch-return-logs-for-licence.service.js
  app/services/check/allocate-returns-volumes.service.js
  app/services/check/calculate-returns-volumes.service.js
  app/services/check/friendly-response.service.js
  app/services/check/two-part.service.js
  test/models/returns/line.model.test.js
  test/models/returns/return.model.test.js
  test/models/returns/version.model.test.js
  test/services/bill-runs/two-part-tariff/fetch-return-logs-for-licence.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-returns-for-licence.service.test.js
  test/support/helpers/returns/line.helper.js
  test/support/helpers/returns/return.helper.js
  test/support/helpers/returns/version.helper.js
Labels: housekeeping

#575 Remove mock data endpoint
  app/controllers/data.controller.js
  app/presenters/data/mock-bill-run.presenter.js
  app/routes/data.routes.js
  app/services/data/mock/generate-bill-run.service.js
  app/services/data/mock/generate-mock-data.service.js
  app/services/data/mock/generate-returns-review.service.js
  app/services/data/mock/mock.service.js
  test/controllers/data.controller.test.js
  test/presenters/data/mock-bill-run.presenter.test.js
  test/services/data/mock/generate-bill-run.service.test.js
  test/services/data/mock/generate-mock-data.service.test.js
  test/services/data/mock/mock.service.test.js
Labels: housekeeping

#574 Add Select the start date (return requirements)
  app/controllers/licences.controller.js
  app/plugins/router.plugin.js
  app/routes/licence.routes.js
  app/views/return-requirements/select-return-start-date.njk
  test/controllers/licences.controller.test.js
Labels: enhancement

#573 Add no returns required page (return requirements)
  app/controllers/licences.controller.js
  app/views/return-requirements/no-returns-required.njk
  test/controllers/licences.controller.test.js
Labels: enhancement

#581 Return `aggregate` as a float
  app/services/bill-runs/two-part-tariff/fetch-charge-versions.service.js
Labels: bug

#580 Add requirements approved page (return requirements)
  app/controllers/licences.controller.js
  app/routes/licence.routes.js
  app/views/return-requirements/requirements-approved.njk
  test/controllers/licences.controller.test.js
Labels: enhancement

#577 Create `fetch-licences` service
  app/services/bill-runs/two-part-tariff/fetch-licences.service.js
  test/services/bill-runs/two-part-tariff/fetch-licences.service.test.js
Labels: enhancement

#587 Add new page for add a note
  app/controllers/licences.controller.js
  app/routes/licence.routes.js
  app/views/return-requirements/add-a-note.njk
  test/controllers/licences.controller.test.js
Labels: enhancement

#586 Include volume in FetchChargeVersionsService
  app/services/bill-runs/two-part-tariff/fetch-charge-versions.service.js
  test/services/bill-runs/two-part-tariff/fetch-charge-versions.service.test.js
Labels: housekeeping

#595 Exclude ended licences in two-part tariff matching
  app/services/bill-runs/two-part-tariff/fetch-charge-versions.service.js
  test/services/bill-runs/two-part-tariff/fetch-charge-versions.service.test.js
Labels: housekeeping

#582 Update 2PT check endpoint with alternate changes
  app/controllers/check.controller.js
  app/routes/check.routes.js
  app/services/check/allocate-returns-volumes.service.js
  app/services/check/calculate-returns-volumes.service.js
  app/services/check/determine-issues.service.js
  app/services/check/friendly-response.service.js
  app/services/check/scenario-formatter.service.js
  app/services/check/stand-ins.service.js
  app/services/check/two-part.service.js
Labels: housekeeping

#598 Fix check two-part tariff region endpoint
  app/services/check/two-part.service.js
Labels: bug

#599 Fix missing fields in bill runs view
  db/migrations/public/20231215174532_alter-bill-runs-view.js
Labels: bug

#542 Add new bill summaries presenter
  app/presenters/bill-runs/view-bill-summaries.presenter.js
  test/presenters/bill-runs/view-bill-summaries.presenter.test.js
Labels: enhancement

#543 Add new view bill run service
  app/services/bill-runs/view-bill-run.service.js
  test/services/bill-runs/view-bill-run.service.test.js
Labels: enhancement, do not merge

#544 Add new view bill run endpoint and template
  app/controllers/bill-runs.controller.js
  app/routes/bill-runs.routes.js
  app/views/bill-runs/view.njk
  app/views/bills/view-multi-licence.njk
  app/views/bills/view-single-licence-presroc.njk
  app/views/bills/view-single-licence-sroc.njk
  client/sass/application.scss
  test/controllers/bill-runs.controller.test.js
Labels: enhancement

#601 Add Contact info link to header
  app/plugins/views.plugin.js
  app/views/layout.njk
Labels: enhancement

#602 Amend bill count in bill run view for zero-value
  app/presenters/bill-runs/view-bill-run.presenter.js
  app/services/bill-runs/view-bill-run.service.js
  test/presenters/bill-runs/view-bill-run.presenter.test.js
Labels: enhancement

#605 Add README to models and migrations folders
  app/models/README.md
  db/migrations/README.md
Labels: documentation

#607 Move jobs to an explicit /jobs endpoint
  app/controllers/charge-elements.controller.js
  app/controllers/data.controller.js
  app/controllers/jobs.controller.js
  app/plugins/router.plugin.js
  app/routes/charge-elements.routes.js
  app/routes/data.routes.js
  app/routes/jobs.routes.js
  app/services/jobs/export/compress-schema-folder.service.js
  app/services/jobs/export/convert-to-csv.service.js
  app/services/jobs/export/delete-files.service.js
  app/services/jobs/export/export-table.service.js
  app/services/jobs/export/export.service.js
  app/services/jobs/export/fetch-table-names.service.js
  app/services/jobs/export/fetch-table.service.js
  app/services/jobs/export/schema-export.service.js
  app/services/jobs/export/send-to-s3-bucket.service.js
  app/services/jobs/export/write-table-to-file.service.js
  app/services/jobs/time-limited/fetch-time-limited-licences.service.js
  app/services/jobs/time-limited/process-time-limited-licences.service.js
  test/controllers/data.controller.test.js
  test/controllers/jobs.controller.test.js
  test/services/jobs/export/compress-schema-folder.service.test.js
  test/services/jobs/export/convert-to-csv.service.test.js
  test/services/jobs/export/delete-files.service.test.js
  test/services/jobs/export/export-table.service.test.js
  test/services/jobs/export/export.service.test.js
  test/services/jobs/export/fetch-table-names.service.test.js
  test/services/jobs/export/fetch-table.service.test.js
  test/services/jobs/export/schema-export.service.test.js
  test/services/jobs/export/send-to-s3-bucket.service.test.js
  test/services/jobs/export/write-table-to-file.service.test.js
  test/services/jobs/time-limited/fetch-time-limited-licences.service.test.js
  test/services/jobs/time-limited/process-time-limited-licences.service.test.js
Labels: housekeeping

#162 Speed up `RequestLib` tests
  app/lib/request.lib.js
  test/lib/request.lib.test.js
Labels: housekeeping

#618 Add LicenceDocumentModel from crm_v2.documents
  app/models/licence-document.model.js
  db/migrations/legacy/20231221145235_create-crm-v2-documents.js
  db/migrations/public/20231221144424_create-licence-documents-view.js
  test/models/licence-document.model.test.js
  test/support/helpers/licence-document.helper.js
Labels: enhancement

#589 Prepare licence for allocation service
  app/services/bill-runs/two-part-tariff/prepare-licences-for-allocation.service.js
  test/services/bill-runs/two-part-tariff/prepare-licences-for-allocation.service.test.js
Labels: enhancement
