Repository DEFRA/water-abstraction-system, pull requests merged in 2023-06, with the labels that each got.

#241 Split `ProcessBillingPeriodService` into multiple services
  app/services/supplementary-billing/pre-generate-billing-data.service.js
  app/services/supplementary-billing/process-billing-period.service.js
  app/services/supplementary-billing/send-billing-transactions.service.js
  test/services/supplementary-billing/pre-generate-billing-data.service.test.js
  test/services/supplementary-billing/process-billing-period.service.test.js
  test/services/supplementary-billing/send-billing-transactions.service.test.js
Labels: housekeeping

#228 Multi-Year SROC Supplementary Billing
  app/services/supplementary-billing/fetch-charge-versions.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  app/services/supplementary-billing/unflag-unbilled-licences.service.js
  test/services/supplementary-billing/fetch-charge-versions.service.test.js
  test/services/supplementary-billing/unflag-unbilled-licences.service.test.js
Labels: enhancement

#255 Create new Charging Module services for reissuing
  app/services/charging-module/reissue-invoice.service.js
  app/services/charging-module/view-invoice.service.js
  test/services/charging-module/reissue-invoice.service.test.js
  test/services/charging-module/view-invoice.service.test.js
Labels: enhancement

#258 Fix no credits for REPLACED charge versions
  app/services/supplementary-billing/process-billing-period.service.js
Labels: bug

#266 SROC Supplementary flag not cleared for 'non-chargeable' licence
  app/services/supplementary-billing/fetch-charge-versions.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  test/services/supplementary-billing/fetch-charge-versions.service.test.js
  test/services/supplementary-billing/process-billing-batch.service.test.js
  test/services/supplementary-billing/process-billing-period.service.test.js
Labels: bug

#273 Better handle errors in Notifiers
  app/lib/base-notifier.lib.js
  app/lib/boom-notifier.lib.js
  app/lib/global-notifier.lib.js
  app/lib/request-notifier.lib.js
  app/services/data/tear-down/tear-down.service.js
  app/services/db-export/db-export.service.js
  app/services/db-export/schema-export.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  test/lib/base-notifier.lib.test.js
  test/lib/boom-notifier.lib.test.js
  test/lib/global-notifier.lib.test.js
  test/lib/request-notifier.lib.test.js
  test/services/data/tear-down/tear-down.service.test.js
  test/services/db-export/db-export.service.test.js
  test/services/supplementary-billing/process-billing-batch.service.test.js
Labels: enhancement

#286 Fix -billableDays 4 out of period charge versions
  app/services/supplementary-billing/determine-charge-period.service.js
  app/services/supplementary-billing/process-billing-period.service.js
  test/services/supplementary-billing/determine-charge-period.service.test.js
Labels: bug

#288 Fix tear-down service
  app/services/data/tear-down/water-schema.service.js
Labels: bug
