Repository DEFRA/water-abstraction-system, pull requests merged in 2023-10, with the labels that each got.

#436 Allocate returns volumes to charge elements
  app/services/check/allocate-returns-volumes.service.js
  app/services/check/calculate-returns-volumes.service.js
  app/services/check/friendly-response.service.js
  app/services/check/two-part.service.js
Labels: enhancement

#445 Change where the allocated Return volume is held
  app/services/check/allocate-returns-volumes.service.js
  app/services/check/friendly-response.service.js
Labels: bug

#451 Add capitalize() method to base presenter
  app/presenters/base.presenter.js
  test/presenters/base.presenter.test.js
Labels: enhancement

#452 Make test data helpers more 'unique'
  app/services/billing/supplementary/fetch-charge-versions.service.js
  test/presenters/charging-module/create-transaction.presenter.test.js
  test/services/billing-accounts/change-address.service.test.js
  test/services/billing/fetch-region.service.test.js
  test/services/billing/supplementary/fetch-charge-versions.service.test.js
  test/services/billing/supplementary/fetch-previous-transactions.service.test.js
  test/services/billing/supplementary/generate-transactions.service.test.js
  test/services/data/export/write-table-to-file.service.test.js
  test/services/data/mock/generate-bill-run.service.test.js
  test/support/helpers/crm-v2/address.helper.js
  test/support/helpers/crm-v2/company.helper.js
  test/support/helpers/crm-v2/contact.helper.js
  test/support/helpers/crm-v2/invoice-account-address.helper.js
  test/support/helpers/crm-v2/invoice-account.helper.js
  test/support/helpers/general.helper.js
  test/support/helpers/idm/group-role.helper.js
  test/support/helpers/idm/group.helper.js
  test/support/helpers/idm/role.helper.js
  test/support/helpers/idm/user-group.helper.js
  test/support/helpers/idm/user-role.helper.js
  test/support/helpers/idm/user.helper.js
  test/support/helpers/returns/line.helper.js
  test/support/helpers/returns/return.helper.js
  test/support/helpers/returns/version.helper.js
  test/support/helpers/water/bill-licence.helper.js
  test/support/helpers/water/bill-run.helper.js
  test/support/helpers/water/bill.helper.js
  test/support/helpers/water/charge-category.helper.js
  test/support/helpers/water/charge-element.helper.js
  test/support/helpers/water/charge-reference.helper.js
  test/support/helpers/water/charge-version.helper.js
  test/support/helpers/water/event.helper.js
  test/support/helpers/water/licence.helper.js
  test/support/helpers/water/purpose.helper.js
  test/support/helpers/water/region.helper.js
  test/support/helpers/water/transaction.helper.js
  test/support/helpers/water/workflow.helper.js
Labels: housekeeping

#456 Create migration script, model, helper and unit tests for `licence_versions`
  app/models/water/licence-version.model.js
  app/models/water/licence.model.js
  db/migrations/20231009155523_create-water-licence-versions.js
  test/models/water/licence-version.model.test.js
  test/models/water/licence.model.test.js
  test/support/helpers/water/licence-version.helper.js
Labels: enhancement

#443 Remove licences with charge elements with approaching time limits from billing
  app/controllers/charge-elements.controller.js
  app/plugins/router.plugin.js
  app/routes/charge-elements.routes.js
  app/services/charge-elements/fetch-time-limited-licences.service.js
  app/services/charge-elements/process-time-limited-licences.service.js
  test/controllers/charge-elements.controller.test.js
  test/services/billing/supplementary/calculate-authorised-and-billable-days.service.test.js
  test/services/billing/supplementary/determine-minimum-charge.service.test.js
  test/services/billing/supplementary/generate-transactions.service.test.js
  test/services/charge-elements/fetch-time-limited-licences.service.test.js
  test/services/charge-elements/process-time-limited-licences.service.test.js
  test/services/charging-module/create-bill-run.service.test.js
  test/services/idm/fetch-user-roles-and-groups.service.test.js
Labels: enhancement

#462 Add `system` to new status page
  app/services/health/fetch-system-info.service.js
  app/services/health/info.service.js
  test/services/health/fetch-system-info.service.test.js
  test/services/health/info.service.test.js
Labels: enhancement

#464 Fix and rename Authentication plugin
  app/plugins/auth.plugin.js
  app/server.js
  app/services/plugins/auth.service.js
  test/services/plugins/auth.service.test.js
Labels: bug

#466 Enable and config authentication as default
  app/plugins/auth.plugin.js
  app/routes/assets.routes.js
  app/routes/bill-runs.routes.js
  app/routes/billing-accounts.routes.js
  app/routes/charge-elements.routes.js
  app/routes/check.routes.js
  app/routes/data.routes.js
  app/routes/health.routes.js
  app/routes/root.routes.js
  test/controllers/bill-runs.controller.test.js
  test/controllers/billing-accounts.controller.test.js
  test/plugins/error-pages.plugin.test.js
Labels: enhancement

#473 Add missing links to page footer
  app/views/layout.njk
Labels: housekeeping

#472 Handle unauthorized errors plus return safe codes
  app/services/plugins/error-pages.service.js
  test/plugins/error-pages.plugin.test.js
  test/services/plugins/error-pages.service.test.js
Labels: enhancement

#477 Add auth & user details to view context by default
  app/plugins/views.plugin.js
  app/views/layout.njk
Labels: enhancement

#474 Update page header with user links
  app/routes/health.routes.js
  app/views/layout.njk
Labels: enhancement

#480 Add phase banner to our page layout
  app/views/layout.njk
Labels: enhancement

#486 Add referrer (request source) to global context
  app/plugins/views.plugin.js
  app/views/includes/back-link.njk
Labels: enhancement
