Repository DEFRA/water-abstraction-system, pull requests merged in 2023-09, with the labels that each got.

#397 Update billing-accounts ctrlr to validate request
  app/controllers/billing-accounts.controller.js
  test/controllers/billing-accounts.controller.test.js
Labels: enhancement

#358 Add proxy support to SendToS3BucketService
  app/services/data/export/send-to-s3-bucket.service.js
  package-lock.json
  package.json
Labels: bug

#396 Add new billing accounts send customer change svc
  app/services/billing-accounts/send-customer-change.service.js
  test/services/billing-accounts/send-customer-change.service.test.js
Labels: enhancement

#402 Add Redis info to `health/info` page
  .env.example
  app/services/health/info.service.js
  config/redis.config.js
  package-lock.json
  package.json
  test/services/health/info.service.test.js
Labels: enhancement

#403 Create new presenter to format a date
  app/presenters/base.presenter.js
  test/presenters/base.presenter.test.js
Labels: enhancement

#392 Create `FetchUserRolesAndGroupsService`
  app/models/idm/group-role.model.js
  app/models/idm/group.model.js
  app/models/idm/role.model.js
  app/models/idm/user-group.model.js
  app/models/idm/user-role.model.js
  app/models/idm/user.model.js
  app/models/legacy-base.model.js
  app/services/idm/fetch-user-roles-and-groups.service.js
  test/models/idm/group-role.model.test.js
  test/models/idm/group.model.test.js
  test/models/idm/role.model.test.js
  test/models/idm/user-group.model.test.js
  test/models/idm/user-role.model.test.js
  test/models/idm/user.model.test.js
  test/services/idm/fetch-user-roles-and-groups.service.test.js
Labels: enhancement

#405 Fix missing schema from DatabaseHelper
  test/support/helpers/database.helper.js
Labels: bug

#404 Add missing CRM_V2 table constraints
  db/migrations/20230904125928_alter-crm-v2-addresses.js
  db/migrations/20230904140538_alter-crm-v2-companies.js
  db/migrations/20230904140845_alter-crm-v2-invoice-account-addresses.js
  test/models/crm-v2/address.model.test.js
  test/models/crm-v2/company.model.test.js
  test/models/crm-v2/contact.model.test.js
  test/models/crm-v2/invoice-account-address.model.test.js
  test/models/crm-v2/invoice-account.model.test.js
Labels: housekeeping

#376 Add missing information to `/health/info` page
  app/services/health/fetch-import-jobs.service.js
  app/services/health/info.service.js
  app/views/info.njk
  test/services/health/info.service.test.js
Labels: enhancement

#400 Add new Billing Account change address service
  app/controllers/billing-accounts.controller.js
  app/services/billing-accounts/change-address.service.js
  test/controllers/billing-accounts.controller.test.js
  test/services/billing-accounts/change-address.service.test.js
Labels: enhancement

#351 Create authentication plugin
  .env.example
  .github/workflows/ci.yml
  app/plugins/authentication.plugin.js
  app/server.js
  app/services/idm/fetch-user-roles-and-groups.service.js
  app/services/plugins/authentication.service.js
  config/authentication.config.js
  package-lock.json
  package.json
  test/services/idm/fetch-user-roles-and-groups.service.test.js
  test/services/plugins/authentication.service.test.js
Labels: enhancement

#415 Move UUID generator to single place
  app/lib/general.lib.js
  app/services/billing/supplementary/generate-billing-invoice-licence.service.js
  app/services/billing/supplementary/generate-billing-invoice.service.js
  app/services/billing/supplementary/generate-billing-transactions.service.js
  app/services/billing/supplementary/reissue-invoice.service.js
  app/services/billing/supplementary/reverse-billing-transactions.service.js
  db/seeds/01-users.js
  test/lib/general.lib.test.js
  test/services/billing/supplementary/reissue-invoice.service.test.js
  test/services/billing/supplementary/reissue-invoices.service.test.js
  test/support/helpers/idm/group.helper.js
  test/support/helpers/idm/user-group.helper.js
  test/support/helpers/idm/user-role.helper.js
  test/support/helpers/returns/line.helper.js
  test/support/helpers/returns/version.helper.js
Labels: housekeeping

#410 Add service to calculate volumes for a return
  app/services/check/calculate-returns-volumes.service.js
  app/services/check/friendly-response.service.js
  app/services/check/two-part.service.js
Labels: enhancement

#423 Add support for alias to Legacy Models
  app/models/legacy-base.model.js
  app/models/legacy.query-builder.js
  test/models/legacy.query-builder.test.js
Labels: housekeeping

#431 Upgrade to Node 20
  .github/workflows/ci.yml
  .nvmrc
Labels: housekeeping

#433 Only include return submissions for the billing period
  app/services/check/two-part.service.js
Labels: bug

#434 Tweak data tear-down
  app/services/data/tear-down/crm-schema.service.js
Labels: housekeeping

#440 Add new bill run volume model
  app/models/water/bill-run-volume.model.js
  app/models/water/bill-run.model.js
  app/models/water/charge-reference.model.js
  app/services/data/mock/generate-returns-review.service.js
  app/services/data/mock/mock.service.js
  db/migrations/20230929085159_create-water-billing-volumes.js
  test/models/water/bill-run-volume.model.test.js
  test/models/water/bill-run.model.test.js
  test/models/water/charge-reference.model.test.js
  test/support/helpers/water/bill-run-volume.helper.js
Labels: enhancement
