Repository DEFRA/water-abstraction-system, pull requests merged in 2023-08, with the labels that each got.

#324 Identify Licences for 2 Part Tariff Annual Billing (SROC)
  app/services/check/two-part.service.js
Labels: enhancement

#327 Major version update of packages
  package-lock.json
  package.json
Labels: housekeeping

#328 Match CV data to returns data for 2PT billing
  app/models/legacy-base.model.js
  app/models/returns/return.model.js
  app/models/returns/returns-base.model.js
  app/services/check/two-part.service.js
  db/migrations/20230802134043_create_returns_schema.js
  db/migrations/20230802134153_create_returns_returns.js
  test/models/returns/return.model.test.js
  test/support/helpers/database.helper.js
  test/support/helpers/returns/return.helper.js
Labels: enhancement

#332 Update existing JSONB queries to use whereJsonPath
  app/services/data/tear-down/crm-schema.service.js
  app/services/data/tear-down/idm-schema.service.js
  app/services/data/tear-down/permit-schema.service.js
  app/services/data/tear-down/water-schema.service.js
Labels: housekeeping

#330 Update migrations to follow team convention
  db/migrations/20221108152353_create-water-charge-versions.js
  db/migrations/20221111155222_create-water-licences.js
  db/migrations/20221114104700_create-water-regions.js
  db/migrations/20221125164859_create-water-billing-batches.js
  db/migrations/20221209193845_create-water-events.js
  db/migrations/20221215174926_create-water-charge-elements.js
  db/migrations/20221216112650_create-water-billing-charge-categories.js
  db/migrations/20221216154722_create-water-charge-purposes.js
  db/migrations/20230111152047_alter-water-billing-batches.js
  db/migrations/20230111160155_create-water-billing-invoices.js
  db/migrations/20230111160251_create-water-billing-invoice-licences.js
  db/migrations/20230113180624_alter-water-events.js
  db/migrations/20230131152030_alter-water-billing-batches.js
  db/migrations/20230206172349_alter-charge-elements.js
  db/migrations/20230221140243_create-crm-v2-invoice-accounts.js
  db/migrations/20230221161454_alter-water-billing-invoices.js
  db/migrations/20230223124044_alter-water-charge-versions.js
  db/migrations/20230302110453_create-water-change-reasons.js
  db/migrations/20230302110745_alter-water-charge-versions.js
  db/migrations/20230302114546_create-water-billing-transactions.js
  db/migrations/20230302143311_alter-water-licences.js
  db/migrations/20230310181716_alter-charge-versions.js
  db/migrations/20230327095020_create-charge-version-workflows.js
  db/migrations/20230327211801_alter-licences.js
  db/migrations/20230802134153_create_returns_returns.js
Labels: housekeeping

#336 Fix broken process billing period unit test
  test/services/billing/supplementary/process-billing-period.service.test.js
Labels: bug

#335 Create model for `purposes_uses` table
  app/models/water/charge-purpose.model.js
  app/models/water/purposes-use.model.js
  db/migrations/20230802134043_create-returns-schema.js
  db/migrations/20230802134153_create-returns-returns.js
  db/migrations/20230803160405_create-water-purposes-uses.js
  test/models/water/charge-purpose.model.test.js
  test/models/water/purposes-use.model.test.js
  test/support/helpers/returns/return.helper.js
  test/support/helpers/water/purposes-use.helper.js
Labels: enhancement

#319 Using streams on schema export service
  app/services/data/export/convert-to-csv.service.js
  app/services/data/export/delete-files.service.js
  app/services/data/export/export-data-files.service.js
  app/services/data/export/export-table.service.js
  app/services/data/export/fetch-table.service.js
  app/services/data/export/write-table-to-file.service.js
  package-lock.json
  package.json
  test/services/data/export/convert-to-csv.service.test.js
  test/services/data/export/delete-files.service.test.js
  test/services/data/export/export-data-files.service.test.js
  test/services/data/export/export-table.service.test.js
  test/services/data/export/fetch-table.service.test.js
  test/services/data/export/write-table-to-file.service.test.js
Labels: bug

#337 Add crm_v2 to DatabaseHelper clean() method
  test/support/helpers/database.helper.js
Labels: housekeeping

#334 Match CV data to returns data for 2PT billing pt2
  app/services/check/two-part.service.js
Labels: enhancement

#340 Switch to Charge Version as base for 2PT matching
  app/services/check/two-part.service.js
Labels: housekeeping

#342 Match returns to charge version by purpose type
  app/services/check/two-part.service.js
Labels: enhancement

#343 Include charge category in 2PT matching results
  app/services/check/two-part.service.js
Labels: enhancement

#344 Add friendly formatting to two-part tariff endpoint
  app/controllers/check/check.controller.js
  app/routes/check.routes.js
  app/services/check/two-part.service.js
Labels: enhancement

#346 Add timing to 2PT matching service
  app/services/check/two-part.service.js
Labels: enhancement

#350 Add new data formatters to base presenter
  app/presenters/base.presenter.js
  app/presenters/charging-module/create-transaction.presenter.js
  test/presenters/base.presenter.test.js
Labels: enhancement

#353 TPT testing scenarios fixes
  app/services/check/two-part.service.js
Labels: bug

#347 Create endpoint to generate fake data
  app/controllers/data/data.controller.js
  app/presenters/data/mock-bill-run.presenter.js
  app/routes/data.routes.js
  app/services/data/mock/generate-bill-run.service.js
  app/services/data/mock/generate-mock-data.service.js
  app/services/data/mock/mock.service.js
  app/services/plugins/filter-routes.service.js
  test/controllers/data/data.controller.test.js
  test/presenters/data/mock-bill-run.presenter.test.js
  test/services/data/mock/generate-bill-run.service.test.js
  test/services/data/mock/generate-mock-data.service.test.js
  test/services/data/mock/mock.service.test.js
Labels: enhancement

#354 Add Got retry hook to log when retries happen
  app/lib/request.lib.js
  test/lib/request.lib.test.js
Labels: enhancement

#356 Match returns to chargePurpose
  app/services/check/two-part.service.js
Labels: enhancement

#357 Get Return Status as part of Matching Algorithm
  app/services/check/two-part.service.js
Labels: enhancement

#359 Implement TwoPartService 'friendly' response
  app/controllers/check/check.controller.js
  app/services/check/friendly-response.service.js
  app/services/check/two-part.service.js
Labels: enhancement

#360 Get Return Status as part of Matching Algorithm
  app/services/check/two-part.service.js
Labels: enhancement

#361 Amend 2PT friendly response following changes
  app/services/check/friendly-response.service.js
Labels: housekeeping

#365 Determine returns matching status for licence
  app/services/check/friendly-response.service.js
  app/services/check/two-part.service.js
Labels: enhancement

#368 Refactor controllers out of folders
  app/controllers/bill-runs.controller.js
  app/controllers/check.controller.js
  app/controllers/data.controller.js
  app/controllers/health.controller.js
  app/controllers/health/airbrake.controller.js
  app/controllers/health/database.controller.js
  app/controllers/health/info.controller.js
  app/routes/bill-runs.routes.js
  app/routes/check.routes.js
  app/routes/data.routes.js
  app/routes/health.routes.js
  test/controllers/bill-runs.controller.test.js
  test/controllers/check.controller.test.js
  test/controllers/data.controller.test.js
  test/controllers/health.controller.test.js
  test/controllers/health/airbrake.controller.test.js
  test/controllers/health/database.controller.test.js
  test/controllers/health/info.controller.test.js
Labels: housekeeping

#372 Remove unnecessary async
  app/controllers/root.controller.js
Labels: housekeeping

#375 Add automatic payload cleaning
  app/plugins/payload-cleaner.plugin.js
  app/server.js
  app/services/plugins/payload-cleaning.service.js
  package-lock.json
  package.json
  test/services/plugins/payload-cleaning.service.test.js
Labels: enhancement

#378 Add CRM_V2 address model
  app/models/crm-v2/address.model.js
  db/migrations/20230818154709_create-crm-v2-addresses.js
  test/models/crm-v2/address.model.test.js
  test/support/helpers/crm-v2/address.helper.js
Labels: enhancement

#379 Add CRM_V2 contact model
  app/models/crm-v2/contact.model.js
  db/migrations/20230820170600_create-crm-v2-contacts.js
  test/models/crm-v2/contact.model.test.js
  test/support/helpers/crm-v2/contact.helper.js
Labels: enhancement

#380 Add CRM_V2 company model
  app/models/crm-v2/company.model.js
  db/migrations/20230821082826_create-crm-v2-companies.js
  test/models/crm-v2/company.model.test.js
  test/support/helpers/crm-v2/company.helper.js
Labels: enhancement

#381 Add CRM_V2 invoice account address model
  app/models/crm-v2/invoice-account-address.model.js
  db/migrations/20230818155314_create-crm-v2-invoice-account-addressses.js
  test/models/crm-v2/invoice-account-address.model.test.js
  test/support/helpers/crm-v2/invoice-account-address.helper.js
Labels: enhancement

#382 Add new /billing-accounts endpoint
  app/controllers/billing-accounts.controller.js
  app/plugins/router.plugin.js
  app/routes/billing-accounts.routes.js
  test/controllers/billing-accounts.controller.test.js
Labels: enhancement

#384 Create `idm` migrations for authentication plugin
  db/migrations/20230823150507_create-idm-schema.js
  db/migrations/20230823150600_create-idm-users.js
  db/migrations/20230824092452_create-idm-group-roles.js
  db/migrations/20230824092657_create-idm-groups.js
  db/migrations/20230824092939_create-idm-roles.js
  db/migrations/20230824093122_create-idm-user-groups.js
  db/migrations/20230824142221_create-idm-user-roles.js
Labels: enhancement

#386 Fix `idm-group-roles` migration
  db/migrations/20230824092452_create-idm-group-roles.js
Labels: bug

#385 Update new CRM_V2 models with relationships
  app/models/crm-v2/address.model.js
  app/models/crm-v2/company.model.js
  app/models/crm-v2/contact.model.js
  app/models/crm-v2/invoice-account-address.model.js
  app/models/crm-v2/invoice-account.model.js
  test/models/crm-v2/address.model.test.js
  test/models/crm-v2/company.model.test.js
  test/models/crm-v2/contact.model.test.js
  test/models/crm-v2/invoice-account-address.model.test.js
  test/models/crm-v2/invoice-account.model.test.js
Labels: enhancement

#390 Housekeeping for create bill run validator
  app/controllers/bill-runs.controller.js
  app/validators/create-bill-run.validator.js
  test/validators/create-bill-run.validator.test.js
Labels: housekeeping

#387 Create `group`, `role` and `user` models for authentication plugin
  app/models/idm/group.model.js
  app/models/idm/idm-base.model.js
  app/models/idm/role.model.js
  app/models/idm/user.model.js
  db/migrations/20230823150600_create-idm-users.js
  db/migrations/20230824092939_create-idm-roles.js
  test/models/idm/group.model.test.js
  test/models/idm/role.model.test.js
  test/models/idm/user.model.test.js
  test/support/helpers/idm/group.helper.js
  test/support/helpers/idm/role.helper.js
  test/support/helpers/idm/user.helper.js
Labels: enhancement

#394 Add new CHA create customer change service
  app/services/charging-module/create-customer-change.service.js
  test/services/charging-module/create-customer-change.service.test.js
Labels: enhancement
