Repository DEFRA/water-abstraction-system, pull requests merged in 2023-03, with the labels that each got.

#134 Add change_reason model to water-abstraction-system
  app/models/water/change-reason.model.js
  app/models/water/charge-version.model.js
  db/migrations/20230302110453_create-water-change-reasons.js
  db/migrations/20230302110745_alter-water-charge-versions.js
  test/models/water/change-reason.model.test.js
  test/models/water/charge-version.model.test.js
  test/support/helpers/water/change-reason.helper.js
Labels: enhancement

#135 Add billing_transaction model to water-abstraction-system
  app/models/water/billing-invoice-licence.model.js
  app/models/water/billing-transaction.model.js
  app/models/water/charge-element.model.js
  db/migrations/20230302114546_create-water-billing-transactions.js
  test/models/water/billing-invoice-licence.model.test.js
  test/models/water/billing-transaction.model.test.js
  test/models/water/charge-element.model.test.js
  test/support/helpers/water/billing-transaction.helper.js
Labels: enhancement

#136 Update fetch charge versions service in water-abstraction-system
  app/services/supplementary-billing/fetch-charge-versions.service.js
  db/migrations/20230302143311_alter-water-licences.js
  test/services/supplementary-billing/fetch-charge-versions.service.test.js
  test/support/helpers/water/licence.helper.js
Labels: enhancement

#138 Fix response handling for Charging Module requests
  app/lib/charging-module-request.lib.js
  app/services/charging-module/create-bill-run.service.js
  app/services/health/info.service.js
  app/services/supplementary-billing/initiate-billing-batch.service.js
  test/lib/charging-module-request.lib.test.js
  test/services/charging-module/create-bill-run.service.test.js
  test/services/health/info.service.test.js
  test/services/supplementary-billing/initiate-billing-batch.service.test.js
Labels: bug

#137 Fix missing bill run number in batch
  app/services/supplementary-billing/initiate-billing-batch.service.js
  test/services/supplementary-billing/initiate-billing-batch.service.test.js
Labels: bug

#142 Add PATCH support to our request lib modules
  app/lib/charging-module-request.lib.js
  app/lib/request.lib.js
  test/lib/charging-module-request.lib.test.js
  test/lib/request.lib.test.js
Labels: enhancement

#141 Add Charging Module generate bill run service
  app/services/charging-module/generate-bill-run.service.js
  test/services/charging-module/generate-bill-run.service.test.js
Labels: enhancement

#143 Add LegacyRequestLib
  .env.example
  .github/workflows/ci.yml
  app/lib/charging-module-request.lib.js
  app/lib/legacy-request.lib.js
  app/services/health/info.service.js
  config/services.config.js
  test/lib/legacy-request.lib.test.js
  test/services/health/info.service.test.js
Labels: enhancement

#144 Add Base Presenter module
  app/presenters/base.presenter.js
  test/presenters/base.presenter.test.js
Labels: enhancement

#146 Return PostgreSQL decimals as numbers not strings
  db/db.js
  test/services/supplementary-billing/format-sroc-transaction-line.service.test.js
Labels: bug

#145 Add Charging Module Create Transaction Presenter
  app/presenters/charging-module/create-transaction.presenter.js
  test/presenters/charging-module/create-transaction.presenter.test.js
  test/support/helpers/water/billing-transaction.helper.js
Labels: enhancement

#147 Start processing the billing batch from Initiate
  app/services/supplementary-billing/initiate-billing-batch.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  test/services/supplementary-billing/initiate-billing-batch.service.test.js
  test/services/supplementary-billing/process-billing-batch.service.test.js
Labels: enhancement

#150 Move determineChargePeriod() to a service
  app/services/supplementary-billing/determine-charge-period.service.js
  app/services/supplementary-billing/format-sroc-transaction-line.service.js
  test/services/supplementary-billing/determine-charge-period.service.test.js
Labels: housekeeping

#151 Refactor CreateTransactionsService to persist
  app/services/check/supplementary-data.service.js
  app/services/supplementary-billing/create-billing-transaction.service.js
  app/services/supplementary-billing/create-transactions.service.js
  test/services/supplementary-billing/create-billing-transaction.service.test.js
  test/services/supplementary-billing/create-transactions.service.test.js
Labels: housekeeping

#133 Update Process Batch service for debit only
  app/services/supplementary-billing/create-billing-invoice.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  test/services/supplementary-billing/create-billing-invoice.service.test.js
  test/services/supplementary-billing/process-billing-batch.service.test.js
Labels: enhancement

#155 Fix dupe bill. invoice licence in process service
  app/services/supplementary-billing/create-billing-invoice-licence.service.js
  test/services/supplementary-billing/create-billing-invoice-licence.service.test.js
Labels: bug

#156 Fix error calculating auth. and billable days
  app/services/supplementary-billing/abstraction-billing-period.service.js
  app/services/supplementary-billing/calculate-authorised-and-billable-days.service.js
  app/services/supplementary-billing/format-sroc-transaction-line.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  test/services/supplementary-billing/abstraction-billing-period.service.test.js
  test/services/supplementary-billing/calculate-authorised-and-billable-days.service.test.js
  test/services/supplementary-billing/format-sroc-transaction-line.service.test.js
Labels: bug

#157 Refactor how we create transactions
  app/services/supplementary-billing/format-sroc-transaction-line.service.js
  app/services/supplementary-billing/generate-billing-transactions.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  test/services/supplementary-billing/format-sroc-transaction-line.service.test.js
  test/services/supplementary-billing/generate-billing-transactions.service.test.js
Labels: housekeeping

#153 Handle empty supplementary bill runs
  app/services/supplementary-billing/create-billing-invoice-licence.service.js
  app/services/supplementary-billing/create-billing-invoice.service.js
  app/services/supplementary-billing/fetch-invoice-account.service.js
  app/services/supplementary-billing/generate-billing-invoice-licence.service.js
  app/services/supplementary-billing/generate-billing-invoice.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  test/services/supplementary-billing/create-billing-invoice-licence.service.test.js
  test/services/supplementary-billing/create-billing-invoice.service.test.js
  test/services/supplementary-billing/fetch-invoice-account.service.test.js
  test/services/supplementary-billing/generate-billing-invoice-licence.service.test.js
  test/services/supplementary-billing/generate-billing-invoice.service.test.js
Labels: enhancement

#158 Amend charge versions fetched for SROC supplementary
  app/services/supplementary-billing/fetch-charge-versions.service.js
  db/migrations/20230310181716_alter-charge-versions.js
  test/services/supplementary-billing/fetch-charge-versions.service.test.js
  test/support/helpers/water/charge-version.helper.js
Labels: housekeeping

#161 Handle errors in ProcessBillingBatchService
  app/services/supplementary-billing/handle-errored-billing-batch.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  test/services/supplementary-billing/handle-errored-billing-batch.service.test.js
  test/services/supplementary-billing/process-billing-batch.service.test.js
Labels: enhancement

#163 Log time taken to process a bill run
  app/services/supplementary-billing/process-billing-batch.service.js
  test/services/supplementary-billing/process-billing-batch.service.test.js
Labels: enhancement

#166 Fix cached data in ProcessBillingBatchService
  app/services/supplementary-billing/process-billing-batch.service.js
Labels: bug

#167 Create Reverse Billing Batch Licences service
  app/services/supplementary-billing/fetch-charge-versions.service.js
  app/services/supplementary-billing/fetch-previous-billing-transactions.service.js
  app/services/supplementary-billing/generate-billing-invoice-licence.service.js
  app/services/supplementary-billing/generate-billing-invoice.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  app/services/supplementary-billing/process-billing-transactions.service.js
  app/services/supplementary-billing/reverse-billing-transactions.service.js
  test/services/supplementary-billing/generate-billing-invoice-licence.service.test.js
  test/services/supplementary-billing/generate-billing-invoice.service.test.js
  test/services/supplementary-billing/process-billing-transactions.service.test.js
  test/services/supplementary-billing/reverse-billing-transactions.service.test.js
Labels: enhancement

#176 Licences in Workflow should not be considered
  app/models/water/charge-version-workflow.model.js
  app/models/water/licence.model.js
  app/services/supplementary-billing/fetch-charge-versions.service.js
  db/migrations/20230327095020_create-charge-version-workflows.js
  test/models/water/charge-version-workflow.model.test.js
  test/models/water/licence.model.test.js
  test/services/supplementary-billing/fetch-charge-versions.service.test.js
  test/support/helpers/water/charge-version-workflow.helper.js
Labels: enhancement

#178 Remove FetchLicencesService
  app/presenters/check/supplementary-data.presenter.js
  app/services/check/supplementary-data.service.js
  app/services/supplementary-billing/fetch-licences.service.js
  test/presenters/check/supplementary-data.presenter.test.js
  test/services/check/supplementary-data.service.test.js
  test/services/supplementary-billing/fetch-licences.service.test.js
Labels: housekeeping

#181 Fix no error in logs for process billing batch
  app/services/supplementary-billing/process-billing-batch.service.js
  test/services/supplementary-billing/process-billing-batch.service.test.js
Labels: bug

#174 Handle no charge versions in ProcessBillingBatch
  app/services/supplementary-billing/process-billing-batch.service.js
  test/services/supplementary-billing/process-billing-batch.service.test.js
  test/services/supplementary-billing/process-billing-transactions.service.test.js
Labels: bug
