Repository DEFRA/water-abstraction-system, pull requests merged in 2023-05, with the labels that each got.

#207 Inc. changes to agreements & charges in supp bill
  app/services/supplementary-billing/process-billing-transactions.service.js
  test/services/supplementary-billing/process-billing-transactions.service.test.js
Labels: enhancement

#203 Improve supplementary billing test coverage
  test/services/supplementary-billing/process-billing-batch.service.test.js
Labels: housekeeping

#205 Compress billing-charge-categories export
  app/services/db-export/compress-files.service.js
  app/services/db-export/export-data-files.service.js
  test/fixtures/compress-files.service.csv
  test/services/db-export/compress-files.service.test.js
  test/services/db-export/export-data-files.service.test.js
Labels: enhancement

#210 Fix including unnecessary supp. billing trans.
  app/services/supplementary-billing/fetch-previous-billing-transactions.service.js
  test/support/helpers/water/billing-transaction.helper.js
Labels: bug

#213 Handle soft deleted workflow in supp. billing
  app/services/supplementary-billing/fetch-charge-versions.service.js
  test/services/supplementary-billing/fetch-charge-versions.service.test.js
Labels: enhancement

#208 Tidy supplementary billing code - second pass
  app/lib/legacy-request.lib.js
  app/lib/request.lib.js
  app/services/plugins/filter-routes.service.js
  app/services/supplementary-billing/calculate-authorised-and-billable-days.service.js
  app/services/supplementary-billing/determine-charge-period.service.js
  app/services/supplementary-billing/fetch-previous-billing-transactions.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  app/services/supplementary-billing/process-billing-transactions.service.js
Labels: housekeeping

#216 Fix incorrect cleanse of previous transactions
  app/services/supplementary-billing/fetch-previous-billing-transactions.service.js
  test/services/supplementary-billing/fetch-previous-billing-transactions.service.test.js
Labels: bug

#215 Reliable test data clear down
  app/controllers/data/data.controller.js
  app/plugins/router.plugin.js
  app/routes/data.routes.js
  app/services/data/tear-down/crm-schema.service.js
  app/services/data/tear-down/idm-schema.service.js
  app/services/data/tear-down/permit-schema.service.js
  app/services/data/tear-down/returns-schema.service.js
  app/services/data/tear-down/tear-down.service.js
  app/services/data/tear-down/water-schema.service.js
  sonar-project.properties
  test/controllers/data/data.controller.test.js
  test/services/data/tear-down/tear-down.service.test.js
Labels: enhancement

#214 Refactor `ProcessBillingBatchService` - first pass
  app/services/supplementary-billing/fetch-invoice-account-numbers.service.js
  app/services/supplementary-billing/generate-billing-invoice.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  test/services/supplementary-billing/fetch-invoice-account-numbers.service.test.js
  test/services/supplementary-billing/generate-billing-invoice.service.test.js
  test/services/supplementary-billing/process-billing-batch.service.test.js
Labels: housekeeping

#217 Fix `ProcessBillingBatchService` refactor bug
  app/services/supplementary-billing/process-billing-batch.service.js
Labels: bug

#219 Clean up temporary files
  app/services/db-export/delete-file.service.js
  package-lock.json
  package.json
  test/services/db-export/compress-files.service.test.js
  test/services/db-export/convert-to-csv.service.test.js
  test/services/db-export/delete-file.service.test.js
  test/services/db-export/export-data-files.service.test.js
  test/services/db-export/send-to-s3-bucket.service.test.js
Labels: enhancement

#221 Unflag all processed licences not in bill run
  app/services/supplementary-billing/process-billing-batch.service.js
  app/services/supplementary-billing/unflag-unbilled-licences.service.js
  test/services/supplementary-billing/unflag-unbilled-licences.service.test.js
Labels: enhancement

#218 `ProcessBillingBatchService` refactor - pre-generate invoice licences
  app/services/supplementary-billing/generate-billing-invoice-licence.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  test/services/supplementary-billing/generate-billing-invoice-licence.service.test.js
Labels: housekeeping

#224 Fix comparison Section 126 factor in supp. billing
  app/services/supplementary-billing/generate-billing-transactions.service.js
  test/support/helpers/water/charge-element.helper.js
Labels: bug

#223 Add endpoint for Db export
  .env.example
  app/controllers/data/data.controller.js
  app/routes/data.routes.js
  app/services/db-export/db-export.service.js
  app/services/db-export/send-to-s3-bucket.service.js
  test/controllers/data/data.controller.test.js
  test/services/db-export/db-export.service.test.js
Labels: enhancement

#226 Multi Year Supplementary Billing
  app/services/supplementary-billing/billing-period.service.js
  app/services/supplementary-billing/billing-periods.service.js
  app/services/supplementary-billing/initiate-billing-batch.service.js
  test/services/supplementary-billing/billing-period.service.test.js
  test/services/supplementary-billing/billing-periods.service.test.js
  test/services/supplementary-billing/initiate-billing-batch.service.test.js
Labels: enhancement

#230 Process billing batch move db writes
  app/services/supplementary-billing/process-billing-batch.service.js
Labels: housekeeping

#229 Stop sending Airbrake notifications in tests
  test/controllers/bill-runs/bill-runs.controller.test.js
  test/controllers/data/data.controller.test.js
  test/controllers/health/airbrake.controller.test.js
  test/plugins/error-pages.plugin.test.js
Labels: housekeeping

#231 Fix Airbrake integration
  app/plugins/airbrake.plugin.js
  app/plugins/error-pages.plugin.js
Labels: bug

#233 Refactor start of processing a supp. billing batch
  app/controllers/bill-runs/bill-runs.controller.js
  app/services/supplementary-billing/check-live-bill-run.service.js
  app/services/supplementary-billing/create-billing-batch.service.js
  app/services/supplementary-billing/initiate-billing-batch.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  app/services/supplementary-billing/process-billing-period.service.js
  test/controllers/bill-runs/bill-runs.controller.test.js
  test/services/supplementary-billing/create-billing-batch.service.test.js
  test/services/supplementary-billing/initiate-billing-batch.service.test.js
  test/services/supplementary-billing/process-billing-period.service.test.js
Labels: housekeeping

#232 Generalising fetch billing charge categories service
  app/services/db-export/db-export.service.js
  app/services/db-export/fetch-billing-charge-categories.service.js
  app/services/db-export/fetch-table.service.js
  app/services/db-export/table-export.service.js
  test/services/db-export/fetch-table.service.test.js
  test/services/db-export/table-export.service.test.js
Labels: enhancement

#236 Refactor, unit tests & add NewBillingBatchService
  app/controllers/bill-runs/bill-runs.controller.js
  app/errors/billing-batch.error.js
  app/services/supplementary-billing/initiate-billing-batch.service.js
  app/services/supplementary-billing/new-billing-batch.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
  app/services/supplementary-billing/process-billing-period.service.js
  test/controllers/bill-runs/bill-runs.controller.test.js
  test/services/supplementary-billing/new-billing-batch.service.test.js
  test/services/supplementary-billing/process-billing-batch.service.test.js
  test/services/supplementary-billing/process-billing-period.service.test.js
Labels: housekeeping

#237 Getting table names from schema
  app/services/db-export/fetch-table-names.service.js
  test/services/db-export/fetch-table-names.service.test.js
Labels: enhancement

#242 Fix issue using Array.at() - Node is to old
  app/services/supplementary-billing/new-billing-batch.service.js
  app/services/supplementary-billing/process-billing-batch.service.js
Labels: bug

#243 Fix isNewLicence null violation for prev. trans.
  app/services/supplementary-billing/fetch-previous-billing-transactions.service.js
Labels: bug

#238 Export a schema
  app/services/db-export/db-export.service.js
  app/services/db-export/delete-folder.service.js
  app/services/db-export/export-compressed-table.service.js
  app/services/db-export/export-data-files.service.js
  app/services/db-export/schema-export.service.js
  app/services/db-export/send-to-s3-bucket.service.js
  app/services/db-export/table-export.service.js
  test/services/db-export/db-export.service.test.js
  test/services/db-export/delete-folder.service.test.js
  test/services/db-export/export-compressed-table.service.test.js
  test/services/db-export/export-data-files.service.test.js
  test/services/db-export/send-to-s3-bucket.service.test.js
Labels: housekeeping
