Repository DEFRA/water-abstraction-system, pull requests merged in 2023-01, with the labels that each got.

#73 Refactor CreateEventService for bill runs
  app/presenters/supplementary-billing/create-billing-batch-event.presenter.js
  app/services/supplementary-billing/create-billing-batch-event.service.js
  app/services/supplementary-billing/create-event.service.js
  db/migrations/20230102173756_alter_regions.js
  db/migrations/20230102174930_alter_billing_batches.js
  test/presenters/supplementary-billing/create-billing-batch-event.presenter.test.js
  test/services/supplementary-billing/create-billing-batch-event.service.test.js
  test/services/supplementary-billing/create-event.service.test.js
  test/support/helpers/billing-batch.helper.js
  test/support/helpers/region.helper.js
Labels: housekeeping

#74 Refactor CreateBillingBatchService
  app/services/supplementary-billing/create-billing-batch.service.js
  test/services/supplementary-billing/create-billing-batch.service.test.js
Labels: housekeeping

#75 Add user to CreateBillRunValidator
  app/validators/bill-runs/create-bill-run.validator.js
  test/controllers/bill-runs.controller.test.js
  test/validators/bill-runs/create-bill-run.validator.js
Labels: enhancement

#56 Update "create bill run" endpoint to create a bill run
  app/controllers/bill-runs.controller.js
  app/controllers/bill-runs/bill-runs.controller.js
  app/presenters/supplementary-billing/create-billing-batch.presenter.js
  app/routes/bill-runs.routes.js
  app/services/supplementary-billing/initiate-billing-batch.service.js
  test/controllers/bill-runs.controller.test.js
  test/controllers/bill-runs/bill-runs.controller.test.js
  test/presenters/supplementary-billing/create-billing-batch.presenter.test.js
  test/services/supplementary-billing/initiate-billing-batch.service.test.js
Labels: enhancement

#78 Restructure models by type and scheme
  app/models/base.model.js
  app/models/legacy-base.model.js
  app/models/water/billing-batch.model.js
  app/models/water/billing-charge-category.model.js
  app/models/water/charge-element.model.js
  app/models/water/charge-purpose.model.js
  app/models/water/charge-version.model.js
  app/models/water/event.model.js
  app/models/water/licence.model.js
  app/models/water/region.model.js
  app/models/water/water-base.model.js
  app/services/supplementary-billing/create-billing-batch-event.service.js
  app/services/supplementary-billing/create-billing-batch.service.js
  app/services/supplementary-billing/fetch-charge-versions.service.js
  app/services/supplementary-billing/fetch-licences.service.js
  app/services/supplementary-billing/fetch-region.service.js
  test/models/legacy-base.model.test.js
  test/models/water/billing-batch.model.test.js
  test/models/water/billing-charge-category.model.test.js
  test/models/water/charge-element.model.test.js
  test/models/water/charge-purpose.model.test.js
  test/models/water/charge-version.model.test.js
  test/models/water/event.model.test.js
  test/models/water/licence.model.test.js
  test/models/water/region.model.test.js
  test/presenters/supplementary-billing/create-billing-batch-event.presenter.test.js
  test/services/supplementary-billing/create-billing-batch-event.service.test.js
  test/services/supplementary-billing/create-billing-batch.service.test.js
  test/services/supplementary-billing/fetch-charge-versions.service.test.js
  test/services/supplementary-billing/fetch-licences.service.test.js
  test/services/supplementary-billing/fetch-region.service.test.js
  test/services/supplementary-billing/initiate-billing-batch.service.test.js
  test/support/helpers/water/billing-batch.helper.js
  test/support/helpers/water/billing-charge-category.helper.js
  test/support/helpers/water/charge-element.helper.js
  test/support/helpers/water/charge-purpose.helper.js
  test/support/helpers/water/charge-version.helper.js
  test/support/helpers/water/event.helper.js
  test/support/helpers/water/licence.helper.js
  test/support/helpers/water/region.helper.js
Labels: housekeeping

#77 Rewrite the migrations to match legacy tables
  db/migrations/20221108143017_add-pgcrypto-extension.js
  db/migrations/20221108143106_create-update-timestamp-trigger.js
  db/migrations/20221108152353_create-water-charge-versions.js
  db/migrations/20221111155222_create-water-licences.js
  db/migrations/20221111184905_alter_charge_versions.js
  db/migrations/20221114104700_create-water-regions.js
  db/migrations/20221114155444_alter_licences.js
  db/migrations/20221125164859_create-water-billing-batches.js
  db/migrations/20221206084612_alter_charge_versions.js
  db/migrations/20221209193845_create-water-events.js
  db/migrations/20221215174926_create-water-charge-elements.js
  db/migrations/20221216112650_create-water-billing-charge-categories.js
  db/migrations/20221216154722_create-water-charge-purposes.js
  db/migrations/20230102173756_alter_regions.js
  db/migrations/20230102174930_alter_billing_batches.js
  test/presenters/supplementary-billing/create-billing-batch-event.presenter.test.js
  test/support/helpers/water/billing-charge-category.helper.js
Labels: housekeeping

#84 Implement Charging Module Create Bill Run Service
  app/services/charging-module-create-bill-run.service.js
  test/services/charging-module-create-bill-run.service.test.js
Labels: enhancement

#85 Make timestamps consistent at model layer
  app/models/legacy-base.model.js
  app/models/water/billing-batch.model.js
  app/models/water/billing-charge-category.model.js
  app/models/water/charge-element.model.js
  app/models/water/charge-purpose.model.js
  app/models/water/charge-version.model.js
  app/models/water/event.model.js
  app/models/water/licence.model.js
  app/models/water/region.model.js
  app/presenters/supplementary-billing/create-billing-batch-event.presenter.js
  test/models/legacy-base.model.test.js
  test/presenters/supplementary-billing/create-billing-batch-event.presenter.test.js
  test/support/helpers/water/billing-charge-category.helper.js
Labels: housekeeping

#89 Fix issue with dotenv in tests
  app/server.js
  config/airbrake.config.js
  config/database.config.js
  config/log.config.js
  config/request.config.js
  config/server.config.js
  config/services.config.js
Labels: bug

#83 Request new bill run in Charging Module API
  app/controllers/bill-runs/bill-runs.controller.js
  app/presenters/supplementary-billing/create-billing-batch.presenter.js
  app/services/charging-module/create-bill-run.service.js
  app/services/charging-module/token.service.js
  app/services/supplementary-billing/create-billing-batch.service.js
  app/services/supplementary-billing/initiate-billing-batch.service.js
  db/migrations/20230111152047_alter-water-billing-batches.js
  test/controllers/bill-runs/bill-runs.controller.test.js
  test/presenters/supplementary-billing/create-billing-batch.presenter.test.js
  test/services/charging-module/create-bill-run.service.test.js
  test/services/charging-module/token.service.test.js
  test/services/supplementary-billing/create-billing-batch.service.test.js
  test/services/supplementary-billing/initiate-billing-batch.service.test.js
Labels: enhancement

#92 Fix invalid GOT POST reg. to create CHA bill run
  app/services/charging-module/create-bill-run.service.js
  test/services/charging-module/create-bill-run.service.test.js
Labels: bug

#81 Add logic 2 determine billable abstraction periods
  app/services/supplementary-billing/abstraction-billing-period.service.js
  test/services/supplementary-billing/abstraction-billing-period.service.test.js
Labels: enhancement

#91 Create `ChargingModuleTokenCachePlugin` to cache Charging Module JWT token
  app/controllers/root.controller.js
  app/plugins/charging-module-token-cache.plugin.js
  app/server.js
  test/plugins/charging-module-token-cache.plugin.test.js
Labels: enhancement

#93 Add comments to AbstractionBillingPeriodService
  app/services/supplementary-billing/abstraction-billing-period.service.js
Labels: documentation

#95 Support new queued bill run status
  app/services/supplementary-billing/create-billing-batch.service.js
  test/services/supplementary-billing/create-billing-batch.service.test.js
  test/services/supplementary-billing/initiate-billing-batch.service.test.js
  test/support/helpers/water/billing-batch.helper.js
Labels: enhancement

#96 Fix handling of Charging Module errors
  app/services/charging-module/create-bill-run.service.js
  app/services/supplementary-billing/initiate-billing-batch.service.js
  test/services/charging-module/create-bill-run.service.test.js
  test/services/supplementary-billing/initiate-billing-batch.service.test.js
Labels: bug

#98 Do not create SROC bill run if one already exists
  app/services/supplementary-billing/check-live-bill-run.service.js
  app/services/supplementary-billing/initiate-billing-batch.service.js
  test/services/supplementary-billing/check-live-bill-run.service.test.js
  test/services/supplementary-billing/initiate-billing-batch.service.test.js
Labels: enhancement

#97 SRoC Supplementary Billing - Determine Abstraction Period
  app/services/supplementary-billing/abstraction-billing-period.service.js
  test/services/supplementary-billing/abstraction-billing-period.service.test.js
Labels: enhancement

#101 Determine if licence is 'billed'
  app/presenters/check/supplementary-data.presenter.js
  app/services/supplementary-billing/fetch-licences.service.js
  test/presenters/check/supplementary-data.presenter.test.js
  test/services/supplementary-billing/fetch-licences.service.test.js
  test/support/helpers/water/billing-invoice.helper.js
Labels: enhancement

#105 Fix CHA CreateBillRunService result parsing
  app/services/charging-module/create-bill-run.service.js
  test/services/charging-module/create-bill-run.service.test.js
Labels: bug
