Repository DEFRA/water-abstraction-system, pull requests merged in 2023-07, with the labels that each got.

#293 Fix licence ends before billing period
  app/services/supplementary-billing/determine-charge-period.service.js
  app/services/supplementary-billing/determine-minimum-charge.service.js
  app/services/supplementary-billing/process-billing-period.service.js
  test/services/supplementary-billing/determine-charge-period.service.test.js
  test/services/supplementary-billing/determine-minimum-charge.service.test.js
Labels: bug

#256 Implement SROC invoice reissuing
  app/services/supplementary-billing/fetch-invoices-to-be-reissued.service.js
  app/services/supplementary-billing/reissue-invoice.service.js
  app/services/supplementary-billing/reissue-invoices.service.js
  test/services/supplementary-billing/fetch-invoices-to-be-reissued.service.test.js
  test/services/supplementary-billing/reissue-invoice.service.test.js
  test/services/supplementary-billing/reissue-invoices.service.test.js
Labels: enhancement

#285 Add initial seeding support using users
  .env.example
  app/controllers/data/data.controller.js
  app/routes/data.routes.js
  app/services/data/seed/seed.service.js
  config/database.config.js
  db/seeds/01-users.js
  package-lock.json
  package.json
  test/controllers/data/data.controller.test.js
  test/services/data/seed/seed.service.test.js
Labels: enhancement

#296 Add new custom ExpandedError
  app/errors/expanded.error.js
  app/services/supplementary-billing/initiate-billing-batch.service.js
  app/services/supplementary-billing/reissue-invoice.service.js
  test/errors/expanded.error.test.js
  test/services/supplementary-billing/initiate-billing-batch.service.test.js
Labels: enhancement

#299 Move db-export services to data folder
  app/controllers/data/data.controller.js
  app/routes/data.routes.js
  app/services/data/export/compress-schema-folder.service.js
  app/services/data/export/convert-to-csv.service.js
  app/services/data/export/delete-files.service.js
  app/services/data/export/export-data-files.service.js
  app/services/data/export/export-table.service.js
  app/services/data/export/export.service.js
  app/services/data/export/fetch-table-names.service.js
  app/services/data/export/fetch-table.service.js
  app/services/data/export/schema-export.service.js
  app/services/data/export/send-to-s3-bucket.service.js
  test/controllers/data/data.controller.test.js
  test/services/data/export/compress-schema-folder.service.test.js
  test/services/data/export/convert-to-csv.service.test.js
  test/services/data/export/delete-files.service.test.js
  test/services/data/export/export-data-files.service.test.js
  test/services/data/export/export-table.service.test.js
  test/services/data/export/export.service.test.js
  test/services/data/export/fetch-table-names.service.test.js
  test/services/data/export/fetch-table.service.test.js
  test/services/data/export/schema-export.service.test.js
  test/services/data/export/send-to-s3-bucket.service.test.js
Labels: housekeeping

#302 Add back in our check endpoint
  app/controllers/check/check.controller.js
  app/plugins/router.plugin.js
  app/routes/check.routes.js
  app/services/check/two-part.service.js
  test/controllers/check/check.controller.test.js
Labels: enhancement

#304 Move and make generic some billing services
  app/controllers/bill-runs/bill-runs.controller.js
  app/lib/static-lookups.lib.js
  app/presenters/billing/create-billing-batch-event.presenter.js
  app/presenters/billing/create-billing-batch.presenter.js
  app/services/billing/check-live-bill-run.service.js
  app/services/billing/create-billing-batch-event.service.js
  app/services/billing/create-billing-batch.service.js
  app/services/billing/determine-billing-periods.service.js
  app/services/billing/fetch-region.service.js
  app/services/billing/initiate-billing-batch.service.js
  app/services/billing/new-billing-batch.service.js
  app/services/billing/supplementary/new-billing-batch.service.js
  app/services/billing/supplementary/process-billing-batch.service.js
  app/services/billing/two-part-tariff/process-billing-batch.service.js
  app/services/check/two-part.service.js
  app/validators/bill-runs/create-bill-run.validator.js
  test/controllers/bill-runs/bill-runs.controller.test.js
  test/presenters/billing/create-billing-batch-event.presenter.test.js
  test/presenters/billing/create-billing-batch.presenter.test.js
  test/services/billing/check-live-bill-run.service.test.js
  test/services/billing/create-billing-batch-event.service.test.js
  test/services/billing/create-billing-batch.service.test.js
  test/services/billing/determine-billing-periods.service.test.js
  test/services/billing/fetch-region.service.test.js
  test/services/billing/initiate-billing-batch.service.test.js
  test/services/billing/new-billing-batch.service.test.js
  test/services/billing/supplementary-billing/check-live-bill-run.service.test.js
  test/services/billing/supplementary-billing/new-billing-batch.service.test.js
  test/services/billing/supplementary-billing/process-billing-batch.service.test.js
  test/services/billing/two-part-tariff/process-billing-batch.service.test.js
Labels: housekeeping

#305 Fix where supplementary billing service tests are
  test/services/billing/supplementary/calculate-authorised-and-billable-days.service.test.js
  test/services/billing/supplementary/consolidate-date-ranges.service.test.js
  test/services/billing/supplementary/create-billing-transaction.service.test.js
  test/services/billing/supplementary/determine-charge-period.service.test.js
  test/services/billing/supplementary/determine-minimum-charge.service.test.js
  test/services/billing/supplementary/fetch-charge-versions.service.test.js
  test/services/billing/supplementary/fetch-invoice-account-numbers.service.test.js
  test/services/billing/supplementary/fetch-invoices-to-be-reissued.service.test.js
  test/services/billing/supplementary/fetch-previous-billing-transactions.service.test.js
  test/services/billing/supplementary/generate-billing-invoice-licence.service.test.js
  test/services/billing/supplementary/generate-billing-invoice.service.test.js
  test/services/billing/supplementary/generate-billing-transactions.service.test.js
  test/services/billing/supplementary/handle-errored-billing-batch.service.test.js
  test/services/billing/supplementary/pre-generate-billing-data.service.test.js
  test/services/billing/supplementary/process-billing-batch.service.test.js
  test/services/billing/supplementary/process-billing-period.service.test.js
  test/services/billing/supplementary/process-billing-transactions.service.test.js
  test/services/billing/supplementary/reissue-invoice.service.test.js
  test/services/billing/supplementary/reissue-invoices.service.test.js
  test/services/billing/supplementary/reverse-billing-transactions.service.test.js
  test/services/billing/supplementary/send-billing-transactions.service.test.js
  test/services/billing/supplementary/unflag-unbilled-licences.service.test.js
Labels: housekeeping

#310 Fix reissuing bugs
  app/models/water/billing-transaction.model.js
  app/services/billing/supplementary/fetch-invoices-to-be-reissued.service.js
  app/services/billing/supplementary/process-billing-batch.service.js
  app/services/billing/supplementary/reissue-invoice.service.js
  app/services/charging-module/bill-run-status.service.js
  test/models/water/billing-transaction.model.test.js
  test/services/billing/supplementary/fetch-invoices-to-be-reissued.service.test.js
  test/services/billing/supplementary/reissue-invoice.service.test.js
  test/services/billing/supplementary/reissue-invoices.service.test.js
  test/services/charging-module/bill-run-status.service.test.js
Labels: bug

#311 Fix reissuing ALCS invoice bug
  app/services/billing/supplementary/fetch-invoices-to-be-reissued.service.js
  test/services/billing/supplementary/fetch-invoices-to-be-reissued.service.test.js
Labels: bug

#320 Improve reissuing error logging
  app/services/billing/supplementary/reissue-invoice.service.js
  test/services/billing/supplementary/reissue-invoice.service.test.js
Labels: enhancement
