Repository DEFRA/water-abstraction-system, pull requests merged in 2024-10, with the labels that each got.

#1377 Fix down migrations for return logs view
  db/migrations/public/20240807132127_alter-return-logs-view-include-source.js
  db/migrations/public/20240918144353_alter-return-logs-view.js
Labels: bug

#1378 Stop adding link on due returns for unauth users
  app/presenters/licences/view-licence-returns.presenter.js
  app/services/licences/view-licence-returns.service.js
  app/views/licences/tabs/returns.njk
  test/presenters/licences/view-licence-returns.presenter.test.js
  test/services/licences/view-licence-returns.service.test.js
Labels: bug

#1380 Handle return requirements with no site desc.
  app/presenters/return-requirements/view.presenter.js
  app/views/return-requirements/view.njk
  test/presenters/return-requirements/view.presenter.test.js
Labels: housekeeping

#1371 Import company address data for a licence
  app/presenters/import/legacy/company-address.presenter.js
  app/presenters/import/legacy/company.presenter.js
  app/services/import/legacy/fetch-company-address.service.js
  app/services/import/legacy/process-licence.service.js
  app/services/import/legacy/transform-addresses.service.js
  app/services/import/legacy/transform-company-addresses.service.js
  app/services/import/persist-licence.service.js
  app/validators/import/company.validator.js
  test/presenters/import/legacy/company-address.presenter.test.js
  test/presenters/import/legacy/company.presenter.test.js
  test/services/import/legacy/process-licence.service.test.js
  test/services/import/legacy/transform-addresses.service.test.js
  test/services/import/legacy/transform-companies.service.test.js
  test/services/import/legacy/transform-company-addresses.service.test.js
  test/services/import/persist-licence.service.test.js
  test/validators/import/company.validator.test.js
Labels: enhancement

#1383 Stop display null site desc. in view licence rtn
  app/presenters/licences/view-licence-returns.presenter.js
  test/presenters/licences/view-licence-returns.presenter.test.js
Labels: bug

#1375 Add abstraction method to lic. purpose points
  db/migrations/legacy/20221108007039_water-licence-version-purpose-points.js
  db/migrations/public/20241003073555_alter-licence-version-purpose-points-view.js
Labels: housekeeping

#1385 Import company address data for a licence
  app/services/import/legacy/fetch-company-address.service.js
Labels: enhancement

#1384 Handle empty site description in returns setup
  app/services/return-requirements/fetch-existing-requirements.js
  app/services/return-requirements/generate-from-existing-requirements.service.js
  test/services/return-requirements/fetch-existing-requirements.test.js
  test/services/return-requirements/generate-from-existing-requirements.service.test.js
Labels: bug

#1340 Migrate monitoring station view page
  app/controllers/monitoring-stations.controller.js
  app/plugins/router.plugin.js
  app/presenters/licences/view-licence-summary.presenter.js
  app/presenters/monitoring-stations/view-monitoring-stations.presenter.js
  app/routes/monitoring-station.routes.js
  app/services/monitoring-stations/fetch-monitoring-station.service.js
  app/services/monitoring-stations/view.service.js
  app/views/licences/tabs/summary.njk
  app/views/monitoring-stations/view.njk
  config/feature-flags.config.js
  test/controllers/monitoring-stations.controller.test.js
  test/presenters/licences/view-licence-summary.presenter.test.js
  test/presenters/monitoring-stations/view-monitoring-stations.presenter.test.js
  test/services/licences/view-licence-summary.service.test.js
  test/services/monitoring-stations/fetch-monitoring-stations.service.test.js
  test/services/monitoring-stations/view.service.test.js
Labels: enhancement

#1394 Handle special characters in rtn req. bookmarks
  app/views/return-requirements/view.njk
Labels: bug

#1395 Fix QA issues in new Monitoring stations page
  app/presenters/monitoring-stations/view-monitoring-stations.presenter.js
  app/views/monitoring-stations/view.njk
  test/presenters/monitoring-stations/view-monitoring-stations.presenter.test.js
  test/services/monitoring-stations/view.service.test.js
Labels: bug

#1398 Remove setting return cycle in ReturnLogHelper
  test/support/helpers/return-log.helper.js
Labels: housekeeping

#1399 Fix error with return cycles seeder
  db/seeds/16-return-cycles.seed.js
Labels: bug

#1400 Fix error when seeding in AWS non-production
  db/seeds/09-users.seed.js
Labels: bug

#1409 Add option to run tests without cleaning
  package.json
Labels: housekeeping

#1392 Import licence document for a licence
  app/presenters/import/legacy/licence-document.presenter.js
  app/services/import/legacy/fetch-licence-document.service.js
  app/services/import/legacy/process-licence.service.js
  app/services/import/legacy/transform-licence-document.service.js
  app/services/import/persist-import.service.js
  app/services/import/persist/persist-licence-document.service.js
  app/validators/import/licence-document.validator.js
  db/migrations/legacy/20221108003004_crm-v2-documents.js
  test/presenters/import/legacy/licence-document.presenter.test.js
  test/services/import/legacy/process-licence.service.test.js
  test/services/import/legacy/transform-licence-document.service.test.js
  test/services/import/persist-import.service.test.js
  test/services/import/persist/persist-licence-document.service.test.js
  test/validators/import/licence-document.validator.test.js
Labels: enhancement

#1413 Fix auth scope on view monitoring station route
  app/routes/monitoring-station.routes.js
  test/controllers/monitoring-stations.controller.test.js
Labels: bug

#1419 Exclude VOID returns from two-part tariff billing
  app/presenters/bill-runs/two-part-tariff/match-details.presenter.js
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/services/bill-runs/two-part-tariff/fetch-return-logs-for-licence.service.js
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-return-logs-for-licence.service.test.js
Labels: enhancement

#1418 Remove POST create bill run route
  app/controllers/bill-runs.controller.js
  app/routes/bill-runs.routes.js
  app/validators/create-bill-run.validator.js
  test/controllers/bill-runs.controller.test.js
  test/validators/create-bill-run.validator.test.js
Labels: housekeeping

#1414 Import licence document roles for a licence
  app/presenters/import/legacy/licence-document-role.presenter.js
  app/presenters/import/legacy/licence-document.presenter.js
  app/services/import/legacy/fetch-licence-document-roles.service.js
  app/services/import/legacy/process-licence.service.js
  app/services/import/legacy/transform-licence-document-roles.service.js
  app/services/import/persist/persist-licence-document.service.js
  app/services/import/persist/persist-licence.service.js
  app/validators/import/licence-document-role.validator.js
  app/validators/import/licence-document.validator.js
  test/presenters/import/legacy/licence-document-role.presenter.test.js
  test/presenters/import/legacy/licence-document.presenter.test.js
  test/services/import/legacy/process-licence.service.test.js
  test/services/import/legacy/transform-licence-document-role.service.test.js
  test/services/import/legacy/transform-licence-document.service.test.js
  test/services/import/persist/persist-licence-document.service.test.js
  test/support/helpers/licence-document-role.helper.js
  test/validators/import/licence-document-role.validator.test.js
  test/validators/import/licence-document.validator.test.js
Labels: enhancement

#1430 Tidy up view licence inconsistencies
  app/presenters/licences/view-licence-communications.presenter.js
  app/presenters/licences/view-licence-set-up.presenter.js
  app/services/licences/fetch-communications.service.js
  app/services/licences/fetch-licence-bills.service.js
  app/services/licences/fetch-licence-returns.service.js
  app/services/licences/view-licence-bills.service.js
  app/services/licences/view-licence-communications.service.js
  app/services/licences/view-licence-returns.service.js
  app/services/licences/view-licence-set-up.service.js
  test/presenters/licences/view-licence-communications.presenter.test.js
  test/presenters/licences/view-licence-set-up.presenter.test.js
Labels: housekeeping

#1391 Add Sinon.restore to submit-year.service.test.js
  app/services/bill-runs/fetch-region.service.js
  test/services/bill-runs/setup/submit-year.service.test.js
Labels: housekeeping

#1426 Update some unit tests to use Model stubbing
  test/services/bill-runs/fetch-bill-runs.service.test.js
Labels: housekeeping, testing

#1388 Flag licences removed from workflow for supp billing
  app/services/licences/supplementary/determine-workflow-years.service.js
  app/services/licences/supplementary/fetch-licence.service.js
  app/services/licences/supplementary/process-billing-flag.service.js
  test/services/licences/supplementary/determine-workflow-years.service.test.js
  test/services/licences/supplementary/fetch-licence.service.test.js
  test/services/licences/supplementary/process-billing-flag.service.test.js
Labels: enhancement

#1435 Licence Import Supplementary billing test endpoint
  app/controllers/check.controller.js
  app/routes/check.routes.js
Labels: enhancement

#1440 Fix testing endpoint for supplementary flags
  app/controllers/check.controller.js
Labels: bug

#1444 Refactor billing account contact details to model
  app/models/billing-account.model.js
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/presenters/bills/remove-bill.presenter.js
  app/presenters/bills/view-bill.presenter.js
  app/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.js
  app/services/bills/fetch-bill-summary.service.js
  app/services/bills/view-bill.service.js
  app/services/fetch-billing-account.service.js
  test/models/billing-account.model.test.js
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
  test/presenters/bills/remove-bill.presenter.test.js
  test/presenters/bills/view-bill.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.test.js
  test/services/bills/fetch-bill-summary.service.test.js
  test/services/bills/view-bill.service.test.js
  test/services/fetch-billing-account.service.test.js
Labels: housekeeping

#1445 Fix failing unit tests
  test/presenters/bills/remove-bill.presenter.test.js
  test/services/bill-runs/two-part-tariff/review-licence.service.test.js
  test/services/bills/remove-bill.service.test.js
  test/support/helpers/return-cycle.helper.js
Labels: testing

#1379 Migrate abstraction details view page
  app/controllers/licences.controller.js
  app/presenters/licences/view-licence-purposes.presenter.js
  app/presenters/licences/view-licence-summary.presenter.js
  app/routes/licence.routes.js
  app/services/licences/fetch-licence-purposes.service.js
  app/services/licences/view-licence-purposes.service.js
  app/views/licences/purposes.njk
  app/views/licences/tabs/summary.njk
  config/feature-flags.config.js
  test/controllers/licences.controller.test.js
  test/presenters/licences/view-licence-purposes.presenter.test.js
  test/presenters/licences/view-licence-summary.presenter.test.js
  test/services/licences/fetch-licence-purposes.service.test.js
  test/services/licences/view-licence-purposes.service.test.js
  test/services/licences/view-licence-summary.service.test.js
Labels: enhancement

#1424 Import licence document roles for a licence - licence holder
  app/services/import/legacy/fetch-licence-document-roles.service.js
Labels: enhancement

#1284 Fix JSDOC's lint seeder descriptions
  db/seeds/01-regions.seed.js
  db/seeds/02-purposes.seed.js
  db/seeds/03-primary-purposes.seed.js
  db/seeds/04-secondary-purposes.seed.js
  db/seeds/05-licence-version-purpose-condition-types.seed.js
Labels: housekeeping

#1452 Fix env var for licence purposes view
  config/feature-flags.config.js
Labels: bug

#1457 Add `,` between abstraction points in point model
  app/models/point.model.js
  test/models/point.model.test.js
  test/presenters/return-versions/setup/points.presenter.test.js
Labels: housekeeping
