Repository DEFRA/water-abstraction-system, pull requests merged in 2024-11, with the labels that each got.

#1461 Decouple start date logic
  app/presenters/return-versions/setup/check/check.presenter.js
  app/services/return-versions/setup/check/generate-return-version.service.js
  app/services/return-versions/setup/submit-start-date.service.js
  test/presenters/return-versions/setup/check/check.presenter.test.js
  test/services/jobs/return-logs/fetch-return-cycle.service.test.js
  test/services/return-versions/setup/check/check.service.test.js
  test/services/return-versions/setup/check/generate-return-version.service.test.js
  test/services/return-versions/setup/submit-start-date.service.test.js
Labels: housekeeping

#1469 Fix broken return version start date page
  app/services/return-versions/setup/submit-start-date.service.js
  test/services/return-versions/setup/check/generate-return-version.service.test.js
  test/services/return-versions/setup/submit-start-date.service.test.js
Labels: bug

#1471 Move 2PT match and allocate logic to own folder
  app/services/bill-runs/match/allocate-returns-to-charge-element.service.js
  app/services/bill-runs/match/determine-licence-issues.service.js
  app/services/bill-runs/match/fetch-charge-versions.service.js
  app/services/bill-runs/match/fetch-licences.service.js
  app/services/bill-runs/match/fetch-return-logs-for-licence.service.js
  app/services/bill-runs/match/match-and-allocate.service.js
  app/services/bill-runs/match/match-returns-to-charge-element.service.js
  app/services/bill-runs/match/persist-allocated-licence-to-results.service.js
  app/services/bill-runs/match/prepare-charge-version.service.js
  app/services/bill-runs/match/prepare-return-logs.service.js
  app/services/bill-runs/two-part-tariff/process-bill-run.service.js
  test/services/bill-runs/match/allocate-returns-to-charge-element.service.test.js
  test/services/bill-runs/match/determine-licence-issues.service.test.js
  test/services/bill-runs/match/fetch-charge-versions.service.test.js
  test/services/bill-runs/match/fetch-licences.service.test.js
  test/services/bill-runs/match/fetch-return-logs-for-licence.service.test.js
  test/services/bill-runs/match/match-and-allocate.service.test.js
  test/services/bill-runs/match/match-returns-to-charge-element.service.test.js
  test/services/bill-runs/match/persist-allocated-licence-to-results.service.test.js
  test/services/bill-runs/match/prepare-charge-version.service.test.js
  test/services/bill-runs/match/prepare-return-logs.service.test.js
  test/services/bill-runs/two-part-tariff/process-bill-run.service.test.js
Labels: housekeeping

#1472 Move 2PT review result tables into 'water' schema
  app/models/review-charge-element-return.model.js
  app/models/review-charge-element.model.js
  app/models/review-return.model.js
  app/services/bill-runs/review/remove-review-licence.service.js
  app/services/bill-runs/submit-cancel-bill-run.service.js
  app/services/data/tear-down/public-schema.service.js
  app/services/data/tear-down/tear-down.service.js
  app/services/data/tear-down/water-schema.service.js
  db/migrations/legacy/20221108006004_returns-return-cycles.js
  db/migrations/legacy/20221108007042_water-licence-supplementary-years.js
  db/migrations/legacy/20221108007043_water-review-charge-elements.js
  db/migrations/legacy/20221108007044_water-review-charge-element-returns.js
  db/migrations/legacy/20221108007045_water-review-charge-references.js
  db/migrations/legacy/20221108007046_water-review-charge-versions.js
  db/migrations/legacy/20221108007047_water-review-licences.js
  db/migrations/legacy/20221108007048_water-review-returns.js
  db/migrations/public/20241110153834_drop-review-tables.js
  db/migrations/public/20241110154027_create-licence-supplementary-years-view.js
  db/migrations/public/20241110154202_create-review-charge-elements-view.js
  db/migrations/public/20241110154305_create-review-charge-element-returns-view.js
  db/migrations/public/20241110154434_create-review-charge-references-view.js
  db/migrations/public/20241110154606_create-review-charge-versions-view.js
  db/migrations/public/20241110154652_create-review-licences-view.js
  db/migrations/public/20241110154755_create-review-returns-view.js
  test/services/bill-runs/review/fetch-review-charge-element.service.test.js
  test/services/bill-runs/review/fetch-review-charge-reference.test.js
  test/services/bill-runs/review/fetch-review-licence.service.test.js
  test/services/data/tear-down/tear-down.service.test.js
  test/support/helpers/review-charge-element.helper.js
  test/support/helpers/review-charge-reference.helper.js
  test/support/helpers/review-licence.helper.js
  test/support/helpers/review-return.helper.js
Labels: housekeeping

#1478 Add code coverage report to job summary
  .github/workflows/ci.yml
  .labrc.js
Labels: housekeeping

#1485 Improve coverage on lib date
  test/lib/dates.lib.test.js
Labels: housekeeping, testing

#1482 Add quarterly returns submissions to return versions
  app/lib/dates.lib.js
  app/presenters/return-versions/setup/additional-submission-options.presenter.js
  app/services/return-versions/setup/submit-additional-submission-options.service.js
  app/services/return-versions/setup/submit-start-date.service.js
  app/views/return-versions/setup/additional-submission-options.njk
  test/lib/dates.lib.test.js
  test/presenters/return-versions/setup/additional-submission-options.presenter.test.js
  test/services/return-versions/setup/additional-submission-options.service.test.js
  test/services/return-versions/setup/submit-additional-submission-options.service.test.js
  test/services/return-versions/setup/submit-start-date.service.test.js
Labels: enhancement

#1489 Add quarterly returns submissions to check return versions
  app/presenters/return-versions/setup/check/check.presenter.js
  app/views/return-versions/setup/additional-submission-options.njk
  app/views/return-versions/setup/check.njk
  test/presenters/return-versions/setup/check/check.presenter.test.js
  test/services/return-versions/setup/check/check.service.test.js
Labels: enhancement

#1491 View quarterly returns submissions option
  app/presenters/return-versions/view.presenter.js
  app/services/return-versions/fetch-return-version.service.js
  app/views/return-versions/view.njk
  test/presenters/return-versions/view.presenter.test.js
  test/services/return-versions/fetch-return-version.service.test.js
  test/services/return-versions/view.service.test.js
Labels: enhancement

#1493 Fix back in view licence contact details text
  app/views/licences/licence-contact-details.njk
Labels: bug

#1494 Fix back link for copy existing in rtn vers setup
  app/presenters/return-versions/setup/existing.presenter.js
  app/views/return-versions/setup/existing.njk
  test/presenters/return-versions/setup/existing.presenter.test.js
  test/services/return-versions/setup/existing.service.test.js
  test/services/return-versions/setup/submit-existing.service.test.js
Labels: bug

#1470 Fix issues on view monitoring station page
  app/controllers/monitoring-stations.controller.js
  app/models/licence-monitoring-station.model.js
  app/models/licence-version-purpose-condition.model.js
  app/presenters/monitoring-stations/view-monitoring-stations.presenter.js
  app/presenters/monitoring-stations/view.presenter.js
  app/services/monitoring-stations/fetch-monitoring-station.service.js
  app/services/monitoring-stations/view.service.js
  app/views/monitoring-stations/view.njk
  db/migrations/public/20241115180557_alter-licence-monitoring-stations-view.js
  test/models/licence-monitoring-station.model.test.js
  test/models/licence-version-purpose-condition.model.test.js
  test/presenters/monitoring-stations/view-monitoring-stations.presenter.test.js
  test/presenters/monitoring-stations/view.presenter.test.js
  test/services/licences/fetch-licence-summary.service.test.js
  test/services/monitoring-stations/fetch-monitoring-station.service.test.js
  test/services/monitoring-stations/fetch-monitoring-stations.service.test.js
  test/services/monitoring-stations/view.service.test.js
  test/support/helpers/licence-monitoring-station.helper.js
  test/support/helpers/monitoring-station.helper.js
Labels: bug

#1492 Fix outstanding JSDoc issues
  .eslintrc.js
  app/errors/expanded.error.js
  app/lib/request-notifier.lib.js
  app/models/base.model.js
  app/models/licence-entity.model.js
  app/plugins/yar.plugin.js
  app/presenters/bill-runs/create-bill-run-event.presenter.js
  app/presenters/bill-runs/view-bill-run.presenter.js
  app/presenters/bill-runs/view-bill-summaries.presenter.js
  app/presenters/bills/view-licence-summaries.presenter.js
  app/presenters/import/legacy/address.presenter.js
  app/presenters/licences/customer-contacts.presenter.js
  app/presenters/licences/licence-contacts.presenter.js
  app/presenters/licences/view-licence-bills.presenter.js
  app/presenters/paginator.presenter.js
  app/requests/base.request.js
  app/requests/charging-module/reissue-bill.request.js
  app/requests/charging-module/view-bill.request.js
  app/requests/legacy/create-bill-run.request.js
  app/services/bill-runs/calculate-authorised-and-billable-days.service.js
  app/services/bill-runs/create-bill-run.service.js
  app/services/bill-runs/reissue/reissue-bill.service.js
  app/services/bill-runs/setup/determine-financial-year-end.service.js
  app/services/bill-runs/supplementary/process-transactions.service.js
  app/services/billing-accounts/change-address.service.js
  app/services/data/deduplicate/submit-deduplicate.service.js
  app/services/data/tear-down/crm-schema.service.js
  app/services/data/tear-down/idm-schema.service.js
  app/services/data/tear-down/permit-schema.service.js
  app/services/data/tear-down/returns-schema.service.js
  app/services/health/create-redis-client.service.js
  app/services/health/database-health-check.service.js
  app/services/idm/fetch-user-roles-and-groups.service.js
  app/services/import/persist/persist-company.service.js
  app/services/import/persist/persist-licence-versions.service.js
  app/services/jobs/export/write-table-to-file.service.js
  app/services/licences/supplementary/submit-mark-for-supplementary-billing.service.js
  app/services/plugins/auth.service.js
  app/services/plugins/hapi-pino-log-in-test.service.js
  app/services/plugins/payload-cleaning.service.js
  app/services/return-versions/setup/add.service.js
  app/validators/bill-runs/setup/region.validator.js
  app/validators/bill-runs/setup/season.validator.js
  app/validators/bill-runs/setup/type.validator.js
  app/validators/bill-runs/setup/year.validator.js
  app/validators/change-address.validator.js
  app/validators/return-versions/setup/additional-submission-options.validator.js
  app/validators/return-versions/setup/existing.validator.js
  app/validators/return-versions/setup/frequency-reported.validator.js
  app/validators/return-versions/setup/method.validator.js
  app/validators/return-versions/setup/no-returns-required.validator.js
  app/validators/return-versions/setup/note.validator.js
  app/validators/return-versions/setup/points.validator.js
  app/validators/return-versions/setup/purpose.validator.js
  app/validators/return-versions/setup/reason.validator.js
  db/migrations/public/20231215113321_create-sessions.js
  db/seeds/15-sources.seed.js
  test/support/database.js
  test/support/helpers/billing-account.helper.js
  test/support/helpers/mod-log.helper.js
Labels: housekeeping

#1483 Refactor existing supplementary billing flags service
  app/services/licences/supplementary/determine-charge-version-flags.service.js
  app/services/licences/supplementary/determine-charge-version-years.service.js
  app/services/licences/supplementary/determine-return-log-flags.service.js
  app/services/licences/supplementary/determine-return-log-years.service.js
  app/services/licences/supplementary/determine-workflow-flags.service.js
  app/services/licences/supplementary/determine-workflow-years.service.js
  app/services/licences/supplementary/fetch-licence.service.js
  app/services/licences/supplementary/process-billing-flag.service.js
  test/services/licences/supplementary/determine-charge-version-flags.service.test.js
  test/services/licences/supplementary/determine-charge-version-years.service.test.js
  test/services/licences/supplementary/determine-return-log-flags.service.test.js
  test/services/licences/supplementary/determine-return-log-years.service.test.js
  test/services/licences/supplementary/determine-workflow-flags.service.test.js
  test/services/licences/supplementary/determine-workflow-years.service.test.js
  test/services/licences/supplementary/fetch-licence.service.test.js
  test/services/licences/supplementary/process-billing-flag.service.test.js
Labels: housekeeping

#1503 Add await to supplementary controller
  app/controllers/licences.controller.js
Labels: bug

#1502 Ensure ordering of reqs in view return version
  app/services/return-versions/fetch-return-version.service.js
  test/services/return-versions/fetch-return-version.service.test.js
  test/support/seeders/requirements-for-returns.seeder.js
Labels: bug

#1495 Add abstraction method to licence purpose page
  app/models/licence-version-purpose.model.js
  app/presenters/licences/view-licence-purposes.presenter.js
  app/services/licences/fetch-licence-purposes.service.js
  app/views/licences/purposes.njk
  test/models/licence-version-purpose.model.test.js
  test/presenters/licences/view-licence-purposes.presenter.test.js
  test/services/licences/fetch-licence-purposes.service.test.js
  test/services/licences/view-licence-purposes.service.test.js
Labels: housekeeping

#1501 Refactor cancel bill run handling
  app/controllers/bill-runs.controller.js
  app/presenters/bill-runs/view-cancel-bill-run.presenter.js
  app/services/bill-runs/cancel/cancel-bill-run.service.js
  app/services/bill-runs/cancel/delete-bill-run.service.js
  app/services/bill-runs/cancel/submit-cancel-bill-run.service.js
  app/services/bill-runs/cancel/view-cancel-bill-run.service.js
  app/services/bill-runs/submit-cancel-bill-run.service.js
  test/controllers/bill-runs.controller.test.js
  test/presenters/bill-runs/view-cancel-bill-run.presenter.test.js
  test/services/bill-runs/cancel/cancel-bill-run.service.test.js
  test/services/bill-runs/cancel/delete-bill-run.service.test.js
  test/services/bill-runs/cancel/submit-cancel-bill-run.service.test.js
  test/services/bill-runs/cancel/view-cancel-bill-run.service.test.js
  test/services/bill-runs/submit-cancel-bill-run.service.test.js
Labels: housekeeping

#1451 Migrate licence points view page
  app/controllers/licences.controller.js
  app/presenters/licences/view-licence-points.presenter.js
  app/presenters/licences/view-licence-summary.presenter.js
  app/routes/licence.routes.js
  app/services/licences/fetch-licence-points.service.js
  app/services/licences/view-licence-points.service.js
  app/views/licences/points.njk
  app/views/licences/tabs/summary.njk
  config/feature-flags.config.js
  test/controllers/licences.controller.test.js
  test/presenters/licences/view-licence-points.presenter.test.js
  test/presenters/licences/view-licence-summary.presenter.test.js
  test/services/licences/fetch-licence-points.service.test.js
  test/services/licences/view-licence-points.service.test.js
  test/services/licences/view-licence-summary.service.test.js
Labels: enhancement

#1499 Stop returning command-only async calls
  app/requests/charging-module/send-bill-run.request.js
  app/services/bill-runs/annual/process-bill-run.service.js
  app/services/bill-runs/review/remove-review-licence.service.js
  app/services/bill-runs/review/submit-review-bill-run.service.js
  app/services/bill-runs/review/submit-review-licence.service.js
  app/services/bill-runs/setup/create.service.js
  app/services/bill-runs/two-part-tariff/generate-bill-run.service.js
  app/services/data/deduplicate/de-duplicate-licence.service.js
  app/services/import/determine-supplementary-billing-flags.service.js
  app/services/import/persist/persist-company.service.js
  app/services/import/persist/persist-licence-versions.service.js
  app/services/licences/supplementary/persist-supplementary-billing-flags.service.js
  app/services/licences/supplementary/process-imported-licence.service.js
  app/services/return-versions/setup/delete-note.service.js
  app/services/return-versions/setup/submit-cancel.service.js
  app/services/return-versions/setup/submit-remove.service.js
  test/requests/charging-module/send-bill-run-request.test.js
Labels: housekeeping

#1509 Upgrade node to v22
  .nvmrc
Labels: enhancement

#1514 Fix null values in view monitoring station page
  app/presenters/monitoring-stations/view.presenter.js
  app/views/monitoring-stations/view.njk
  test/presenters/monitoring-stations/view.presenter.test.js
  test/services/monitoring-stations/view.service.test.js
Labels: bug

#1513 Set flags for existing return version
  app/services/return-versions/setup/existing/fetch-existing-requirements.service.js
  app/services/return-versions/setup/existing/generate-from-existing-requirements.service.js
  app/services/return-versions/setup/existing/submit-existing.service.js
  test/services/return-versions/setup/existing/fetch-existing-requirements.service.test.js
  test/services/return-versions/setup/existing/generate-from-existing-requirements.service.test.js
  test/services/return-versions/setup/existing/submit-existing.service.test.js
Labels: enhancement

#1506 Add determine licence flags service
  app/services/licences/supplementary/determine-licence-flags.service.js
  app/services/licences/supplementary/process-billing-flag.service.js
  test/services/licences/supplementary/determine-licence-flags.service.test.js
  test/services/licences/supplementary/process-billing-flag.service.test.js
Labels: housekeeping

#1507 Add determine bill licence flags service
  app/services/bill-licences/submit-remove-bill-licence.service.js
  app/services/licences/supplementary/determine-bill-licence-flags.service.js
  app/services/licences/supplementary/process-billing-flag.service.js
  test/services/bill-licences/submit-remove-bill-licence.service.test.js
  test/services/licences/supplementary/determine-bill-licence-flags.service.test.js
  test/services/licences/supplementary/process-billing-flag.service.test.js
Labels: housekeeping

#1518 Update bill run statuses in DetermineExistingBillRunService
  app/services/licences/supplementary/determine-existing-bill-run-years.service.js
  test/services/licences/supplementary/determine-existing-bill-run-years.service.test.js
Labels: housekeeping

#1517 Refactor submit mark for supplementary billing
  app/controllers/licences.controller.js
  app/services/licences/supplementary/submit-mark-for-supplementary-billing.service.js
  test/services/licences/supplementary/submit-mark-for-supplementary-billing.service.test.js
Labels: housekeeping

#1498 Create `.git-blame-ignore-revs` file
  .git-blame-ignore-revs
Labels: housekeeping

#1519 Fix MaxListenersExceededWarning in tests
  test/controllers/bill-licences.controller.test.js
  test/controllers/bill-runs-setup.controller.test.js
  test/controllers/billing-accounts.controller.test.js
  test/controllers/bills.controller.test.js
  test/controllers/check.controller.test.js
  test/controllers/data.controller.test.js
  test/controllers/health.controller.test.js
  test/controllers/import.controller.test.js
  test/controllers/jobs.controller.test.js
  test/controllers/licences.controller.test.js
  test/controllers/monitoring-stations.controller.test.js
  test/controllers/return-versions-setup.controller.test.js
  test/controllers/return-versions.controller.test.js
  test/controllers/root.controller.test.js
  test/plugins/error-pages.plugin.test.js
Labels: housekeeping

#1526 Fix notifications returns period page title
  app/services/notifications/setup/returns-period.service.js
  test/controllers/notifications.controller.test.js
  test/services/notifications/setup/returns-period.services.test.js
Labels: enhancement

#1523 Add determine bill flags service
  app/services/bills/submit-remove-bill.service.js
  app/services/licences/supplementary/fetch-existing-licence-details.service.js
  test/services/bills/submit-remove-bill.services.test.js
  test/services/licences/supplementary/fetch-existing-licence-details.service.test.js
Labels: housekeeping

#1527 Notifications returns period options - January
  app/lib/static-lookups.lib.js
  app/presenters/notifications/setup/returns-period.presenter.js
  test/presenters/notifications/setup/returns-period.presenter.test.js
Labels: enhancement
