Repository DEFRA/water-abstraction-system, pull requests merged in 2024-04, with the labels that each got.

#875 Bump supplementary end year if no annual bill run
  app/services/bill-runs/setup/determine-financial-year-end.service.js
  app/services/bill-runs/setup/exists.service.js
  test/services/bill-runs/setup/determine-financial-year-end.service.test.js
  test/services/bill-runs/setup/exists.service.test.js
Labels: enhancement

#864 Refactor DetermineBillingPeriods to use type
  app/services/bill-runs/determine-billing-periods.service.js
  app/services/bill-runs/setup/create.service.js
  app/services/bill-runs/start-bill-run-process.service.js
  test/services/bill-runs/determine-billing-periods.service.test.js
  test/services/bill-runs/setup/create.service.test.js
Labels: housekeeping

#884 Fix send bill run unflagging licences
  app/services/bill-runs/submit-send-bill-run.service.js
  app/services/bill-runs/supplementary/unflag-billed-licences.service.js
  test/services/bill-runs/submit-send-bill-run.service.test.js
Labels: bug

#814 Persist and retrieve rtn-req set up session values
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/check-your-answers.presenter.js
  app/presenters/return-requirements/start-date.presenter.js
  app/services/return-requirements/check-your-answers.service.js
  app/services/return-requirements/submit-no-returns-required.service.js
  app/services/return-requirements/submit-purpose.service.js
  app/services/return-requirements/submit-reason.service.js
  app/services/return-requirements/submit-setup.service.js
  app/services/return-requirements/submit-start-date.service.js
  app/validators/return-requirements/no-returns-required.validator.js
  app/validators/return-requirements/reason.validator.js
  app/views/return-requirements/check-your-answers.njk
  app/views/return-requirements/no-returns-required.njk
  app/views/return-requirements/reason.njk
  test/presenters/return-requirements/check-your-answers.presenter.test.js
  test/presenters/return-requirements/start-date.presenter.test.js
  test/services/return-requirements/check-your-answers.service.test.js
  test/services/return-requirements/submit-no-returns-required.service.test.js
  test/services/return-requirements/submit-purpose.service.test.js
  test/services/return-requirements/submit-reason.service.test.js
  test/services/return-requirements/submit-setup.service.test.js
  test/services/return-requirements/submit-start-date.service.test.js
  test/validators/no-returns-required/no-returns-required.validator.test.js
  test/validators/no-returns-required/reason.validator.test.js
Labels: enhancement

#889 Fix return link logic on two-part tariff licence review page
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/views/bill-runs/review-licence.njk
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
Labels: housekeeping

#883 Add a remove duplicate licence feature
  app/controllers/data.controller.js
  app/routes/data.routes.js
  app/services/data/deduplicate/de-duplicate-licence.service.js
  app/services/data/deduplicate/submit-deduplicate.service.js
  app/views/data/deduplicate.njk
  db/migrations/legacy/20221108007023-water-return-versions.js
  db/migrations/legacy/20221108007024-water-return-requirements.js
  db/migrations/legacy/20221108007025-water-return-requirement-purposes.js
  test/controllers/data.controller.test.js
  test/services/data/deduplicate/de-duplicate-licence.service.test.js
  test/services/data/deduplicate/submit-deduplicate.service.test.js
Labels: enhancement

#891 Fix DetermineFinancialEndYearService
  app/services/bill-runs/setup/determine-financial-year-end.service.js
  test/services/bill-runs/setup/determine-financial-year-end.service.test.js
Labels: bug

#871 View match details for an element during 2PT review
  app/controllers/bill-runs.controller.js
  app/presenters/bill-runs/two-part-tariff/match-details.presenter.js
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/routes/bill-runs.routes.js
  app/services/bill-runs/two-part-tariff/fetch-match-details.service.js
  app/services/bill-runs/two-part-tariff/match-details.service.js
  app/views/bill-runs/match-details.njk
  app/views/bill-runs/review-licence.njk
  client/sass/application.scss
  test/controllers/bill-runs.controller.test.js
  test/presenters/bill-runs/two-part-tariff/match-details.presenter.test.js
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-match-details.service.test.js
  test/services/bill-runs/two-part-tariff/match-details.service.test.js
Labels: enhancement

#877 Persisting purposes data to session database
  app/presenters/return-requirements/purpose.presenter.js
  app/services/return-requirements/submit-purpose.service.js
  app/validators/return-requirements/purpose.validator.js
  app/views/return-requirements/purpose.njk
  test/presenters/return-requirements/purpose.presenter.test.js
  test/services/return-requirements/purpose.service.test.js
  test/services/return-requirements/submit-purpose.service.test.js
Labels: enhancement

#862 Return requirements link referral
  app/controllers/return-requirements.controller.js
  app/services/return-requirements/check-your-answers.service.js
  app/services/return-requirements/initiate-return-requirement-session.service.js
  app/services/return-requirements/no-returns-required.service.js
  app/services/return-requirements/start-date.service.js
  app/services/return-requirements/submit-no-returns-required.service.js
  app/services/return-requirements/submit-start-date.service.js
  app/views/return-requirements/no-returns-required.njk
  app/views/return-requirements/start-date.njk
  test/controllers/return-requirements.controller.test.js
  test/services/return-requirements/check-your-answers.service.test.js
  test/services/return-requirements/initiate-return-requirement-session.service.test.js
  test/services/return-requirements/no-returns-required.service.test.js
  test/services/return-requirements/start-date.service.test.js
  test/services/return-requirements/submit-no-returns-required.service.test.js
  test/services/return-requirements/submit-start-date.service.test.js
Labels: enhancement

#907 Update /jobs/export to be a POST request
  app/routes/jobs.routes.js
  test/controllers/jobs.controller.test.js
Labels: housekeeping

#908 Fix and update time-limited job
  app/services/jobs/time-limited/fetch-time-limited-licences.service.js
  app/services/jobs/time-limited/process-time-limited-licences.service.js
  test/services/bill-runs/determine-billing-periods.service.test.js
  test/services/jobs/licence-updates/process-licence-updates.service.test.js
  test/services/jobs/time-limited/fetch-time-limited-licences.service.test.js
  test/services/jobs/time-limited/process-time-limited-licences.service.test.js
Labels: bug

#909 Fix unique constraint issue in licences-update job
  app/services/jobs/licence-updates/fetch-licence-updates.service.js
  test/services/jobs/licence-updates/fetch-licence-updates.service.test.js
Labels: bug

#894 Mark Progress when reviewing Licence in 2PT Bill Run
  app/controllers/bill-runs.controller.js
  app/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.js
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/routes/bill-runs.routes.js
  app/services/bill-runs/two-part-tariff/review-licence.service.js
  app/views/bill-runs/review-licence.njk
  app/views/bill-runs/review.njk
  db/migrations/public/20240409101132_alter-review-licences.js
  test/controllers/bill-runs.controller.test.js
  test/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.test.js
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.test.js
  test/services/bill-runs/two-part-tariff/review-licence.service.test.js
  test/support/helpers/purpose.helper.js
  test/support/helpers/review-licence.helper.js
Labels: enhancement

#901 Add calculated column to two-part tariff persisted data
  app/services/bill-runs/two-part-tariff/persist-allocated-licence-to-results.service.js
  db/migrations/public/20240416145558_alter-review-charge-elements-columns.js
  test/services/bill-runs/two-part-tariff/fetch-match-details.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.test.js
  test/services/bill-runs/two-part-tariff/persist-allocated-licence-to-results.service.test.js
  test/support/helpers/review-charge-element.helper.js
Labels: enhancement

#847 Enter the abstraction period for the requirements for returns page
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/abstraction-period.presenter.js
  app/services/return-requirements/abstraction-period.service.js
  app/services/return-requirements/submit-abstraction-period.service.js
  app/validators/return-requirements/abstraction-period.validator.js
  app/views/return-requirements/abstraction-period.njk
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/abstraction-period.presenter.test.js
  test/services/return-requirements/abstraction-period.service.test.js
  test/services/return-requirements/submit-abstraction-period.service.test.js
  test/validators/no-returns-required/abstraction-period.validator.test.js
Labels: enhancement

#917 Fix 2PT volume allocation
  app/services/bill-runs/two-part-tariff/allocate-returns-to-charge-element.service.js
  test/services/bill-runs/two-part-tariff/allocate-returns-to-charge-element.service.test.js
Labels: bug

#920 Fix fetching returns for two part tariff
  app/services/bill-runs/two-part-tariff/fetch-return-logs-for-licence.service.js
  test/services/bill-runs/two-part-tariff/fetch-return-logs-for-licence.service.test.js
Labels: enhancement

#876 Select the returns cycle for the requirements for returns
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/returns-cycle.presenter.js
  app/services/return-requirements/returns-cycle.service.js
  app/services/return-requirements/submit-returns-cycle.service.js
  app/validators/return-requirements/returns-cycle.validator.js
  app/views/return-requirements/returns-cycle.njk
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/returns-cycle.presenter.test.js
  test/services/return-requirements/returns-cycle.service.test.js
  test/services/return-requirements/submit-returns-cycle.service.test.js
  test/validators/no-returns-required/returns-cycle.validator.test.js
Labels: enhancement

#899 Select how often readings or volumes are collected page
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/frequency-collected.presenter.js
  app/services/return-requirements/frequency-collected.service.js
  app/services/return-requirements/submit-frequency-collected.service.js
  app/validators/return-requirements/frequency-collected.validator.js
  app/views/return-requirements/frequency-collected.njk
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/frequency-collected.presenter.test.js
  test/services/return-requirements/frequency-collected.service.test.js
  test/services/return-requirements/submit-frequency-collected.service.test.js
  test/validators/no-returns-required/frequency-collected.validator.test.js
Labels: enhancement

#921 Add new fetch bill runs service
  app/services/bill-runs/fetch-bill-runs.service.js
  config/database.config.js
  test/services/bill-runs/fetch-bill-runs.service.test.js
Labels: enhancement

#922 Add new check 'busy' bill runs service
  app/services/bill-runs/check-busy-bill-runs.service.js
  test/services/bill-runs/check-busy-bill-runs.service.test.js
Labels: enhancement

#918 Manage 2PT Status on Licence review page
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/services/bill-runs/two-part-tariff/review-licence.service.js
  app/views/bill-runs/review-licence.njk
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
  test/services/bill-runs/two-part-tariff/review-licence.service.test.js
Labels: enhancement

#926 Add Hapi yar session manager to the project
  .github/workflows/ci.yml
  app/plugins/yar.plugin.js
  app/server.js
  package-lock.json
  package.json
Labels: enhancement

#924 Add paginator presenter
  app/presenters/paginator.presenter.js
  test/presenters/paginator.presenter.test.js
Labels: enhancement

#906 Returns required journey - Notes page
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/add-note.presenter.js
  app/presenters/return-requirements/check-your-answers.presenter.js
  app/services/return-requirements/add-note.service.js
  app/services/return-requirements/submit-add-note.service.js
  app/validators/return-requirements/add-note.validator.js
  app/views/return-requirements/add-note.njk
  app/views/return-requirements/check-your-answers.njk
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/add-note.presenter.test.js
  test/presenters/return-requirements/check-your-answers.presenter.test.js
  test/services/return-requirements/add-note.service.test.js
  test/services/return-requirements/check-your-answers.service.test.js
  test/services/return-requirements/submit-add-note.service.test.js
  test/validators/no-returns-required/add-note.validator.test.js
Labels: enhancement

#931 Redirect to check-your-answers from reason page
  app/controllers/return-requirements.controller.js
  app/services/return-requirements/submit-reason.service.js
  app/views/return-requirements/reason.njk
  test/services/return-requirements/submit-reason.service.test.js
Labels: bug

#925 Migrate view bill runs page from legacy UI
  app/controllers/bill-runs-setup.controller.js
  app/controllers/bill-runs.controller.js
  app/presenters/bill-runs/index-bill-runs.presenter.js
  app/routes/bill-runs.routes.js
  app/services/bill-runs/index-bill-runs.service.js
  app/views/bill-runs/empty.njk
  app/views/bill-runs/errored.njk
  app/views/bill-runs/index.njk
  app/views/bill-runs/review.njk
  app/views/bill-runs/setup/type.njk
  app/views/bill-runs/view.njk
  app/views/includes/nav-bar.njk
  app/views/macros/bill-run-status-tag.njk
  test/controllers/bill-runs-setup.controller.test.js
  test/controllers/bill-runs.controller.test.js
  test/presenters/bill-runs/index.bill-runs.presenter.test.js
  test/services/bill-runs/index-bill-runs.service.test.js
Labels: enhancement

#932 Returns Required - Reason back link fixed
  app/services/return-requirements/reason.service.js
  test/services/return-requirements/reason.service.test.js
Labels: bug

#928 Refactor review licence POST pattern
  app/controllers/bill-runs.controller.js
  app/routes/bill-runs.routes.js
  app/services/bill-runs/two-part-tariff/review-licence.service.js
  app/services/bill-runs/two-part-tariff/submit-review-licence.service.js
  test/controllers/bill-runs.controller.test.js
  test/services/bill-runs/two-part-tariff/review-licence.service.test.js
  test/services/bill-runs/two-part-tariff/submit-review-licence.service.test.js
Labels: housekeeping

#941 Fix licence status button text
  app/views/bill-runs/review-licence.njk
Labels: bug

#938 Use yar for Review licence flash notifications
  app/controllers/bill-runs.controller.js
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/services/bill-runs/two-part-tariff/review-licence.service.js
  app/services/bill-runs/two-part-tariff/submit-review-licence.service.js
  app/views/bill-runs/review-licence.njk
  test/controllers/bill-runs.controller.test.js
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
  test/services/bill-runs/two-part-tariff/review-licence.service.test.js
  test/services/bill-runs/two-part-tariff/submit-review-licence.service.test.js
Labels: housekeeping

#943 feat: add notification banner to license view
  app/presenters/licences/view-licence.presenter.js
  app/services/licences/fetch-licence.service.js
  app/views/licences/view.njk
  test/presenters/licences/view-licence.presenter.test.js
  test/services/licences/fetch-licence.service.test.js
  test/services/licences/view-licence.service.test.js
Labels: enhancement

#940 Fix validation messages for two-part tariff billable returns page
  app/services/bill-runs/two-part-tariff/submit-amended-billable-returns.service.js
  app/validators/bill-runs/two-part-tariff/billable-returns.validator.js
  app/views/bill-runs/amend-billable-returns.njk
  test/services/bill-runs/two-part-tariff/submit-amended-billable-returns.service.test.js
  test/validators/bill-runs/two-part-tariff/billable-returns.validator.test.js
Labels: bug

#945 Fix bill run status badge in bill runs page
  app/presenters/bill-runs/index-bill-runs.presenter.js
  app/views/macros/bill-run-status-tag.njk
  test/presenters/bill-runs/index.bill-runs.presenter.test.js
Labels: bug

#946 Fix bill run 'busy' tags in bill runs page
  app/presenters/bill-runs/index-bill-runs.presenter.js
  app/views/macros/bill-run-status-tag.njk
  test/presenters/bill-runs/index-bill-runs.presenter.test.js
Labels: housekeeping

#942 Update the two-part tariff review tables to include adjustments
  app/presenters/bill-runs/two-part-tariff/match-details.presenter.js
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/services/bill-runs/two-part-tariff/fetch-charge-versions.service.js
  app/services/bill-runs/two-part-tariff/persist-allocated-licence-to-results.service.js
  app/services/bill-runs/two-part-tariff/submit-amended-billable-returns.service.js
  db/migrations/public/20240425143644_alter-review-tables.js
  test/presenters/bill-runs/two-part-tariff/match-details.presenter.test.js
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-charge-versions.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-match-details.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.test.js
  test/services/bill-runs/two-part-tariff/persist-allocated-licence-to-results.service.test.js
  test/services/bill-runs/two-part-tariff/submit-amended-billable-returns.service.test.js
  test/support/helpers/review-charge-element.helper.js
  test/support/helpers/review-charge-reference.helper.js
Labels: enhancement

#912 Select agreements and exceptions for requirements
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/agreements-exceptions.presenter.js
  app/services/return-requirements/agreements-exceptions.service.js
  app/services/return-requirements/submit-abstraction-period.service.js
  app/services/return-requirements/submit-agreements-exceptions.service.js
  app/services/return-requirements/submit-reason.service.js
  app/validators/return-requirements/agreements-exceptions.validator.js
  app/views/return-requirements/abstraction-period.njk
  app/views/return-requirements/agreements-exceptions.njk
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/agreements-exceptions.presenter.test.js
  test/services/return-requirements/agreements-exceptions.service.test.js
  test/services/return-requirements/submit-abstraction-period.service.test.js
  test/services/return-requirements/submit-agreements-exceptions.service.test.js
  test/validators/no-returns-required/agreements-exceptions.validator.test.js
Labels: enhancement

#933 Fix from and to date to start and end date
  app/presenters/return-requirements/abstraction-period.presenter.js
  app/services/return-requirements/submit-abstraction-period.service.js
  app/validators/return-requirements/abstraction-period.validator.js
  app/views/return-requirements/abstraction-period.njk
  test/presenters/return-requirements/abstraction-period.presenter.test.js
  test/services/return-requirements/abstraction-period.service.test.js
  test/services/return-requirements/submit-abstraction-period.service.test.js
  test/validators/no-returns-required/abstraction-period.validator.test.js
Labels: housekeeping

#954 Fix broken PRESROC review bill run links
  app/presenters/bill-runs/index-bill-runs.presenter.js
  test/presenters/bill-runs/index-bill-runs.presenter.test.js
Labels: bug

#949 Display view licence tabs only to permitted users
  app/controllers/licences.controller.js
  app/presenters/licences/view-licence.presenter.js
  app/services/licences/view-licence.service.js
  app/views/licences/view.njk
  test/presenters/licences/view-licence.presenter.test.js
  test/services/licences/view-licence.service.test.js
Labels: security

#947 Add validation for amend billable returns page
  app/presenters/bill-runs/two-part-tariff/amend-billable-returns.presenter.js
  app/services/bill-runs/two-part-tariff/fetch-match-details.service.js
  app/views/bill-runs/amend-billable-returns.njk
  test/controllers/bill-runs.controller.test.js
  test/presenters/bill-runs/two-part-tariff/amend-billable-returns.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-match-details.service.test.js
Labels: enhancement

#936 Add charge reference links to licence review page
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/views/bill-runs/review-licence.njk
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
Labels: enhancement

#939 Saving input from return requirements in session
  app/presenters/return-requirements/abstraction-period.presenter.js
  app/presenters/return-requirements/points.presenter.js
  app/presenters/return-requirements/reason.presenter.js
  app/presenters/return-requirements/setup.presenter.js
  app/presenters/return-requirements/site-description.presenter.js
  app/services/return-requirements/points.service.js
  app/services/return-requirements/submit-abstraction-period.service.js
  app/services/return-requirements/submit-points.service.js
  app/services/return-requirements/submit-purpose.service.js
  app/services/return-requirements/submit-setup.service.js
  app/services/return-requirements/submit-site-description.service.js
  app/validators/return-requirements/setup.validator.js
  app/views/return-requirements/abstraction-period.njk
  app/views/return-requirements/points.njk
  app/views/return-requirements/reason.njk
  app/views/return-requirements/setup.njk
  app/views/return-requirements/site-description.njk
  test/presenters/return-requirements/abstraction-period.presenter.test.js
  test/presenters/return-requirements/points.presenter.test.js
  test/presenters/return-requirements/reason.presenter.test.js
  test/presenters/return-requirements/setup.presenter.test.js
  test/presenters/return-requirements/site-description.presenter.test.js
  test/services/return-requirements/abstraction-period.service.test.js
  test/services/return-requirements/points.service.test.js
  test/services/return-requirements/reason.service.test.js
  test/services/return-requirements/setup.service.test.js
  test/services/return-requirements/site-description.service.test.js
  test/services/return-requirements/submit-abstraction-period.service.test.js
  test/services/return-requirements/submit-points.service.test.js
  test/services/return-requirements/submit-reason.service.test.js
  test/services/return-requirements/submit-setup.service.test.js
  test/services/return-requirements/submit-site-description.service.test.js
  test/validators/no-returns-required/setup.validator.test.js
Labels: enhancement, housekeeping

#956 Replay submitted data with a validation error
  app/services/return-requirements/submit-start-date.service.js
  test/services/return-requirements/submit-start-date.service.test.js
Labels: enhancement, housekeeping
