Repository DEFRA/water-abstraction-system, pull requests merged in 2024-06, with the labels that each got.

#1067 Tidy up of the Models and comments
  app/models/company-contact.model.js
  app/models/financial-agreement.model.js
  app/models/gauging-station.model.js
  app/models/licence-agreement.model.js
  app/models/licence-gauging-station.model.js
  app/models/licence-version-purpose-condition-type.model.js
  app/models/licence-version-purpose-condition.model.js
  app/models/licence-version-purpose.model.js
  app/models/licence-version.model.js
  app/models/permit-licence.model.js
  app/models/scheduled-notification.model.js
  app/services/bill-runs/generate-transactions.service.js
  app/services/licences/fetch-agreements.service.js
  test/support/helpers/bill-run-volume.helper.js
  test/support/helpers/licence-version-purpose-condition-type.helper.js
  test/support/helpers/licence-version-purpose-condition.helper.js
  test/support/helpers/licence-version-purpose.helper.js
Labels: housekeeping

#1063 Update two-part tariff review views to add Cypress data test attributes
  app/views/bill-runs/amend-billable-returns.njk
  app/views/bill-runs/charge-reference-details.njk
  app/views/bill-runs/match-details.njk
  app/views/bill-runs/review-licence.njk
Labels: enhancement

#1077 Tidy up the file names of legacy migrations
  db/migrations/legacy/20221108002001_crm-document-header.js
  db/migrations/legacy/20221108002002_crm-entity.js
  db/migrations/legacy/20221108002003_crm-entity-roles.js
  db/migrations/legacy/20221108003001_crm-v2-addresses.js
  db/migrations/legacy/20221108003002_crm-v2-contacts.js
  db/migrations/legacy/20221108004001_idm-groups.js
  db/migrations/legacy/20221108004002_idm-roles.js
  db/migrations/legacy/20221108004003_idm-users.js
  db/migrations/legacy/20221108004004_idm-group-roles.js
  db/migrations/legacy/20221108004005_idm-user-groups.js
  db/migrations/legacy/20221108004006_idm-user-roles.js
  db/migrations/legacy/20221108005001_permit-licence.js.js
  db/migrations/legacy/20221108006001_returns-returns.js
  db/migrations/legacy/20221108006002_returns-versions.js
  db/migrations/legacy/20221108006003_returns-lines.js
  db/migrations/legacy/20221108007001_water-regions.js
  db/migrations/legacy/20221108007002_water-billing-charge-categories.js
  db/migrations/legacy/20221108007003_water-change-reasons.js
  db/migrations/legacy/20221108007004_water-events.js
  db/migrations/legacy/20221108007005_water-purposes-uses.js
  db/migrations/legacy/20221108007006_water-licences.js
  db/migrations/legacy/20221108007007_water-licence-versions.js
  db/migrations/legacy/20221108007008_water-licence-version-purposes-table.js
  db/migrations/legacy/20221108007009_water-charge-version-workflows.js
  db/migrations/legacy/20221108007010_water-charge-versions.js
  db/migrations/legacy/20221108007011_water-charge-elements.js
  db/migrations/legacy/20221108007012_water-charge-purposes.js
  db/migrations/legacy/20221108007013_water-billing-batches.js
  db/migrations/legacy/20221108007014_water-billing-volumes.js
  db/migrations/legacy/20221108007015_water-billing-invoices.js
  db/migrations/legacy/20221108007016_water-billing-invoice-licences.js
  db/migrations/legacy/20221108007017_water-billing-transactions.js
  db/migrations/legacy/20221108007018_water-billing-batch-charge-version-years.js
  db/migrations/legacy/20221108007023_water-return-versions.js
  db/migrations/legacy/20221108007024_water-return-requirements.js
  db/migrations/legacy/20221108007025_water-return-requirement-purposes.js
  db/migrations/legacy/20221108007026_water-gauging-stations.js
  db/migrations/legacy/20221108007027_water-licence-gauging-stations.js
  db/migrations/legacy/20221108007028_water-licence-version-purpose-condition-types.js
  db/migrations/legacy/20221108007029_water-licence-version-purpose-conditions.js
  db/migrations/legacy/20221108007030_water-financial-agreement-types.js
  db/migrations/legacy/20221108007031_water-licence-agreements.js
  db/migrations/legacy/20221108007032_water-company-contacts.js
  db/migrations/legacy/20221108007033_water-scheduled-notifications.js
Labels: housekeeping

#1076 Add the agreement exceptions text to the returns requirements check page
  app/presenters/return-requirements/check/returns-requirements.presenter.js
  app/views/return-requirements/check.njk
  test/presenters/return-requirements/check/returns-requirements.presenter.test.js
  test/services/return-requirements/check/returns-requirements.service.test.js
Labels: enhancement

#1080 Remove blipp plugin
  app/plugins/blipp.plugin.js
  app/routes/bill-licences.routes.js
  app/routes/bill-runs-setup.routes.js
  app/routes/bill-runs.routes.js
  app/routes/billing-accounts.routes.js
  app/routes/bills.routes.js
  app/routes/data.routes.js
  app/routes/health.routes.js
  app/routes/jobs.routes.js
  app/routes/licence.routes.js
  app/routes/return-requirement.routes.js
  app/routes/root.routes.js
  app/server.js
  package-lock.json
  package.json
Labels: housekeeping

#1079 Add flash notification when changes occur on returns Requirements
  app/controllers/return-requirements.controller.js
  app/lib/general.lib.js
  app/services/return-requirements/submit-abstraction-period.service.js
  app/services/return-requirements/submit-agreements-exceptions.service.js
  app/services/return-requirements/submit-frequency-collected.service.js
  app/services/return-requirements/submit-frequency-reported.service.js
  app/services/return-requirements/submit-points.service.js
  app/services/return-requirements/submit-purpose.service.js
  app/services/return-requirements/submit-reason.service.js
  app/services/return-requirements/submit-returns-cycle.service.js
  app/services/return-requirements/submit-site-description.service.js
  app/services/return-requirements/submit-start-date.service.js
  test/controllers/return-requirements.controller.test.js
  test/lib/general.lib.test.js
  test/services/return-requirements/submit-abstraction-period.service.test.js
  test/services/return-requirements/submit-agreements-exceptions.service.test.js
  test/services/return-requirements/submit-frequency-collected.service.test.js
  test/services/return-requirements/submit-frequency-reported.service.test.js
  test/services/return-requirements/submit-points.service.test.js
  test/services/return-requirements/submit-purpose.service.test.js
  test/services/return-requirements/submit-reason.service.test.js
  test/services/return-requirements/submit-returns-cycle.service.test.js
  test/services/return-requirements/submit-site-description.service.test.js
  test/services/return-requirements/submit-start-date.service.test.js
Labels: enhancement

#1081 Add copy existing rtn req. option to setup journey
  app/presenters/return-requirements/setup.presenter.js
  app/services/return-requirements/initiate-session.service.js
  app/validators/return-requirements/setup.validator.js
  app/views/return-requirements/setup.njk
  test/presenters/return-requirements/setup.presenter.test.js
  test/services/return-requirements/initiate-session.service.test.js
  test/services/return-requirements/setup.service.test.js
  test/services/return-requirements/submit-setup.service.test.js
Labels: enhancement

#1083 Fix return req. frequency fields in view
  db/migrations/legacy/20221108007024_water-return-requirements.js
  db/migrations/public/20240606104018_create-return-requirements-view.js
Labels: bug

#1084 Two-part tariff review pages - Removing validation
  app/validators/bill-runs/two-part-tariff/adjustment-factor.validator.js
  app/validators/bill-runs/two-part-tariff/authorised-volume.validator.js
  app/views/bill-runs/amend-authorised-volume.njk
  test/validators/bill-runs/two-part-tariff/adjustment-factor.validator.test.js
  test/validators/bill-runs/two-part-tariff/authorised-volume.validator.test.js
Labels: enhancement

#895 Complete Select existing return requirement page
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/existing.presenter.js
  app/services/return-requirements/existing.service.js
  app/services/return-requirements/fetch-existing-requirements.service.js
  app/services/return-requirements/submit-existing.service.js
  app/services/return-requirements/submit-setup.service.js
  app/validators/return-requirements/existing.validator.js
  app/views/return-requirements/existing.njk
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/existing.presenter.test.js
  test/services/return-requirements/existing.service.test.js
  test/services/return-requirements/fetch-existing-requirements.service.test.js
  test/services/return-requirements/submit-existing.service.test.js
  test/services/return-requirements/submit-setup.service.test.js
  test/support/seeders/requirements-for-returns.seeder.js
  test/validators/return-requirements/existing.validator.test.js
Labels: enhancement

#1070 Adding tags to view for acceptance tests (returns)
  app/views/return-requirements/check.njk
  test/services/return-requirements/check/returns-requirements.service.test.js
  test/support/helpers/permit-licence.helper.js
Labels: housekeeping

#1092 Correct copy existing return req. page title
  app/services/return-requirements/existing.service.js
  app/services/return-requirements/submit-existing.service.js
  app/validators/return-requirements/existing.validator.js
  app/views/return-requirements/existing.njk
  test/controllers/return-requirements.controller.test.js
  test/services/return-requirements/existing.service.test.js
  test/services/return-requirements/submit-existing.service.test.js
  test/validators/return-requirements/existing.validator.test.js
Labels: housekeeping

#1096 Fix the title for the requirements for returns check page
  app/presenters/return-requirements/check.presenter.js
  test/presenters/return-requirements/check.presenter.test.js
  test/services/return-requirements/check.service.test.js
Labels: bug

#1094 Add purpose description on two-part tariff licence review page
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.js
  app/views/bill-runs/review-licence.njk
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.test.js
  test/services/bill-runs/two-part-tariff/review-licence.service.test.js
Labels: enhancement

#1093 Adding acceptance test tags for no returns journey
  app/views/return-requirements/check.njk
Labels: housekeeping

#1097 Remove multiple issues showing as review status on two-part tariff pages
  app/services/bill-runs/two-part-tariff/determine-licence-issues.service.js
  test/services/bill-runs/two-part-tariff/determine-licence-issues.service.test.js
Labels: bug

#1088 Add purpose primary and secondary models
  app/models/licence-version-purpose.model.js
  app/models/primary-purpose.model.js
  app/models/return-requirement-purpose.model.js
  app/models/secondary-purpose.model.js
  db/migrations/legacy/20221108007035_water-purposes-primary.js
  db/migrations/legacy/20221108007036_water-purposes-secondary.js
  db/migrations/public/20240611200155_create-primary-purposes-view.js
  db/migrations/public/20240611200206_create-secondary-purposes-view.js
  db/migrations/public/20240611200226_alter-licence-version-purposes-view.js
  db/migrations/public/20240611215502_alter-return-requirement-purposes-view.js
  test/models/licence-version-purpose.model.test.js
  test/models/primary-purpose.model.test.js
  test/models/return-requirement-purpose.model.test.js
  test/models/secondary-purpose.model.test.js
  test/support/helpers/licence-version-purpose.helper.js
  test/support/helpers/primary-purpose.helper.js
  test/support/helpers/return-requirement-purpose.helper.js
  test/support/helpers/secondary-purpose.helper.js
Labels: enhancement

#1095 Add ability to search by Licence Number in 2 Part Tariff Review
  app/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.js
  app/services/bill-runs/two-part-tariff/fetch-bill-run-licences.service.js
  app/services/bill-runs/two-part-tariff/review-bill-run.service.js
  app/services/bill-runs/two-part-tariff/submit-review-bill-run.service.js
  app/views/bill-runs/review.njk
  test/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-bill-run-licences.service.test.js
  test/services/bill-runs/two-part-tariff/review-bill-run.service.test.js
  test/services/bill-runs/two-part-tariff/submit-review-bill-run.service.test.js
Labels: enhancement

#1087 Amend no returns message in view licence Returns tab
  app/presenters/licences/view-licence-returns.presenter.js
  app/services/licences/determine-licence-has-return-versions.service.js
  app/services/licences/view-licence-returns.service.js
  app/services/licences/view-licence.service.js
  app/views/licences/tabs/returns.njk
  test/controllers/licences.controller.test.js
  test/presenters/licences/view-licence-returns-presenter.test.js
  test/services/licences/determine-licence-has-return-versions.service.test.js
  test/services/licences/view-licence-returns.service.test.js
Labels: enhancement

#1054 Display return versions in view licence setup tab
  .env.example
  app/presenters/licences/set-up.presenter.js
  app/services/licences/fetch-return-versions.service.js
  app/services/licences/view-licence-set-up.service.js
  app/views/licences/tabs/set-up.njk
  config/feature-flags.config.js
  test/controllers/licences.controller.test.js
  test/presenters/licences/set-up.presenter.test.js
  test/services/licences/fetch-return-versions.service.test.js
  test/services/licences/view-licence-set-up.service.test.js
Labels: enhancement

#1098 Link licences to licence agreements
  app/models/licence-agreement.model.js
  app/models/licence.model.js
  test/models/licence-agreement.model.test.js
  test/models/licence.model.test.js
Labels: enhancement

#1101 Fix pagination text in 2PT review screen
  app/presenters/paginator.presenter.js
  app/services/bill-runs/two-part-tariff/review-bill-run.service.js
  test/services/bill-runs/two-part-tariff/review-bill-run.service.test.js
Labels: bug

#1104 Fix No returns required missing notification banner
  app/controllers/return-requirements.controller.js
  app/services/return-requirements/submit-no-returns-required.service.js
  test/controllers/return-requirements.controller.test.js
  test/services/licences/view-licence-set-up.service.test.js
  test/services/return-requirements/submit-no-returns-required.service.test.js
Labels: bug

#1105 Update two-part tariff review pages to add Cypress data test attributes
  app/views/bill-runs/review-licence.njk
  app/views/bill-runs/review.njk
Labels: enhancement

#1102 Fix licence 2 licence gauging station relationship
  app/models/licence-gauging-station.model.js
  app/models/licence.model.js
  app/presenters/licences/view-licence-summary.presenter.js
  app/services/licences/fetch-licence-summary.service.js
  app/views/licences/tabs/summary.njk
  db/migrations/legacy/20221108007026_water-gauging-stations.js
  db/migrations/legacy/20221108007027_water-licence-gauging-stations.js
  db/migrations/public/20240613152012_alter-licence-gauging-stations.js
  test/models/gauging-station.model.test.js
  test/models/licence-gauging-station.model.test.js
  test/models/licence.model.test.js
  test/presenters/licences/view-licence-summary.presenter.test.js
  test/services/licences/fetch-licence-summary.service.test.js
  test/services/licences/view-licence-summary.service.test.js
  test/support/helpers/gauging-station.helper.js
  test/support/helpers/licence-gauging-station.helper.js
  test/support/seeders/licence-holder.seeder.js
Labels: bug

#1109 Add Return Requirement helpers to data loader
  app/services/data/load/load.service.js
Labels: housekeeping

#1110 Fix missing view licence returns status tags
  app/presenters/licences/view-licence-returns.presenter.js
  app/services/licences/fetch-licence-returns.service.js
  app/views/licences/tabs/returns.njk
  app/views/macros/return-status-tag.njk
  test/presenters/licences/view-licence-returns.presenter.test.js
Labels: bug

#1107 Use abstraction data to create return requirements
  app/controllers/return-requirements.controller.js
  app/lib/static-lookups.lib.js
  app/services/return-requirements/fetch-licence-agreements.service.js
  app/services/return-requirements/generate-from-existing-requirements.service.js
  app/services/return-requirements/setup/fetch-abstraction-data.service.js
  app/services/return-requirements/setup/generate-from-abstraction-data.service.js
  app/services/return-requirements/setup/setup.service.js
  app/services/return-requirements/setup/submit-setup.service.js
  app/services/return-requirements/submit-existing.service.js
  app/views/return-requirements/agreements-exceptions.njk
  test/controllers/return-requirements.controller.test.js
  test/services/return-requirements/fetch-licence-agreements.service.test.js
  test/services/return-requirements/generate-from-existing-requirements.service.test.js
  test/services/return-requirements/setup/fetch-abstraction-data.service.test.js
  test/services/return-requirements/setup/generate-from-abstraction-data.service.test.js
  test/services/return-requirements/setup/setup.service.test.js
  test/services/return-requirements/setup/submit-setup.service.test.js
  test/services/return-requirements/submit-existing.service.test.js
  test/services/return-requirements/submit-reason.service.test.js
  test/support/seeders/licence-abstraction-data.seeder.js
  test/support/seeders/requirements-for-returns.seeder.js
Labels: enhancement

#1100 Temporary session storage cleanup job
  app/controllers/jobs.controller.js
  app/routes/jobs.routes.js
  app/services/jobs/session-cleanup/process-session-storage-cleanup.service.js
  test/controllers/jobs.controller.test.js
  test/services/jobs/session-cleanup/process-session-storage-cleanup.service.test.js
Labels: enhancement

#1112 Update validation msg for ret. req. copy existing
  app/validators/return-requirements/existing.validator.js
  test/services/return-requirements/submit-existing.service.test.js
  test/validators/return-requirements/existing.validator.test.js
Labels: housekeeping

#1115 Remove additional hr on requirements check page
  app/views/return-requirements/check.njk
Labels: bug

#1114 Update empty requirements for returns message
  app/views/licences/tabs/set-up.njk
  test/controllers/licences.controller.test.js
Labels: bug

#1120 Add charging model to review model relationships
  app/models/charge-element.model.js
  app/models/charge-reference.model.js
  app/models/charge-version.model.js
  test/models/charge-element.model.test.js
  test/models/charge-reference.model.test.js
  test/models/charge-version.model.test.js
Labels: housekeeping

#1122 Add Continue bill run btn to 2PT review screen
  app/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.js
  app/views/bill-runs/review.njk
  test/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.test.js
Labels: enhancement

#1125 Update validation msg for ret. req. copy existing
  app/validators/return-requirements/existing.validator.js
  test/services/return-requirements/submit-existing.service.test.js
  test/validators/return-requirements/existing.validator.test.js
Labels: housekeeping

#1124 Fix Ret. Req. logic to determine cycle for 2PT
  app/services/return-requirements/setup/generate-from-abstraction-data.service.js
  test/services/return-requirements/setup/generate-from-abstraction-data.service.test.js
Labels: bug

#1128 Update two-part tariff review pages to add Cypress data test attributes
  app/views/bill-runs/review-licence.njk
Labels: enhancement

#1123 Add new two-part tariff generate bill run endpoint
  app/controllers/bill-runs.controller.js
  app/routes/bill-runs.routes.js
  app/services/bill-runs/two-part-tariff/generate-bill-run.service.js
  test/controllers/bill-runs.controller.test.js
  test/services/bill-runs/two-part-tariff/generate-bill-run.service.test.js
Labels: enhancement

#1131 Add orderBy to data fetched for two-part tariff review
  app/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.js
  test/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.test.js
Labels: enhancement

#1135 Fix ordering of points and purposes in ret. req.
  app/services/return-requirements/fetch-licence-purposes.service.js
  app/services/return-requirements/fetch-points.service.js
  test/services/return-requirements/fetch-licence-purposes.service.test.js
  test/services/return-requirements/fetch-points.service.test.js
Labels: bug

#1136 Remove points data created during acceptance tests
  app/services/data/tear-down/water-schema.service.js
Labels: enhancement

#1140 Add company address model and relationships
  app/models/address.model.js
  app/models/company-address.model.js
  app/models/company.model.js
  app/models/licence-role.model.js
  app/services/data/load/load.service.js
  db/migrations/legacy/20221108003010_crm-v2-company-addresses.js
  db/migrations/public/20240625082201_create-company-addresses-view.js
  test/models/address.model.test.js
  test/models/company-address.model.test.js
  test/models/company.model.test.js
  test/models/licence-role.model.test.js
  test/support/helpers/company-address.helper.js
Labels: enhancement

#1139 Update two-part tariff review pages to add Cypress data test attributes
  app/views/bill-runs/review-licence.njk
Labels: enhancement

#1141 Fix licence set up links
  app/views/licences/tabs/set-up.njk
Labels: bug

#1142 Fix company contact model relationships
  app/models/company-contact.model.js
  app/models/company.model.js
  app/models/contact.model.js
  app/models/licence-role.model.js
  app/services/licences/fetch-customer-contacts.service.js
  db/migrations/public/20240513134550_create-company-contacts-view.js
  test/models/company-contact.model.test.js
  test/models/company-contacts.model.test.js
  test/models/company.model.test.js
  test/models/contact.model.test.js
  test/models/licence-role.model.test.js
  test/services/licences/fetch-customer-contacts.service.test.js
  test/support/helpers/company-contact.helper.js
Labels: bug

#1143 Lint - spaces around blocks and expressions
  .eslintrc.js
  test/presenters/return-requirements/view.presenter.test.js
Labels: conventions

#1146 Enhance the padding-line lint rules
  .eslintrc.js
  app/controllers/root.controller.js
  app/presenters/base.presenter.js
  app/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.js
  app/presenters/licences/set-up.presenter.js
Labels: housekeeping

#1144 Spike allowing test to be independent of cleanup.
  db/clean.js
  package.json
  test/services/bill-licences/fetch-bill-licence.service.test.js
  test/services/bill-runs/determine-blocking-bill-run.service.test.js
  test/services/bill-runs/fetch-live-bill-runs.service.test.js
  test/services/idm/fetch-user-roles-and-groups.service.test.js
  test/services/licences/fetch-licence-bills.service.test.js
  test/services/licences/fetch-licence.service.test.js
  test/services/return-requirements/initiate-session.service.test.js
  test/support/database.js
Labels: do not merge

#1149 Fetch conditions from licence summary service
  app/models/licence-version-purpose-condition.model.js
  app/models/licence-version-purpose.model.js
  app/presenters/licences/view-licence-summary.presenter.js
  app/services/licences/fetch-licence-abstraction-conditions.service.js
  app/services/licences/fetch-licence-summary.service.js
  app/services/licences/view-licence-summary.service.js
  app/views/licences/tabs/summary.njk
  test/models/licence-version-purpose-condition.model.test.js
  test/models/licence-version-purpose.model.test.js
  test/presenters/licences/view-licence-summary.presenter.test.js
  test/services/licences/fetch-licence-abstraction-conditions.service.test.js
  test/services/licences/fetch-licence-summary.service.test.js
  test/services/licences/view-licence-summary.service.test.js
  test/services/licences/view-licence.service.test.js
Labels: housekeeping
