Repository DEFRA/water-abstraction-system, pull requests merged in 2024-02, with the labels that each got.

#708 Update no-returns-required to use submit service
  app/controllers/return-requirements.controller.js
  app/lib/static-lookups.lib.js
  app/presenters/return-requirements/no-returns-required.presenter.js
  app/services/return-requirements/no-returns-required.service.js
  app/services/return-requirements/submit-no-returns-required.service.js
  app/validators/return-requirements/no-returns-required.validator.js
  app/views/return-requirements/no-returns-required.njk
  test/presenters/return-requirements/no-returns-required.presenter.test.js
  test/services/return-requirements/no-returns-required.service.test.js
  test/services/return-requirements/submit-no-returns-required.service.test.js
  test/validators/no-returns-required/no-returns-required.validator.test.js
Labels: housekeeping

#682 Display purposes in view licence page summary tab
  app/models/licence-version-purpose.model.js
  app/models/licence-version.model.js
  app/presenters/licences/view-licence.presenter.js
  app/services/licences/fetch-licence.service.js
  app/views/licences/tabs/summary.njk
  db/migrations/legacy/20240129145658_create-licence-version-purposes-table.js
  db/migrations/public/20240129151549_create-licence-version-purposes-view.js
  test/models/licence-version-purposes.model.test.js
  test/models/licence-version.model.test.js
  test/presenters/licences/view-licence.presenter.test.js
  test/services/licences/fetch-licence.service.test.js
  test/services/licences/view-licence.service.test.js
  test/support/helpers/licence-version-purpose.helper.js
Labels: enhancement

#705 Connect 2PT bill run request to match & allocate engine
  app/services/bill-runs/handle-errored-bill-run.service.js
  app/services/bill-runs/start-bill-run-process.service.js
  app/services/bill-runs/supplementary/process-bill-run.service.js
  app/services/bill-runs/two-part-tariff/match-and-allocate.service.js
  app/services/bill-runs/two-part-tariff/process-bill-run.service.js
  app/services/bill-runs/two-part-tariff/process-two-part-tariff-returns.service.js
  test/services/bill-runs/start-bill-run-process.service.test.js
  test/services/bill-runs/supplementary/handle-errored-bill-run.service.test.js
  test/services/bill-runs/supplementary/process-bill-run.service.test.js
  test/services/bill-runs/two-part-tariff/match-and-allocate.service.test.js
  test/services/bill-runs/two-part-tariff/process-bill-run.service.test.js
  test/services/bill-runs/two-part-tariff/process-two-part-tariff-returns.service.test.js
Labels: enhancement

#707 View licence summary registered user
  app/presenters/licences/view-licence.presenter.js
  app/services/licences/fetch-licence.service.js
  app/views/licences/view.njk
  test/presenters/licences/view-licence.presenter.test.js
  test/services/licences/fetch-licence.service.test.js
  test/services/licences/view-licence.service.test.js
Labels: enhancement

#713 Fix bill licence charge ref decimal in wrong place
  app/presenters/bill-licences/view-standard-charge-transaction.presenter.js
  test/presenters/bill-licences/view-standard-charge-transaction.presenter.test.js
Labels: bug

#714 Fix bill licence supp source decimal in wrong place
  app/presenters/bill-licences/view-standard-charge-transaction.presenter.js
  test/presenters/bill-licences/view-standard-charge-transaction.presenter.test.js
Labels: bug

#716 Add pre back into protected environments
  app/services/plugins/filter-routes.service.js
Labels: housekeeping

#718 Make requests to the CHA more resilient
  app/lib/charging-module-request.lib.js
  app/lib/request.lib.js
  config/request.config.js
  test/lib/charging-module-request.lib.test.js
  test/lib/request.lib.test.js
Labels: housekeeping

#704 Create review an individual licence for 2PT bill run
  app/controllers/bill-runs.controller.js
  app/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.js
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/routes/bill-runs.routes.js
  app/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.js
  app/services/bill-runs/two-part-tariff/prepare-review-licence-results.service.js
  app/services/bill-runs/two-part-tariff/review-licence.service.js
  app/views/bill-runs/review-licence.njk
  app/views/bill-runs/review.njk
  test/controllers/bill-runs.controller.test.js
  test/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.test.js
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.test.js
  test/services/bill-runs/two-part-tariff/prepare-review-licence-results.service.test.js
  test/services/bill-runs/two-part-tariff/review-bill-run.service.test.js
  test/services/bill-runs/two-part-tariff/review-licence.service.test.js
Labels: enhancement

#719 Stop showing supp source charge as negative
  app/presenters/bill-licences/view-standard-charge-transaction.presenter.js
  test/presenters/bill-licences/view-standard-charge-transaction.presenter.test.js
Labels: bug

#720 Move shared billing services to bill-runs root
  app/services/bill-runs/calculate-authorised-and-billable-days.service.js
  app/services/bill-runs/consolidate-date-ranges.service.js
  app/services/bill-runs/determine-minimum-charge.service.js
  app/services/bill-runs/generate-transactions.service.js
  app/services/bill-runs/supplementary/process-billing-period.service.js
  test/services/bill-runs/calculate-authorised-and-billable-days.service.test.js
  test/services/bill-runs/consolidate-date-ranges.service.test.js
  test/services/bill-runs/determine-minimum-charge.service.test.js
  test/services/bill-runs/generate-transactions.service.test.js
  test/services/bill-runs/supplementary/process-billing-period.service.test.js
Labels: housekeeping

#724 Add wipe test DB function to project
  db/wipe.database.js
  package.json
  test/support/helpers/database.helper.js
Labels: enhancement

#731 Add no returns to licence review page
  app/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.js
  app/services/bill-runs/two-part-tariff/prepare-review-licence-results.service.js
  app/services/bill-runs/two-part-tariff/review-licence.service.js
  app/views/bill-runs/review-licence.njk
  test/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.test.js
Labels: enhancement

#736 Remove abstraction text for under query licence
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
Labels: enhancement

#747 Remove Landing Page From System
  app/controllers/landing-page.controller.js
  app/plugins/router.plugin.js
  app/routes/landing-page.routes.js
  app/views/landing-page.njk
  test/controllers/landing-page.controller.test.js
Labels: housekeeping

#749 Add missed table to tear-down function
  app/services/data/tear-down/water-schema.service.js
Labels: housekeeping

#750 Add relationship - billing acc. <-> chg. version
  app/models/billing-account.model.js
  app/models/charge-version.model.js
  test/models/billing-account.model.test.js
  test/models/charge-version.model.test.js
Labels: housekeeping

#751 Add annual bill run FetchBillingAccountsService
  app/services/bill-runs/annual/fetch-billing-accounts.service.js
  db/migrations/legacy/20221108007011-water-charge-elements.js
  test/services/bill-runs/annual/fetch-billing-accounts.service.test.js
  test/services/bill-runs/generate-transactions.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-charge-versions.service.test.js
Labels: enhancement

#732 Display source of supply in view licence page summary tab
  app/models/licence.model.js
  app/models/permit-licence.model.js
  app/presenters/licences/view-licence.presenter.js
  app/services/licences/fetch-licence.service.js
  app/views/licences/tabs/summary.njk
  db/migrations/legacy/20221108005001-permit-licence.js.js
  db/migrations/public/20240214142212_create-permit-licence-view.js
  test/presenters/licences/view-licence.presenter.test.js
  test/services/licences/fetch-licence.service.test.js
  test/services/licences/view-licence.service.test.js
  test/support/helpers/database.helper.js
  test/support/helpers/permit-licence.helper.js
Labels: enhancement

#753 Add Annual ProcessBillingPeriodService
  .env.example
  app/services/bill-runs/annual/process-billing-period.service.js
  config/billing.config.js
  test/services/bill-runs/annual/process-billing-period.service.test.js
  test/services/bill-runs/supplementary/process-billing-period.service.test.js
Labels: enhancement

#763 Fix annual billing not excluding workflow licences
  app/services/bill-runs/annual/fetch-billing-accounts.service.js
  test/services/bill-runs/annual/fetch-billing-accounts.service.test.js
Labels: bug

#765 Fix bill licences with no transactions in bill run
  app/services/bill-runs/annual/process-billing-period.service.js
  test/services/bill-runs/annual/process-billing-period.service.test.js
Labels: bug

#759 Update allocation engine to handle overdue returns
  app/services/bill-runs/two-part-tariff/allocate-returns-to-charge-element.service.js
  app/services/bill-runs/two-part-tariff/determine-bill-run-issues.service.js
  test/services/bill-runs/two-part-tariff/allocate-returns-to-charge-element.service.test.js
Labels: enhancement

#775 Display public water supply charge in bill licence
  app/presenters/bill-licences/view-standard-charge-transaction.presenter.js
  app/services/bill-licences/fetch-bill-licence.service.js
  test/presenters/bill-licences/view-standard-charge-transaction.presenter.test.js
Labels: enhancement

#764 Determine match and allocate issues and status
  app/services/bill-runs/two-part-tariff/allocate-returns-to-charge-element.service.js
  app/services/bill-runs/two-part-tariff/determine-licence-issues.service.js
  app/services/bill-runs/two-part-tariff/match-and-allocate.service.js
  app/services/bill-runs/two-part-tariff/prepare-return-logs.service.js
  test/services/bill-runs/two-part-tariff/allocate-returns-to-charge-element.service.test.js
  test/services/bill-runs/two-part-tariff/determine-licence-issues.service.test.js
  test/services/bill-runs/two-part-tariff/match-and-allocate.service.test.js
  test/services/bill-runs/two-part-tariff/prepare-return-logs.service.test.js
Labels: enhancement
