Repository DEFRA/water-abstraction-system, pull requests merged in 2024-09, with the labels that each got.

#1303 Fix licence agreements recalculate link bug
  app/presenters/licences/view-licence.presenter.js
  test/presenters/licences/view-licence.presenter.test.js
  test/services/licences/view-licence.service.test.js
Labels: bug

#1299 Only include the required information in the metadata field
  app/services/jobs/return-logs/fetch-return-logs.service.js
  test/services/jobs/return-logs/fetch-return-logs.service.test.js
Labels: housekeeping

#1305 Add relation mapping to `LicenceModel`
  app/models/licence.model.js
  test/models/licence.model.test.js
Labels: enhancement

#1306 Update Banners to incorporate 2PT Supplementary Bills
  app/presenters/licences/view-licence.presenter.js
  app/services/licences/fetch-licence.service.js
  test/presenters/licences/view-licence.presenter.test.js
  test/services/licences/fetch-licence.service.test.js
  test/services/licences/view-licence.service.test.js
Labels: enhancement

#1262 Trigger 2PT Supplementary Bill Run - Pt2
  app/controllers/bill-runs-setup.controller.js
  app/presenters/bill-runs/setup/year.presenter.js
  app/routes/bill-runs-setup.routes.js
  app/services/bill-runs/setup/fetch-licence-supplementary-years.service.js
  app/services/bill-runs/setup/no-licences.service.js
  app/services/bill-runs/setup/submit-region.service.js
  app/services/bill-runs/setup/submit-year.service.js
  app/services/bill-runs/setup/year.service.js
  app/views/bill-runs/setup/no-licences.njk
  app/views/bill-runs/setup/year.njk
  test/controllers/bill-runs-setup.controller.test.js
  test/presenters/bill-runs/setup/year.presenter.test.js
  test/services/bill-runs/setup/fetch-licence-supplementary-years.service.test.js
  test/services/bill-runs/setup/no-licences.service.test.js
  test/services/bill-runs/setup/submit-region.service.test.js
  test/services/bill-runs/setup/submit-year.service.test.js
  test/services/bill-runs/setup/year.service.test.js
Labels: enhancement

#1308 Add missed ModLog and Points models to test loader
  app/services/data/load/load.service.js
  app/services/data/tear-down/water-schema.service.js
Labels: housekeeping

#1309 Add external id to companies view.
  db/migrations/public/20240905081225_alter-companies-view.js
Labels: enhancement

#1311 Fix incorrect edit link for void returns
  app/presenters/licences/view-licence-returns.presenter.js
  test/presenters/licences/view-licence-returns.presenter.test.js
Labels: bug

#1304 Import company data for a licence
  app/presenters/import/legacy/company.presenter.js
  app/services/import/legacy/fetch-company.service.js
  app/services/import/legacy/process-licence.service.js
  app/services/import/legacy/transform-companies.service.js
  app/services/import/persist-licence.service.js
  app/validators/import/company.validator.js
  test/presenters/import/legacy/company.presenter.test.js
  test/services/import/legacy/process-licence.service.test.js
  test/services/import/legacy/transform-companies.service.test.js
  test/services/import/persist-licence.service.test.js
  test/support/helpers/company.helper.js
  test/validators/import/company.validator.test.js
Labels: enhancement

#1313 Fix import licence log silencer
  app/services/plugins/hapi-pino-ignore-request.service.js
  test/services/plugins/hapi-pino-ignore-request.service.test.js
Labels: bug

#1301 Update Return req set up journey to use new points
  app/presenters/return-requirements/check/returns-requirements.presenter.js
  app/presenters/return-requirements/points.presenter.js
  app/services/return-requirements/check.service.js
  app/services/return-requirements/fetch-points.service.js
  app/services/return-requirements/points.service.js
  app/services/return-requirements/setup/fetch-abstraction-data.service.js
  app/services/return-requirements/setup/generate-from-abstraction-data.service.js
  test/presenters/return-requirements/check/returns-requirements.presenter.test.js
  test/presenters/return-requirements/points.presenter.test.js
  test/services/return-requirements/fetch-points.service.test.js
  test/services/return-requirements/points.service.test.js
  test/services/return-requirements/setup/fetch-abstraction-data.service.test.js
  test/services/return-requirements/setup/generate-from-abstraction-data.service.test.js
  test/services/return-requirements/submit-points.service.test.js
  test/support/seeders/licence-abstraction-data.seeder.js
Labels: housekeeping

#1314 Fix use of new points in setup ret. req. journey
  app/presenters/return-requirements/check/returns-requirements.presenter.js
  app/presenters/return-requirements/points.presenter.js
  app/services/return-requirements/fetch-points.service.js
  app/services/return-requirements/setup/fetch-abstraction-data.service.js
  app/services/return-requirements/setup/generate-from-abstraction-data.service.js
  app/views/return-requirements/points.njk
  test/presenters/return-requirements/check/returns-requirements.presenter.test.js
  test/presenters/return-requirements/points.presenter.test.js
  test/services/return-requirements/fetch-points.service.test.js
  test/services/return-requirements/points.service.test.js
  test/services/return-requirements/setup/fetch-abstraction-data.service.test.js
  test/services/return-requirements/setup/generate-from-abstraction-data.service.test.js
  test/services/return-requirements/submit-points.service.test.js
Labels: housekeeping

#1315 Update approve new return req. to use new points
  app/services/return-requirements/generate-return-version-requirements.service.js
  test/services/return-requirements/generate-return-version-requirements.service.test.js
Labels: housekeeping

#1318 Add external id to contacts view.
  db/migrations/public/20240909132727_alter-contacts-view.js
Labels: enhancement

#1319 Add wlrs licence id to the nald licence import
  app/services/import/legacy/fetch-licence.service.js
  app/services/import/legacy/process-licence.service.js
  app/services/import/legacy/transform-licence.service.js
Labels: enhancement

#1320 Amend supplementary billing editing return journey
  app/services/licences/supplementary/determine-return-log-years.service.js
  test/services/licences/supplementary/determine-return-log-years.service.test.js
Labels: bug

#1312 Create seeder for `charge_categories`
  .eslintrc.js
  app/services/data/load/load.service.js
  db/seeds/13-charge-categories.seed.js
  db/seeds/data/charge-categories.js
  test/models/charge-category.model.test.js
  test/models/charge-reference.model.test.js
  test/presenters/charging-module/create-transaction.presenter.test.js
  test/services/bill-runs/annual/fetch-billing-accounts.service.test.js
  test/services/bill-runs/generate-transactions.service.test.js
  test/services/bill-runs/supplementary/fetch-charge-versions.service.test.js
  test/services/bill-runs/supplementary/process-billing-period.service.test.js
  test/services/bill-runs/two-part-tariff/calculate-charge.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-authorised-volume.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-billing-accounts.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-charge-versions.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-charge-reference.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.test.js
  test/services/data/load/load.service.test.js
  test/services/jobs/export/fetch-table.service.test.js
  test/services/jobs/export/write-table-to-file.service.test.js
  test/support/database.js
  test/support/helpers/charge-category.helper.js
  test/support/helpers/transaction.helper.js
Labels: housekeeping

#1323 Increase licence and bill-runs controller test coverage
  test/controllers/bill-runs.controller.test.js
  test/controllers/licences.controller.test.js
Labels: housekeeping

#1324 Put 2PT tariff supplementary option behind flag
  .env.example
  app/services/bill-runs/setup/type.service.js
  app/views/bill-runs/setup/type.njk
  config/feature-flags.config.js
  test/services/bill-runs/setup/type.service.test.js
Labels: bug

#1325 Incorrect status showing on licence set up page
  app/services/return-requirements/generate-return-version.service.js
  test/services/return-requirements/generate-return-version.service.test.js
Labels: bug

#1329 Increase controllers unit test coverage
  test/controllers/bill-licences.controller.test.js
  test/controllers/bill-runs-setup.controller.test.js
  test/controllers/bills.controller.test.js
  test/controllers/jobs.controller.test.js
Labels: housekeeping

#1238 Replace view licence contact details page
  app/controllers/licences.controller.js
  app/presenters/licences/customer-contacts.presenter.js
  app/presenters/licences/licence-contacts.presenter.js
  app/presenters/licences/view-licence-contact-details.presenter.js
  app/routes/licence.routes.js
  app/services/licences/fetch-customer-contacts.service.js
  app/services/licences/fetch-licence-contact-details.service.js
  app/services/licences/fetch-licence-contacts.service.js
  app/services/licences/view-licence-contact-details.service.js
  app/services/licences/view-licence-contacts.service.js
  app/views/licences/licence-contact-details.njk
  app/views/licences/tabs/summary.njk
  test/controllers/licences.controller.test.js
  test/presenters/licences/view-licence-contact-details.presenter.test.js
  test/services/licences/fetch-licence-contact-details.service.test.js
  test/services/licences/view-licence-contact-details.service.test.js
  test/services/licences/view-licence-contacts.service.test.js
Labels: enhancement

#1341 https://eaflood.atlassian.net/browse/WATER-4579
  db/seeds/14-licence-roles.seed.js
  db/seeds/data/licence-roles.js
  test/support/database.js
Labels: testing, conventions

#1346 Add external id to addresses view.
  db/migrations/public/20240918152451_alter-addresses-view.js.js
Labels: enhancement

#1335 Add pre sroc returns flagging to service
  app/services/licences/supplementary/determine-return-log-years.service.js
  test/services/licences/supplementary/determine-return-log-years.service.test.js
Labels: bug

#1317 Import contact data for a licence
  app/presenters/import/legacy/company-contact.presenter.js
  app/presenters/import/legacy/contact.presenter.js
  app/services/import/legacy/fetch-company.service.js
  app/services/import/legacy/fetch-contacts.service.js
  app/services/import/legacy/process-licence.service.js
  app/services/import/legacy/transform-contacts.service.js
  app/services/import/persist-licence.service.js
  app/validators/import/contact.validator.js
  test/presenters/import/legacy/company-contact.presenter.test.js
  test/presenters/import/legacy/contact.presenter.test.js
  test/services/import/legacy/process-licence.service.test.js
  test/services/import/legacy/transform-contacts.service.test.js
  test/services/import/persist-licence.service.test.js
  test/validators/import/contact.validator.test.js
Labels: enhancement

#1357 Fix show unregistered label in view licence page
  app/presenters/licences/view-licence.presenter.js
  app/views/licences/view.njk
  test/presenters/licences/view-licence.presenter.test.js
Labels: bug

#1358 Add site description to rtn. req. bookmark links
  app/views/return-requirements/view.njk
Labels: enhancement

#1359 Alter 2PT agreement logic in rtn req setup journey
  app/services/return-requirements/setup/generate-from-abstraction-data.service.js
  test/services/return-requirements/setup/generate-from-abstraction-data.service.test.js
Labels: housekeeping

#1355 Import addresses data for a licence
  app/presenters/import/legacy/address.presenter.js
  app/services/import/legacy/fetch-address.service.js
  app/services/import/legacy/process-licence.service.js
  app/services/import/legacy/transform-addresses.service.js
  app/services/import/persist-licence.service.js
  app/validators/import/address.validator.js
  test/presenters/import/legacy/address.presenter.test.js
  test/services/import/legacy/process-licence.service.test.js
  test/services/import/legacy/transform-addresses.service.test.js
  test/services/import/persist-licence.service.test.js
  test/support/helpers/address.helper.js
  test/validators/import/address.validator.test.js
Labels: enhancement

#1336 Remove import jobs stats from /health/info
  app/services/health/fetch-import-jobs.service.js
  app/services/health/info.service.js
  app/views/info.njk
  test/services/health/info.service.test.js
Labels: housekeeping

#1363 Incorrect status showing on licence set up page
  app/services/return-requirements/generate-return-version.service.js
  test/services/return-requirements/generate-return-version.service.test.js
Labels: bug

#1364 Include water.points in data tear down
  app/services/data/tear-down/water-schema.service.js
Labels: housekeeping

#1316 Update view licence summary to use new points data
  app/lib/general.lib.js
  app/presenters/licences/view-licence-summary.presenter.js
  app/services/licences/fetch-licence-summary.service.js
  test/presenters/licences/view-licence-summary.presenter.test.js
  test/presenters/return-requirements/check/returns-requirements.presenter.test.js
  test/presenters/return-requirements/view.presenter.test.js
  test/services/licences/fetch-licence-summary.service.test.js
  test/services/licences/view-licence-summary.service.test.js
Labels: housekeeping

#1367 Incorrect status showing on licence set up page
  app/services/return-requirements/process-existing-return-versions.service.js
Labels: bug
