Repository DEFRA/water-abstraction-system, pull requests merged in 2024-03, with the labels that each got.

#777 Add Bill Run Charge Version Years model
  app/models/bill-run-charge-version-year.model.js
  app/models/charge-version.model.js
  db/migrations/legacy/20221108007018-water-billing-batch-charge-version-years.js
  db/migrations/public/20240229170332_create-bill-run-charge-version-years.js
  test/models/bill-run-charge-version-year.model.test.js
  test/models/charge-version.model.test.js
  test/support/helpers/bill-run-charge-version-year.helper.js
Labels: enhancement

#778 Add support for DELETE to RequestLib
  app/lib/request.lib.js
  test/lib/request.lib.test.js
Labels: enhancement

#780 Add cancel bill run page
  app/controllers/bill-runs.controller.js
  app/presenters/bill-runs/cancel-bill-run.presenter.js
  app/routes/bill-runs.routes.js
  app/services/bill-runs/cancel-bill-run.service.js
  app/views/bill-runs/cancel.njk
  app/views/bill-runs/view.njk
  test/presenters/bill-runs/cancel-bill-run.presenter.test.js
  test/services/bill-runs/cancel-bill-run.service.test.js
Labels: enhancement

#782 Add submit cancel bill run endpoint
  app/controllers/bill-runs.controller.js
  app/routes/bill-runs.routes.js
  app/services/bill-runs/submit-cancel-bill-run.service.js
  test/controllers/bill-runs.controller.test.js
  test/services/bill-runs/submit-cancel-bill-run.service.test.js
Labels: enhancement

#784 Fix badge for empty status
  app/views/bill-runs/cancel.njk
  app/views/bill-runs/empty.njk
  app/views/bill-runs/view.njk
  app/views/bills/view-multi-licence.njk
  app/views/bills/view-single-licence-presroc.njk
  app/views/bills/view-single-licence-sroc.njk
  app/views/macros/badge.njk
Labels: bug

#785 Migrate view errored bill run page
  app/presenters/bill-runs/empty-bill-run-presenter.js
  app/presenters/bill-runs/errored-bill-run-presenter.js
  app/services/bill-runs/fetch-bill-run.service.js
  app/services/bill-runs/view-bill-run.service.js
  app/views/bill-runs/errored.njk
  app/views/macros/badge.njk
  test/presenters/bill-runs/errored-bill-run.presenter.test.js
  test/services/bill-runs/view-bill-run.service.test.js
Labels: enhancement

#786 Remove unused frontend macros from cancel view
  app/views/bill-runs/cancel.njk
Labels: housekeeping

#787 Fix cancel back link to PRESROC 2pt review
  app/presenters/bill-runs/cancel-bill-run.presenter.js
  test/presenters/bill-runs/cancel-bill-run.presenter.test.js
Labels: bug

#781 Alter `return_logs` view
  app/services/bill-runs/two-part-tariff/fetch-return-logs-for-licence.service.js
  app/services/bill-runs/two-part-tariff/persist-allocated-licence-to-results.service.js
  app/services/check/scenario-formatter.service.js
  db/migrations/public/20240301151323_alter-return-logs-view.js
  test/services/bill-runs/two-part-tariff/match-and-allocate.service.test.js
  test/services/bill-runs/two-part-tariff/persist-allocated-licence-to-results.service.test.js
  test/services/bill-runs/two-part-tariff/prepare-return-logs.service.test.js
  test/support/helpers/return-log.helper.js
  test/support/helpers/review-return-result.helper.js
Labels: housekeeping

#794 Move currentFinancialYear() from test
  app/lib/general.lib.js
  app/services/bill-runs/determine-billing-periods.service.js
  test/lib/general.lib.test.js
  test/services/bill-runs/annual/fetch-billing-accounts.service.test.js
  test/services/bill-runs/annual/process-bill-run.service.test.js
  test/services/bill-runs/annual/process-billing-period.service.test.js
  test/services/bill-runs/check-live-bill-run.service.test.js
  test/support/helpers/general.helper.js
  test/support/helpers/transaction.helper.js
Labels: housekeeping

#796 Add defra-user-id header to legacy requests
  app/lib/legacy-request.lib.js
  test/lib/legacy-request.lib.test.js
Labels: enhancement

#797 Migrate Charging Module services to *.request.js
  app/plugins/charging-module-token-cache.plugin.js
  app/requests/base.request.js
  app/requests/charging-module.request.js
  app/requests/charging-module/create-bill-run.request.js
  app/requests/charging-module/create-customer-change.request.js
  app/requests/charging-module/create-transaction.request.js
  app/requests/charging-module/delete-bill-run.request.js
  app/requests/charging-module/generate-bill-run.request.js
  app/requests/charging-module/reissue-bill.request.js
  app/requests/charging-module/token.request.js
  app/requests/charging-module/view-bill-run-status.request.js
  app/requests/charging-module/view-bill.request.js
  app/requests/legacy.request.js
  app/services/bill-runs/annual/process-bill-run.service.js
  app/services/bill-runs/initiate-bill-run.service.js
  app/services/bill-runs/send-transactions.service.js
  app/services/bill-runs/submit-cancel-bill-run.service.js
  app/services/bill-runs/supplementary/process-bill-run.service.js
  app/services/bill-runs/supplementary/reissue-bill.service.js
  app/services/billing-accounts/send-customer-change.service.js
  app/services/charging-module/bill-run-status.service.js
  app/services/charging-module/create-bill-run.service.js
  app/services/charging-module/create-customer-change.service.js
  app/services/charging-module/create-transaction.service.js
  app/services/charging-module/generate-bill-run.service.js
  app/services/charging-module/reissue-bill.service.js
  app/services/charging-module/view-bill.service.js
  app/services/health/info.service.js
  test/lib/general.lib.test.js
  test/lib/legacy-db-snake-case-mappers.lib.test.js
  test/plugins/charging-module-token-cache.plugin.test.js
  test/requests/base.request.test.js
  test/requests/charging-module.request.test.js
  test/requests/charging-module/create-bill-run.request.test.js
  test/requests/charging-module/create-customer-change.request.test.js
  test/requests/charging-module/create-transaction.request.test.js
  test/requests/charging-module/delete-bill-run.request.test.js
  test/requests/charging-module/generate-bill-run.request.test.js
  test/requests/charging-module/reissue-bill.request.test.js
  test/requests/charging-module/token.request.test.js
  test/requests/charging-module/view-bill-run-status.request.test.js
  test/requests/charging-module/view-bill.request.test.js
  test/requests/legacy.request.test.js
  test/services/bill-runs/annual/process-bill-run.service.test.js
  test/services/bill-runs/annual/process-billing-period.service.test.js
  test/services/bill-runs/initiate-bill-run.service.test.js
  test/services/bill-runs/send-transactions.service.test.js
  test/services/bill-runs/submit-cancel-bill-run.service.test.js
  test/services/bill-runs/supplementary/handle-errored-bill-run.service.test.js
  test/services/bill-runs/supplementary/process-bill-run.service.test.js
  test/services/bill-runs/supplementary/process-billing-period.service.test.js
  test/services/bill-runs/supplementary/reissue-bill.service.test.js
  test/services/bill-runs/supplementary/reissue-bills.service.test.js
  test/services/billing-accounts/send-customer-change.service.test.js
  test/services/health/info.service.test.js
Labels: housekeeping

#798 Move legacy refresh requests to module
  app/requests/charging-module/generate-bill-run.request.js
  app/requests/legacy/refresh-bill-run.request.js
  app/services/bill-runs/annual/process-bill-run.service.js
  app/services/bill-runs/supplementary/process-bill-run.service.js
  test/requests/legacy/refresh-bill-run.request.test.js
  test/services/bill-runs/annual/process-bill-run.service.test.js
  test/services/bill-runs/supplementary/process-bill-run.service.test.js
  test/services/bill-runs/supplementary/reissue-bills.service.test.js
Labels: housekeeping

#799 Return instead of await requests
  app/requests/charging-module/create-customer-change.request.js
  app/requests/charging-module/create-transaction.request.js
  app/requests/charging-module/delete-bill-run.request.js
  app/requests/charging-module/generate-bill-run.request.js
  app/requests/charging-module/reissue-bill.request.js
  app/requests/charging-module/view-bill-run-status.request.js
  app/requests/charging-module/view-bill.request.js
  app/requests/legacy/refresh-bill-run.request.js
Labels: housekeeping

#800 Add legacy create bill run request
  app/requests/legacy/create-bill-run.request.js
  test/requests/legacy/create-bill-run.request.test.js
Labels: enhancement

#801 Add first route to bill run setup journey
  app/controllers/bill-runs-setup.controller.js
  app/plugins/router.plugin.js
  app/routes/bill-runs-setup.routes.js
  app/services/bill-runs/setup/initiate-session.service.js
  test/controllers/bill-runs-setup.controller.test.js
  test/services/bill-runs/setup/initialise-session.service.test.js
Labels: enhancement

#802 Add bill runs setup type page to journey
  app/controllers/bill-runs-setup.controller.js
  app/presenters/bill-runs/setup/type.presenter.js
  app/routes/bill-runs-setup.routes.js
  app/services/bill-runs/setup/submit-type.service.js
  app/services/bill-runs/setup/type.service.js
  app/validators/bill-runs/setup/type.validator.js
  app/views/bill-runs/setup/type.njk
  test/controllers/bill-runs-setup.controller.test.js
  test/presenters/bill-runs/setup/type.presenter.test.js
  test/services/bill-runs/setup/submit-type.service.test.js
  test/services/bill-runs/setup/type.service.test.js
  test/validators/bill-runs/setup/type.validator.test.js
Labels: enhancement

#803 Make the test helper licence ref more random
  test/support/helpers/licence.helper.js
Labels: bug

#805 Add bill runs setup financial year page to journey
  app/controllers/bill-runs-setup.controller.js
  app/presenters/bill-runs/setup/year.presenter.js
  app/routes/bill-runs-setup.routes.js
  app/services/bill-runs/setup/region.service.js
  app/services/bill-runs/setup/submit-year.service.js
  app/services/bill-runs/setup/type.service.js
  app/services/bill-runs/setup/year.service.js
  app/validators/bill-runs/setup/year.validator.js
  app/views/bill-runs/setup/year.njk
  test/controllers/bill-runs-setup.controller.test.js
  test/presenters/bill-runs/setup/year.presenter.test.js
  test/services/bill-runs/setup/submit-region.service.test.js
  test/services/bill-runs/setup/submit-type.service.test.js
  test/services/bill-runs/setup/submit-year.service.test.js
  test/services/bill-runs/setup/year.service.test.js
  test/validators/bill-runs/setup/year.validator.test.js
Labels: enhancement

#807 Fix missing page titles from 500 and 404
  app/views/404.njk
  app/views/500.njk
Labels: bug

#808 Add bill runs setup season page to journey
  app/controllers/bill-runs-setup.controller.js
  app/presenters/bill-runs/setup/season.presenter.js
  app/routes/bill-runs-setup.routes.js
  app/services/bill-runs/setup/season.service.js
  app/services/bill-runs/setup/submit-region.service.js
  app/services/bill-runs/setup/submit-season.service.js
  app/validators/bill-runs/setup/season.validator.js
  app/views/bill-runs/setup/season.njk
  test/controllers/bill-runs-setup.controller.test.js
  test/presenters/bill-runs/setup/season.presenter.test.js
  test/services/bill-runs/setup/season.service.test.js
  test/services/bill-runs/setup/submit-season.service.test.js
  test/validators/bill-runs/setup/season.validator.test.js
Labels: enhancement

#810 Handle bill run setup matches an existing bill run
  app/controllers/bill-runs-setup.controller.js
  app/presenters/bill-runs/setup/create.presenter.js
  app/routes/bill-runs-setup.routes.js
  app/services/bill-runs/setup/exists.service.js
  app/services/bill-runs/setup/fetch-matching-bill-run.service.js
  app/views/bill-runs/setup/create.njk
  test/controllers/bill-runs-setup.controller.test.js
  test/presenters/bill-runs/setup/create.presenter.test.js
  test/services/bill-runs/setup/exists.service.test.js
  test/services/bill-runs/setup/fetch-matching-bill-run.service.test.js
Labels: enhancement

#812 Add creating the bill run to end of setup journey
  app/controllers/bill-runs-setup.controller.js
  app/services/bill-runs/setup/create.service.js
  app/services/bill-runs/setup/exists.service.js
  test/controllers/bill-runs-setup.controller.test.js
  test/services/bill-runs/setup/create.service.test.js
  test/services/bill-runs/setup/exists.service.test.js
Labels: enhancement

#818 Fix matching logic in bill run setup
  app/services/bill-runs/setup/determine-blocking-bill-run.service.js
  app/services/bill-runs/setup/exists.service.js
  app/services/bill-runs/setup/fetch-live-bill-runs.service.js
  test/services/bill-runs/setup/determine-blocking-bill-run.service.test.js
  test/services/bill-runs/setup/exists.service.test.js
  test/services/bill-runs/setup/fetch-live-bill-runs.service.test.js
Labels: bug

#774 Select the purpose for the requirements for returns page
  app/controllers/return-requirements.controller.js
  app/models/licence-version-purpose.model.js
  app/models/purpose.model.js
  app/presenters/return-requirements/purpose.presenter.js
  app/routes/return-requirement.routes.js
  app/services/return-requirements/fetch-purposes.service.js
  app/services/return-requirements/purpose.service.js
  app/services/return-requirements/submit-purpose.service.js
  app/validators/return-requirements/purpose.validator.js
  app/views/return-requirements/purpose.njk
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/purpose.presenter.test.js
  test/services/return-requirements/fetch-purposes.service.test.js
  test/services/return-requirements/purpose.service.test.js
  test/services/return-requirements/submit-purpose.service.test.js
  test/validators/no-returns-required/purpose.validator.test.js
Labels: enhancement

#809 Filter Licences by Licence Holder Name on the 2PT Review Licences Page
  app/controllers/bill-runs.controller.js
  app/models/bill-run.model.js
  app/models/review-licence.model.js
  app/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.js
  app/routes/bill-runs.routes.js
  app/services/bill-runs/two-part-tariff/fetch-bill-run-licences.service.js
  app/services/bill-runs/two-part-tariff/review-bill-run.service.js
  app/views/bill-runs/review.njk
  test/controllers/bill-runs.controller.test.js
  test/models/bill-run.model.test.js
  test/models/review-licence.model.test.js
  test/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-bill-run-licences.service.test.js
Labels: enhancement

#825 Add DELETE support to LegacyRequest
  app/requests/legacy.request.js
  test/requests/legacy.request.test.js
Labels: enhancement

#826 Add Legacy DeleteBillLicenceRequest
  app/requests/legacy/delete-bill-licence.request.js
  test/requests/legacy/delete-bill-licence.request.test.js
Labels: enhancement

#827 Add relationship between bill and billing account
  app/models/bill.model.js
  app/models/billing-account.model.js
  test/models/bill.model.test.js
  test/models/billing-account.model.test.js
Labels: enhancement

#828 Migrate confirm remove licence from bill run page
  app/controllers/bill-licences.controller.js
  app/presenters/bill-licences/remove-bill-licence.presenter.js
  app/routes/bill-licences.routes.js
  app/services/bill-licences/fetch-bill-licence-summary.service.js
  app/services/bill-licences/remove-bill-licence.service.js
  app/services/bill-licences/submit-remove-bill-licence.service.js
  app/views/bill-licences/remove.njk
  test/controllers/bill-licences.controller.test.js
  test/presenters/bill-licences/remove-bill-licence.presenter.test.js
  test/services/bill-licences/fetch-bill-licence-summary.service.test.js
  test/services/bill-licences/remove-bill-licence.service.test.js
  test/services/bill-licences/submit-remove-bill-licence.service.test.js
  test/support/helpers/contact.helper.js
Labels: enhancement

#829 Add new Charging Module WaitForStatusRequest
  .env.example
  app/requests/charging-module/wait-for-status.request.js
  config/billing.config.js
  test/requests/charging-module/wait-for-status.request.test.js
Labels: enhancement

#830 Add new Charging Module ViewBillRunRequest
  app/requests/charging-module/view-bill-run.request.js
  test/requests/charging-module/view-bill-run.request.test.js
Labels: enhancement

#831 Add new Charging Module SendBillRunRequest
  app/requests/charging-module/send-bill-run.request.js
  test/requests/charging-module/send-bill-run-request.test.js
Labels: enhancement

#771 Migrate legacy send bill run functionality
  app/controllers/bill-runs.controller.js
  app/presenters/bill-runs/send-bill-run.presenter.js
  app/routes/bill-runs.routes.js
  app/services/bill-runs/send-bill-run.service.js
  app/services/bill-runs/submit-send-bill-run.service.js
  app/views/bill-runs/send.njk
  app/views/bill-runs/view.njk
  test/controllers/bill-runs.controller.test.js
  test/presenters/bill-runs/send-bill-run.presenter.test.js
  test/requests/charging-module/send-bill-run.request.test.js
  test/services/bill-runs/send-bill-run.service.test.js
Labels: enhancement

#824 Add missed remove licence button
  app/presenters/bill-licences/view-bill-licence.presenter.js
  app/services/bill-licences/fetch-bill-licence.service.js
  app/views/bill-licences/view-presroc.njk
  app/views/bill-licences/view-sroc.njk
  test/presenters/bill-licences/view-bill-licence.presenter.test.js
  test/services/bill-licences/fetch-bill-licence.service.test.js
Labels: bug

#823 Fix std charge transaction presenter for S130
  app/presenters/bill-licences/view-standard-charge-transaction.presenter.js
  test/presenters/bill-licences/view-standard-charge-transaction.presenter.test.js
Labels: bug

#838 Add Legacy DeleteBillRequest
  app/requests/legacy/delete-bill.request.js
  test/requests/legacy/delete-bill.request.test.js
Labels: enhancement

#811 Submit Check your answers page
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/check-your-answers.presenter.js
  app/services/return-requirements/check-licence-ended.service.js
  app/services/return-requirements/check-your-answers.service.js
  app/services/return-requirements/submit-check-your-answers.service.js
  app/views/return-requirements/check-your-answers.njk
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/check-your-answers.presenter.test.js
  test/services/return-requirements/check-licence-ended.service.test.js
  test/services/return-requirements/check-your-answers.service.test.js
  test/services/return-requirements/submit-check-your-answers.service.test.js
Labels: enhancement

#835 Filter licences by status on the 2PT Review Licences Page
  app/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.js
  app/services/bill-runs/two-part-tariff/fetch-bill-run-licences.service.js
  app/services/bill-runs/two-part-tariff/review-bill-run.service.js
  app/views/bill-runs/review.njk
  test/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-bill-run-licences.service.test.js
  test/services/bill-runs/two-part-tariff/review-bill-run.service.test.js
  test/support/helpers/purpose.helper.js
Labels: enhancement

#841 Fix broken CheckLiveBillRunService
  app/services/bill-runs/check-live-bill-run.service.js
Labels: bug

#843 Replace live bill run checking in engine
  app/services/bill-runs/check-live-bill-run.service.js
  app/services/bill-runs/determine-blocking-bill-run.service.js
  app/services/bill-runs/fetch-live-bill-runs.service.js
  app/services/bill-runs/fetch-matching-bill-run.service.js
  app/services/bill-runs/initiate-bill-run.service.js
  app/services/bill-runs/setup/exists.service.js
  test/services/bill-runs/check-live-bill-run.service.test.js
  test/services/bill-runs/determine-blocking-bill-run.service.test.js
  test/services/bill-runs/fetch-live-bill-runs.service.test.js
  test/services/bill-runs/fetch-matching-bill-run.service.test.js
  test/services/bill-runs/initiate-bill-run.service.test.js
  test/services/bill-runs/setup/exists.service.test.js
Labels: housekeeping

#845 Fix FetchLiveBillRunsService
  app/services/bill-runs/fetch-live-bill-runs.service.js
  test/services/bill-runs/fetch-live-bill-runs.service.test.js
Labels: bug

#849 Fix supplementary flags not clearing after 'send'
  app/services/bill-runs/submit-send-bill-run.service.js
  app/services/bill-runs/supplementary/unflag-billed-licences.service.js
  test/services/bill-runs/supplementary/unflag-billed-licences.service.test.js
Labels: bug

#852 Do not unflag all SROC supplementary
  app/services/bill-runs/supplementary/process-bill-run.service.js
  app/services/bill-runs/supplementary/unflag-billed-licences.service.js
  app/services/bill-runs/supplementary/unflag-unbilled-licences.service.js
  test/services/bill-runs/supplementary/unflag-billed-licences.service.test.js
  test/services/bill-runs/supplementary/unflag-unbilled-licences.service.test.js
Labels: enhancement

#851 Add missing SubmitSendBillRunService unit tests
  app/services/bill-runs/submit-cancel-bill-run.service.js
  app/services/bill-runs/submit-send-bill-run.service.js
  test/services/bill-runs/submit-send.service.test.js
Labels: housekeeping

#854 Silo rebilling from supplementary
  app/services/bill-runs/reissue/README.md
  app/services/bill-runs/reissue/fetch-bills-to-be-reissued.service.js
  app/services/bill-runs/reissue/reissue-bill.service.js
  app/services/bill-runs/reissue/reissue-bills.service.js
  app/services/bill-runs/supplementary/process-bill-run.service.js
  test/services/bill-runs/reissue/fetch-bills-to-be-reissued.service.test.js
  test/services/bill-runs/reissue/reissue-bill.service.test.js
  test/services/bill-runs/reissue/reissue-bills.service.test.js
  test/services/bill-runs/supplementary/process-bill-run.service.test.js
Labels: housekeeping

#855 Move transaction matching logic to GeneralLib
  app/lib/general.lib.js
  app/services/bill-runs/supplementary/fetch-previous-transactions.service.js
  app/services/bill-runs/supplementary/process-transactions.service.js
  test/lib/general.lib.test.js
  test/services/bill-runs/supplementary/fetch-previous-transactions.service.test.js
  test/services/bill-runs/supplementary/process-transactions.service.test.js
Labels: housekeeping

#856 Remove generate bill and bill licence services
  app/services/bill-runs/reissue/reissue-bill.service.js
  app/services/bill-runs/supplementary/generate-bill-licence.service.js
  app/services/bill-runs/supplementary/generate-bill.service.js
  app/services/bill-runs/supplementary/pre-generate-billing-data.service.js
  test/services/bill-runs/supplementary/generate-bill-licence.service.test.js
  test/services/bill-runs/supplementary/generate-bill.service.test.js
Labels: housekeeping

#857 Supplementary billing housekeeping
  app/services/bill-runs/annual/process-bill-run.service.js
  app/services/bill-runs/supplementary/fetch-previous-transactions.service.js
  app/services/bill-runs/supplementary/process-billing-period.service.js
  app/services/bill-runs/supplementary/process-transactions.service.js
  app/services/bill-runs/supplementary/reverse-transactions.service.js
  test/services/bill-runs/handle-errored-bill-run.service.test.js
  test/services/bill-runs/supplementary/fetch-previous-transactions.service.test.js
  test/services/bill-runs/supplementary/process-transactions.service.test.js
  test/services/bill-runs/supplementary/reverse-transactions.service.test.js
Labels: housekeeping

#833 Select the points for the requirements for returns page
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/points.presenter.js
  app/presenters/return-requirements/purpose.presenter.js
  app/routes/return-requirement.routes.js
  app/services/return-requirements/fetch-points.service.js
  app/services/return-requirements/points.service.js
  app/services/return-requirements/submit-points.service.js
  app/validators/return-requirements/points.validator.js
  app/views/return-requirements/points.njk
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/points.presenter.test.js
  test/services/return-requirements/fetch-points.service.test.js
  test/services/return-requirements/points.service.test.js
  test/services/return-requirements/submit-points.service.test.js
  test/validators/no-returns-required/points.validator.test.js
Labels: enhancement

#859 Fix determine billing periods
  app/services/bill-runs/setup/create.service.js
  test/services/bill-runs/determine-billing-periods.service.test.js
  test/services/bill-runs/setup/create.service.test.js
Labels: bug

#861 Fix duplicated abstraction points for return requirements points page
  app/presenters/return-requirements/points.presenter.js
  test/presenters/return-requirements/points.presenter.test.js
Labels: bug

#860 Fix legacy requests for /heath/info page
  app/services/health/info.service.js
  test/services/health/info.service.test.js
Labels: bug

#863 Fix bill run exists page for bill runs in review
  app/presenters/bill-runs/setup/create.presenter.js
  app/views/bill-runs/setup/create.njk
  test/controllers/bill-runs-setup.controller.test.js
  test/presenters/bill-runs/setup/create.presenter.test.js
Labels: bug

#842 Filter licences by issue on the 2PT Review Licences Page
  app/lib/static-lookups.lib.js
  app/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.js
  app/services/bill-runs/two-part-tariff/determine-licence-issues.service.js
  app/services/bill-runs/two-part-tariff/fetch-bill-run-licences.service.js
  app/services/bill-runs/two-part-tariff/review-bill-run.service.js
  app/views/bill-runs/review.njk
  test/controllers/bill-runs.controller.test.js
  test/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.test.js
  test/services/bill-runs/two-part-tariff/determine-licence-issues.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-bill-run-licences.service.test.js
  test/services/bill-runs/two-part-tariff/review-bill-run.service.test.js
Labels: enhancement

#866 Remove redundant fetch for region code in service
  app/services/bill-runs/two-part-tariff/fetch-charge-versions.service.js
  test/services/bill-runs/two-part-tariff/fetch-charge-versions.service.test.js
Labels: housekeeping

#870 Fix FetchMatchingBillRunService for PRESROC 2PT
  app/services/bill-runs/fetch-matching-bill-run.service.js
  test/services/bill-runs/fetch-matching-bill-run.service.test.js
Labels: bug

#806 Review an individual licence page
  app/controllers/bill-runs.controller.js
  app/models/review-charge-element.model.js
  app/models/review-charge-reference.model.js
  app/models/review-charge-version.model.js
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.js
  app/services/bill-runs/two-part-tariff/review-licence.service.js
  app/services/bills/view-bill.service.js
  app/services/fetch-billing-account.service.js
  app/views/bill-runs/review-licence.njk
  client/sass/application.scss
  test/controllers/bill-runs.controller.test.js
  test/models/review-charge-element.model.test.js
  test/models/review-charge-reference.model.test.js
  test/models/review-charge-version.model.test.js
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.test.js
  test/services/bill-runs/two-part-tariff/review-licence.service.test.js
  test/services/bills/view-bill.service.test.js
  test/services/fetch-billing-account.service.test.js
Labels: enhancement

#867 Fix licence issues failing to insert for review
  app/services/bill-runs/two-part-tariff/determine-licence-issues.service.js
  db/migrations/public/20240327200101_alter-review-issues-columns.js
  test/services/bill-runs/two-part-tariff/determine-licence-issues.service.test.js
Labels: bug

#869 Fix error in match & allocate service crashing app
  app/services/bill-runs/two-part-tariff/determine-licence-issues.service.js
  app/services/bill-runs/two-part-tariff/match-and-allocate.service.js
Labels: bug
