Repository DEFRA/water-abstraction-system, pull requests merged in 2024-05, with the labels that each got.

#959 Return to Check Your Answers after making a change
  app/controllers/return-requirements.controller.js
  app/services/return-requirements/submit-abstraction-period.service.js
  app/services/return-requirements/submit-agreements-exceptions.service.js
  app/services/return-requirements/submit-frequency-collected.service.js
  app/services/return-requirements/submit-frequency-reported.service.js
  app/services/return-requirements/submit-points.service.js
  app/services/return-requirements/submit-purpose.service.js
  app/services/return-requirements/submit-returns-cycle.service.js
  app/services/return-requirements/submit-site-description.service.js
  test/services/return-requirements/submit-abstraction-period.service.test.js
  test/services/return-requirements/submit-agreements-exceptions.service.test.js
  test/services/return-requirements/submit-frequency-collected.service.test.js
  test/services/return-requirements/submit-frequency-reported.service.test.js
  test/services/return-requirements/submit-points.service.test.js
  test/services/return-requirements/submit-purpose.service.test.js
  test/services/return-requirements/submit-returns-cycle.service.test.js
  test/services/return-requirements/submit-site-description.service.test.js
Labels: enhancement

#965 How do you want to set up H1 Title text change
  app/routes/return-requirement.routes.js
  app/services/return-requirements/setup.service.js
  app/services/return-requirements/submit-setup.service.js
  test/controllers/return-requirements.controller.test.js
  test/services/return-requirements/setup.service.test.js
  test/services/return-requirements/submit-setup.service.test.js
Labels: housekeeping

#957 Refactor View License Summary services and presenters
  .gitignore
  app/controllers/licences.controller.js
  app/presenters/licences/view-licence.presenter.js
  app/presenters/licences/view-license-summary.presenter.js
  app/services/licences/fetch-licence.service.js
  app/services/licences/fetch-license-summary.service.js
  app/services/licences/view-licence.service.js
  app/services/licences/view-license-summary.service.js
  test/controllers/licences.controller.test.js
  test/presenters/licences/view-licence-presenter.test.js
  test/presenters/licences/view-licence-summary.presenter.test.js
  test/services/licences/fetch-licence-summary.service.test.js
  test/services/licences/fetch-licence.service.test.js
  test/services/licences/view-licence.service.test.js
  test/services/licences/view-license-summary.service.test.js
Labels: housekeeping

#964 Select the reason page H1 Title text change
  app/routes/return-requirement.routes.js
  app/services/return-requirements/reason.service.js
  app/services/return-requirements/submit-reason.service.js
  app/validators/return-requirements/no-returns-required.validator.js
  app/validators/return-requirements/reason.validator.js
  test/controllers/return-requirements.controller.test.js
  test/services/return-requirements/reason.service.test.js
  test/services/return-requirements/submit-no-returns-required.service.test.js
  test/services/return-requirements/submit-reason.service.test.js
  test/validators/no-returns-required/no-returns-required.validator.test.js
  test/validators/no-returns-required/reason.validator.test.js
Labels: housekeeping

#962 Fix amended billable returns banner two-part tariff review
  app/controllers/bill-runs.controller.js
  app/presenters/bill-runs/two-part-tariff/match-details.presenter.js
  app/services/bill-runs/two-part-tariff/match-details.service.js
  app/services/bill-runs/two-part-tariff/submit-amended-billable-returns.service.js
  app/views/bill-runs/match-details.njk
  test/presenters/bill-runs/two-part-tariff/match-details.presenter.test.js
  test/services/bill-runs/two-part-tariff/match-details.service.test.js
  test/services/bill-runs/two-part-tariff/submit-amended-billable-returns.service.test.js
Labels: bug

#966 Persist charge reference authorised volume for two-part tariff review
  app/presenters/bill-runs/two-part-tariff/amend-billable-returns.presenter.js
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/services/bill-runs/two-part-tariff/fetch-match-details.service.js
  app/services/bill-runs/two-part-tariff/persist-allocated-licence-to-results.service.js
  db/migrations/public/20240501152641_alter-review-charge-references.js
  test/presenters/bill-runs/two-part-tariff/amend-billable-returns.presenter.test.js
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-match-details.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.test.js
  test/services/bill-runs/two-part-tariff/persist-allocated-licence-to-results.service.test.js
  test/support/helpers/review-charge-reference.helper.js
Labels: enhancement

#971 Show correct text in textarea in Add Note page
  app/services/return-requirements/submit-add-note.service.js
Labels: bug

#923 Check your answers page with notes for additions, changes and deletions
  app/controllers/return-requirements.controller.js
  app/routes/return-requirement.routes.js
  app/services/return-requirements/check-your-answers.service.js
  app/services/return-requirements/delete-note.service.js
  app/services/return-requirements/submit-add-note.service.js
  app/views/return-requirements/check-your-answers.njk
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/check-your-answers.presenter.test.js
  test/services/return-requirements/check-your-answers.service.test.js
  test/services/return-requirements/delete-note.service.test.js
  test/services/return-requirements/submit-add-note.service.test.js
Labels: enhancement

#972 Add model relationship for return logs & licences
  app/models/licence.model.js
  app/models/return-log.model.js
  test/models/licence.model.test.js
  test/models/return-log.model.test.js
Labels: housekeeping

#974 Fix permissions for licence summary
  app/routes/licence.routes.js
  test/controllers/licences.controller.test.js
Labels: bug

#927 Remove Licence from bill 2PT bill run during review
  app/controllers/bill-runs.controller.js
  app/presenters/bill-runs/two-part-tariff/remove-bill-run-licence.presenter.js
  app/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.js
  app/routes/bill-runs.routes.js
  app/services/bill-runs/two-part-tariff/remove-bill-run-licence.service.js
  app/services/bill-runs/two-part-tariff/remove-review-data.service.js
  app/services/bill-runs/two-part-tariff/review-bill-run.service.js
  app/services/bill-runs/two-part-tariff/review-licence.service.js
  app/services/bill-runs/two-part-tariff/submit-remove-bill-run-licence.service.js
  app/views/bill-runs/remove-licence.njk
  app/views/bill-runs/review-licence.njk
  app/views/bill-runs/review.njk
  db/migrations/legacy/20221108007006-water-licences.js
  db/migrations/public/20240429145100_alter-licences-view-add-tpt-billing-column.js
  test/controllers/bill-runs.controller.test.js
  test/presenters/bill-runs/two-part-tariff/remove-bill-run-licence.presenter.test.js
  test/services/bill-runs/two-part-tariff/remove-bill-run-licence.service.test.js
  test/services/bill-runs/two-part-tariff/remove-review-data.service.test.js
  test/services/bill-runs/two-part-tariff/review-bill-run.service.test.js
  test/services/bill-runs/two-part-tariff/submit-remove-bill-run-licence.service.test.js
Labels: enhancement

#967 Add View License Returns page
  app/controllers/licences.controller.js
  app/presenters/licences/view-licence-returns.presenter.js
  app/presenters/licences/view-licence-summary.presenter.js
  app/presenters/licences/view-licence.presenter.js
  app/routes/licence.routes.js
  app/services/licences/fetch-licence-returns.service.js
  app/services/licences/fetch-licence-summary.service.js
  app/services/licences/fetch-licence.service.js
  app/services/licences/view-licence-returns.service.js
  app/services/licences/view-licence-summary.service.js
  app/views/licences/tabs/returns.njk
  app/views/licences/view.njk
  test/controllers/licences.controller.test.js
  test/presenters/bill-runs/view-bill-summaries.presenter.test.js
  test/presenters/licences/view-licence-presenter.test.js
  test/presenters/licences/view-licence-returns-presenter.test.js
  test/presenters/licences/view-licence-summary.presenter.test.js
  test/services/licences/fetch-licence-returns.service.test.js
  test/services/licences/fetch-licence-summary.service.test.js
  test/services/licences/fetch-licence.service.test.js
  test/services/licences/view-licence-returns.service.test.js
  test/services/licences/view-licence-summary.service.test.js
  test/services/licences/view-licence.service.test.js
Labels: enhancement

#968 Check Return req. radio buttons using session data
  app/presenters/return-requirements/no-returns-required.presenter.js
  app/presenters/return-requirements/start-date.presenter.js
  app/services/return-requirements/submit-no-returns-required.service.js
  app/views/return-requirements/no-returns-required.njk
  app/views/return-requirements/start-date.njk
  test/presenters/return-requirements/no-returns-required.presenter.test.js
  test/presenters/return-requirements/start-date.presenter.test.js
  test/services/return-requirements/no-returns-required.service.test.js
  test/services/return-requirements/start-date.service.test.js
  test/services/return-requirements/submit-no-returns-required.service.test.js
  test/services/return-requirements/submit-start-date.service.test.js
Labels: bug

#979 Correct validators test folder name
  test/validators/return-requirements/abstraction-period.validator.test.js
  test/validators/return-requirements/agreements-exceptions.validator.test.js
  test/validators/return-requirements/frequency-collected.validator.test.js
  test/validators/return-requirements/frequency-reported.validator.test.js
  test/validators/return-requirements/no-returns-required.validator.test.js
  test/validators/return-requirements/note.validator.test.js
  test/validators/return-requirements/points.validator.test.js
  test/validators/return-requirements/purpose.validator.test.js
  test/validators/return-requirements/reason.validator.test.js
  test/validators/return-requirements/returns-cycle.validator.test.js
  test/validators/return-requirements/setup.validator.test.js
  test/validators/return-requirements/site-description.validator.test.js
  test/validators/return-requirements/start-date.validator.test.js
Labels: housekeeping

#981 Enhance the SessionModel to expose and update data
  app/models/session.model.js
  test/models/session.model.test.js
  test/services/return-requirements/check-your-answers.service.test.js
  test/services/return-requirements/delete-note.service.test.js
Labels: enhancement

#983 Update bill run setup journey to use new session
  app/presenters/bill-runs/setup/create.presenter.js
  app/presenters/bill-runs/setup/region.presenter.js
  app/presenters/bill-runs/setup/season.presenter.js
  app/presenters/bill-runs/setup/type.presenter.js
  app/presenters/bill-runs/setup/year.presenter.js
  app/services/bill-runs/setup/create.service.js
  app/services/bill-runs/setup/exists.service.js
  app/services/bill-runs/setup/submit-region.service.js
  app/services/bill-runs/setup/submit-season.service.js
  app/services/bill-runs/setup/submit-type.service.js
  app/services/bill-runs/setup/submit-year.service.js
  test/presenters/bill-runs/setup/create.presenter.test.js
  test/presenters/bill-runs/setup/region.presenter.test.js
  test/presenters/bill-runs/setup/season.presenter.test.js
  test/presenters/bill-runs/setup/type.presenter.test.js
  test/presenters/bill-runs/setup/year.presenter.test.js
  test/services/bill-runs/setup/create.service.test.js
  test/services/bill-runs/setup/submit-region.service.test.js
  test/services/bill-runs/setup/submit-season.service.test.js
  test/services/bill-runs/setup/submit-type.service.test.js
  test/services/bill-runs/setup/submit-year.service.test.js
Labels: housekeeping

#986 Add View Licence Bills page
  app/controllers/licences.controller.js
  app/presenters/licences/view-licence-bills.presenter.js
  app/presenters/licences/view-licence.presenter.js
  app/routes/licence.routes.js
  app/services/licences/fetch-licence-bills.service.js
  app/services/licences/view-licence-bills.service.js
  app/views/licences/tabs/bills.njk
  app/views/licences/view.njk
  test/controllers/licences.controller.test.js
  test/presenters/licences/view-licence-bills-presenter.test.js
  test/presenters/licences/view-licence-presenter.test.js
  test/services/licences/fetch-licence-bills.service.test.js
  test/services/licences/view-licence-bills.service.test.js
  test/services/licences/view-licence.service.test.js
  test/support/helpers/bill-licence.helper.js
Labels: housekeeping

#948 Add linting using eslint with standard as the base
  .eslintrc.js
  package-lock.json
  package.json
Labels: housekeeping

#952 Add two-part tariff charge reference details review page
  app/controllers/bill-runs.controller.js
  app/presenters/bill-runs/two-part-tariff/charge-reference-details.presenter.js
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/routes/bill-runs.routes.js
  app/services/bill-runs/two-part-tariff/charge-reference-details.service.js
  app/services/bill-runs/two-part-tariff/fetch-review-charge-reference.service.js
  app/views/bill-runs/charge-reference-details.njk
  app/views/bill-runs/review-licence.njk
  test/controllers/bill-runs.controller.test.js
  test/presenters/bill-runs/two-part-tariff/charge-reference-details.presenter.test.js
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
  test/services/bill-runs/two-part-tariff/charge-reference-details.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-charge-reference.service.test.js
Labels: enhancement

#989 Use @stylistic/eslint-plugin-js for max-len rule
  .eslintrc.js
  package-lock.json
  package.json
Labels: housekeeping

#992 Exclude long strings from ESLint max-len rule
  .eslintrc.js
Labels: conventions

#934 Cancel these requirements for returns page
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/cancel-requirements.presenter.js
  app/routes/return-requirement.routes.js
  app/services/return-requirements/cancel-requirements.service.js
  app/services/return-requirements/submit-cancel-requirements.service.js
  app/views/return-requirements/cancel-requirements.njk
  app/views/return-requirements/check-your-answers.njk
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/cancel-requirements.presenter.test.js
  test/services/return-requirements/cancel-requirements.service.test.js
  test/services/return-requirements/submit-cancel-requirements.service.test.js
Labels: enhancement

#1002 Remove two-part tariff check endpoint from project
  app/controllers/check.controller.js
  app/plugins/router.plugin.js
  app/routes/check.routes.js
  app/services/check/determine-issues.service.js
  app/services/check/scenario-formatter.service.js
  app/services/check/stand-ins.service.js
  app/services/check/two-part.service.js
  test/controllers/check.controller.test.js
Labels: housekeeping

#1001 Fix all max-len ESLint rule infractions
  app/controllers/bill-runs.controller.js
  app/lib/base-notifier.lib.js
  app/models/licence-entity-role.model.js
  app/plugins/hapi-pino.plugin.js
  app/services/bill-licences/fetch-bill-licence.service.js
  app/services/bill-licences/view-bill-licence.service.js
  app/services/bill-runs/determine-billing-periods.service.js
  app/services/bill-runs/fetch-bill-run.service.js
  app/services/bill-runs/start-bill-run-process.service.js
  app/services/bill-runs/two-part-tariff/allocate-returns-to-charge-element.service.js
  app/services/bill-runs/two-part-tariff/fetch-licences.service.js
  app/services/bill-runs/two-part-tariff/fetch-return-logs-for-licence.service.js
  app/services/bill-runs/view-bill-run.service.js
  app/services/billing-accounts/change-address.service.js
  app/services/bills/fetch-bill-service.js
  app/services/bills/view-bill.service.js
  app/services/jobs/export/fetch-table.service.js
  app/services/return-requirements/site-description.service.js
  test/models/licence-version-purpose-condition.model.test.js
  test/services/bill-licences/fetch-bill-licence-summary.service.test.js
  test/services/bill-runs/create-bill-run.service.test.js
  test/services/bill-runs/supplementary/fetch-previous-transactions.service.test.js
  test/services/bill-runs/supplementary/pre-generate-billing-data.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-match-details.service.test.js
  test/services/bill-runs/two-part-tariff/submit-amended-billable-returns.service.test.js
Labels: housekeeping

#1003 Fix all no-unused-vars ESLint rule infractions
  test/services/return-requirements/check.service.test.js
Labels: housekeeping

#1008 Add eslint rule to enforce file extenstions
  .eslintrc.js
Labels: conventions

#999 Use `yar` to store 2PT Review Licences filter data
  app/controllers/bill-runs.controller.js
  app/routes/bill-runs.routes.js
  app/services/bill-runs/two-part-tariff/review-bill-run.service.js
  app/services/bill-runs/two-part-tariff/submit-review-bill-run.service.js
  app/views/bill-runs/review.njk
  test/controllers/bill-runs.controller.test.js
  test/services/bill-runs/two-part-tariff/review-bill-run.service.test.js
  test/services/bill-runs/two-part-tariff/submit-review-bill-run.service.test.js
Labels: enhancement

#1004 Ensure parens used in all arrow functions
  .eslintrc.js
  app/lib/base-notifier.lib.js
  app/plugins/airbrake.plugin.js
  app/server.js
  app/services/bill-runs/supplementary/fetch-billing-accounts.service.js
  app/services/bill-runs/supplementary/fetch-charge-versions.service.js
  app/services/bill-runs/supplementary/process-bill-run.service.js
  app/services/bill-runs/two-part-tariff/fetch-return-logs-for-licence.service.js
  app/services/health/info.service.js
  app/services/jobs/export/fetch-table-names.service.js
  db/wipe.database.js
  test/presenters/base.presenter.test.js
  test/presenters/charging-module/create-transaction.presenter.test.js
  test/services/bill-runs/reissue/reissue-bill.service.test.js
  test/services/idm/fetch-user-roles-and-groups.service.test.js
Labels: conventions

#1005 Ensure strict mode directive in all files
  .eslintrc.js
Labels: conventions

#993 Add View Licence contact details page
  app/controllers/licences.controller.js
  app/presenters/licences/licence-contacts.presenter.js
  app/routes/licence.routes.js
  app/services/licences/fetch-licence-contacts.service.js
  app/services/licences/view-licence-contact-details.service.js
  app/views/licences/tabs/contact-details.njk
  app/views/licences/view.njk
  test/controllers/licences.controller.test.js
  test/presenters/licences/licence-contacts.presenter.test.js
  test/services/licences/fetch-licence-contacts.service.test.js
  test/services/licences/view-licence-contact-details.service.test.js
Labels: enhancement

#1006 Ensure use of block body for arrow functions
  .eslintrc.js
  app/lib/legacy-db-snake-case-mappers.lib.js
  app/models/contact.model.js
  app/models/licence.model.js
  app/presenters/bills/view-bill.presenter.js
  app/services/bill-runs/annual/process-billing-period.service.js
  app/services/bill-runs/determine-charge-period.service.js
  app/services/bill-runs/reissue/reissue-bill.service.js
  app/services/bill-runs/supplementary/fetch-previous-transactions.service.js
  app/services/bill-runs/supplementary/process-bill-run.service.js
  app/services/health/fetch-import-jobs.service.js
  app/services/jobs/export/fetch-table-names.service.js
  app/services/plugins/filter-routes.service.js
  db/seeds/01-users.js
  test/lib/boom-notifier.lib.test.js
  test/lib/global-notifier.lib.test.js
  test/presenters/base.presenter.test.js
  test/requests/base.request.test.js
  test/services/bill-runs/reissue/reissue-bill.service.test.js
  test/services/bill-runs/supplementary/fetch-previous-transactions.service.test.js
  test/services/health/info.service.test.js
  test/services/idm/fetch-user-roles-and-groups.service.test.js
Labels: conventions

#1007 Ensure blank line b4 function return statements
  .eslintrc.js
  app/controllers/return-requirements.controller.js
  app/presenters/bill-runs/create-bill-run-event.presenter.js
  app/presenters/bill-runs/two-part-tariff/charge-reference-details.presenter.js
  app/presenters/licences/view-licence-summary.presenter.js
  app/services/bill-runs/annual/process-bill-run.service.js
  app/services/bill-runs/calculate-authorised-and-billable-days.service.js
  app/services/bill-runs/supplementary/pre-generate-billing-data.service.js
  app/services/bill-runs/supplementary/process-bill-run.service.js
  app/services/bill-runs/two-part-tariff/submit-review-licence.service.js
  app/services/health/fetch-system-info.service.js
  app/services/health/info.service.js
  app/services/idm/fetch-user-roles-and-groups.service.js
  app/services/licences/fetch-licence.service.js
  app/services/return-requirements/check-licence-ended.service.js
  app/validators/return-requirements/start-date.validator.js
Labels: conventions

#1015 Fix unsent bills displaying in licence bills tab
  app/services/licences/fetch-licence-bills.service.js
  test/services/licences/fetch-licence-bills.service.test.js
Labels: bug

#997 Add pagination to 2PT review page
  app/controllers/bill-runs.controller.js
  app/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.js
  app/services/bill-runs/two-part-tariff/fetch-bill-run-licences.service.js
  app/services/bill-runs/two-part-tariff/review-bill-run.service.js
  app/views/bill-runs/review.njk
  test/controllers/bill-runs.controller.test.js
  test/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-bill-run-licences.service.test.js
  test/services/bill-runs/two-part-tariff/review-bill-run.service.test.js
Labels: enhancement

#996 You are about to remove these return requirements
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/cancel.presenter.js
  app/presenters/return-requirements/remove.presenter.js
  app/routes/return-requirement.routes.js
  app/services/return-requirements/remove.service.js
  app/services/return-requirements/submit-remove.service.js
  app/views/return-requirements/remove.njk
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/remove.presenter.test.js
  test/services/return-requirements/remove.service.test.js
  test/services/return-requirements/submit-remove.service.test.js
Labels: enhancement

#1018 Add Scheduled Notifications model
  app/models/scheduled-notification.model.js
  db/migrations/legacy/20240515104554_water-add-scheduled-notifications.js
  db/migrations/public/20240515082450_create-scheduled-notifications-view.js
  test/models/scheduled-notification.model.test.js
  test/support/helpers/scheduled-notification.helper.js
Labels: enhancement

#1014 Adding multiple return requirements to the session
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/check.presenter.js
  app/presenters/return-requirements/purpose.presenter.js
  app/routes/return-requirement.routes.js
  app/services/return-requirements/add.service.js
  app/views/return-requirements/check.njk
  test/presenters/return-requirements/check.presenter.test.js
  test/services/return-requirements/add.service.test.js
  test/services/return-requirements/check.service.test.js
Labels: enhancement

#1024 Alter 2PT Review Licences filter behaviour
  app/controllers/bill-runs.controller.js
  app/services/bill-runs/two-part-tariff/review-bill-run.service.js
  app/services/bill-runs/two-part-tariff/submit-review-bill-run.service.js
  test/services/bill-runs/two-part-tariff/submit-review-bill-run.service.test.js
Labels: enhancement

#1028 View licence contact details title format
  app/views/licences/tabs/contact-details.njk
  test/controllers/licences.controller.test.js
Labels: bug

#1021 Remove returns requirements button on check page
  app/controllers/return-requirements.controller.js
  app/services/return-requirements/submit-remove.service.js
  app/views/return-requirements/check.njk
  test/services/return-requirements/submit-remove.service.test.js
Labels: enhancement

#1027 Fix QA issues found with the review adjustment factors validation
  app/services/bill-runs/two-part-tariff/submit-amended-adjustment-factor.service.js
  app/validators/bill-runs/two-part-tariff/adjustment-factor.validator.js
  test/validators/bill-runs/two-part-tariff/adjustment-factor.validator.test.js
Labels: enhancement

#1029 Add sentence case function & rename capitalize
  app/presenters/base.presenter.js
  app/presenters/bill-licences/remove-bill-licence.presenter.js
  app/presenters/bill-licences/view-standard-charge-transaction.presenter.js
  app/presenters/bill-runs/cancel-bill-run.presenter.js
  app/presenters/bill-runs/empty-bill-run-presenter.js
  app/presenters/bill-runs/errored-bill-run-presenter.js
  app/presenters/bill-runs/index-bill-runs.presenter.js
  app/presenters/bill-runs/send-bill-run.presenter.js
  app/presenters/bill-runs/setup/create.presenter.js
  app/presenters/bill-runs/view-bill-run.presenter.js
  app/presenters/bills/remove-bill.presenter.js
  app/presenters/bills/view-bill.presenter.js
  test/presenters/base.presenter.test.js
  test/presenters/bills/view-bill.presenter.test.js
Labels: enhancement

#1025 Refactor purposes page to use purpose ids as values
  app/presenters/return-requirements/purpose.presenter.js
  app/services/return-requirements/fetch-licence-purposes.service.js
  app/services/return-requirements/purpose.service.js
  app/services/return-requirements/submit-purpose.service.js
  app/validators/return-requirements/purpose.validator.js
  app/views/return-requirements/purpose.njk
  test/presenters/return-requirements/purpose.presenter.test.js
  test/services/return-requirements/fetch-licence-purposes.service.test.js
  test/services/return-requirements/purpose.service.test.js
  test/services/return-requirements/submit-purpose.service.test.js
  test/validators/return-requirements/purpose.validator.test.js
Labels: housekeeping

#1020 Add View Licence communications
  app/controllers/licences.controller.js
  app/presenters/licences/communications.presenter.js
  app/presenters/licences/view-licence.presenter.js
  app/routes/licence.routes.js
  app/services/licences/fetch-communications.service.js
  app/services/licences/view-licence-communications.service.js
  app/views/licences/tabs/communications.njk
  app/views/licences/view.njk
  db/migrations/public/20240516044126_alter-scheduled-notification-add-message-ref-column.js
  test/controllers/licences.controller.test.js
  test/presenters/licences/communications.presenter.test.js
  test/presenters/licences/view-licence-presenter.test.js
  test/services/licences/fetch-communications.service.test.js
  test/services/licences/view-licence-communications.service.test.js
  test/services/licences/view-licence.service.test.js
  test/support/helpers/scheduled-notification.helper.js
Labels: housekeeping

#1031 View Licence customer duplicate contacts
  app/services/licences/fetch-customer-contacts.service.js
Labels: bug

#1032 Fix typo with remove button in remove requirements
  app/views/return-requirements/remove.njk
Labels: housekeeping

#1033 Fix view licence summary for incomplete licences
  app/presenters/licences/view-licence-summary.presenter.js
  app/services/licences/fetch-licence-abstraction-conditions.service.js
  app/services/licences/view-licence-summary.service.js
  test/presenters/licences/view-licence-summary.presenter.test.js
  test/services/licences/fetch-licence-abstraction-conditions.service.test.js
  test/services/licences/view-licence-summary.service.test.js
Labels: bug

#1035 Fix adjustment factors link
  app/presenters/bill-runs/two-part-tariff/charge-reference-details.presenter.js
  test/presenters/bill-runs/two-part-tariff/charge-reference-details.presenter.test.js
Labels: bug

#1041 Content change on set adjustment factors page 2pt
  app/presenters/bill-runs/two-part-tariff/amend-adjustment-factor.presenter.js
  app/views/bill-runs/amend-adjustment-factor.njk
  test/controllers/bill-runs.controller.test.js
Labels: enhancement

#1036 Calculate and display expected charge during 2PT review
  app/requests/charging-module/calculate-charge.request.js
  test/requests/charging-module/calculate-charge.request.test.js
Labels: enhancement

#1034 View Licence set up page
  app/controllers/licences.controller.js
  app/presenters/licences/set-up.presenter.js
  app/presenters/licences/view-licence.presenter.js
  app/routes/licence.routes.js
  app/services/licences/fetch-charge-versions.service.js
  app/services/licences/fetch-workflows.service.js
  app/services/licences/view-licence-set-up.service.js
  app/services/licences/view-licence.service.js
  app/views/licences/tabs/set-up.njk
  app/views/licences/view.njk
  app/views/macros/charge-version-status-tag.njk
  test/controllers/licences.controller.test.js
  test/presenters/licences/set-up.presenter.test.js
  test/presenters/licences/view-licence-presenter.test.js
  test/services/licences/fetch-charge-versions.service.test.js
  test/services/licences/fetch-workflows.service.test.js
  test/services/licences/view-licence-set-up.service.test.js
  test/services/licences/view-licence.service.test.js
Labels: housekeeping

#1048 Fix user seeding not creating user groups
  db/seeds/01-users.js
Labels: bug

#1049 Add NALD test data to permit licence helper
  test/support/helpers/permit-licence.helper.js
Labels: housekeeping

#1050 Two-part tariff review pages housekeeping
  app/services/bill-runs/two-part-tariff/fetch-review-charge-reference.service.js
  app/views/bill-runs/amend-adjustment-factor.njk
  app/views/bill-runs/amend-billable-returns.njk
  app/views/bill-runs/match-details.njk
  test/services/bill-runs/two-part-tariff/amend-adjustment-factor.service.test.js
  test/services/bill-runs/two-part-tariff/charge-reference-details.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-charge-reference.service.test.js
Labels: housekeeping

#1051 Add new acceptance test data loader
  app/controllers/data.controller.js
  app/routes/data.routes.js
  app/services/data/load/load.service.js
  test/controllers/data.controller.test.js
  test/services/data/load/load.service.test.js
Labels: enhancement

#1058 Change message text and add a link to approve page
  app/controllers/return-requirements.controller.js
  app/routes/return-requirement.routes.js
  test/controllers/return-requirements.controller.test.js
Labels: enhancement, housekeeping

#1047 View licence set up agreements
  app/presenters/licences/set-up.presenter.js
  app/presenters/licences/view-licence.presenter.js
  app/services/licences/fetch-agreements.service.js
  app/services/licences/view-licence-set-up.service.js
  app/views/licences/tabs/set-up.njk
  test/controllers/licences.controller.test.js
  test/presenters/licences/set-up.presenter.test.js
  test/presenters/licences/view-licence-presenter.test.js
  test/services/licences/fetch-agreements.service.test.js
  test/services/licences/fetch-charge-versions.service.test.js
  test/services/licences/view-licence-set-up.service.test.js
  test/services/licences/view-licence.service.test.js
Labels: housekeeping

#1046 Calculate and display expected charge during 2PT review - Part 2
  app/controllers/bill-runs.controller.js
  app/routes/bill-runs.routes.js
  app/services/bill-runs/two-part-tariff/calculate-charge.service.js
  app/services/bill-runs/two-part-tariff/charge-reference-details.service.js
  app/views/bill-runs/charge-reference-details.njk
  test/controllers/bill-runs.controller.test.js
  test/services/bill-runs/two-part-tariff/calculate-charge.service.test.js
  test/services/bill-runs/two-part-tariff/charge-reference-details.service.test.js
  test/support/helpers/review-charge-reference.helper.js
Labels: enhancement

#1043 Adding tags in view for acceptance tests
  app/views/return-requirements/check.njk
Labels: enhancement

#1019 Check your requirements page (with requirements summary cards)
  app/presenters/return-requirements/check.presenter.js
  app/views/return-requirements/check.njk
  test/presenters/return-requirements/check.presenter.test.js
Labels: enhancement
