Repository DEFRA/water-abstraction-system, pull requests merged in 2024-08, with the labels that each got.

#1194 Acceptance test data loader
  app/views/licences/view.njk
  test/support/helpers/gauging-station.helper.js
  test/support/helpers/permit-licence.helper.js
  test/support/helpers/return-log.helper.js
Labels: housekeeping

#1226 Update return logs helper
  test/support/helpers/return-log.helper.js
Labels: housekeeping

#1223 Add 'Temporary trade' option no-returns-reason page
  app/lib/static-lookups.lib.js
  app/validators/return-requirements/no-returns-required.validator.js
  app/views/return-requirements/no-returns-required.njk
Labels: housekeeping

#1219 Add insert on conflict to seeders
  db/migrations/legacy/20221108007028_water-licence-version-purpose-condition-types.js
  test/support/seeders/licence-version-purpose-condition-types.seeder.js
  test/support/seeders/primary-purpose.seeder.js
  test/support/seeders/purposes.seeder.js
  test/support/seeders/secondary-purpose.seeder.js
Labels: testing

#1220 Deleted agreements shouldn't show in the setup tab
  app/services/licences/fetch-agreements.service.js
  test/services/licences/fetch-agreements.service.test.js
Labels: bug

#1224 Return version can be on/after licence start date
  app/validators/return-requirements/start-date.validator.js
  test/validators/return-requirements/start-date.validator.test.js
Labels: bug

#1232 Update tear down service
  app/services/data/tear-down/idm-schema.service.js
Labels: housekeeping

#1236 Removing licence from annual 2pt flags for supp billing
  app/models/licence-supplementary-year.model.js
  app/services/bill-runs/two-part-tariff/submit-remove-bill-run-licence.service.js
  app/services/data/load/load.service.js
  app/services/data/tear-down/public-schema.service.js
  db/migrations/public/20240806103222_create-licence-supplementary-years.js
  test/models/licence-supplementary-year.model.test.js
  test/services/bill-runs/two-part-tariff/submit-remove-bill-run-licence.service.test.js
  test/support/helpers/licence-supplementary-year.helper.js
Labels: enhancement

#1241 Remove more DatabaseSupport.clean() from tests
  test/services/bills/fetch-bill-summary.service.test.js
  test/services/bills/fetch-bill.service.test.js
  test/services/bills/submit-remove-bill.services.test.js
  test/services/data/deduplicate/de-duplicate-licence.service.test.js
  test/services/licences/determine-licence-has-return-versions.service.test.js
  test/services/licences/fetch-communications.service.test.js
  test/services/licences/fetch-customer-contacts.service.test.js
  test/services/licences/fetch-licence-contacts.service.test.js
  test/services/licences/fetch-licence-returns.service.test.js
  test/services/licences/fetch-return-versions.service.test.js
  test/services/return-requirements/abstraction-period.service.test.js
  test/services/return-requirements/add.service.test.js
  test/services/return-requirements/additional-submission-options.service.test.js
  test/services/return-requirements/agreements-exceptions.service.test.js
  test/services/return-requirements/cancel.service.test.js
  test/services/return-requirements/check-licence-ended.service.test.js
  test/services/return-requirements/delete-note.service.test.js
  test/services/return-requirements/existing.service.test.js
  test/services/return-requirements/fetch-points.service.test.js
  test/services/return-requirements/frequency-collected.service.test.js
  test/services/return-requirements/frequency-reported.service.test.js
  test/services/return-requirements/no-returns-required.service.test.js
  test/services/return-requirements/note.service.test.js
  test/services/return-requirements/points.service.test.js
  test/services/return-requirements/purpose.service.test.js
  test/services/return-requirements/reason.service.test.js
  test/services/return-requirements/remove.service.test.js
  test/services/return-requirements/returns-cycle.service.test.js
  test/services/return-requirements/setup/fetch-abstraction-data.service.test.js
  test/services/return-requirements/setup/setup.service.test.js
  test/services/return-requirements/setup/submit-setup.service.test.js
  test/services/return-requirements/site-description.service.test.js
  test/services/return-requirements/start-date.service.test.js
  test/services/return-requirements/submit-abstraction-period.service.test.js
  test/services/return-requirements/submit-additional-submission-options.service.test.js
  test/services/return-requirements/submit-agreements-exceptions.service.test.js
  test/services/return-requirements/submit-cancel.service.test.js
  test/services/return-requirements/submit-existing.service.test.js
  test/services/return-requirements/submit-frequency-collected.service.test.js
  test/services/return-requirements/submit-frequency-reported.service.test.js
  test/services/return-requirements/submit-no-returns-required.service.test.js
  test/services/return-requirements/submit-note.service.test.js
  test/services/return-requirements/submit-points.service.test.js
  test/services/return-requirements/submit-reason.service.test.js
  test/services/return-requirements/submit-remove.service.test.js
  test/services/return-requirements/submit-returns-cycle.service.test.js
  test/services/return-requirements/submit-site-description.service.test.js
  test/services/return-requirements/submit-start-date.service.test.js
  test/support/helpers/financial-agreement.helper.js
  test/support/helpers/licence-version-purpose.helper.js
  test/support/helpers/licence-version.helper.js
  test/support/seeders/licence-abstraction-data.seeder.js
Labels: testing

#1242 Remove two-part tariff supplementary billing flag from the `Licences` view
  db/migrations/public/20240807160605_alter-licences-view.js
Labels: enhancement

#1245 Update `alter-licences-view` migration script
  db/migrations/public/20240807160605_alter-licences-view.js
Labels: enhancement

#1246 Remove more DatabaseSupport.clean() from services/job
  test/services/jobs/export/fetch-table.service.test.js
Labels: testing

#1216 Update existing return versions when a new one is added
  app/services/return-requirements/generate-return-version.service.js
  app/services/return-requirements/persist-return-version.service.js
  app/services/return-requirements/process-existing-return-versions.service.js
  test/services/return-requirements/generate-return-version.service.test.js
  test/services/return-requirements/process-existing-return-versions.service.test.js
  test/services/return-requirements/submit-check.service.test.js
Labels: enhancement

#1252 Add mod_log field to return versions view
  db/migrations/legacy/20221108007023_water-return-versions.js
  db/migrations/public/20240809164102_alter-return-versions-view.js
Labels: enhancement

#1251 Fix order of return versions in view licence
  app/services/licences/fetch-return-versions.service.js
  test/services/licences/fetch-return-versions.service.test.js
Labels: bug

#1253 Add JSDoc as dependency to validate documentation
  .github/workflows/ci.yml
  .gitignore
  .jsdoc.js
  app/services/bill-runs/annual/fetch-billing-accounts.service.js
  app/services/bill-runs/cancel-bill-run.service.js
  app/services/bill-runs/consolidate-date-ranges.service.js
  app/services/bill-runs/send-bill-run.service.js
  app/services/bill-runs/two-part-tariff/fetch-billing-accounts.service.js
  app/services/bill-runs/two-part-tariff/remove-bill-run-licence.service.js
  app/services/jobs/export/convert-to-csv.service.js
  package-lock.json
  package.json
Labels: housekeeping

#1240 Create `chargeVersionNotes` table model, helper and view
  app/models/charge-version-note.model.js
  app/models/charge-version.model.js
  app/models/user.model.js
  db/migrations/legacy/20240807142828_water-notes.js
  db/migrations/public/20240807131002_create-charge-version-note-view.js
  test/models/charge-version-note.model.test.js
  test/models/charge-version.model.test.js
  test/models/user.model.test.js
  test/support/helpers/charge-version-note.helper.js
Labels: housekeeping

#1257 Add new NoBillingPeriodsError as a reminder
  app/errors/no-billing-periods.error.js
  app/services/bill-runs/start-bill-run-process.service.js
  test/services/bill-runs/start-bill-run-process.service.test.js
Labels: enhancement

#1256 Add create licence supplementary years service
  app/services/bill-runs/two-part-tariff/submit-remove-bill-run-licence.service.js
  app/services/licences/supplementary/create-licence-supplementary-year.service.js
  test/services/licences/supplementary/create-licence-supplementary-year.service.test.js
Labels: enhancement

#1259 Trigger 2PT Supplementary Bill Run
  app/controllers/bill-runs-setup.controller.js
  app/services/bill-runs/setup/submit-region.service.js
  app/validators/bill-runs/setup/type.validator.js
  app/views/bill-runs/setup/type.njk
  test/controllers/bill-runs-setup.controller.test.js
  test/services/bill-runs/setup/submit-region.service.test.js
Labels: enhancement

#1263 Remove return versions view mod log change
  db/migrations/legacy/20221108007023_water-return-versions.js
  db/migrations/legacy/20221108007037_water-notes.js
  db/migrations/public/20240809164102_alter-return-versions-view.js
Labels: housekeeping

#1264 Add Mod Log model
  app/models/charge-version.model.js
  app/models/licence-version.model.js
  app/models/licence.model.js
  app/models/mod-log.model.js
  app/models/return-version.model.js
  db/migrations/legacy/20221108007038_water-mod-logs.js
  db/migrations/public/20240818105000_create-mod-logs-view.js
  test/models/charge-version.model.test.js
  test/models/licence-version.model.test.js
  test/models/licence.model.test.js
  test/models/mod-log.model.test.js
  test/models/return-version.model.test.js
  test/support/helpers/mod-log.helper.js
Labels: enhancement

#1266 Fix blown server logs in import service
  app/services/import/legacy-licence.service.js
Labels: bug

#1239 Create SROC two-part tariff flagging endpoint for new charge versions
  app/controllers/licences.controller.js
  app/routes/licence.routes.js
  app/services/licences/supplementary/determine-billing-years.service.js
  app/services/licences/supplementary/determine-charge-version-years.service.js
  app/services/licences/supplementary/determine-existing-bill-run-years.service.js
  app/services/licences/supplementary/process-billing-flag.service.js
  test/controllers/licences.controller.test.js
  test/services/licences/supplementary/determine-billing-years.service.test.js
  test/services/licences/supplementary/determine-charge-version-years.service.test.js
  test/services/licences/supplementary/determine-existing-bill-run-years.service.test.js
  test/services/licences/supplementary/process-billing-flag.service.test.js
Labels: enhancement

#1267 Add history attributes to ReturnVersionModel
  app/models/return-version.model.js
  test/models/return-version.model.test.js
Labels: enhancement

#1268 Linting should not apply to the docs folder
  .eslintrc.js
Labels: housekeeping

#1271 Add history attributes to LicenceVersionModel
  app/models/licence-version.model.js
  app/models/return-version.model.js
  test/models/licence-version.model.test.js
  test/models/return-version.model.test.js
Labels: enhancement

#1269 Lint JSDOC's
  .eslintrc.js
  package-lock.json
  package.json
Labels: housekeeping

#1274 Add Charge version change reasons to seeder
  app/services/bill-runs/two-part-tariff/fetch-charge-versions.service.js
  db/seeds/12-change-reasons.seed.js
  db/seeds/data/change-reasons.js
  test/models/change-reason.model.test.js
  test/models/charge-version.model.test.js
  test/services/bill-runs/annual/fetch-billing-accounts.service.test.js
  test/services/bill-runs/determine-minimum-charge.service.test.js
  test/services/bill-runs/supplementary/fetch-charge-versions.service.test.js
  test/services/bill-runs/supplementary/process-billing-period.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-charge-versions.service.test.js
  test/services/licences/fetch-charge-versions.service.test.js
  test/services/licences/fetch-licence-summary.service.test.js
  test/support/database.js
  test/support/helpers/change-reason.helper.js
  test/support/seeders/licence-holder.seeder.js
Labels: housekeeping

#1272 Add history attributes to ChargeVersionModel
  app/models/charge-version.model.js
  test/models/charge-version.model.test.js
  test/models/return-version.model.test.js
Labels: enhancement

#1276 Alan's Update view return version with mod log
  app/presenters/return-requirements/view.presenter.js
  app/views/return-requirements/view.njk
  test/presenters/return-requirements/view.presenter.test.js
  test/services/return-requirements/view.service.test.js
  test/support/seeders/requirements-for-returns.seeder.js
Labels: enhancement

#1261 Update view return version to include mod log info
  app/presenters/return-requirements/view.presenter.js
  app/services/return-requirements/fetch-return-version.service.js
  app/views/return-requirements/view.njk
  test/presenters/return-requirements/view.presenter.test.js
  test/services/return-requirements/fetch-return-version.service.test.js
  test/services/return-requirements/view.service.test.js
Labels: housekeeping

#1275 Ignore new `/import/licence` endpoint in logs
  app/services/plugins/hapi-pino-ignore-request.service.js
  test/services/plugins/hapi-pino-ignore-request.service.test.js
Labels: housekeeping

#1281 Update return versions table with reasons in view
  app/presenters/licences/set-up.presenter.js
  app/services/licences/fetch-return-versions.service.js
  test/presenters/licences/set-up.presenter.test.js
  test/services/licences/fetch-return-versions.service.test.js
  test/services/licences/view-licence-set-up.service.test.js
Labels: enhancement

#1282 Update use previous in ret. req setup with mod log
  app/models/return-version.model.js
  app/presenters/return-requirements/existing.presenter.js
  app/services/return-requirements/existing.service.js
  app/services/return-requirements/initiate-session.service.js
  test/presenters/return-requirements/existing.presenter.test.js
  test/services/return-requirements/existing.service.test.js
  test/services/return-requirements/frequency-collected.service.test.js
  test/services/return-requirements/frequency-reported.service.test.js
  test/services/return-requirements/initiate-session.service.test.js
  test/services/return-requirements/no-returns-required.service.test.js
  test/services/return-requirements/note.service.test.js
  test/services/return-requirements/points.service.test.js
  test/services/return-requirements/purpose.service.test.js
  test/services/return-requirements/reason.service.test.js
  test/services/return-requirements/remove.service.test.js
  test/services/return-requirements/returns-cycle.service.test.js
  test/services/return-requirements/site-description.service.test.js
  test/services/return-requirements/start-date.service.test.js
  test/services/return-requirements/submit-abstraction-period.service.test.js
  test/services/return-requirements/submit-additional-submission-options.service.test.js
  test/services/return-requirements/submit-agreements-exceptions.service.test.js
  test/services/return-requirements/submit-cancel.service.test.js
  test/services/return-requirements/submit-existing.service.test.js
  test/services/return-requirements/submit-frequency-collected.service.test.js
  test/services/return-requirements/submit-frequency-reported.service.test.js
  test/services/return-requirements/submit-no-returns-required.service.test.js
  test/services/return-requirements/submit-note.service.test.js
  test/services/return-requirements/submit-points.service.test.js
  test/services/return-requirements/submit-purpose.service.test.js
  test/services/return-requirements/submit-reason.service.test.js
  test/services/return-requirements/submit-remove.service.test.js
  test/services/return-requirements/submit-returns-cycle.service.test.js
  test/services/return-requirements/submit-site-description.service.test.js
  test/services/return-requirements/submit-start-date.service.test.js
Labels: enhancement

#1285 Remove more DatabaseSupport.clean()
  test/presenters/bill-runs/create-bill-run-event.presenter.test.js
  test/presenters/charging-module/create-transaction.presenter.test.js
  test/services/bill-runs/annual/process-bill-run.service.test.js
  test/services/bill-runs/setup/create.service.test.js
  test/services/bill-runs/setup/exists.service.test.js
  test/services/bill-runs/setup/fetch-regions.service.test.js
  test/services/bill-runs/setup/initialise-session.service.test.js
  test/services/bill-runs/setup/region.service.test.js
  test/services/bill-runs/setup/season.service.test.js
  test/services/bill-runs/setup/submit-region.service.test.js
  test/services/bill-runs/setup/submit-season.service.test.js
  test/services/bill-runs/setup/submit-type.service.test.js
  test/services/bill-runs/setup/submit-year.service.test.js
  test/services/bill-runs/setup/type.service.test.js
  test/services/bill-runs/setup/year.service.test.js
  test/services/bill-runs/supplementary/fetch-billing-accounts.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-bill-run-licences.service.test.js
  test/services/bill-runs/two-part-tariff/submit-amended-authorised-volume.service.test.js
  test/services/bill-runs/two-part-tariff/submit-amended-billable-returns.service.test.js
  test/services/bill-runs/two-part-tariff/submit-review-licence.service.test.js
  test/services/jobs/licence-updates/fetch-licence-updates.service.test.js
  test/services/jobs/session-cleanup/process-session-storage-cleanup.service.test.js
  test/services/jobs/time-limited/process-time-limited-licences.service.test.js
  test/support/database.js
Labels: housekeeping, testing

#1195 Import Licence versions
  app/controllers/import.controller.js
  app/lib/dates.lib.js
  app/lib/static-lookups.lib.js
  app/presenters/import/legacy/licence-version-purpose.presenter.js
  app/presenters/import/legacy/licence-version.presenter.js
  app/presenters/import/legacy/licence.presenter.js
  app/routes/import.routes.js
  app/services/import/legacy-import/constants.js
  app/services/import/legacy-import/fetch-licence-versions.service.js
  app/services/import/legacy-import/fetch-licence.service.js
  app/services/import/legacy-import/licence.mapper.js
  app/services/import/legacy-licence.service.js
  app/services/import/legacy/fetch-licence-version-purposes.service.js
  app/services/import/legacy/fetch-licence-versions.service.js
  app/services/import/legacy/fetch-licence.service.js
  app/services/import/legacy/process-licence.service.js
  app/services/import/legacy/transform-licence-version-purposes.service.js
  app/services/import/legacy/transform-licence-versions.service.js
  app/services/import/legacy/transform-licence.service.js
  app/services/import/licence-validator.service.js
  app/services/import/persist-licence.service.js
  app/validators/custom/date.validators.js
  app/validators/import/licence-structure.validator.js
  app/validators/import/licence-version-purpose-condition.validator.js
  app/validators/import/licence-version-purpose.validator.js
  app/validators/import/licence-version.validator.js
  app/validators/import/licence.validator.js
  db/migrations/legacy/20221108007007_water-licence-versions.js
  db/migrations/legacy/20221108007008_water-licence-version-purposes-table.js
  test/controllers/import.controller.test.js
  test/presenters/import/legacy/licence-version-purpose.presenter.test.js
  test/presenters/import/legacy/licence-version.presenter.test.js
  test/presenters/import/legacy/licence.presenter.test.js
  test/services/import/_fixtures/licence.js
  test/services/import/_fixtures/versions.js
  test/services/import/legacy-import/licence.mapper.test.js
  test/services/import/legacy-licence.service.test.js
  test/services/import/legacy/process-licence.service.test.js
  test/services/import/legacy/transform-licence-version-purposes.service.test.js
  test/services/import/legacy/transform-licence-versions.service.test.js
  test/services/import/legacy/transform-licence.service.test.js
  test/services/import/licence-validator.service.test.js
  test/services/import/persist-licence.service.test.js
  test/validators/import/_fixtures/valid-licence.fixture.js
  test/validators/import/licence-structure.validator.test.js
  test/validators/import/licence-version-purpose.validator.test.js
  test/validators/import/licence-version.validator.test.js
  test/validators/import/licence.validator.test.js
Labels: enhancement

#1244 Generate return logs from requirements
  app/controllers/jobs.controller.js
  app/routes/jobs.routes.js
  app/services/jobs/return-logs/fetch-return-logs.service.js
  app/services/jobs/return-logs/process-return-logs.service.js
  db/migrations/public/20240807132127_alter-return-logs-view-include-source.js
  test/controllers/jobs.controller.test.js
  test/services/jobs/return-logs/fetch-return-logs.service.test.js
  test/services/jobs/return-logs/process-return-logs.service.test.js
  test/services/return-requirements/fetch-return-version.service.test.js
  test/support/helpers/return-log.helper.js
  test/support/helpers/return-requirement-point.helper.js
  test/support/helpers/return-requirement-purpose.helper.js
Labels: enhancement

#1288 Add Licence Version Purpose Point model
  app/models/licence-version-purpose-point.model.js
  app/models/licence-version-purpose.model.js
  db/migrations/legacy/20221108007039_water-licence-version-purpose-points.js
  db/migrations/public/20240827195147_create-licence-version-purpose-points-view.js
  test/models/licence-version-purpose-point.model.test.js
  test/models/licence-version-purpose.model.test.js
  test/models/return-requirement-point.model.test.js
  test/support/helpers/licence-version-purpose-point.helper.js
Labels: enhancement

#1291 Fix registered to link in view licence
  app/models/licence-document-header.model.js
  app/models/licence-entity-role.model.js
  app/models/licence-entity.model.js
  app/models/licence.model.js
  app/models/user.model.js
  app/presenters/licences/view-licence.presenter.js
  app/services/licences/fetch-licence-summary.service.js
  app/services/licences/fetch-licence.service.js
  app/services/licences/view-licence.service.js
  app/views/licences/view.njk
  db/migrations/public/20240828111744_alter-users-view.js
  db/seeds/data/users.js
  test/controllers/licences.controller.test.js
  test/models/charge-version-note.model.test.js
  test/models/group.model.test.js
  test/models/licence-document-header.model.test.js
  test/models/licence-entity-role.model.test.js
  test/models/licence-entity.model.test.js
  test/models/licence.model.test.js
  test/models/return-version.model.test.js
  test/models/role.model.test.js
  test/models/user-group.model.test.js
  test/models/user-role.model.test.js
  test/models/user.model.test.js
  test/presenters/licences/view-licence.presenter.test.js
  test/services/idm/fetch-user-roles-and-groups.service.test.js
  test/services/licences/fetch-licence-summary.service.test.js
  test/services/licences/fetch-licence.service.test.js
  test/services/licences/view-licence.service.test.js
  test/support/helpers/user.helper.js
  test/support/seeders/registered-to-and-licence-name.seeder.js
Labels: bug

#1292 Override "Missing JSDoc comment" rule for controllers
  .eslintrc.js
  app/controllers/billing-accounts.controller.js
  app/controllers/jobs.controller.js
  app/lib/base-notifier.lib.js
  app/lib/legacy-db-snake-case-mappers.lib.js
Labels: housekeeping

#1293 Add createdAt to Version history modifiers
  app/models/charge-version.model.js
  app/models/licence-version.model.js
  app/models/return-version.model.js
  test/services/return-requirements/fetch-return-version.service.test.js
Labels: housekeeping

#1182 Build new licence history page
  app/controllers/licences.controller.js
  app/presenters/licences/view-licence-history.presenter.js
  app/routes/licence.routes.js
  app/services/licences/fetch-licence-history.service.js
  app/services/licences/view-licence-history.service.js
  app/views/licences/history.njk
  client/sass/application.scss
  test/presenters/licences/view-licence-history.presenter.test.js
  test/services/licences/fetch-licence-history.service.test.js
  test/services/licences/view-licence-history.service.test.js
Labels: enhancement

#1289 Add base point model with a describe helper
  app/lib/general.lib.js
  app/models/base-point.model.js
  app/models/licence-version-purpose-point.model.js
  app/models/return-requirement-point.model.js
  app/presenters/return-requirements/view.presenter.js
  test/models/base-point.model.test.js
Labels: housekeeping

#1290 Flag Supplementary 2PT for editing returns
  app/services/licences/supplementary/determine-return-log-years.service.js
  app/services/licences/supplementary/process-billing-flag.service.js
  test/services/licences/supplementary/determine-return-log-years.service.test.js
Labels: enhancement

#1287 Import Licence version purpose conditions
  app/presenters/import/legacy/licence-version-purpose-condition.presenter.js
  app/presenters/import/legacy/licence-version-purpose.presenter.js
  app/services/import/legacy/fetch-licence-version-purpose-conditions.service.js
  app/services/import/legacy/process-licence.service.js
  app/services/import/legacy/transform-licence-version-purpose-conditions.service.js
  app/services/import/licence-version-purpose-condition.service.js
  app/services/import/persist-licence.service.js
  app/validators/import/licence-version-purpose-condition.validator.js
  app/validators/import/licence-version-purpose.validator.js
  test/presenters/import/legacy/licence-version-purpose-condition.presenter.test.js
  test/presenters/import/legacy/licence-version-purpose.presenter.test.js
  test/services/import/legacy/process-licence.service.test.js
  test/services/import/legacy/transform-licence-version-purpose-conditions.service.test.js
  test/services/import/legacy/transform-licence-version-purposes.service.test.js
  test/services/import/licence-version-purpose-condition.service.test.js
  test/services/import/persist-licence.service.test.js
  test/validators/import/licence-version-purpose-conditions.validator.test.js
Labels: enhancement

#1295 Fix return version tests
  test/models/return-version.model.test.js
  test/support/general.js
  test/support/helpers/mod-log.helper.js
  test/support/helpers/return-version.helper.js
Labels: bug, testing

#1296 Fix user model tests
  test/models/user.model.test.js
Labels: bug, testing

#1298 Do not display draft return versions in set up
  app/services/licences/fetch-return-versions.service.js
  test/services/licences/fetch-return-versions.service.test.js
Labels: housekeeping
