Repository DEFRA/water-abstraction-system, pull requests merged in 2024-01, with the labels that each got.

#629 Add LicenceRoleModel from crm_v2.roles
  app/models/licence-role.model.js
  db/migrations/legacy/20240103123926_create-crm-v2-roles.js
  db/migrations/public/20240103124409_create-licence-roles-view.js
  test/models/licence-role.model.test.js
  test/support/helpers/licence-role.helper.js
Labels: enhancement

#630 Add LicenceDocumentRoleModel from document_roles
  app/models/address.model.js
  app/models/company.model.js
  app/models/contact.model.js
  app/models/licence-document-role.model.js
  app/models/licence-document.model.js
  app/models/licence-role.model.js
  db/migrations/legacy/20240103145832_create-crm-v2-document-roles.js
  db/migrations/public/20240103152905_create-licence-document-roles-view.js
  test/models/address.model.test.js
  test/models/company.model.test.js
  test/models/contact.model.test.js
  test/models/licence-document-role.model.test.js
  test/models/licence-document.model.test.js
  test/models/licence-role.model.test.js
  test/support/helpers/licence-document-role.helper.js
Labels: enhancement

#632 Add LicenceDocument relationship to LicenceModel
  app/models/licence-document.model.js
  app/models/licence.model.js
  test/models/licence-document.model.test.js
  test/models/licence.model.test.js
Labels: enhancement

#639 Add licence ref. and holder to rtn. req. session
  app/controllers/licences.controller.js
  app/services/return-requirements/initiate-return-requirement-session.service.js
  test/controllers/licences.controller.test.js
  test/services/return-requirements/initiate-return-requirement-session.service.test.js
Labels: enhancement

#642 Fix download link in view bill run page
  app/views/bill-runs/view.njk
Labels: bug

#636 Why no returns required? page iteration 2
  app/controllers/return-requirements.controller.js
  app/lib/static-lookups.lib.js
  app/presenters/return-requirements/no-returns-required.presenter.js
  app/services/return-requirements/no-returns-required.service.js
  app/validators/return-requirements/no-returns-required.validator.js
  app/views/return-requirements/no-returns-required.njk
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/no-returns-required.presenter.test.js
  test/services/return-requirements/no-returns-required.service.test.js
  test/validators/no-returns-required/no-returns-required.validator.test.js
Labels: enhancement

#647 Housekeeping of return requirement routes
  app/controllers/licences.controller.js
  app/controllers/return-requirements.controller.js
  app/routes/return-requirement.routes.js
  app/views/return-requirements/add-note.njk
  app/views/return-requirements/agreements-exceptions.njk
  app/views/return-requirements/approved.njk
  app/views/return-requirements/check-your-answers.njk
  app/views/return-requirements/frequency-collected.njk
  app/views/return-requirements/frequency-reported.njk
  app/views/return-requirements/no-returns-check-your-answers.njk
  app/views/return-requirements/no-returns-required.njk
  app/views/return-requirements/purpose.njk
  app/views/return-requirements/reason.njk
  app/views/return-requirements/returns-cycle.njk
  app/views/return-requirements/setup.njk
  app/views/return-requirements/site-description.njk
  app/views/return-requirements/start-date.njk
  test/controllers/licences.controller.test.js
  test/controllers/return-requirements.controller.test.js
Labels: housekeeping

#648 Support both return requirements set up journeys
  app/controllers/licences.controller.js
  app/routes/licence.routes.js
  app/services/return-requirements/initiate-return-requirement-session.service.js
  test/controllers/licences.controller.test.js
  test/services/return-requirements/initiate-return-requirement-session.service.test.js
Labels: enhancement

#649 Fix return requirements start-date back link
  app/views/return-requirements/start-date.njk
Labels: bug

#650 Redirect rtns reqs start-date to correct journey
  app/controllers/return-requirements.controller.js
Labels: enhancement

#651 Fix missing titles in returns reqs. set up pages
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/no-returns-required.presenter.js
  app/routes/return-requirement.routes.js
  app/services/return-requirements/no-returns-required.service.js
  app/views/return-requirements/abstraction-period.njk
  app/views/return-requirements/add-note.njk
  app/views/return-requirements/agreements-exceptions.njk
  app/views/return-requirements/approved.njk
  app/views/return-requirements/check-your-answers.njk
  app/views/return-requirements/frequency-collected.njk
  app/views/return-requirements/frequency-reported.njk
  app/views/return-requirements/no-returns-check-your-answers.njk
  app/views/return-requirements/no-returns-required.njk
  app/views/return-requirements/points.njk
  app/views/return-requirements/purpose.njk
  app/views/return-requirements/reason.njk
  app/views/return-requirements/returns-cycle.njk
  app/views/return-requirements/setup.njk
  app/views/return-requirements/site-description.njk
  app/views/return-requirements/start-date.njk
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/no-returns-required.presenter.test.js
  test/services/return-requirements/no-returns-required.service.test.js
Labels: bug

#655 Determine licence start date 4 returns reqs setup
  app/services/return-requirements/initiate-return-requirement-session.service.js
  test/services/return-requirements/initiate-return-requirement-session.service.test.js
Labels: enhancement

#656 Refactor Prepare Licence For Allocation Service
  app/services/bill-runs/two-part-tariff/prepare-charge-version.service.js
  app/services/bill-runs/two-part-tariff/prepare-licences-for-allocation.service.js
  app/services/bill-runs/two-part-tariff/prepare-return-logs.service.js
  test/services/bill-runs/two-part-tariff/prepare-charge-version.service.test.js
  test/services/bill-runs/two-part-tariff/prepare-return-logs.service.test.js
Labels: housekeeping

#638 Match return to charge element service
  app/services/bill-runs/two-part-tariff/match-returns-to-charge-element.service.js
  test/services/bill-runs/two-part-tariff/match-returns-to-charge-element.service.test.js
Labels: enhancement

#640 Add LicenceDocumentHeaderModel
  app/models/licence-document-header.model.js
  app/models/licence.model.js
  db/migrations/legacy/20240107231129_create-crm-schema.js
  db/migrations/legacy/20240107231603_create-crm-document-header.js
  db/migrations/public/20240107233126_create-licence-document-headers.js
  test/models/licence-document-header.model.test.js
  test/models/licence.model.test.js
  test/support/helpers/database.helper.js
  test/support/helpers/licence-document-header.helper.js
Labels: enhancement

#628 Allocate returns to licence service
  app/services/bill-runs/two-part-tariff/allocate-returns-to-charge-element.service.js
  test/services/bill-runs/two-part-tariff/allocate-returns-to-charge-element.service.test.js
Labels: enhancement

#631 Licence Summary Page - Summary Tab
  app/controllers/licences.controller.js
  app/presenters/licences/view-licence.presenter.js
  app/routes/licence.routes.js
  app/services/licences/fetch-licence.service.js
  app/services/licences/view-licence.service.js
  app/views/licences/tabs/summary.njk
  app/views/licences/view.njk
  test/controllers/licences.controller.test.js
  test/services/licences/view-licence.service.test.js
Labels: enhancement

#665 Fix and improve acceptance testing attributes
  app/views/bill-runs/view.njk
  app/views/bills/view-multi-licence.njk
  app/views/bills/view-single-licence-presroc.njk
  app/views/bills/view-single-licence-sroc.njk
Labels: bug

#671 Improve tear down speed
  app/services/data/tear-down/README.md
  app/services/data/tear-down/crm-schema.service.js
  app/services/data/tear-down/idm-schema.service.js
  app/services/data/tear-down/permit-schema.service.js
  app/services/data/tear-down/returns-schema.service.js
  app/services/data/tear-down/water-schema.service.js
Labels: enhancement

#673 Fix broken licence agreement tear-down
  app/services/data/tear-down/water-schema.service.js
Labels: bug

#674 Fix tear-down by switching to single query
  app/services/data/tear-down/README.md
  app/services/data/tear-down/crm-schema.service.js
  app/services/data/tear-down/idm-schema.service.js
  app/services/data/tear-down/permit-schema.service.js
  app/services/data/tear-down/returns-schema.service.js
  app/services/data/tear-down/tear-down.service.js
  app/services/data/tear-down/water-schema.service.js
  test/services/data/tear-down/tear-down.service.test.js
Labels: bug

#675 Fix licence agreement tear down again!
  app/services/data/tear-down/water-schema.service.js
Labels: bug

#680 Update 2PT /check endpoint with latest services
  app/services/check/scenario-formatter.service.js
  app/services/check/stand-ins.service.js
  app/services/check/two-part.service.js
Labels: housekeeping

#689 Create licence holder seeder
  test/services/return-requirements/initiate-return-requirement-session.service.test.js
  test/support/seeders/licence-holder.seeder.js
Labels: enhancement

#690 Add LicenceEntityModel
  app/models/licence-entity.model.js
  db/migrations/legacy/20240127115605_create-crm-entity.js
  db/migrations/public/20240127121136_create-licence-entities-view.js
  test/models/licence-entity.model.test.js
  test/support/helpers/licence-entity.helper.js
Labels: enhancement

#692 Fix database cleaning breaking migrations
  test/support/helpers/database.helper.js
Labels: bug

#693 Add registered user modifier to LicenceModel
  app/models/licence.model.js
  db/migrations/public/20240127170505_alter-licence-document-headers.js
  test/models/licence.model.test.js
  test/support/helpers/licence-entity.helper.js
  test/support/seeders/registered-to-and-licence-name.seeder.js
Labels: enhancement

#694 Add missing title in view licence page
  app/presenters/licences/view-licence.presenter.js
  test/presenters/licences/view-licence.presenter.test.js
  test/services/bill-runs/view-bill-run.service.test.js
  test/services/licences/view-licence.service.test.js
Labels: bug

#646 Returns required journey - Select start date page iteration 2 (1 of 7)
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/start-date.presenter.js
  app/services/return-requirements/initiate-return-requirement-session.service.js
  app/services/return-requirements/start-date.service.js
  app/services/return-requirements/submit-start-date.service.js
  app/validators/return-requirements/start-date.validator.js
  app/views/return-requirements/start-date.njk
  package-lock.json
  package.json
  test/controllers/return-requirements.controller.test.js
  test/presenters/return-requirements/start-date.presenter.test.js
  test/services/return-requirements/initiate-return-requirement-session.service.test.js
  test/services/return-requirements/start-date.service.test.js
  test/services/return-requirements/submit-start-date.service.test.js
  test/validators/no-returns-required/start-date.validator.test.js
Labels: enhancement

#697 Handle create annual bill run requests
  app/lib/static-lookups.lib.js
  app/services/bill-runs/annual/process-bill-run.service.js
  app/services/bill-runs/start-bill-run-process.service.js
  test/services/bill-runs/annual/process-bill-run.service.test.js
  test/services/bill-runs/start-bill-run-process.service.test.js
Labels: enhancement

#701 Move the calculate & log time feature to lib
  app/lib/general.lib.js
  app/services/bill-runs/supplementary/process-bill-run.service.js
  app/services/bill-runs/two-part-tariff/match-and-allocate.service.js
  app/services/data/tear-down/tear-down.service.js
  app/services/jobs/export/export.service.js
  test/lib/general.lib.test.js
Labels: housekeeping

#663 Review Result of 2PT Matching for selected Region
  app/controllers/bill-runs.controller.js
  app/models/licence.model.js
  app/models/review-result.model.js
  app/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.js
  app/services/bill-runs/two-part-tariff/determine-bill-run-issues.service.js
  app/services/bill-runs/two-part-tariff/fetch-bill-run-licences.service.js
  app/services/bill-runs/two-part-tariff/fetch-review-results.service.js
  app/services/bill-runs/two-part-tariff/match-and-allocate.service.js
  app/services/bill-runs/two-part-tariff/review-bill-run.service.js
  app/services/bills/fetch-bill-service.js
  app/services/jobs/export/fetch-table-names.service.js
  app/views/bill-runs/review.njk
  test/controllers/bill-runs.controller.test.js
  test/models/licence.model.test.js
  test/models/review-result.model.test.js
  test/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.test.js
  test/services/bill-runs/two-part-tariff/determine-bill-run-issues.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-bill-run-licences.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-results.service.test.js
  test/services/bill-runs/two-part-tariff/match-and-allocate.service.test.js
  test/services/bill-runs/two-part-tariff/review-bill-run.service.test.js
Labels: enhancement
