Repository DEFRA/water-abstraction-system, pull requests merged in 2024-12, with the labels that each got.

#1524 Update determine charge versions flags service
  app/services/licences/supplementary/process-billing-flag.service.js
  test/services/licences/supplementary/process-billing-flag.service.test.js
Labels: housekeeping

#1528 Notifications returns period options - November - December
  app/lib/static-lookups.lib.js
  app/presenters/notifications/setup/returns-period.presenter.js
  test/presenters/notifications/setup/returns-period.presenter.test.js
  test/services/notifications/setup/returns-period.services.test.js
Labels: enhancement

#1540 Notifications returns period options - October - November
  app/lib/static-lookups.lib.js
  app/presenters/notifications/setup/returns-period.presenter.js
  test/presenters/notifications/setup/returns-period.presenter.test.js
Labels: enhancement

#1543 Update model tests to use before block
  test/models/address.model.test.js
  test/models/bill-licence.model.test.js
  test/models/bill-run-charge-version-year.model.test.js
  test/models/bill-run-volume.model.test.js
  test/models/bill-run.model.test.js
  test/models/bill.model.test.js
Labels: housekeeping

#1544 Update model tests to use before block
  test/models/billing-account-address.model.test.js
  test/models/change-reason.model.test.js
  test/models/charge-category.model.test.js
  test/models/charge-element.model.test.js
  test/models/charge-reference.model.test.js
  test/models/charge-version.model.test.js
  test/models/company-address.model.test.js
  test/models/company-contact.model.test.js
  test/models/company.model.test.js
  test/models/contact.model.test.js
  test/models/event.model.test.js
  test/models/financial-agreement.model.test.js
  test/models/licence-agreement.model.test.js
  test/models/licence-document-role.model.test.js
  test/models/licence-document.model.test.js
  test/models/licence-role.model.test.js
Labels: housekeeping

#1547 Update updatedAt date for new supplementary flags
  app/services/licences/supplementary/persist-supplementary-billing-flags.service.js
Labels: bug

#1551 Fix return log helper breaking acceptance tests
  test/support/helpers/return-log.helper.js
Labels: bug

#1550 Add /check into bill run setup ready for 2PT supp.
  app/controllers/bill-runs-setup.controller.js
  app/lib/static-lookups.lib.js
  app/presenters/base.presenter.js
  app/presenters/bill-runs/setup/check.presenter.js
  app/presenters/bill-runs/setup/create.presenter.js
  app/routes/bill-runs-setup.routes.js
  app/services/bill-runs/setup/check.service.js
  app/services/bill-runs/setup/create.service.js
  app/services/bill-runs/setup/exists.service.js
  app/services/bill-runs/setup/submit-check.service.js
  app/services/bill-runs/setup/submit-year.service.js
  app/views/bill-runs/setup/check.njk
  app/views/bill-runs/setup/create.njk
  test/controllers/bill-runs-setup.controller.test.js
  test/presenters/base.presenter.test.js
  test/presenters/bill-runs/setup/check.presenter.test.js
  test/presenters/bill-runs/setup/create.presenter.test.js
  test/services/bill-runs/setup/check.service.test.js
  test/services/bill-runs/setup/create.service.test.js
  test/services/bill-runs/setup/exists.service.test.js
  test/services/bill-runs/setup/submit-check.service.test.js
  test/services/bill-runs/setup/submit-year.service.test.js
Labels: enhancement

#1552 Amend transaction line description for 2PT bills
  app/services/bill-runs/generate-transactions.service.js
  app/services/bill-runs/two-part-tariff/generate-transaction.service.js
  test/controllers/bill-licences.controller.test.js
  test/services/bill-runs/generate-transactions.service.test.js
  test/services/bill-runs/two-part-tariff/generate-transaction.service.test.js
Labels: enhancement

#1559 Feature returns period lib determine upcoming periods
  app/lib/return-periods.lib.js
  test/lib/return-periods.lib.test.js
Labels: enhancement

#1557 Fix SonarQube test coverage issue
  .github/workflows/ci.yml
Labels: bug, housekeeping

#1562 Use existing title helpers in review pages
  app/presenters/bill-runs/review/review-bill-run.presenter.js
  app/presenters/bill-runs/review/review-licence.presenter.js
  app/services/bill-runs/review/fetch-bill-run-licences.service.js
  app/services/bill-runs/review/fetch-review-licence.service.js
  app/views/bill-runs/review/review-licence.njk
  app/views/bill-runs/review/review.njk
  test/controllers/bill-runs-review.controller.test.js
  test/fixtures/bill-runs-review.fixture.js
  test/presenters/bill-runs/review/review-bill-run.presenter.test.js
  test/presenters/bill-runs/review/review-licence.presenter.test.js
  test/services/bill-runs/review/fetch-bill-run-licences.service.test.js
  test/services/bill-runs/review/fetch-review-licence.service.test.js
  test/services/bill-runs/review/review-licence.service.test.js
Labels: housekeeping

#1560 Refactor returns period presenter to use determine upcoming periods
  app/lib/return-periods.lib.js
  app/lib/static-lookups.lib.js
  app/presenters/notifications/setup/returns-period.presenter.js
  test/lib/return-periods.lib.test.js
  test/presenters/notifications/setup/returns-period.presenter.test.js
  test/services/notifications/setup/returns-period.services.test.js
Labels: enhancement

#1549 Display multiple purposes in 2PT review pages
  app/presenters/bill-runs/review/base-review.presenter.js
  app/presenters/bill-runs/review/review-licence.presenter.js
  test/presenters/bill-runs/review/base-review.presenter.test.js
Labels: enhancement

#1563 Remove redundant code in create bill run services
  app/presenters/bill-runs/create-bill-run.presenter.js
  app/services/bill-runs/determine-billing-periods.service.js
  app/services/bill-runs/start-bill-run-process.service.js
  test/presenters/bill-runs/create-bill-run.presenter.test.js
  test/services/bill-runs/determine-billing-periods.service.test.js
  test/services/bill-runs/start-bill-run-process.service.test.js
Labels: housekeeping

#1453 New 'import' job to trigger return log and supplementary flag checks
  app/controllers/jobs.controller.js
  app/routes/jobs.routes.js
  app/services/jobs/import/fetch-licences.service.js
  app/services/jobs/import/import-licences.service.js
  app/services/jobs/import/process-import-licence.service.js
  config/jobs.config.js
  package-lock.json
  package.json
  test/controllers/jobs.controller.test.js
  test/services/jobs/import/import-licences.service.test.js
  test/services/jobs/import/process-import-licence.service.test.js
Labels: enhancement

#1555 Add ad-hoc returns enter licence page
  app/controllers/notifications-ad-hoc-returns.controller.js
  app/plugins/router.plugin.js
  app/presenters/notifications/ad-hoc-returns/licence.presenter.js
  app/routes/notifications-ad-hoc-returns.route.js
  app/services/notifications/ad-hoc-returns/initiate-session.service.js
  app/services/notifications/ad-hoc-returns/licence.service.js
  app/services/notifications/ad-hoc-returns/submit-licence.service.js
  app/views/notifications/ad-hoc-returns/licence.njk
  test/controllers/notifications-ad-hoc-returns.controller.test.js
  test/presenters/notifications/ad-hoc-returns/licence.presenter.test.js
  test/services/notifications/ad-hoc-returns/initiate-session.service.test.js
  test/services/notifications/ad-hoc-returns/licence.service.test.js
  test/services/notifications/ad-hoc-returns/submit-licence.service.test.js
Labels: enhancement

#1571 Feature returns period submit logic
  app/controllers/notifications-setup.controller.js
  app/routes/notifications-setup.routes.js
  app/services/notifications/setup/submit-returns-period.service.js
  app/validators/notifications/setup/returns-periods.validator.js
  app/views/notifications/setup/view-returns-period.njk
  test/controllers/notifications.controller.test.js
  test/services/notifications/setup/submit-returns-period.services.test.js
  test/support/general.js
  test/validators/notifications/setup/returns-period.validator.test.js
Labels: enhancement

#1574 Feature notifications setup session
  app/controllers/notifications-setup.controller.js
  app/routes/notifications-setup.routes.js
  app/services/notifications/setup/initiate-session.service.js
  test/controllers/notifications-setup.controller.test.js
  test/services/notifications/setup/initiate-session.service.test.js
Labels: enhancement

#1575 Feature notifications setup returns period session
  app/controllers/notifications-setup.controller.js
  app/presenters/notifications/setup/returns-period.presenter.js
  app/services/notifications/setup/returns-period.service.js
  app/services/notifications/setup/submit-returns-period.service.js
  test/presenters/notifications/setup/returns-period.presenter.test.js
  test/services/notifications/setup/returns-period.services.test.js
  test/services/notifications/setup/submit-returns-period.services.test.js
Labels: enhancement

#1569 Add `param_1_label` & `param_2_label` to lvpct view
  db/migrations/legacy/20221108007028_water-licence-version-purpose-condition-types.js
  db/migrations/public/20241216143417_alter-licence-version-purpose-condition-types-view.js
  db/seeds/data/licence-version-purpose-condition-types.js
Labels: housekeeping

#1583 Fix miscalculated preview 2PT charge in review
  app/services/bill-runs/review/preview.service.js
  test/services/bill-runs/review/preview.service.test.js
Labels: bug

#1584 Fix miscalculated preview 2PT charge in review pt2
  app/services/bill-runs/review/fetch-review-charge-reference.service.js
  test/services/bill-runs/review/fetch-review-charge-reference.service.test.js
Labels: bug

#1585 Remove the replacement legacy import code
  .env.example
  app/controllers/import.controller.js
  app/plugins/router.plugin.js
  app/routes/import.routes.js
  app/services/import/legacy/fetch-address.service.js
  app/services/import/legacy/fetch-company-address.service.js
  app/services/import/legacy/fetch-company.service.js
  app/services/import/legacy/fetch-contacts.service.js
  app/services/import/legacy/fetch-licence-document-roles.service.js
  app/services/import/legacy/fetch-licence-document.service.js
  app/services/import/legacy/fetch-licence-version-purpose-conditions.service.js
  app/services/import/legacy/fetch-licence-version-purposes.service.js
  app/services/import/legacy/fetch-licence-versions.service.js
  app/services/import/legacy/fetch-licence.service.js
  app/services/import/legacy/process-licence.service.js
  app/services/import/legacy/transform-addresses.service.js
  app/services/import/legacy/transform-companies.service.js
  app/services/import/legacy/transform-company-addresses.service.js
  app/services/import/legacy/transform-contacts.service.js
  app/services/import/legacy/transform-licence-document-roles.service.js
  app/services/import/legacy/transform-licence-document.service.js
  app/services/import/legacy/transform-licence-version-purpose-conditions.service.js
  app/services/import/legacy/transform-licence-version-purposes.service.js
  app/services/import/legacy/transform-licence-versions.service.js
  app/services/import/legacy/transform-licence.service.js
  app/services/import/persist-import.service.js
  app/services/import/persist/persist-company.service.js
  app/services/import/persist/persist-licence-document.service.js
  app/services/import/persist/persist-licence-versions.service.js
  app/services/import/persist/persist-licence.service.js
  app/services/jobs/import/determine-licence-end-date-changed.service.js
  app/services/jobs/import/generate-return-logs.service.js
  app/services/jobs/import/process-import-licence.service.js
  config/feature-flags.config.js
  test/controllers/import.controller.test.js
  test/services/import/legacy/process-licence.service.test.js
  test/services/import/legacy/transform-addresses.service.test.js
  test/services/import/legacy/transform-companies.service.test.js
  test/services/import/legacy/transform-company-addresses.service.test.js
  test/services/import/legacy/transform-contacts.service.test.js
  test/services/import/legacy/transform-licence-document-role.service.test.js
  test/services/import/legacy/transform-licence-document.service.test.js
  test/services/import/legacy/transform-licence-version-purpose-conditions.service.test.js
  test/services/import/legacy/transform-licence-version-purposes.service.test.js
  test/services/import/legacy/transform-licence-versions.service.test.js
  test/services/import/legacy/transform-licence.service.test.js
  test/services/import/persist-import.service.test.js
  test/services/import/persist/persist-company.service.test.js
  test/services/import/persist/persist-licence-document.service.test.js
  test/services/import/persist/persist-licence-versions.service.test.js
  test/services/import/persist/persist-licence.service.test.js
  test/services/jobs/import/determine-licence-end-date-changed.service.test.js
  test/services/jobs/import/generate-return-logs.service.test.js
  test/services/jobs/import/process-import-licence.service.test.js
Labels: housekeeping

#1587 Remove missed replacement legacy import code
  app/presenters/import/legacy/address.presenter.js
  app/presenters/import/legacy/company-address.presenter.js
  app/presenters/import/legacy/company-contact.presenter.js
  app/presenters/import/legacy/company.presenter.js
  app/presenters/import/legacy/contact.presenter.js
  app/presenters/import/legacy/licence-document-role.presenter.js
  app/presenters/import/legacy/licence-document.presenter.js
  app/presenters/import/legacy/licence-version-purpose-condition.presenter.js
  app/presenters/import/legacy/licence-version-purpose.presenter.js
  app/presenters/import/legacy/licence-version.presenter.js
  app/presenters/import/legacy/licence.presenter.js
  app/services/plugins/hapi-pino-ignore-request.service.js
  app/validators/import/address.validator.js
  app/validators/import/company.validator.js
  app/validators/import/contact.validator.js
  app/validators/import/licence-document-role.validator.js
  app/validators/import/licence-document.validator.js
  app/validators/import/licence-structure.validator.js
  app/validators/import/licence-version-purpose-condition.validator.js
  app/validators/import/licence-version-purpose.validator.js
  app/validators/import/licence-version.validator.js
  app/validators/import/licence.validator.js
  test/presenters/import/legacy/address.presenter.test.js
  test/presenters/import/legacy/company-address.presenter.test.js
  test/presenters/import/legacy/company-contact.presenter.test.js
  test/presenters/import/legacy/company.presenter.test.js
  test/presenters/import/legacy/contact.presenter.test.js
  test/presenters/import/legacy/licence-document-role.presenter.test.js
  test/presenters/import/legacy/licence-document.presenter.test.js
  test/presenters/import/legacy/licence-version-purpose-condition.presenter.test.js
  test/presenters/import/legacy/licence-version-purpose.presenter.test.js
  test/presenters/import/legacy/licence-version.presenter.test.js
  test/presenters/import/legacy/licence.presenter.test.js
  test/services/plugins/hapi-pino-ignore-request.service.test.js
  test/validators/import/address.validator.test.js
  test/validators/import/company.validator.test.js
  test/validators/import/contact.validator.test.js
  test/validators/import/licence-document-role.validator.test.js
  test/validators/import/licence-document.validator.test.js
  test/validators/import/licence-structure.validator.test.js
  test/validators/import/licence-version-purpose-conditions.validator.test.js
  test/validators/import/licence-version-purpose.validator.test.js
  test/validators/import/licence-version.validator.test.js
  test/validators/import/licence.validator.test.js
Labels: housekeeping

#1586 Add enforcement of .js extensions for require()
  .labrc.js
  app/controllers/notifications-setup.controller.js
  app/presenters/notifications/setup/returns-period.presenter.js
  app/services/jobs/import/process-import-licence.service.js
  app/services/notifications/setup/returns-period.service.js
  app/services/notifications/setup/submit-returns-period.service.js
  app/validators/notifications/setup/returns-periods.validator.js
  eslint.config.js
  package-lock.json
  package.json
  test/services/jobs/import/process-import-licence.service.test.js
Labels: housekeeping

#1590 Editing a return log session data
  app/controllers/return-logs-edit.controller.js
  app/plugins/router.plugin.js
  app/routes/return-logs-edit.routes.js
  app/services/return-logs-edit/initiate-session.service.js
  test/controllers/return-logs-edit.controller.test.js
  test/services/return-logs-edit/initiate-session.service.test.js
Labels: enhancement
