Repository DEFRA/water-abstraction-system, pull requests merged in 2024-07, with the labels that each got.

#1132 Fix view licence abs amounts issue plus refactor
  app/presenters/licences/view-licence-summary.presenter.js
  app/services/licences/fetch-licence-summary.service.js
  app/views/licences/tabs/summary.njk
  test/presenters/licences/view-licence-summary.presenter.test.js
  test/services/licences/fetch-licence-summary.service.test.js
  test/services/licences/view-licence-summary.service.test.js
Labels: bug, housekeeping

#1150 Enhance view licence page contacts tab
  app/views/licences/tabs/contact-details.njk
  test/controllers/licences.controller.test.js
Labels: enhancement

#1147 Stop using version in package.json
  app/services/health/fetch-system-info.service.js
  test/services/health/fetch-system-info.service.test.js
Labels: housekeeping

#1152 Fix duplicate monitoring stations in view licence
  app/presenters/licences/view-licence-summary.presenter.js
  test/presenters/licences/view-licence-summary.presenter.test.js
Labels: bug

#1153 Display msg for multiple abs amounts in view
  app/presenters/licences/view-licence-summary.presenter.js
  app/views/licences/tabs/summary.njk
  test/presenters/licences/view-licence-summary.presenter.test.js
  test/services/licences/view-licence-summary.service.test.js
Labels: enhancement

#1157 Switch to GOV.UK table component for licence comms
  app/views/licences/tabs/communications.njk
Labels: housekeeping

#1158 Switch to GOV.UK table component for licence bills
  app/views/licences/tabs/bills.njk
Labels: housekeeping

#1159 Fix bill run type in view licence bills tab
  app/presenters/licences/view-licence-bills.presenter.js
  app/services/licences/fetch-licence-bills.service.js
  app/services/licences/view-licence-bills.service.js
  app/views/licences/tabs/bills.njk
  test/presenters/licences/view-licence-bills-presenter.test.js
  test/presenters/licences/view-licence-bills.presenter.test.js
  test/presenters/licences/view-licence.presenter.test.js
  test/services/licences/fetch-licence-bills.service.test.js
  test/services/licences/view-licence-bills.service.test.js
Labels: bug

#1155 Fix route handler property to follow same pattern
  app/routes/assets.routes.js
  app/routes/bill-runs-setup.routes.js
  app/routes/bill-runs.routes.js
  app/routes/billing-accounts.routes.js
  app/routes/data.routes.js
  app/routes/health.routes.js
  app/routes/jobs.routes.js
  app/routes/licence.routes.js
  app/routes/return-requirement.routes.js
  app/routes/root.routes.js
Labels: housekeeping

#1162 Fix order of charge versions in view licence page
  app/services/licences/fetch-charge-versions.service.js
  test/services/licences/fetch-charge-versions.service.test.js
Labels: bug

#1163 Fix returns link in view licence page
  app/presenters/licences/view-licence-returns.presenter.js
  app/services/licences/view-licence-returns.service.js
  app/views/licences/tabs/returns.njk
  test/presenters/licences/view-licence-returns.presenter.test.js
  test/services/licences/view-licence-returns.service.test.js
Labels: bug

#1161 Add abs period to returns on two-part tariff review page
  app/models/review-return.model.js
  app/presenters/bill-runs/two-part-tariff/match-details.presenter.js
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/services/bill-runs/two-part-tariff/fetch-match-details.service.js
  app/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.js
  app/views/bill-runs/match-details.njk
  app/views/bill-runs/review-licence.njk
  test/models/review-return.model.test.js
  test/presenters/bill-runs/two-part-tariff/match-details.presenter.test.js
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-match-details.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.test.js
  test/services/bill-runs/two-part-tariff/match-details.service.test.js
  test/services/bill-runs/two-part-tariff/review-licence.service.test.js
Labels: enhancement

#1164 Make Bill run value blank when in Review Status
  app/presenters/bill-runs/index-bill-runs.presenter.js
  test/presenters/bill-runs/index-bill-runs.presenter.test.js
Labels: enhancement

#1168 Fix order of charge vers. in view licence - again!
  app/services/licences/fetch-charge-versions.service.js
  test/services/licences/fetch-charge-versions.service.test.js
Labels: bug

#1165 Fix unit tests after enablingSystemLicenceView tag
  .github/workflows/ci.yml
  test/presenters/return-requirements/start-date.presenter.test.js
  test/services/return-requirements/start-date.service.test.js
  test/services/return-requirements/submit-start-date.service.test.js
Labels: testing

#1129 Add FetchBillingAccountsService for 2-part tariff
  app/services/bill-runs/two-part-tariff/fetch-billing-accounts.service.js
  test/services/bill-runs/two-part-tariff/fetch-billing-accounts.service.test.js
Labels: enhancement

#1169 Add missing return requirement set up reasons
  app/lib/static-lookups.lib.js
  app/validators/return-requirements/reason.validator.js
  app/views/return-requirements/reason.njk
Labels: housekeeping

#1172 Implement annual two-part tariff billing engine
  app/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.js
  app/services/bill-runs/two-part-tariff/fetch-billing-accounts.service.js
  app/services/bill-runs/two-part-tariff/generate-bill-run.service.js
  app/services/bill-runs/two-part-tariff/generate-transaction.service.js
  app/services/bill-runs/two-part-tariff/process-billing-period.service.js
  test/presenters/bill-runs/two-part-tariff/review-bill-run.presenter.test.js
  test/services/bill-runs/two-part-tariff/fetch-billing-accounts.service.test.js
  test/services/bill-runs/two-part-tariff/generate-bill-run.service.test.js
  test/services/bill-runs/two-part-tariff/generate-transaction.service.test.js
  test/services/bill-runs/two-part-tariff/process-billing-period.service.test.js
  test/support/helpers/region.helper.js
Labels: enhancement

#1170 Two-part tariff warning message for licence review page
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/views/bill-runs/review-licence.njk
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
Labels: enhancement

#1175 Fix dates in view licence set up tab
  app/presenters/licences/set-up.presenter.js
  test/presenters/licences/set-up.presenter.test.js
  test/services/licences/view-licence-set-up.service.test.js
Labels: bug

#1174 Update tear down service
  app/services/data/tear-down/public-schema.service.js
  app/services/data/tear-down/tear-down.service.js
  test/services/data/tear-down/tear-down.service.test.js
Labels: enhancement

#1177 Add optional alias to return requirement purpose
  app/presenters/return-requirements/check/returns-requirements.presenter.js
  app/presenters/return-requirements/purpose.presenter.js
  app/services/return-requirements/check.service.js
  app/services/return-requirements/check/returns-requirements.service.js
  app/services/return-requirements/submit-purpose.service.js
  app/validators/return-requirements/purpose.validator.js
  app/views/return-requirements/purpose.njk
  test/presenters/return-requirements/check/returns-requirements.presenter.test.js
  test/presenters/return-requirements/purpose.presenter.test.js
  test/services/return-requirements/check.service.test.js
  test/services/return-requirements/check/returns-requirements.service.test.js
  test/services/return-requirements/purpose.service.test.js
  test/services/return-requirements/submit-purpose.service.test.js
  test/validators/return-requirements/purpose.validator.test.js
Labels: enhancement

#1171 Update display of points in return requirements
  app/views/return-requirements/check.njk
  app/views/return-requirements/view.njk
Labels: enhancement, housekeeping

#1180 Fix duplicate purposes in return reqs. set up
  app/services/return-requirements/fetch-purposes.service.js
  app/services/return-requirements/purpose.service.js
  app/services/return-requirements/submit-purpose.service.js
  test/services/return-requirements/fetch-licence-purposes.service.test.js
  test/services/return-requirements/fetch-purposes.service.test.js
  test/services/return-requirements/purpose.service.test.js
  test/services/return-requirements/submit-purpose.service.test.js
Labels: bug

#1184 Only use 1st site description in return reqs set up
  app/services/return-requirements/setup/generate-from-abstraction-data.service.js
  test/services/return-requirements/setup/generate-from-abstraction-data.service.test.js
Labels: housekeeping

#1183 Display the purpose desc (alias) in rtn req view
  app/presenters/return-requirements/view.presenter.js
  app/services/return-requirements/fetch-return-version.service.js
  app/services/return-requirements/view.service.js
  test/presenters/return-requirements/check/returns-requirements.presenter.test.js
  test/presenters/return-requirements/view.presenter.test.js
  test/services/return-requirements/fetch-return-version.service.test.js
  test/services/return-requirements/generate-from-existing-requirements.service.test.js
  test/services/return-requirements/view.service.test.js
  test/support/seeders/requirements-for-returns.seeder.js
Labels: enhancement

#1185 Update ret. req. setup use abstraction & copy
  app/models/licence-version-purpose.model.js
  app/services/return-requirements/generate-from-existing-requirements.service.js
  app/services/return-requirements/setup/generate-from-abstraction-data.service.js
  test/services/return-requirements/cancel.service.test.js
  test/services/return-requirements/check-licence-ended.service.test.js
  test/services/return-requirements/check.service.test.js
  test/services/return-requirements/generate-from-existing-requirements.service.test.js
  test/services/return-requirements/remove.service.test.js
  test/services/return-requirements/setup/fetch-abstraction-data.service.test.js
  test/services/return-requirements/setup/generate-from-abstraction-data.service.test.js
  test/services/return-requirements/submit-cancel.service.test.js
  test/services/return-requirements/submit-remove.service.test.js
Labels: enhancement

#1186 Add bookmarks to return reqs check page
  app/views/return-requirements/check.njk
Labels: enhancement

#1187 Add bookmarks to return requirements view page
  app/presenters/return-requirements/view.presenter.js
  app/views/return-requirements/view.njk
  test/presenters/return-requirements/view.presenter.test.js
  test/services/return-requirements/view.service.test.js
Labels: enhancement

#1188 Fix error in generate 2PT bill run transactions
  app/services/bill-runs/two-part-tariff/generate-transaction.service.js
  app/services/bill-runs/two-part-tariff/process-billing-period.service.js
  test/services/bill-runs/two-part-tariff/generate-transaction.service.test.js
  test/services/bill-runs/two-part-tariff/process-billing-period.service.test.js
Labels: bug

#1190 Alter two-part tariff returns allocation by date
  app/services/bill-runs/two-part-tariff/allocate-returns-to-charge-element.service.js
  app/services/bill-runs/two-part-tariff/match-and-allocate.service.js
  test/services/bill-runs/two-part-tariff/allocate-returns-to-charge-element.service.test.js
Labels: enhancement

#1137 Persist a new return version and its requirements
  app/controllers/return-requirements.controller.js
  app/presenters/return-requirements/cancel.presenter.js
  app/presenters/return-requirements/check/returns-requirements.presenter.js
  app/presenters/return-requirements/remove.presenter.js
  app/services/return-requirements/fetch-points.service.js
  app/services/return-requirements/generate-from-existing-requirements.service.js
  app/services/return-requirements/generate-return-version-requirements.service.js
  app/services/return-requirements/generate-return-version.service.js
  app/services/return-requirements/persist-return-version.service.js
  app/services/return-requirements/setup/generate-from-abstraction-data.service.js
  app/services/return-requirements/submit-check.service.js
  app/validators/return-requirements/frequency-collected.validator.js
  app/validators/return-requirements/frequency-reported.validator.js
  app/views/return-requirements/frequency-collected.njk
  app/views/return-requirements/frequency-reported.njk
  test/presenters/return-requirements/cancel.presenter.test.js
  test/presenters/return-requirements/check/returns-requirements.presenter.test.js
  test/presenters/return-requirements/frequency-collected.presenter.test.js
  test/presenters/return-requirements/frequency-reported.presenter.test.js
  test/presenters/return-requirements/remove.presenter.test.js
  test/services/return-requirements/cancel.service.test.js
  test/services/return-requirements/generate-from-existing-requirements.service.test.js
  test/services/return-requirements/generate-return-version-requirements.service.test.js
  test/services/return-requirements/generate-return-version.service.test.js
  test/services/return-requirements/persist-return-version.service.test.js
  test/services/return-requirements/remove.service.test.js
  test/services/return-requirements/setup/generate-from-abstraction-data.service.test.js
  test/services/return-requirements/submit-cancel.service.test.js
  test/services/return-requirements/submit-check.service.test.js
  test/services/return-requirements/submit-existing.service.test.js
  test/services/return-requirements/submit-frequency-collected.service.test.js
  test/services/return-requirements/submit-frequency-reported.service.test.js
  test/services/return-requirements/submit-remove.service.test.js
  test/validators/return-requirements/frequency-collected.validator.test.js
  test/validators/return-requirements/frequency-reported.validator.test.js
Labels: enhancement

#1191 Import Licence
  app/controllers/import.controller.js
  app/lib/dates.lib.js
  app/plugins/router.plugin.js
  app/routes/import.routes.js
  app/services/import/legacy-import/constants.js
  app/services/import/legacy-import/fetch-licence-versions.service.js
  app/services/import/legacy-import/fetch-licence.service.js
  app/services/import/legacy-import/licence.mapper.js
  app/services/import/legacy-licence.service.js
  app/services/import/licence-validator.service.js
  app/services/import/persist-licence.service.js
  app/validators/custom/date.validators.js
  app/validators/import/licence.validator.js
  test/controllers/import.controller.test.js
  test/lib/dates.lib.test.js
  test/services/import/_fixtures/licence.js
  test/services/import/_fixtures/versions.js
  test/services/import/legacy-import/licence.mapper.test.js
  test/services/import/legacy-licence.service.test.js
  test/services/import/licence-validator.service.test.js
  test/services/import/persist-licence.service.test.js
  test/validators/import/_fixtures/valid-licence.fixture.js
  test/validators/import/licence.validator.test.js
Labels: enhancement

#1198 Two-part tariff due returns to show as blank
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
Labels: enhancement

#1199 Amend licence holder display two-part tariff review pages
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  app/views/bill-runs/review-licence.njk
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
  test/services/bill-runs/two-part-tariff/review-licence.service.test.js
Labels: enhancement

#1202 Lower case H for licence holder on 2pt review page
  app/views/bill-runs/review-licence.njk
Labels: bug

#1205 Two-part tariff void returns to show as void on review screens
  app/presenters/bill-runs/two-part-tariff/review-licence.presenter.js
  test/presenters/bill-runs/two-part-tariff/review-licence.presenter.test.js
Labels: enhancement

#1200 Some returns not received error incorrectly applies 2pt
  app/services/bill-runs/two-part-tariff/determine-licence-issues.service.js
  test/services/bill-runs/two-part-tariff/determine-licence-issues.service.test.js
Labels: enhancement

#1206 https://eaflood.atlassian.net/browse/WATER-4579
  db/seeds/reference-data.js
  test/models/charge-element.model.test.js
  test/models/charge-reference.model.test.js
  test/models/licence-version-purpose.model.test.js
  test/models/licence-version.model.test.js
  test/models/primary-purpose.model.test.js
  test/models/purpose.model.test.js
  test/models/return-requirement-purpose.model.test.js
  test/models/secondary-purpose.model.test.js
  test/services/bill-licences/fetch-bill-licence.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-charge-versions.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-review-licence-results.service.test.js
  test/services/licences/fetch-licence-summary.service.test.js
  test/services/return-requirements/fetch-purposes.service.test.js
  test/services/return-requirements/setup/fetch-abstraction-data.service.test.js
  test/support/seeders/data/primary-purposes.js
  test/support/seeders/data/purposes.data.js
  test/support/seeders/data/secondary-purposes.js
  test/support/seeders/licence-abstraction-data.seeder.js
  test/support/seeders/primary-purpose.seeder.js
  test/support/seeders/purposes.seeder.js
  test/support/seeders/requirements-for-returns.seeder.js
  test/support/seeders/secondary-purpose.seeder.js
  test/support/seeders/seed-builder.js
Labels: housekeeping

#1208 Align regions seeder
  test/services/bill-runs/fetch-region.service.test.js
  test/services/bill-runs/setup/fetch-regions.service.test.js
  test/services/import/legacy-licence.service.test.js
  test/services/import/persist-licence.service.test.js
  test/support/seeders/data/region.data.js
  test/support/seeders/regions.seeder.js
Labels: conventions

#1204 Add licence workflow warning to view licence page
  app/presenters/licences/view-licence.presenter.js
  app/services/licences/fetch-licence.service.js
  app/views/licences/view.njk
  test/presenters/licences/view-licence.presenter.test.js
  test/services/licences/view-licence.service.test.js
Labels: enhancement

#1207 Removing DatabaseSupport.clean()
  test/models/address.model.test.js
  test/models/bill-licence.model.test.js
  test/models/bill-run-charge-version-year.model.test.js
  test/models/bill-run-volume.model.test.js
  test/models/bill-run.model.test.js
  test/models/bill.model.test.js
  test/models/billing-account-address.model.test.js
  test/models/billing-account.model.test.js
  test/models/change-reason.model.test.js
  test/models/charge-category.model.test.js
  test/models/charge-element.model.test.js
  test/models/charge-reference.model.test.js
  test/models/charge-version.model.test.js
  test/models/company-address.model.test.js
  test/models/company-contact.model.test.js
  test/models/company.model.test.js
  test/models/contact.model.test.js
  test/models/event.model.test.js
  test/models/financial-agreement.model.test.js
  test/models/gauging-station.model.test.js
  test/models/group-role.model.test.js
  test/models/group.model.test.js
  test/models/licence-agreement.model.test.js
  test/models/licence-document-header.model.test.js
  test/models/licence-document-role.model.test.js
  test/models/licence-document.model.test.js
  test/models/licence-entity-role.model.test.js
  test/models/licence-entity.model.test.js
  test/models/licence-gauging-station.model.test.js
  test/models/licence-role.model.test.js
  test/models/licence-version.model.test.js
  test/models/licence.model.test.js
  test/models/region.model.test.js
  test/models/return-log.model.test.js
  test/models/return-requirement-point.model.test.js
  test/models/return-requirement.model.test.js
  test/models/return-submission-line.model.test.js
  test/models/return-submission.model.test.js
  test/models/return-version.model.test.js
  test/models/review-charge-element-return.model.test.js
  test/models/review-charge-element.model.test.js
  test/models/review-charge-reference.model.test.js
  test/models/review-charge-version.model.test.js
  test/models/review-licence.model.test.js
  test/models/review-return.model.test.js
  test/models/role.model.test.js
  test/models/scheduled-notification.model.test.js
  test/models/session.model.test.js
  test/models/transaction.model.test.js
  test/models/user-group.model.test.js
  test/models/user-role.model.test.js
  test/models/user.model.test.js
  test/models/workflow.model.test.js
Labels: housekeeping

#1213 Persist a new return version for 'no returns required'
  app/services/return-requirements/generate-return-version.service.js
  test/services/return-requirements/generate-return-version.service.test.js
Labels: enhancement

#1215 Amend 'Agreements' title on Licence set up tab
  app/views/licences/tabs/set-up.njk
  test/controllers/licences.controller.test.js
Labels: housekeeping

#1217 Change 'Transfer licence' reason for 'No returns needed' journey
  app/lib/static-lookups.lib.js
  app/services/return-requirements/submit-no-returns-required.service.js
  app/validators/return-requirements/no-returns-required.validator.js
  app/views/return-requirements/no-returns-required.njk
  test/presenters/return-requirements/no-returns-required.presenter.test.js
  test/services/return-requirements/initiate-session.service.test.js
  test/validators/return-requirements/no-returns-required.validator.test.js
Labels: housekeeping

#911 Adding CSRF form protection via Hapi Crumb plugin
  app/plugins/crumb.plugin.js
  app/routes/bill-runs.routes.js
  app/routes/billing-accounts.routes.js
  app/routes/data.routes.js
  app/routes/import.routes.js
  app/routes/jobs.routes.js
  app/server.js
  app/views/bill-licences/remove.njk
  app/views/bill-runs/amend-adjustment-factor.njk
  app/views/bill-runs/amend-authorised-volume.njk
  app/views/bill-runs/amend-billable-returns.njk
  app/views/bill-runs/cancel.njk
  app/views/bill-runs/remove-licence.njk
  app/views/bill-runs/review-licence.njk
  app/views/bill-runs/review.njk
  app/views/bill-runs/send.njk
  app/views/bill-runs/setup/region.njk
  app/views/bill-runs/setup/season.njk
  app/views/bill-runs/setup/type.njk
  app/views/bill-runs/setup/year.njk
  app/views/bills/remove.njk
  app/views/data/deduplicate.njk
  app/views/return-requirements/abstraction-period.njk
  app/views/return-requirements/additional-submission-options.njk
  app/views/return-requirements/agreements-exceptions.njk
  app/views/return-requirements/cancel.njk
  app/views/return-requirements/check.njk
  app/views/return-requirements/existing.njk
  app/views/return-requirements/frequency-collected.njk
  app/views/return-requirements/frequency-reported.njk
  app/views/return-requirements/no-returns-required.njk
  app/views/return-requirements/note.njk
  app/views/return-requirements/points.njk
  app/views/return-requirements/purpose.njk
  app/views/return-requirements/reason.njk
  app/views/return-requirements/remove.njk
  app/views/return-requirements/returns-cycle.njk
  app/views/return-requirements/setup.njk
  app/views/return-requirements/site-description.njk
  app/views/return-requirements/start-date.njk
  package-lock.json
  package.json
  test/controllers/bill-licences.controller.test.js
  test/controllers/bill-runs-setup.controller.test.js
  test/controllers/bill-runs.controller.test.js
  test/controllers/bills.controller.test.js
  test/controllers/data.controller.test.js
  test/controllers/return-requirements.controller.test.js
  test/support/general.js
Labels: enhancement
