Repository DEFRA/water-abstraction-system, pull requests merged in 2025-03, with the labels that each got.

#1765 Move reusable two-part tariff billing services
  app/controllers/bill-runs.controller.js
  app/services/bill-runs/generate-two-part-tariff-bill-run.service.js
  app/services/bill-runs/generate-two-part-tariff-transaction.service.js
  app/services/bill-runs/tpt-supplementary/process-billing-period.service.js
  app/services/bill-runs/two-part-tariff/process-billing-period.service.js
  test/controllers/bill-runs.controller.test.js
  test/services/bill-runs/generate-two-part-tariff-bill-run.service.test.js
  test/services/bill-runs/generate-two-part-tariff-transaction.service.test.js
  test/services/bill-runs/tpt-supplementary/process-billing-period.service.test.js
  test/services/bill-runs/two-part-tariff/process-billing-period.service.test.js
Labels: housekeeping

#1766 Show credits/debits in view bill for tpt supp.
  app/presenters/base.presenter.js
  app/presenters/bill-licences/remove-bill-licence.presenter.js
  app/presenters/bill-licences/view-bill-licence.presenter.js
  app/presenters/bill-runs/empty-bill-run-presenter.js
  app/presenters/bill-runs/errored-bill-run-presenter.js
  app/presenters/bill-runs/index-bill-runs.presenter.js
  app/presenters/bill-runs/review/review-bill-run.presenter.js
  app/presenters/bill-runs/review/review-licence.presenter.js
  app/presenters/bill-runs/setup/check/allowed-bill-run.presenter.js
  app/presenters/bill-runs/setup/check/blocked-bill-run.presenter.js
  app/presenters/bill-runs/setup/check/no-annual-bill-run.presenter.js
  app/presenters/bill-runs/view-bill-run.presenter.js
  app/presenters/bill-runs/view-cancel-bill-run.presenter.js
  app/presenters/bill-runs/view-send-bill-run.presenter.js
  app/presenters/billing.presenter.js
  app/presenters/bills/remove-bill.presenter.js
  app/presenters/bills/view-bill.presenter.js
  app/presenters/licences/view-licence-bills.presenter.js
  test/presenters/base.presenter.test.js
  test/presenters/bill-licences/view-bill-licence.presenter.test.js
  test/presenters/bill-runs/view-bill-run.presenter.test.js
  test/presenters/billing.presenter.test.js
  test/presenters/bills/view-bill.presenter.test.js
Labels: housekeeping

#1767 Implement 2PT supplementary billing engine
  app/services/bill-runs/tpt-supplementary/process-billing-period.service.js
  test/fixtures/two-part-tariff.fixture.js
  test/services/bill-runs/tpt-supplementary/process-billing-period.service.test.js
  test/services/bill-runs/two-part-tariff/process-billing-period.service.test.js
Labels: enhancement

#1762 Update how we use DetermineReturnsPeriodService
  app/presenters/notifications/setup/cancel.presenter.js
  app/services/notifications/setup/fetch-download-recipients.service.js
  app/services/notifications/setup/fetch-recipients.service.js
  app/services/notifications/setup/submit-remove-licences.service.js
  app/services/notifications/setup/submit-returns-period.service.js
  test/presenters/notifications/setup/cancel.presenter.test.js
  test/services/notifications/setup/fetch-download-recipients.service.test.js
  test/services/notifications/setup/fetch-recipients.service.test.js
  test/services/notifications/setup/submit-remove-licences.services.test.js
  test/services/notifications/setup/submit-returns-period.services.test.js
Labels: enhancement

#1740 Return log setup received page content changes
  app/presenters/return-logs/setup/received.presenter.js
  app/views/return-logs/setup/received.njk
  test/presenters/return-logs/setup/received.presenter.test.js
  test/services/return-logs/setup/received.service.test.js
  test/services/return-logs/setup/submit-received.service.test.js
Labels: bug

#1733 Splitting single volume on return log lines
  app/services/return-logs/setup/allocate-single-volume-to-lines.service.js
  app/services/return-logs/setup/submit-period-used.service.js
  app/validators/return-logs/setup/period-used.validator.js
  app/validators/return-logs/setup/received-date.validator.js
  test/services/return-logs/setup/allocate-single-volume-to-lines.service.test.js
  test/services/return-logs/setup/submit-period-used.service.test.js
  test/validators/return-logs/setup/received-date.validator.test.js
Labels: enhancement

#1755 Feature notifications setup submit check
  app/controllers/notifications-setup.controller.js
  app/presenters/notifications/setup/check.presenter.js
  app/routes/notifications-setup.routes.js
  app/services/notifications/setup/submit-check.service.js
  test/controllers/notifications-setup.controller.test.js
  test/services/notifications/setup/check.service.test.js
  test/services/notifications/setup/submit-check.service.test.js
Labels: enhancement

#1769 Move supplementary unflagging services
  app/services/bill-runs/send/update-invoice-numbers.service.js
  app/services/bill-runs/supplementary/process-bill-run.service.js
  app/services/bill-runs/unflag-billed-supplementary-licences.service.js
  app/services/bill-runs/unflag-unbilled-supplementary-licences.service.js
  test/services/bill-runs/send/update-invoice-numbers.service.test.js
  test/services/bill-runs/supplementary/process-bill-run.service.test.js
  test/services/bill-runs/unflag-billed-supplementary-licences.service.test.js
  test/services/bill-runs/unflag-unbilled-supplementary-licences.service.test.js
  test/services/bills/submit-remove-bill.service.test.js
Labels: housekeeping

#1752 Add returns notifications presenter
  app/presenters/notifications/setup/returns-notification.presenter.js
  app/services/notifications/setup/submit-check.service.js
  test/presenters/notifications/setup/returns-notification.presenter.test.js
  test/services/notifications/setup/submit-check.service.test.js
Labels: enhancement

#1771 Handle TPT licence flags during supp process - pt1
  app/services/bill-licences/submit-remove-bill-licence.service.js
  app/services/bill-runs/assign-bill-run-to-licences.service.js
  app/services/bill-runs/cancel/submit-cancel-bill-run.service.js
  app/services/bill-runs/generate-two-part-tariff-bill-run.service.js
  app/services/bill-runs/match/match-and-allocate.service.js
  app/services/bill-runs/review/fetch-remove-review-licence.service.js
  app/services/bill-runs/review/submit-remove.service.js
  app/services/bill-runs/tpt-supplementary/process-bill-run.service.js
  app/services/bill-runs/two-part-tariff/process-billing-period.service.js
  app/services/bill-runs/unassign-bill-run-to-licences.service.js
  app/services/bill-runs/unassign-licences-to-bill-run.service.js
  app/services/bill-runs/unflag-unbilled-supplementary-licences.service.js
  app/services/bills/submit-remove-bill.service.js
  app/services/licences/supplementary/create-licence-supplementary-year.service.js
  test/fixtures/bill-runs-review.fixture.js
  test/services/bill-licences/submit-remove-bill-licence.service.test.js
  test/services/bill-runs/assign-bill-run-to-licences.service.test.js
  test/services/bill-runs/cancel/submit-cancel-bill-run.service.test.js
  test/services/bill-runs/fetch-two-part-tariff-billing-accounts.service.test.js
  test/services/bill-runs/generate-two-part-tariff-bill-run.service.test.js
  test/services/bill-runs/match/match-and-allocate.service.test.js
  test/services/bill-runs/review/fetch-remove-review-licence.service.test.js
  test/services/bill-runs/review/submit-remove.service.test.js
  test/services/bill-runs/send/update-invoice-numbers.service.test.js
  test/services/bill-runs/tpt-supplementary/process-bill-run.service.test.js
  test/services/bill-runs/tpt-supplementary/process-billing-period.service.test.js
  test/services/bill-runs/unassign-bill-run-to-licences.service.test.js
  test/services/bill-runs/unassign-licences-to-bill-run.service.test.js
  test/services/bill-runs/unflag-unbilled-supplementary-licences.service.test.js
  test/services/bills/submit-remove-bill.service.test.js
Labels: enhancement

#1773 Handle TPT licence flags during supp process - pt2
  app/services/bill-runs/send/update-invoice-numbers.service.js
  app/services/bill-runs/unflag-billed-supplementary-licences.service.js
  test/services/bill-runs/send/update-invoice-numbers.service.test.js
  test/services/bill-runs/unflag-billed-supplementary-licences.service.test.js
  test/services/bill-runs/unflag-unbilled-supplementary-licences.service.test.js
Labels: enhancement

#1774 Do not include 2PT supp. licences already assigned
  app/services/bill-runs/match/fetch-charge-versions.service.js
  test/services/bill-runs/match/fetch-charge-versions.service.test.js
Labels: bug

#1770 Update notifications setup
  app/presenters/notifications/setup/create-event.presenter.js
  app/services/notifications/setup/create-event.service.js
  app/services/notifications/setup/submit-check.service.js
  test/presenters/notifications/setup/create-event.presenter.test.js
  test/services/notifications/setup/create-event.service.tests.js
  test/services/notifications/setup/submit-check.service.test.js
Labels: enhancement

#1772 Add notifications setup create notification service
  app/services/notifications/setup/create-notifications.service.js
  test/services/notifications/setup/create-notifications.service.tests.js
Labels: enhancement

#1776 Fix transform csv file and affected files
  app/lib/transform-to-csv.lib.js
  app/presenters/notifications/setup/download-recipients.presenter.js
  test/lib/transform-to-csv.lib.test.js
  test/presenters/notifications/setup/download-recipients.presenter.test.js
  test/services/jobs/export/write-table-to-file.service.test.js
  test/services/notifications/setup/download-recipients.service.test.js
Labels: bug

#1736 Download return log as CSV
  app/controllers/return-logs.controller.js
  app/presenters/return-logs/download-return-log.presenter.js
  app/presenters/return-logs/view-return-log.presenter.js
  app/routes/return-logs.routes.js
  app/services/return-logs/download-return-log.service.js
  app/services/return-logs/fetch-download-return-log.service.js
  app/views/return-logs/view.njk
  test/controllers/return-logs.controller.test.js
  test/fixtures/return-logs.fixture.js
  test/presenters/return-logs/download-return-log.presenter.test.js
  test/services/return-logs/download-return-log.service.test.js
  test/services/return-logs/fetch-download-return-log.service.test.js
Labels: enhancement

#1783 Return log setup single volume saved to session
  app/services/return-logs/setup/submit-single-volume.service.js
  test/services/return-logs/setup/submit-single-volume.service.test.js
Labels: bug

#1781 Update notify services response
  app/services/notify/notify-email.service.js
  app/services/notify/notify-letter.service.js
  test/services/notifications/setup/batch-notifications.service.test.js
  test/services/notify/notify-email.service.test.js
  test/services/notify/notify-letter.service.test.js
Labels: enhancement

#1784 Update notifications setup scheduled notification presenter
  app/presenters/notifications/setup/scheduled-notifications.presenter.js
  app/services/notifications/setup/batch-notifications.service.js
  app/services/notifications/setup/submit-check.service.js
  test/presenters/notifications/setup/returns-notification.presenter.test.js
  test/presenters/notifications/setup/scheduled-notifications.presenter.test.js
Labels: enhancement

#1717 Return logs check page - summary section
  app/presenters/base.presenter.js
  app/presenters/return-logs/base-return-logs.presenter.js
  app/presenters/return-logs/setup/check.presenter.js
  app/views/return-logs/setup/check.njk
  test/presenters/return-logs/base-return-logs.presenter.test.js
  test/presenters/return-logs/setup/check.presenter.test.js
  test/services/return-logs/setup/check.service.test.js
Labels: enhancement

#1790 Add 'issuer' to notification setup create event service
  app/controllers/notifications-setup.controller.js
  app/presenters/notifications/setup/create-event.presenter.js
  app/services/notifications/setup/submit-check.service.js
  test/presenters/notifications/setup/create-event.presenter.test.js
  test/services/notifications/setup/submit-check.service.test.js
Labels: enhancement

#1789 Add 'messageRef' to notifications setup scheduled notifications presenter
  app/presenters/notifications/setup/scheduled-notifications.presenter.js
  test/presenters/notifications/setup/scheduled-notifications.presenter.test.js
Labels: enhancement

#1791 Update notification setup submit check to user batch notifications service
  app/services/notifications/setup/batch-notifications.service.js
  app/services/notifications/setup/submit-check.service.js
  test/services/notifications/setup/batch-notifications.service.test.js
  test/services/notifications/setup/submit-check.service.test.js
Labels: enhancement

#1788 Return logs check page - start reading
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/setup/check.presenter.js
  app/views/return-logs/setup/check.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/check.presenter.test.js
  test/services/return-logs/setup/check.service.test.js
Labels: enhancement

#1797 Return logs check page - enter links
  app/presenters/return-logs/setup/check.presenter.js
  test/presenters/return-logs/setup/check.presenter.test.js
Labels: enhancement

#1795 Update notifications setup scheduled notifications
  app/presenters/notifications/setup/scheduled-notifications.presenter.js
  test/presenters/notifications/setup/scheduled-notifications.presenter.test.js
Labels: enhancement

#1796 Add notifications setup scheduled notifications update notify
  app/presenters/notifications/setup/notify-update.presenter.js
  test/presenters/notifications/setup/notify-update.presenter.test.js
Labels: enhancement

#1802 Update notifications setup scheduled notification presenter
  app/presenters/notifications/setup/scheduled-notifications.presenter.js
  test/presenters/notifications/setup/scheduled-notifications.presenter.test.js
Labels: enhancement

#1803 Update notifications setup batch notifications to batch by amount
  .env.example
  app/services/notifications/setup/batch-notifications.service.js
  config/notify.config.js
  test/services/notifications/setup/batch-notifications.service.test.js
Labels: enhancement

#1806 Fix TPT match & allocate for licence end b4 charge
  app/services/bill-runs/match/fetch-charge-versions.service.js
  test/services/bill-runs/match/fetch-charge-versions.service.test.js
Labels: bug

#1807 Fix return log download csv for meter readings
  app/lib/transform-to-csv.lib.js
  app/services/return-logs/fetch-download-return-log.service.js
Labels: bug

#1808 Update notification setup batch notifications service to have a delay
  .env.example
  app/services/notifications/setup/batch-notifications.service.js
  config/notify.config.js
  test/services/notifications/setup/batch-notifications.service.test.js
Labels: enhancement

#1809 Update notification setup batch notifications service test to work with live notify
  db/migrations/legacy/20221108007033_water-scheduled-notification.js
  test/services/notifications/setup/batch-notifications.service.test.js
Labels: enhancement

#1811 Add Notify status service
  app/services/notify/notify-status.service.js
  test/services/notify/notify-status.service.test.js
Labels: enhancement

#1812 Add current financial year end function to dates lib
  app/lib/dates.lib.js
  app/presenters/licences/supplementary/mark-for-supplementary-billing.presenter.js
  app/services/licences/supplementary/determine-billing-years.service.js
  test/lib/dates.lib.test.js
Labels: enhancement

#1804 Handle credit-only TPT tariff supplementary bills
  app/presenters/charging-module/create-transaction.presenter.js
  app/services/bill-runs/assign-bill-run-to-licences.service.js
  app/services/bill-runs/generate-two-part-tariff-bill-run.service.js
  app/services/bill-runs/match/fetch-charge-versions.service.js
  app/services/bill-runs/match/fetch-licences.service.js
  app/services/bill-runs/match/match-and-allocate.service.js
  app/services/bill-runs/review/process-bill-run-post-remove.service.js
  app/services/bill-runs/tpt-supplementary/fetch-billing-accounts.service.js
  app/services/bill-runs/tpt-supplementary/fetch-non-chargeable-billing-accounts.service.js
  app/services/bill-runs/tpt-supplementary/generate-bill-run.service.js
  app/services/bill-runs/tpt-supplementary/process-bill-run.service.js
  app/services/bill-runs/tpt-supplementary/process-billing-period.service.js
  app/services/bill-runs/two-part-tariff/fetch-billing-accounts.service.js
  app/services/bill-runs/two-part-tariff/generate-bill-run.service.js
  app/services/bill-runs/two-part-tariff/process-bill-run.service.js
  test/services/bill-runs/assign-bill-run-to-licences.service.test.js
  test/services/bill-runs/generate-two-part-tariff-bill-run.service.test.js
  test/services/bill-runs/match/fetch-charge-versions.service.test.js
  test/services/bill-runs/match/fetch-licences.service.test.js
  test/services/bill-runs/match/match-and-allocate.service.test.js
  test/services/bill-runs/review/process-bill-run-post-remove.service.test.js
  test/services/bill-runs/tpt-supplementary/fetch-billing-accounts.service.test.js
  test/services/bill-runs/tpt-supplementary/fetch-non-chargeable-billing-accounts.service.test.js
  test/services/bill-runs/tpt-supplementary/generate-bill-run.service.test.js
  test/services/bill-runs/tpt-supplementary/process-bill-run.service.test.js
  test/services/bill-runs/tpt-supplementary/process-billing-period.service.test.js
  test/services/bill-runs/two-part-tariff/fetch-billing-accounts.service.test.js
  test/services/bill-runs/two-part-tariff/generate-bill-run.service.test.js
  test/services/bill-runs/two-part-tariff/process-bill-run.service.test.js
  test/services/bill-runs/two-part-tariff/process-billing-period.service.test.js
Labels: bug

#1794 Fix charge versions 2pt flagging mechanism
  app/controllers/check.controller.js
  app/services/licences/supplementary/determine-charge-version-flags.service.js
  app/services/licences/supplementary/fetch-charge-version-billing-data.service.js
  test/services/licences/supplementary/determine-charge-version-flags.service.test.js
  test/services/licences/supplementary/fetch-charge-version-billing-data.service.test.js
Labels: bug

#1813 Fix assigning bill run to TPT supplementary licences
  app/services/bill-runs/assign-bill-run-to-licences.service.js
  app/services/bill-runs/tpt-supplementary/process-bill-run.service.js
  test/services/bill-runs/assign-bill-run-to-licences.service.test.js
Labels: bug

#1817 Fix dupe results in TPT supp. Fetch Billing Acc.
  app/services/bill-runs/tpt-supplementary/fetch-billing-accounts.service.js
  test/services/bill-runs/tpt-supplementary/fetch-billing-accounts.service.test.js
Labels: bug

#1814 Add Notification setup notify status presenter
  app/presenters/notifications/setup/notify-status.presenter.js
  app/presenters/notifications/setup/notify-update.presenter.js
  app/services/notify/notify-status.service.js
  test/presenters/notifications/setup/notify-status.presenter.test.js
  test/presenters/notifications/setup/notify-update.presenter.test.js
  test/services/notifications/setup/batch-notifications.service.test.js
Labels: enhancement

#1816 Add notification setup confirmation page
  app/controllers/notifications-setup.controller.js
  app/presenters/notifications/setup/confirmation.presenter.js
  app/routes/notifications-setup.routes.js
  app/services/notifications/setup/confirmation.service.js
  app/services/notifications/setup/submit-check.service.js
  app/views/notifications/setup/confirmation.njk
  test/controllers/notifications-setup.controller.test.js
  test/presenters/notifications/setup/confirmation.presenter.test.js
  test/services/notifications/setup/confirmation.service.test.js
  test/services/notifications/setup/submit-check.service.test.js
Labels: enhancement

#1823 Update notification setup submit check tests
  app/services/notifications/setup/submit-check.service.js
  test/services/notifications/setup/submit-check.service.test.js
Labels: enhancement

#1825 Update notification setup notify update status
  app/presenters/notifications/setup/notify-status.presenter.js
  app/presenters/notifications/setup/notify-update.presenter.js
  test/presenters/notifications/setup/notify-status.presenter.test.js
  test/presenters/notifications/setup/notify-update.presenter.test.js
  test/services/notifications/setup/batch-notifications.service.test.js
Labels: enhancement

#1824 Update notification setup default event status
  app/presenters/notifications/setup/create-event.presenter.js
  app/services/notifications/setup/batch-notifications.service.js
  test/presenters/notifications/setup/create-event.presenter.test.js
  test/services/notifications/setup/batch-notifications.service.test.js
  test/services/notifications/setup/submit-check.service.test.js
Labels: enhancement

#1826 Fix change to billing account plus all previous!
  app/services/bill-runs/tpt-supplementary/fetch-billing-accounts.service.js
  app/services/bill-runs/tpt-supplementary/fetch-non-chargeable-billing-accounts.service.js
  test/services/bill-runs/tpt-supplementary/fetch-billing-accounts.service.test.js
  test/services/bill-runs/tpt-supplementary/fetch-non-chargeable-billing-accounts.service.test.js
  test/support/seeders/previous-billing-data.seeder.js
  test/support/seeders/two-part-tariff-supplementary.seeder.js
Labels: bug

#1828 Update notification setup to facilitate 'ad-hoc' journey
  app/lib/notify-templates.lib.js
  app/presenters/notifications/setup/create-event.presenter.js
  app/presenters/notifications/setup/scheduled-notifications.presenter.js
  test/presenters/notifications/setup/create-event.presenter.test.js
  test/presenters/notifications/setup/scheduled-notifications.presenter.test.js
Labels: enhancement

#1829 Update notifications setup submit ad-hoc licence
  app/services/notifications/setup/submit-ad-hoc-licence.service.js
  test/services/notifications/setup/submit-ad-hoc-licence.service.test.js
Labels: enhancement

#1751 Point Edit Return button to Check Details page
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/view-return-log.presenter.js
  app/routes/return-logs-setup.routes.js
  app/services/return-logs/setup/initiate-session.service.js
  app/views/return-logs/view.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/view-return-log.presenter.test.js
  test/services/return-logs/setup/initiate-session.service.test.js
Labels: enhancement

#1835 Add `marked` npm package for markdown rendering
  app/plugins/views.plugin.js
  app/views/filters/markdown.filter.js
  package-lock.json
  package.json
  test/views/filters/markdown.filter.test.js
Labels: enhancement

#1834 Add notifications setup update notifications
  app/services/notifications/setup/update-notifications.service.js
  test/services/notifications/setup/update-notifications.service.tests.js
Labels: enhancement

#1833 Fix 'return received' backlink for submit return
  app/presenters/return-logs/setup/received.presenter.js
  test/presenters/return-logs/setup/received.presenter.test.js
  test/services/return-logs/setup/received.service.test.js
  test/services/return-logs/setup/submit-received.service.test.js
Labels: bug

#1831 Return "not due yet" status
  app/presenters/licences/view-licence-returns.presenter.js
  app/presenters/return-logs/base-return-logs.presenter.js
  app/presenters/return-logs/view-return-log.presenter.js
  app/views/macros/return-status-tag.njk
  app/views/return-logs/view.njk
  test/presenters/licences/view-licence-returns.presenter.test.js
  test/presenters/return-logs/base-return-logs.presenter.test.js
  test/presenters/return-logs/view-return-log.presenter.test.js
Labels: enhancement

#1842 Add job notifications status update
  app/controllers/jobs.controller.js
  app/routes/jobs.routes.js
  app/services/jobs/notifications/notifications-status-updates.service.js
  test/controllers/jobs.controller.test.js
Labels: enhancement

#1841 Return submitted confirmation page
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/setup/confirm-received.presenter.js
  app/presenters/return-logs/setup/confirmed.presenter.js
  app/routes/return-logs-setup.routes.js
  app/services/return-logs/setup/confirmed.service.js
  app/services/return-logs/setup/fetch-return-log.service.js
  app/services/return-logs/setup/submit-confirmed.service.js
  app/views/return-logs/setup/confirmed.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/confirmed.presenter.test.js
  test/services/return-logs/setup/confirmed.service.test.js
  test/services/return-logs/setup/fetch-return-log.service.test.js
  test/services/return-logs/setup/submit-confirmed.service.test.js
Labels: enhancement

#1845 Add job notification fetch event notifications service
  app/models/event.model.js
  app/services/jobs/notifications/fetch-event-notifications.service.js
  test/models/event.model.test.js
  test/services/jobs/notifications/fetch-event-notifications.service.test.js
Labels: enhancement

#1846 Update notification setup error count
  app/services/notifications/setup/batch-notifications.service.js
  app/services/notifications/setup/update-event.service.js
  test/services/notifications/setup/batch-notifications.service.test.js
  test/services/notifications/setup/update-event.service.tests.js
Labels: enhancement

#1844 Feature job notificaitons status update
  app/services/jobs/notifications/notifications-status-updates.service.js
  test/services/jobs/notifications/notifications-status-updates.service.test.js
Labels: enhancement

#1851 Update fetch event notifications service tests
  app/services/jobs/notifications/fetch-event-notifications.service.js
  test/services/jobs/notifications/fetch-event-notifications.service.test.js
Labels: enhancement

#1852 Update fetch event notifications to only withing the last seven days
  app/services/jobs/notifications/fetch-event-notifications.service.js
  test/services/jobs/notifications/fetch-event-notifications.service.test.js
Labels: enhancement

#1850 Add error logging when a call to Notify fails
  app/services/notify/notify-email.service.js
  app/services/notify/notify-letter.service.js
  app/services/notify/notify-status.service.js
  test/services/jobs/notifications/notifications-status-updates.service.test.js
  test/services/notifications/setup/batch-notifications.service.test.js
  test/services/notify/notify-email.service.test.js
  test/services/notify/notify-letter.service.test.js
  test/services/notify/notify-status.service.test.js
Labels: enhancement
