Repository DEFRA/water-abstraction-system, pull requests merged in 2025-05, with the labels that each got.

#1936 Refactor scaffolding script
  scaffold.sh
  templates/README.md
  templates/fetch.js
  templates/fetch.test.js
  templates/presenter.test.js
  templates/service-fetch.service.js
  templates/service-fetch.service.test.js
  templates/service-session-presenter.service.js
  templates/service-session-presenter.service.test.js
  templates/service.js
  templates/service.test.js
  templates/submit.service.test.js
  templates/validator.test.js
Labels: enhancement

#1932 Add notices setup abstraction alert - alert threshold
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/abstraction-alerts/alert-thresholds.presenter.js
  app/routes/notices-setup.routes.js
  app/services/notices/setup/abstraction-alerts/alert-thresholds.service.js
  app/services/notices/setup/abstraction-alerts/submit-alert-thresholds.service.js
  app/validators/notices/setup/abstraction-alerts/alert-thresholds.validator.js
  app/views/notices/setup/abstraction-alerts/alert-thresholds.view.njk
  test/controllers/notices-setup.controller.test.js
  test/presenters/notices/setup/abstraction-alerts/alert-thresholds.presenter.test.js
  test/services/notices/setup/abstraction-alerts/alert-thresholds.service.test.js
  test/services/notices/setup/abstraction-alerts/submit-alert-thresholds.service.test.js
  test/validators/notices/setup/abstraction-alerts/alert-thresholds.validator.test.js
Labels: enhancement

#1938 Add notifications setup abstraction thresholds view
  app/presenters/notices/setup/abstraction-alerts/alert-thresholds.presenter.js
  app/services/notices/setup/abstraction-alerts/alert-thresholds.service.js
  app/services/notices/setup/abstraction-alerts/determine-licence-monitoring-stations.service.js
  app/services/notices/setup/abstraction-alerts/submit-alert-type.service.js
  app/views/notices/setup/abstraction-alerts/alert-thresholds.view.njk
  test/fixtures/abstraction-alert-session-data.fixture.js
  test/presenters/notices/setup/abstraction-alerts/alert-thresholds.presenter.test.js
  test/services/notices/setup/abstraction-alerts/alert-thresholds.service.test.js
  test/services/notices/setup/abstraction-alerts/determine-licence-monitoring-stations.service.test.js
  test/services/notices/setup/abstraction-alerts/submit-alert-thresholds.service.test.js
  test/services/notices/setup/abstraction-alerts/submit-alert-type.service.test.js
Labels: enhancement

#1940 Monitoring stations - View details link
  app/presenters/monitoring-stations/view.presenter.js
  app/services/monitoring-stations/fetch-monitoring-station.service.js
  app/views/monitoring-stations/view.njk
  test/presenters/monitoring-stations/view.presenter.test.js
  test/services/monitoring-stations/fetch-monitoring-station.service.test.js
  test/services/monitoring-stations/view.service.test.js
Labels: enhancement

#1947 Update scaffold presenter test template.
  templates/presenter.test.js
Labels: enhancement

#1941 Replace Math random calls with 'safe' alternate
  app/lib/general.lib.js
  app/services/notices/setup/initiate-session.service.js
  test/models/charge-version.model.test.js
  test/models/licence-version.model.test.js
  test/models/return-version.model.test.js
  test/services/monitoring-stations/fetch-monitoring-station.service.test.js
  test/support/general.js
  test/support/helpers/address.helper.js
  test/support/helpers/billing-account.helper.js
  test/support/helpers/company.helper.js
  test/support/helpers/licence-document-header.helper.js
  test/support/helpers/licence-version-purpose-condition.helper.js
  test/support/helpers/licence-version-purpose-point.helper.js
  test/support/helpers/licence-version-purpose.helper.js
  test/support/helpers/licence-version.helper.js
  test/support/helpers/licence.helper.js
  test/support/helpers/mod-log.helper.js
  test/support/helpers/point.helper.js
  test/support/helpers/region.helper.js
  test/support/helpers/return-requirement-point.helper.js
  test/support/helpers/return-requirement-purpose.helper.js
  test/support/helpers/return-requirement.helper.js
  test/support/helpers/return-version.helper.js
  test/support/helpers/user.helper.js
Labels: housekeeping

#1939 Add notifications setup abstraction thresholds submit
  app/services/notices/setup/abstraction-alerts/submit-alert-thresholds.service.js
  app/validators/notices/setup/abstraction-alerts/alert-thresholds.validator.js
  app/views/notices/setup/abstraction-alerts/alert-thresholds.view.njk
  test/services/notices/setup/abstraction-alerts/submit-alert-thresholds.service.test.js
  test/validators/notices/setup/abstraction-alerts/alert-thresholds.validator.test.js
Labels: enhancement

#1946 Add notifications setup abstraction alerts check licence matches
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/abstraction-alerts/check-licence-matches.presenter.js
  app/routes/notices-setup.routes.js
  app/services/notices/setup/abstraction-alerts/check-licence-matches.service.js
  app/views/notices/setup/abstraction-alerts/check-licence-matches.njk
  test/controllers/notices-setup.controller.test.js
  test/presenters/notices/setup/abstraction-alerts/check-licence-matches.presenter.test.js
  test/services/notices/setup/abstraction-alerts/check-licence-matches.service.test.js
Labels: enhancement

#1953 Update notifications setup abstraction thresholds view
  app/presenters/notices/setup/abstraction-alerts/alert-thresholds.presenter.js
  test/fixtures/abstraction-alert-session-data.fixture.js
  test/presenters/notices/setup/abstraction-alerts/alert-thresholds.presenter.test.js
  test/presenters/notices/setup/abstraction-alerts/alert-type.presenter.test.js
  test/services/notices/setup/abstraction-alerts/alert-thresholds.service.test.js
  test/services/notices/setup/abstraction-alerts/submit-alert-thresholds.service.test.js
Labels: enhancement

#1933 Migrate legacy stop or reduce page
  app/controllers/licence-monitoring-station-setup.controller.js
  app/presenters/licence-monitoring-station/setup/stop-or-reduce.presenter.js
  app/routes/licence-monitoring-station-setup.routes.js
  app/services/licence-monitoring-station/setup/stop-or-reduce.service.js
  app/services/licence-monitoring-station/setup/submit-stop-or-reduce.service.js
  app/validators/licence-monitoring-station/setup/stop-or-reduce.validator.js
  app/validators/licence-monitoring-station/setup/threshold-and-unit.validator.js
  app/views/licence-monitoring-station/setup/stop-or-reduce.njk
  app/views/licence-monitoring-station/setup/threshold-and-unit.njk
  test/controllers/licence-monitoring-station-setup.controller.test.js
  test/presenters/licence-monitoring-station/setup/stop-or-reduce.presenter.test.js
  test/services/licence-monitoring-station/setup/stop-or-reduce.service.test.js
  test/services/licence-monitoring-station/setup/submit-stop-or-reduce.service.test.js
  test/validators/licence-monitoring-station/setup/stop-or-reduce.validator.test.js
  test/validators/licence-monitoring-station/setup/threshold-and-unit.validator.test.js
Labels: enhancement

#1958 Update notifications setup abstraction alerts thresholds to use groups
  app/presenters/notices/setup/abstraction-alerts/alert-thresholds.presenter.js
  app/services/notices/setup/abstraction-alerts/determine-licence-monitoring-stations.service.js
  test/fixtures/abstraction-alert-session-data.fixture.js
  test/presenters/notices/setup/abstraction-alerts/alert-thresholds.presenter.test.js
  test/services/notices/setup/abstraction-alerts/alert-thresholds.service.test.js
  test/services/notices/setup/abstraction-alerts/determine-licence-monitoring-stations.service.test.js
  test/services/notices/setup/abstraction-alerts/submit-alert-thresholds.service.test.js
Labels: enhancement

#1966 Fix "Build Status" badge
  README.md
Labels: documentation

#1956 Create `CreateReturnLinesService`
  app/lib/static-lookups.lib.js
  app/services/return-logs/setup/create-return-lines.service.js
  test/services/return-logs/setup/create-return-lines.service.test.js
Labels: enhancement

#1959 Create `CreateReturnSubmissionService`
  app/services/return-logs/setup/create-return-submission.service.js
  test/services/return-logs/setup/create-return-submission.service.test.js
Labels: enhancement

#1969 Remove Return version migration debug code
  app/services/jobs/return-logs/fetch-water-undertakers.service.js
Labels: bug

#1965 Refactor monitoring station table
  app/presenters/monitoring-stations/base.presenter.js
  app/presenters/monitoring-stations/view.presenter.js
  app/views/macros/licence-monitoring-station-restrictions-table.njk
  app/views/monitoring-stations/view.njk
  test/presenters/monitoring-stations/base.presenter.test.js
  test/presenters/monitoring-stations/view.presenter.test.js
  test/services/monitoring-stations/view.service.test.js
Labels: enhancement

#1973 Pass in licence end date when creating return logs
  app/services/jobs/return-logs/process-return-logs.service.js
  test/services/jobs/return-logs/process-return-logs.service.test.js
Labels: bug

#1976 Revert helper change to fix broken acceptance test
  test/services/licences/fetch-communications.service.test.js
  test/support/helpers/scheduled-notification.helper.js
Labels: bug

#1960 Create `GenerateReturnSubmissionMetadataService`
  app/services/return-logs/setup/generate-return-submission-metadata.service.js
  test/services/return-logs/setup/generate-return-submission-metadata.service.test.js
Labels: enhancement

#1974 Feature notificaitons setup abstraction alert check licence matches view table
  app/presenters/monitoring-stations/base.presenter.js
  app/presenters/notices/setup/abstraction-alerts/check-licence-matches.presenter.js
  app/services/notices/setup/abstraction-alerts/determine-licence-monitoring-stations.service.js
  app/services/notices/setup/abstraction-alerts/fetch-monitoring-station.service.js
  app/views/notices/setup/abstraction-alerts/check-licence-matches.njk
  test/fixtures/abstraction-alert-session-data.fixture.js
  test/presenters/notices/setup/abstraction-alerts/check-licence-matches.presenter.test.js
  test/services/notices/setup/abstraction-alerts/check-licence-matches.service.test.js
  test/services/notices/setup/abstraction-alerts/determine-licence-monitoring-stations.service.test.js
  test/services/notices/setup/abstraction-alerts/fetch-monitoring-station.service.test.js
Labels: enhancement

#1975 Update notifications setup abstraction alerts thresholds
  app/services/notices/setup/abstraction-alerts/submit-alert-type.service.js
  test/services/notices/setup/abstraction-alerts/submit-alert-type.service.test.js
Labels: enhancement

#1977 Migration - Add `created_by` to `licence_monitoring_stations`
  app/models/licence-monitoring-station.model.js
  app/models/user.model.js
  db/migrations/legacy/20221108007027_water-licence-gauging-stations.js
  db/migrations/public/20250512155246_alter-licence-monitoring-stations-view.js
  test/models/licence-monitoring-station.model.test.js
  test/models/user.model.test.js
Labels: enhancement

#1982 Update notifications setup abstraction alert types error message
  app/services/notices/setup/abstraction-alerts/submit-alert-type.service.js
  app/validators/notices/setup/abstraction-alerts/alert-type.validator.js
  test/services/notices/setup/abstraction-alerts/submit-alert-type.service.test.js
  test/validators/notices/setup/abstraction-alerts/alert-type.validator.test.js
Labels: enhancement

#1981 Add notifications setup abstraction check licence remove link
  app/presenters/notices/setup/abstraction-alerts/check-licence-matches.presenter.js
  app/services/notices/setup/abstraction-alerts/fetch-monitoring-station.service.js
  test/fixtures/abstraction-alert-session-data.fixture.js
  test/presenters/notices/setup/abstraction-alerts/check-licence-matches.presenter.test.js
  test/services/notices/setup/abstraction-alerts/check-licence-matches.service.test.js
  test/services/notices/setup/abstraction-alerts/determine-licence-monitoring-stations.service.test.js
  test/services/notices/setup/abstraction-alerts/fetch-monitoring-station.service.test.js
Labels: enhancement

#1984 Add `console.dir()` check to github CI
  .github/workflows/ci.yml
Labels: testing

#1883 Migrate view billing account page
  app/controllers/billing-accounts.controller.js
  app/presenters/billing-account/view-billing-account.presenter.js
  app/routes/billing-accounts.routes.js
  app/services/billing-accounts/fetch-view-billing-account.service.js
  app/services/billing-accounts/view-billing-account.service.js
  app/views/billing-accounts/view.njk
  app/views/licences/tabs/bills.njk
  test/controllers/billing-accounts.controller.test.js
  test/fixtures/billing-accounts.fixtures.js
  test/presenters/billing-accounts/view-billing-account.presenter.test.js
  test/services/billing-accounts/fetch-view-billing-account.service.test.js
  test/services/billing-accounts/view-billing-account.service.test.js
Labels: enhancement

#1993 Update notices setup abstraction alerts - alert type
  app/services/notices/setup/abstraction-alerts/submit-alert-type.service.js
  test/services/notices/setup/abstraction-alerts/submit-alert-type.service.test.js
Labels: enhancement

#1988 Add notifications setup abstraction check licence remove service
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/abstraction-alerts/check-licence-matches.presenter.js
  app/routes/notices-setup.routes.js
  app/services/notices/setup/abstraction-alerts/remove-threshold.service.js
  app/services/notices/setup/abstraction-alerts/submit-alert-type.service.js
  test/controllers/notices-setup.controller.test.js
  test/presenters/notices/setup/abstraction-alerts/check-licence-matches.presenter.test.js
  test/services/notices/setup/abstraction-alerts/check-licence-matches.service.test.js
  test/services/notices/setup/abstraction-alerts/remove-threshold.service.test.js
  test/services/notices/setup/abstraction-alerts/submit-alert-type.service.test.js
Labels: enhancement

#1961 Create `SubmitCheckService` and use on Check Return Details page
  app/controllers/return-logs-setup.controller.js
  app/routes/return-logs-setup.routes.js
  app/services/return-logs/setup/create-return-submission.service.js
  app/services/return-logs/setup/submit-check.service.js
  app/views/return-logs/setup/check.njk
  test/controllers/return-logs-setup.controller.test.js
  test/services/return-logs/setup/create-return-submission.service.test.js
  test/services/return-logs/setup/submit-check.service.test.js
Labels: enhancement

#1992 Update notifications setup abstraction alert cancel
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/abstraction-alerts/cancel-alerts.presenter.js
  app/presenters/notices/setup/abstraction-alerts/check-licence-matches.presenter.js
  app/services/notices/setup/abstraction-alerts/cancel-alerts.service.js
  app/services/notices/setup/abstraction-alerts/submit-cancel-alerts.service.js
  app/views/notices/setup/abstraction-alerts/cancel-alerts.njk
  app/views/notices/setup/abstraction-alerts/check-licence-matches.njk
  app/views/notices/setup/check.njk
  test/controllers/notices-setup.controller.test.js
  test/presenters/notices/setup/abstraction-alerts/cancel-alerts.presenter.test.js
  test/presenters/notices/setup/abstraction-alerts/check-licence-matches.presenter.test.js
  test/services/notices/setup/abstraction-alerts/cancel-alerts.service.test.js
  test/services/notices/setup/abstraction-alerts/check-licence-matches.service.test.js
  test/services/notices/setup/abstraction-alerts/submit-cancel-alerts.service.test.js
Labels: enhancement

#1995 Update notifications setup abstraction check licence remove service
  app/presenters/notices/setup/abstraction-alerts/check-licence-matches.presenter.js
  test/presenters/notices/setup/abstraction-alerts/check-licence-matches.presenter.test.js
Labels: enhancement

#1989 Add notification setup abstraction alert email scaffold
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/abstraction-alerts/alert-email-address.presenter.js
  app/routes/notices-setup.routes.js
  app/services/notices/setup/abstraction-alerts/alert-email-address.service.js
  app/services/notices/setup/abstraction-alerts/submit-alert-email-address.service.js
  app/validators/notices/setup/abstraction-alerts/alert-email-address.validator.js
  app/views/notices/setup/abstraction-alerts/alert-email-address.njk
  test/controllers/notices-setup.controller.test.js
  test/presenters/notices/setup/abstraction-alerts/alert-email-address.presenter.test.js
  test/services/notices/setup/abstraction-alerts/alert-email-address.service.test.js
  test/services/notices/setup/abstraction-alerts/submit-alert-email-address.service.test.js
  test/validators/notices/setup/abstraction-alerts/alert-email-address.validator.test.js
Labels: enhancement

#1996 Update notifications setup abstraction check licence remove service flash notification
  app/controllers/notices-setup.controller.js
  app/presenters/monitoring-stations/base.presenter.js
  app/services/notices/setup/abstraction-alerts/check-licence-matches.service.js
  app/services/notices/setup/abstraction-alerts/remove-threshold.service.js
  app/views/notices/setup/abstraction-alerts/check-licence-matches.njk
  test/presenters/monitoring-stations/base.presenter.test.js
  test/services/notices/setup/abstraction-alerts/check-licence-matches.service.test.js
  test/services/notices/setup/abstraction-alerts/remove-threshold.service.test.js
Labels: enhancement

#1997 Amend button on Return submitted confirmation page
  app/views/return-logs/setup/confirmed.njk
Labels: bug

#2000 Add feature flag for view billing account
  .env.example
  app/presenters/licences/view-licence-bills.presenter.js
  app/views/licences/tabs/bills.njk
  config/feature-flags.config.js
  test/presenters/licences/view-licence-bills.presenter.test.js
Labels: housekeeping

#1999 Add notifications setup abstraction check licence submit service
  app/controllers/notices-setup.controller.js
  app/routes/notices-setup.routes.js
  app/services/notices/setup/abstraction-alerts/submit-check-licence-matches.service.js
  test/controllers/notices-setup.controller.test.js
  test/services/notices/setup/abstraction-alerts/submit-check-licence-matches.service.test.js
Labels: enhancement

#2002 Update Two-part tariff annual years for 2024-25
  app/presenters/bill-runs/setup/year.presenter.js
  test/presenters/bill-runs/setup/year.presenter.test.js
Labels: housekeeping

#2005 Update billing account view to use new change address endpoint
  app/views/billing-accounts/view.njk
Labels: enhancement

#2007 Fix financial year column for billing account page
  app/presenters/billing-account/view-billing-account.presenter.js
  app/services/billing-accounts/fetch-view-billing-account.service.js
  test/fixtures/billing-accounts.fixtures.js
  test/services/billing-accounts/fetch-view-billing-account.service.test.js
Labels: bug

#2001 Add notifications setup abstraction alert to recipients
  app/presenters/notices/setup/check.presenter.js
  app/services/notices/setup/check.service.js
  app/services/notices/setup/determine-recipients.service.js
  app/services/notices/setup/fetch-abstraction-alert-recipients.service.js
  app/services/notices/setup/fetch-recipients.service.js
  app/services/notices/setup/submit-check.service.js
  test/fixtures/recipients.fixtures.js
  test/presenters/notices/setup/check.presenter.test.js
  test/services/notices/setup/check.service.test.js
  test/services/notices/setup/determine-recipients.service.test.js
  test/services/notices/setup/fetch-abstraction-alert-recipients.service.test.js
  test/services/notices/setup/fetch-recipients.service.test.js
  test/services/notices/setup/submit-check.service.test.js
  test/support/seeders/licence-document-header.seeder.js
Labels: enhancement

#2011 Update pagination presenter to handle existing query args
  app/presenters/paginator.presenter.js
  test/presenters/paginator.presenter.test.js
Labels: enhancement

#1951 Monitoring stations - Tag details page
  app/controllers/monitoring-stations.controller.js
  app/presenters/monitoring-stations/licence.presenter.js
  app/presenters/monitoring-stations/view.presenter.js
  app/routes/monitoring-station.routes.js
  app/services/monitoring-stations/fetch-licence-tag-details.service.js
  app/services/monitoring-stations/licence.service.js
  app/views/monitoring-stations/licence.njk
  test/controllers/monitoring-stations.controller.test.js
  test/presenters/monitoring-stations/licence.presenter.test.js
  test/presenters/monitoring-stations/view.presenter.test.js
  test/services/monitoring-stations/fetch-licence-tag-details.service.test.js
  test/services/monitoring-stations/licence.service.test.js
  test/services/monitoring-stations/view.service.test.js
Labels: enhancement

#2015 Update notices batch notifications to use whole session
  app/services/notices/setup/batch-notifications.service.js
  app/services/notices/setup/submit-check.service.js
  test/services/notices/setup/batch-notifications.service.test.js
  test/services/notices/setup/submit-check.service.test.js
Labels: enhancement

#2010 Determine billing account backlink based on route
  app/controllers/billing-accounts.controller.js
  app/presenters/billing-account/view-billing-account.presenter.js
  app/services/billing-accounts/fetch-view-billing-account.service.js
  app/services/billing-accounts/view-billing-account.service.js
  app/views/billing-accounts/view.njk
  app/views/licences/tabs/bills.njk
  test/controllers/billing-accounts.controller.test.js
  test/fixtures/billing-accounts.fixtures.js
  test/presenters/billing-accounts/view-billing-account.presenter.test.js
  test/services/billing-accounts/fetch-view-billing-account.service.test.js
  test/services/billing-accounts/view-billing-account.service.test.js
Labels: enhancement

#2016 Refactor notice submit check to use journey
  app/presenters/notices/setup/create-notice.presenter.js
  app/services/notices/setup/submit-check.service.js
  test/presenters/notices/setup/create-notice.presenter.test.js
  test/services/notices/setup/submit-check.service.test.js
Labels: enhancement

#2018 Add notices determines relevant licence monitoring stations
  app/presenters/notices/setup/abstraction-alerts/check-licence-matches.presenter.js
  app/services/notices/setup/abstraction-alerts/determine-relevant-licence-monitoring-stations.service.js
  app/services/notices/setup/abstraction-alerts/submit-check-licence-matches.service.js
  test/services/notices/setup/abstraction-alerts/determine-relevant-licence-monitoring-stations.service.test.js
  test/services/notices/setup/abstraction-alerts/submit-check-licence-matches.service.test.js
Labels: enhancement

#1822 Notifications - View sent notices page
  app/controllers/notices.controller.js
  app/presenters/notices/index-notices.presenter.js
  app/services/notices/fetch-notices.service.js
  app/services/notices/index-notices.service.js
  app/services/notices/index.service.js
  app/services/notices/submit-index.service.js
  app/validators/notices/index.validator.js
  app/views/macros/notice-status-tag.njk
  app/views/notices/index.njk
  app/views/notifications/index.njk
  test/controllers/notices.controller.test.js
  test/controllers/notifications.controller.test.js
  test/fixtures/notices.fixture.js
  test/presenters/notices/index-notices.presenter.test.js
  test/services/notices/fetch-notices.service.test.js
  test/services/notices/index-notices.service.test.js
  test/services/notices/submit-index.service.test.js
  test/support/seeders/notices.seeder.js
  test/validators/notices/index.validator.test.js
Labels: enhancement

#2022 Fix relevant licence monitoring station
  app/presenters/notices/setup/abstraction-alerts/alert-thresholds.presenter.js
  app/presenters/notices/setup/abstraction-alerts/check-licence-matches.presenter.js
  app/services/notices/setup/abstraction-alerts/determine-relevant-licence-monitoring-stations.service.js
  app/services/notices/setup/abstraction-alerts/submit-check-licence-matches.service.js
  test/presenters/notices/setup/abstraction-alerts/alert-thresholds.presenter.test.js
  test/services/notices/setup/abstraction-alerts/determine-relevant-licence-monitoring-stations.service.test.js
Labels: enhancement

#2017 Add notices abstraction alert notification presenter
  app/lib/notify-templates.lib.js
  app/presenters/notices/setup/abstraction-alerts-notifications.presenter.js
  test/fixtures/recipients.fixtures.js
  test/presenters/notices/setup/abstraction-alert-notifications.presenter.test.js
Labels: enhancement

#2025 Add notes to View Return Log page
  app/presenters/return-logs/view-return-log.presenter.js
  app/services/return-logs/fetch-return-log.service.js
  app/views/return-logs/view.njk
  test/presenters/return-logs/view-return-log.presenter.test.js
  test/services/return-logs/fetch-return-log.service.test.js
Labels: enhancement

#2032 Add abstraction alerts download recipients
  app/presenters/notices/setup/abstraction-alerts-download-recipients.presenter.js
  app/services/notices/setup/download-recipients.service.js
  test/presenters/notices/setup/abstraction-alert-download-recipients.presenter.test.js
  test/services/notices/setup/download-recipients.service.test.js
Labels: enhancement

#2021 Add contact to view billing account page
  app/presenters/billing-account/view-billing-account.presenter.js
  app/services/billing-accounts/fetch-view-billing-account.service.js
  test/controllers/billing-accounts.controller.test.js
  test/fixtures/billing-accounts.fixtures.js
  test/presenters/billing-accounts/view-billing-account.presenter.test.js
  test/services/billing-accounts/fetch-view-billing-account.service.test.js
  test/services/billing-accounts/view-billing-account.service.test.js
Labels: enhancement
