Repository DEFRA/water-abstraction-system, pull requests merged in 2025-06, with the labels that each got.

#2039 Refactor notices page to use payload instead of saved filters
  app/services/notices/fetch-notices.service.js
  app/services/notices/submit-index.service.js
  test/services/notices/submit-index.service.test.js
  test/support/seeders/notices.seeder.js
Labels: bug

#2013 Tag a licence - Enter licence number
  app/controllers/licence-monitoring-station-setup.controller.js
  app/presenters/licence-monitoring-station/setup/licence-number.presenter.js
  app/routes/licence-monitoring-station-setup.routes.js
  app/services/licence-monitoring-station/setup/licence-number.service.js
  app/services/licence-monitoring-station/setup/submit-licence-number.service.js
  app/validators/licence-monitoring-station/setup/licence-number.validator.js
  app/views/licence-monitoring-station/setup/licence-number.njk
  test/controllers/licence-monitoring-station-setup.controller.test.js
  test/presenters/licence-monitoring-station/setup/licence-number.presenter.test.js
  test/services/licence-monitoring-station/setup/licence-number.service.test.js
  test/services/licence-monitoring-station/setup/submit-licence-number.service.test.js
  test/validators/licence-monitoring-station/setup/licence-number.validator.test.js
Labels: enhancement

#2047 Amend return version migration to exclude ended
  app/services/jobs/return-version-migration/fetch-water-undertakers.service.js
Labels: housekeeping

#2050 Fix "Enter licence number" error message
  app/validators/licence-monitoring-station/setup/licence-number.validator.js
  test/services/licence-monitoring-station/setup/submit-licence-number.service.test.js
  test/validators/licence-monitoring-station/setup/licence-number.validator.test.js
Labels: bug

#2051 Fix abstraction alerts download recipients
  app/presenters/notices/setup/abstraction-alerts-download-recipients.presenter.js
  app/services/notices/setup/fetch-abstraction-alert-recipients.service.js
  test/presenters/notices/setup/abstraction-alert-download-recipients.presenter.test.js
  test/services/notices/setup/determine-recipients.service.test.js
  test/services/notices/setup/download-recipients.service.test.js
  test/services/notices/setup/fetch-abstraction-alert-recipients.service.test.js
Labels: enhancement

#2056 Fix invalid fin year in 2PT annual bill run setup
  app/services/bill-runs/setup/submit-year.service.js
  app/validators/bill-runs/setup/year.validator.js
  test/services/bill-runs/setup/submit-year.service.test.js
Labels: bug

#2057 Update rtn requirements to new unique reference
  app/services/jobs/return-logs/fetch-return-requirements.service.js
  app/services/jobs/return-version-migration/generate-return-requirements-data.service.js
  app/services/jobs/return-version-migration/generate-return-version.service.js
  app/services/jobs/return-version-migration/process-return-version-migration.service.js
  app/services/return-logs/fetch-licence-return-requirements.service.js
  app/services/return-logs/generate-return-log.service.js
  app/services/return-versions/setup/check/generate-return-version-requirements.service.js
  app/services/return-versions/setup/check/persist-return-version.service.js
  db/migrations/legacy/20221108007024_water-return-requirements.js
  db/migrations/public/20250607191059_alter-return-requirements-view.js
  test/fixtures/return-logs.fixture.js
  test/services/jobs/return-logs/fetch-return-requirements.service.test.js
  test/services/return-logs/create-return-logs.service.test.js
  test/services/return-logs/fetch-licence-return-requirements.service.test.js
  test/services/return-logs/generate-return-log.service.test.js
  test/services/return-logs/setup/submit-submission.service.test.js
  test/services/return-logs/void-licence-return-logs.service.test.js
  test/services/return-versions/setup/check/generate-return-version-requirements.service.test.js
  test/services/return-versions/setup/check/persist-return-version.service.test.js
  test/support/helpers/return-log.helper.js
  test/support/helpers/return-requirement.helper.js
  test/support/helpers/review-return.helper.js
  test/support/seeders/requirements-for-returns.seeder.js
Labels: bug

#2060 Skip flakey unit tests
  test/services/notices/fetch-notices.service.test.js
  test/services/notices/setup/fetch-abstraction-alert-recipients.service.test.js
Labels: testing

#2066 Fix duplicate points in return versions setup
  app/services/return-versions/setup/fetch-points.service.js
  test/services/return-versions/setup/fetch-points.service.test.js
Labels: bug

#2054 Add source to abstraction alerts notifications
  app/presenters/notices/setup/abstraction-alerts-notifications.presenter.js
  app/services/notices/setup/abstraction-alerts/determine-licence-monitoring-stations.service.js
  app/services/notices/setup/abstraction-alerts/fetch-monitoring-station.service.js
  test/fixtures/abstraction-alert-session-data.fixture.js
  test/presenters/notices/setup/abstraction-alert-notifications.presenter.test.js
  test/services/notices/setup/abstraction-alerts/determine-licence-monitoring-stations.service.test.js
  test/services/notices/setup/abstraction-alerts/fetch-monitoring-station.service.test.js
  test/services/notices/setup/batch-notifications.service.test.js
Labels: enhancement

#2038 Amend "licence hands-off flow or level threshold" page to use radios
  app/lib/static-lookups.lib.js
  app/presenters/licence-monitoring-station/setup/threshold-and-unit.presenter.js
  app/services/licence-monitoring-station/setup/submit-threshold-and-unit.service.js
  app/validators/licence-monitoring-station/setup/threshold-and-unit.validator.js
  app/views/licence-monitoring-station/setup/threshold-and-unit.njk
  test/presenters/licence-monitoring-station/setup/threshold-and-unit.presenter.test.js
  test/services/licence-monitoring-station/setup/submit-threshold-and-unit.service.test.js
  test/services/licence-monitoring-station/setup/threshold-and-unit.service.test.js
  test/validators/licence-monitoring-station/setup/threshold-and-unit.validator.test.js
Labels: enhancement

#2020 Monitoring stations - Remove tag
  app/controllers/licence-monitoring-station.controller.js
  app/controllers/monitoring-stations.controller.js
  app/plugins/router.plugin.js
  app/presenters/licence-monitoring-station/remove.presenter.js
  app/presenters/monitoring-stations/licence.presenter.js
  app/presenters/monitoring-stations/view.presenter.js
  app/routes/licence-monitoring-station.routes.js
  app/services/licence-monitoring-station/fetch-licence-monitoring-station.service.js
  app/services/licence-monitoring-station/remove.service.js
  app/services/licence-monitoring-station/submit-remove.service.js
  app/services/monitoring-stations/licence.service.js
  app/services/monitoring-stations/view.service.js
  app/views/licence-monitoring-station/remove.njk
  app/views/monitoring-stations/licence.njk
  app/views/monitoring-stations/view.njk
  test/controllers/licence-monitoring-station.controller.test.js
  test/controllers/monitoring-stations.controller.test.js
  test/presenters/licence-monitoring-station/remove.presenter.test.js
  test/presenters/monitoring-stations/licence.presenter.test.js
  test/presenters/monitoring-stations/view.presenter.test.js
  test/services/licence-monitoring-station/fetch-licence-monitoring-station.service.test.js
  test/services/licence-monitoring-station/remove.service.test.js
  test/services/licence-monitoring-station/submit-remove.service.test.js
  test/services/monitoring-stations/licence.service.test.js
  test/services/monitoring-stations/view.service.test.js
Labels: enhancement

#2072 Add messageRef to abstraction alerts notifications
  app/presenters/notices/setup/abstraction-alerts-notifications.presenter.js
  test/presenters/notices/setup/abstraction-alert-notifications.presenter.test.js
  test/services/notices/setup/batch-notifications.service.test.js
Labels: enhancement

#2071 Monitoring stations - Remove tag button
  app/presenters/monitoring-stations/view.presenter.js
  app/views/macros/licence-monitoring-station-restrictions-table.njk
  app/views/monitoring-stations/view.njk
  test/presenters/monitoring-stations/view.presenter.test.js
  test/services/monitoring-stations/view.service.test.js
Labels: enhancement

#2074 Add templateId to abstraction alerts notifications
  app/lib/notify-templates.lib.js
  app/presenters/notices/setup/abstraction-alerts-notifications.presenter.js
  test/presenters/notices/setup/abstraction-alert-notifications.presenter.test.js
Labels: enhancement

#2079 Remove tag - Set `deleted_at`
  app/services/licence-monitoring-station/submit-remove.service.js
  test/services/licence-monitoring-station/submit-remove.service.test.js
Labels: bug

#2045 Update AA email address page to check submitted values
  app/presenters/notices/setup/abstraction-alerts/alert-email-address.presenter.js
  app/services/notices/setup/abstraction-alerts/alert-email-address.service.js
  app/services/notices/setup/abstraction-alerts/submit-alert-email-address.service.js
  app/validators/notices/setup/abstraction-alerts/alert-email-address.validator.js
  app/views/notices/setup/abstraction-alerts/alert-email-address.njk
  test/presenters/notices/setup/abstraction-alerts/alert-email-address.presenter.test.js
  test/services/notices/setup/abstraction-alerts/alert-email-address.service.test.js
  test/services/notices/setup/abstraction-alerts/submit-alert-email-address.service.test.js
  test/validators/notices/setup/abstraction-alerts/alert-email-address.validator.test.js
Labels: enhancement

#2081 Add clean empty void return logs task to clean job
  app/services/jobs/clean/clean-empty-void-return-logs.service.js
  app/services/jobs/clean/process-clean.service.js
  test/services/jobs/clean/clean-empty-void-return-logs.service.test.js
  test/services/jobs/clean/process-clean.service.test.js
Labels: enhancement

#2086 Update and correct view return log presenter test
  app/presenters/return-logs/view-return-log.presenter.js
  test/fixtures/return-cycles.fixture.js
  test/fixtures/return-logs.fixture.js
  test/fixtures/return-requirements.fixture.js
  test/presenters/return-logs/download-return-log.presenter.test.js
  test/presenters/return-logs/view-return-log.presenter.test.js
  test/services/jobs/return-logs/process-return-logs.service.test.js
  test/services/return-logs/create-return-logs.service.test.js
  test/services/return-logs/download-return-log.service.test.js
  test/services/return-logs/generate-return-log.service.test.js
  test/services/return-logs/process-licence-return-logs.service.test.js
Labels: housekeeping

#2092 Rename "Remove tag" button to "Continue"
  app/views/licence-monitoring-station/remove.njk
Labels: enhancement

#2093 Fix abstraction alerts multiple licence refs
  app/presenters/notices/setup/abstraction-alerts-notifications.presenter.js
  test/presenters/notices/setup/abstraction-alert-notifications.presenter.test.js
Labels: enhancement

#2094 Update notices abstraction alerts status update
  app/services/jobs/notifications/fetch-notifications.service.js
  app/services/jobs/notifications/notifications-status-updates.service.js
  app/services/jobs/notifications/update-abstraction-alerts.service.js
  test/services/jobs/notifications/fetch-notifications.service.test.js
  test/services/jobs/notifications/notifications-status-updates.service.test.js
  test/services/jobs/notifications/update-abstraction-alerts.service.test.js
  test/services/jobs/notifications/update-notifications.service.test.js
Labels: enhancement

#2103 Fix instantaneous abstraction amount measure text
  app/presenters/licences/view-licence-purposes.presenter.js
  app/views/licences/tabs/summary.njk
  test/presenters/licences/view-licence-purposes.presenter.test.js
  test/services/licences/view-licence-purposes.service.test.js
Labels: bug

#2070 Update abstraction alert thresholds to be ordered
  app/lib/static-lookups.lib.js
  app/presenters/notices/setup/abstraction-alerts/alert-thresholds.presenter.js
  test/fixtures/abstraction-alert-session-data.fixture.js
  test/presenters/notices/setup/abstraction-alerts/alert-thresholds.presenter.test.js
Labels: enhancement

#2110 Fix missed wrong abstraction amount measure text
  app/presenters/licences/base-licences.presenter.js
  app/presenters/licences/view-licence-purposes.presenter.js
  app/presenters/licences/view-licence-summary.presenter.js
  test/presenters/licences/base-licences.presenter.test.js
  test/presenters/licences/view-licence-purposes.presenter.test.js
  test/presenters/licences/view-licence-summary.presenter.test.js
  test/services/licences/view-licence-purposes.service.test.js
Labels: bug

#2111 Update setup initiate session to use determine notice type
  app/services/notices/setup/determine-notice-type.service.js
  app/services/notices/setup/initiate-session.service.js
  test/services/notices/setup/determine-notice-type.service.test.js
  test/services/notices/setup/initiate-session.service.test.js
Labels: enhancement

#2116 Update notices letter contact
  app/presenters/notices/setup/abstraction-alerts-notifications.presenter.js
  app/presenters/notices/setup/notifications.presenter.js
  test/presenters/notices/setup/abstraction-alert-notifications.presenter.test.js
  test/presenters/notices/setup/notifications.presenter.test.js
  test/services/notices/setup/batch-notifications.service.test.js
Labels: enhancement

#2119 Update submit notice type to determine notice type
  app/services/notices/setup/submit-notice-type.service.js
  test/services/notices/setup/submit-notice-type.service.test.js
Labels: enhancement

#2121 Refactor notice setup ad-hoc journey
  app/lib/notify-templates.lib.js
  app/presenters/notices/setup/cancel.presenter.js
  app/presenters/notices/setup/check.presenter.js
  app/presenters/notices/setup/confirmation.presenter.js
  app/presenters/notices/setup/notifications.presenter.js
  app/services/notices/setup/determine-notice-type.service.js
  app/services/notices/setup/fetch-abstraction-alert-recipients.service.js
  app/services/notices/setup/fetch-download-recipients.service.js
  app/services/notices/setup/fetch-recipients.service.js
  app/services/notices/setup/initiate-session.service.js
  app/services/notices/setup/returns-period/returns-period.service.js
  test/presenters/notices/setup/cancel.presenter.test.js
  test/presenters/notices/setup/check.presenter.test.js
  test/presenters/notices/setup/confirmation.presenter.test.js
  test/presenters/notices/setup/notifications.presenter.test.js
  test/services/notices/setup/cancel.service.test.js
  test/services/notices/setup/determine-notice-type.service.test.js
  test/services/notices/setup/fetch-download-recipients.service.test.js
  test/services/notices/setup/fetch-recipients.service.test.js
  test/services/notices/setup/initiate-session.service.test.js
  test/services/notices/setup/submit-cancel.service.test.js
Labels: enhancement

#2122 Scaffold the notices setup check notice page
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/check-notice-type.presenter.js
  app/routes/notices-setup.routes.js
  app/services/notices/setup/check-notice-type.service.js
  app/views/notices/setup/check-notice-type.njk
  test/controllers/notices-setup.controller.test.js
  test/presenters/notices/setup/check-notice-type.presenter.test.js
  test/services/notices/setup/check-notice-type.service.test.js
Labels: enhancement

#2130 Add notice setup returns for paper forms
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/returns-for-paper-forms.presenter.js
  app/routes/notices-setup.routes.js
  app/services/notices/setup/returns-for-paper-forms.service.js
  app/services/notices/setup/submit-returns-for-paper-forms.service.js
  app/validators/notices/setup/returns-for-paper-forms.validator.js
  app/views/notices/setup/returns-for-paper-forms.njk
  test/controllers/notices-setup.controller.test.js
  test/presenters/notices/setup/returns-for-paper-forms.presenter.test.js
  test/services/notices/setup/returns-for-paper-forms.service.test.js
  test/services/notices/setup/submit-returns-for-paper-forms.service.test.js
  test/validators/notices/setup/returns-for-paper-forms.validator.test.js
Labels: enhancement

#2129 Add `activeNavBar` to full condition page
  app/services/licence-monitoring-station/setup/submit-full-condition.service.js
  test/services/licence-monitoring-station/setup/submit-full-condition.service.test.js
Labels: bug

#2132 Update notice setup check notice type
  app/presenters/notices/setup/check-notice-type.presenter.js
  app/views/notices/setup/check-notice-type.njk
  test/presenters/notices/setup/check-notice-type.presenter.test.js
  test/services/notices/setup/check-notice-type.service.test.js
Labels: enhancement

#2135 Update notice setup check notice type to use change links
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/check-notice-type.presenter.js
  app/services/notices/setup/check-notice-type.service.js
  app/services/notices/setup/submit-licence.service.js
  app/views/notices/setup/check-notice-type.njk
  test/controllers/notices-setup.controller.test.js
  test/presenters/notices/setup/check-notice-type.presenter.test.js
  test/services/notices/setup/check-notice-type.service.test.js
  test/services/notices/setup/submit-licence.service.test.js
Labels: enhancement

#2140 Update notice setup check notice type
  app/presenters/notices/setup/check-notice-type.presenter.js
  app/views/notices/setup/check-notice-type.njk
  test/presenters/notices/setup/check-notice-type.presenter.test.js
  test/services/notices/setup/check-notice-type.service.test.js
Labels: enhancement

#2152 Add return id migration for return logs view
  db/migrations/legacy/20221108006001_returns-returns.js
  db/migrations/public/20250630132940_alter-returns-logs-view.js
Labels: enhancement
