Repository DEFRA/water-abstraction-system, pull requests merged in 2025-02, with the labels that each got.

#1666 Return logs check page - populate Reporting details
  app/presenters/return-logs/setup/check.presenter.js
  app/presenters/return-logs/setup/single-volume.presenter.js
  app/validators/return-logs/setup/units.validator.js
  app/views/return-logs/setup/check.njk
  app/views/return-logs/setup/units.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/check.presenter.test.js
  test/presenters/return-logs/setup/single-volume.presenter.test.js
  test/presenters/return-logs/setup/units.presenter.test.js
  test/services/return-logs/setup/check.service.test.js
  test/services/return-logs/setup/single-volume.service.test.js
  test/validators/return-logs/setup/units.validator.test.js
Labels: enhancement

#1676 Refactor Determine Returns Period
  app/services/notifications/setup/determine-returns-period.service.js
  app/services/notifications/setup/review.service.js
  test/services/notifications/setup/determine-returns-period.service.test.js
  test/services/notifications/setup/review.service.test.js
Labels: housekeeping

#1677 Refactor existing CSV converter
  app/lib/transform-to-csv.lib.js
  app/services/jobs/export/write-table-to-file.service.js
  test/lib/transform-to-csv.lib.test.js
  test/services/jobs/export/convert-to-csv.service.test.js
Labels: housekeeping

#1678 Add FetchDownloadRecipientsService
  app/services/notifications/setup/fetch-download-recipients.service.js
  test/services/notifications/setup/fetch-download-recipients.service.test.js
  test/support/helpers/return-log.helper.js
  test/support/seeders/licence-document-header.seeder.js
Labels: enhancement

#1681 Add notifications download link
  app/presenters/notifications/setup/review.presenter.js
  app/services/notifications/setup/review.service.js
  app/views/notifications/setup/review.njk
  test/presenters/notifications/setup/review.presenter.test.js
  test/services/notifications/setup/review.service.test.js
Labels: enhancement

#1679 Return logs check page - populate Log details
  app/presenters/return-logs/setup/check.presenter.js
  app/views/return-logs/setup/check.njk
  test/presenters/return-logs/setup/check.presenter.test.js
  test/services/return-logs/setup/check.service.test.js
Labels: enhancement

#1682 Add notifications download route
  app/controllers/notifications-setup.controller.js
  app/routes/notifications-setup.routes.js
  app/services/notifications/setup/download-recipients.service.js
  app/services/notifications/setup/initiate-session.service.js
  test/controllers/notifications-setup.controller.test.js
  test/services/notifications/setup/download-recipients.service.test.js
  test/services/notifications/setup/initiate-session.service.test.js
Labels: enhancement

#1660 Return Logs setup - Period used
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/setup/period-used.presenter.js
  app/routes/return-logs-setup.routes.js
  app/services/return-logs/setup/period-used.service.js
  app/services/return-logs/setup/submit-period-used.service.js
  app/validators/return-logs/setup/period-used.validator.js
  app/validators/return-versions/setup/abstraction-period.validator.js
  app/views/return-logs/setup/period-used.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/period-used.presenter.test.js
  test/services/return-logs/setup/period-used.service.test.js
  test/services/return-logs/setup/submit-period-used.service.test.js
  test/validators/return-logs/setup/period-used.validator.test.js
Labels: enhancement

#1684 Add notifications download presenter
  app/presenters/notifications/setup/download-recipients.presenter.js
  app/services/notifications/setup/download-recipients.service.js
  app/services/notifications/setup/fetch-download-recipients.service.js
  test/presenters/notifications/setup/download-recipients.presenter.test.js
  test/services/notifications/setup/download-recipients.service.test.js
Labels: enhancement

#1689 Fix return logs setup single volume validation
  app/validators/return-logs/setup/single-volume.validator.js
Labels: bug

#1690 Add remove licences page for notifications setup
  app/controllers/notifications-setup.controller.js
  app/presenters/notifications/setup/remove-licences.presenter.js
  app/presenters/notifications/setup/review.presenter.js
  app/routes/notifications-setup.routes.js
  app/services/notifications/setup/remove-licences.service.js
  app/views/notifications/setup/remove-licences.njk
  app/views/notifications/setup/review.njk
  test/controllers/notifications-setup.controller.test.js
  test/presenters/notifications/setup/remove-licences.presenter.test.js
  test/presenters/notifications/setup/review.presenter.test.js
  test/services/notifications/setup/remove-licences.service.test.js
  test/services/notifications/setup/review.service.test.js
Labels: enhancement

#1683 Return logs check page - change links
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/setup/check.presenter.js
  app/presenters/return-logs/setup/meter-provided.presenter.js
  app/presenters/return-logs/setup/received.presenter.js
  app/presenters/return-logs/setup/reported.presenter.js
  app/presenters/return-logs/setup/units.presenter.js
  app/services/return-logs/setup/submit-meter-details.service.js
  app/services/return-logs/setup/submit-meter-provided.service.js
  app/services/return-logs/setup/submit-received.service.js
  app/services/return-logs/setup/submit-reported.service.js
  app/services/return-logs/setup/submit-units.service.js
  app/views/return-logs/setup/check.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/check.presenter.test.js
  test/presenters/return-logs/setup/meter-provided.presenter.test.js
  test/presenters/return-logs/setup/received.presenter.test.js
  test/presenters/return-logs/setup/reported.presenter.test.js
  test/presenters/return-logs/setup/units.presenter.test.js
  test/services/return-logs/setup/check.service.test.js
  test/services/return-logs/setup/submit-meter-details.service.test.js
  test/services/return-logs/setup/submit-meter-provided.service.test.js
  test/services/return-logs/setup/submit-received.service.test.js
  test/services/return-logs/setup/submit-reported.service.test.js
  test/services/return-logs/setup/submit-units.service.test.js
Labels: enhancement

#1701 Return logs check page - Cancel button
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/setup/cancel.presenter.js
  app/routes/return-logs-setup.routes.js
  app/services/return-logs/setup/cancel.service.js
  app/services/return-logs/setup/submit-cancel.service.js
  app/views/return-logs/setup/cancel.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/cancel.presenter.test.js
  test/services/return-logs/setup/cancel.service.test.js
  test/services/return-logs/setup/submit-cancel.service.test.js
Labels: enhancement

#1702 Update remove licence validation to check licence refs
  app/services/notifications/setup/fetch-returns-due.service.js
  app/services/notifications/setup/submit-remove-licences.service.js
  app/validators/notifications/setup/remove-licences.validator.js
  test/services/notifications/setup/fetch-returns-due.service.test.js
  test/services/notifications/setup/submit-remove-licences.services.test.js
  test/validators/notifications/setup/remove-licences.validator.test.js
Labels: enhancement

#1708 Update notifications setup initiate session
  app/controllers/notifications-ad-hoc-returns.controller.js
  app/controllers/notifications-setup.controller.js
  app/routes/notifications-ad-hoc-returns.route.js
  app/services/notifications/ad-hoc-returns/initiate-session.service.js
  app/services/notifications/setup/initiate-session.service.js
  test/controllers/notifications-ad-hoc-returns.controller.test.js
  test/controllers/notifications-setup.controller.test.js
  test/services/notifications/ad-hoc-returns/initiate-session.service.test.js
  test/services/notifications/setup/initiate-session.service.test.js
Labels: enhancement

#1709 Update notifications fetch services to use the session
  app/services/notifications/setup/download-recipients.service.js
  app/services/notifications/setup/fetch-download-recipients.service.js
  app/services/notifications/setup/fetch-recipients.service.js
  app/services/notifications/setup/review.service.js
  test/services/notifications/setup/download-recipients.service.test.js
  test/services/notifications/setup/fetch-download-recipients.service.test.js
  test/services/notifications/setup/fetch-recipients.service.test.js
  test/services/notifications/setup/review.service.test.js
  test/support/seeders/licence-document-header.seeder.js
Labels: enhancement

#1710 Update notifications ad-hoc error handling
  app/presenters/notifications/ad-hoc-returns/licence.presenter.js
  app/services/notifications/ad-hoc-returns/licence.service.js
  app/services/notifications/ad-hoc-returns/submit-licence.service.js
  app/validators/notifications/setup/ad-hoc-licence.validator.js
  test/presenters/notifications/ad-hoc-returns/licence.presenter.test.js
  test/services/notifications/ad-hoc-returns/licence.service.test.js
  test/services/notifications/ad-hoc-returns/submit-licence.service.test.js
  test/validators/notifications/setup/ad-hoc-licence.validator.test.js
Labels: enhancement

#1691 Update return log setup initialise service
  app/lib/dates.lib.js
  app/services/return-logs/setup/initiate-session.service.js
  test/lib/dates.lib.test.js
  test/services/return-logs/setup/initiate-session.service.test.js
Labels: enhancement

#1713 Updated notifications setup query string
  app/controllers/notifications-setup.controller.js
  test/controllers/notifications-setup.controller.test.js
Labels: enhancement

#1714 Updated notifications ad-hoc due returns error
  app/services/notifications/ad-hoc-returns/submit-licence.service.js
  app/validators/notifications/setup/ad-hoc-licence.validator.js
  app/views/notifications/ad-hoc-returns/licence.njk
  test/services/notifications/ad-hoc-returns/submit-licence.service.test.js
  test/validators/notifications/setup/ad-hoc-licence.validator.test.js
Labels: enhancement

#1715 Refactor notifications ad hoc returns into setup
  app/controllers/notifications-ad-hoc-returns.controller.js
  app/controllers/notifications-setup.controller.js
  app/plugins/router.plugin.js
  app/presenters/notifications/setup/ad-hoc-licence.presenter.js
  app/routes/notifications-ad-hoc-returns.route.js
  app/routes/notifications-setup.routes.js
  app/services/notifications/setup/ad-hoc-licence.service.js
  app/services/notifications/setup/initiate-session.service.js
  app/services/notifications/setup/submit-ad-hoc-licence.service.js
  app/views/notifications/setup/ad-hoc-licence.njk
  test/controllers/notifications-ad-hoc-returns.controller.test.js
  test/controllers/notifications-setup.controller.test.js
  test/presenters/notifications/setup/ad-hoc-licence.presenter.test.js
  test/services/notifications/setup/ad-hoc-licence.service.test.js
  test/services/notifications/setup/initiate-session.service.test.js
  test/services/notifications/setup/submit-ad-hoc-licence.service.test.js
Labels: enhancement

#1718 Add notifications setup ad hoc licence fetch
  app/services/notifications/setup/fetch-download-recipients.service.js
  app/services/notifications/setup/fetch-recipients.service.js
  test/services/notifications/setup/fetch-download-recipients.service.test.js
  test/services/notifications/setup/fetch-recipients.service.test.js
Labels: enhancement

#1721 Update notifications review to present ad-hoc and invitations journeys
  app/presenters/notifications/setup/review.presenter.js
  app/services/notifications/setup/review.service.js
  app/views/notifications/setup/review.njk
  test/presenters/notifications/setup/review.presenter.test.js
  test/services/notifications/setup/review.service.test.js
Labels: enhancement

#1722 Update notifications review to check
  app/controllers/notifications-setup.controller.js
  app/presenters/notifications/setup/check.presenter.js
  app/routes/notifications-setup.routes.js
  app/services/notifications/setup/check.service.js
  app/services/notifications/setup/fetch-recipients.service.js
  app/services/notifications/setup/submit-remove-licences.service.js
  app/services/notifications/setup/submit-returns-period.service.js
  app/views/notifications/setup/check.njk
  app/views/notifications/setup/remove-licences.njk
  test/controllers/notifications-setup.controller.test.js
  test/presenters/notifications/setup/check.presenter.test.js
  test/services/notifications/setup/check.service.test.js
  test/services/notifications/setup/submit-remove-licences.services.test.js
  test/services/notifications/setup/submit-returns-period.services.test.js
Labels: enhancement

#1724 Add reference code to notification views
  app/presenters/notifications/setup/ad-hoc-licence.presenter.js
  app/presenters/notifications/setup/check.presenter.js
  app/presenters/notifications/setup/remove-licences.presenter.js
  app/presenters/notifications/setup/returns-period.presenter.js
  app/services/notifications/setup/ad-hoc-licence.service.js
  app/services/notifications/setup/remove-licences.service.js
  app/services/notifications/setup/submit-ad-hoc-licence.service.js
  app/services/notifications/setup/submit-remove-licences.service.js
  app/views/notifications/setup/ad-hoc-licence.njk
  app/views/notifications/setup/check.njk
  app/views/notifications/setup/remove-licences.njk
  app/views/notifications/setup/view-returns-period.njk
  test/presenters/notifications/setup/ad-hoc-licence.presenter.test.js
  test/presenters/notifications/setup/check.presenter.test.js
  test/presenters/notifications/setup/remove-licences.presenter.test.js
  test/presenters/notifications/setup/returns-period.presenter.test.js
  test/services/notifications/setup/ad-hoc-licence.service.test.js
  test/services/notifications/setup/check.service.test.js
  test/services/notifications/setup/remove-licences.service.test.js
  test/services/notifications/setup/returns-period.service.test.js
  test/services/notifications/setup/submit-ad-hoc-licence.service.test.js
  test/services/notifications/setup/submit-remove-licences.services.test.js
  test/services/notifications/setup/submit-returns-period.services.test.js
Labels: enhancement

#1725 Add reminders journey to notifications setup
  app/presenters/notifications/setup/check.presenter.js
  test/presenters/notifications/setup/check.presenter.test.js
Labels: enhancement

#1726 Fix return log under query notification
  app/controllers/return-logs.controller.js
  app/services/return-logs/submit-view-return-log.service.js
  app/services/return-logs/view-return-log.service.js
  app/views/return-logs/view.njk
  test/controllers/return-logs.controller.test.js
  test/services/return-logs/submit-view-return-log.service.test.js
  test/services/return-logs/view-return-log.service.test.js
Labels: bug

#1727 Fix missing page title in check recipients page
  app/presenters/notifications/setup/check.presenter.js
  app/views/notifications/setup/check.njk
  test/presenters/notifications/setup/check.presenter.test.js
  test/services/notifications/setup/check.service.test.js
Labels: bug

#1728 Amend recipients download CSV headers (licence)
  app/presenters/notifications/setup/download-recipients.presenter.js
  test/presenters/notifications/setup/download-recipients.presenter.test.js
  test/services/notifications/setup/download-recipients.service.test.js
Labels: housekeeping

#1729 Add role to download recipients CSV & tweak order
  app/presenters/notifications/setup/download-recipients.presenter.js
  test/presenters/notifications/setup/download-recipients.presenter.test.js
  test/services/notifications/setup/download-recipients.service.test.js
Labels: housekeeping

#1730 Fix recipients download CSV notification type col.
  app/presenters/notifications/setup/download-recipients.presenter.js
  app/services/notifications/setup/download-recipients.service.js
  test/presenters/notifications/setup/download-recipients.presenter.test.js
  test/services/notifications/setup/download-recipients.service.test.js
Labels: bug

#1732 Add notifications setup link
  app/presenters/notifications/setup/check.presenter.js
  app/views/notifications/setup/check.njk
  test/presenters/notifications/setup/check.presenter.test.js
  test/services/notifications/setup/check.service.test.js
Labels: enhancement

#1734 Add notifications setup cancel page
  app/controllers/notifications-setup.controller.js
  app/presenters/notifications/setup/cancel.presenter.js
  app/routes/notifications-setup.routes.js
  app/services/notifications/setup/cancel.service.js
  app/services/notifications/setup/submit-cancel.service.js
  app/views/notifications/setup/cancel.njk
  test/controllers/notifications-setup.controller.test.js
  test/presenters/notifications/setup/cancel.presenter.test.js
  test/services/notifications/setup/cancel.service.test.js
  test/services/notifications/setup/submit-cancel.service.test.js
Labels: enhancement

#1741 Update notifications check back link
  app/presenters/notifications/setup/check.presenter.js
  app/views/notifications/setup/check.njk
  test/presenters/notifications/setup/check.presenter.test.js
  test/services/notifications/setup/check.service.test.js
Labels: enhancement

#1743 Fix notifications duplicate licence refs
  app/services/notifications/setup/fetch-recipients.service.js
Labels: enhancement

#1745 Fix notifications setup cancel page back link
  app/presenters/notifications/setup/cancel.presenter.js
  app/views/notifications/setup/cancel.njk
  test/presenters/notifications/setup/cancel.presenter.test.js
  test/services/notifications/setup/cancel.service.test.js
Labels: enhancement

#1737 Add GOV.UK notify services
  .env.example
  .github/workflows/ci.yml
  .labrc.js
  app/lib/notify-templates.lib.js
  app/services/notify/notify-email.service.js
  app/services/notify/notify-letter.service.js
  config/notify.config.js
  package-lock.json
  package.json
  test/services/notify/notify-email.service.test.js
  test/services/notify/notify-letter.service.test.js
Labels: enhancement

#1747 Use existing title helpers in review pages part 2
  app/presenters/bill-runs/review/review-bill-run.presenter.js
  app/views/bill-runs/review/review.njk
  test/presenters/bill-runs/review/review-bill-run.presenter.test.js
Labels: housekeeping

#1750 Fix View Daily Returns column order
  app/presenters/return-submissions/view-return-submission.presenter.js
  test/presenters/return-submissions/view-return-submission.presenter.test.js
Labels: bug

#1748 Enable 2PT supplementary bill run to be created
  app/services/bill-runs/determine-billing-periods.service.js
  app/services/bill-runs/match/fetch-charge-versions.service.js
  app/services/bill-runs/match/fetch-licences.service.js
  app/services/bill-runs/match/match-and-allocate.service.js
  app/services/bill-runs/setup/submit-check.service.js
  app/services/bill-runs/start-bill-run-process.service.js
  app/services/bill-runs/tpt-supplementary/process-bill-run.service.js
  test/services/bill-runs/determine-billing-periods.service.test.js
  test/services/bill-runs/match/fetch-charge-versions.service.test.js
  test/services/bill-runs/start-bill-run-process.service.test.js
  test/services/bill-runs/tpt-supplementary/process-bill-run.service.test.js
Labels: enhancement

#1756 Use existing helpers in view bill page
  app/presenters/bills/view-bill.presenter.js
  test/presenters/bills/view-bill.presenter.test.js
Labels: housekeeping

#1759 Fix notifications setup fetch recipients
  app/services/notifications/setup/fetch-recipients.service.js
Labels: enhancement

#1753 Add Event persist service
  app/services/notifications/setup/create-event.service.js
  test/services/notifications/setup/create-event.service.tests.js
Labels: enhancement

#1758 Add notification setup event presenter
  app/presenters/notifications/setup/create-event.presenter.js
  test/fixtures/recipients.fixtures.js
  test/presenters/notifications/setup/create-event.presenter.test.js
Labels: enhancement

#1760 Move reusable supplementary billing services
  app/lib/general.lib.js
  app/services/bill-runs/fetch-previous-transactions.service.js
  app/services/bill-runs/fetch-two-part-tariff-billing-accounts.service.js
  app/services/bill-runs/process-supplementary-transactions.service.js
  app/services/bill-runs/reverse-supplementary-transactions.service.js
  app/services/bill-runs/supplementary/process-billing-period.service.js
  app/services/bill-runs/supplementary/reverse-transactions.service.js
  app/services/bill-runs/two-part-tariff/generate-bill-run.service.js
  test/lib/general.lib.test.js
  test/services/bill-runs/fetch-previous-transactions.service.test.js
  test/services/bill-runs/fetch-two-part-tariff-billing-accounts.service.test.js
  test/services/bill-runs/process-supplementary-transactions.service.test.js
  test/services/bill-runs/reverse-supplementary-transactions.service.test.js
  test/services/bill-runs/two-part-tariff/generate-bill-run.service.test.js
Labels: housekeeping
