Repository DEFRA/water-abstraction-system, pull requests merged in 2025-08, with the labels that each got.

#2225 Select how to contact recipient submit logic
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/contact-type.presenter.js
  app/services/notices/setup/submit-contact-type.service.js
  app/validators/notices/setup/contact-type.validator.js
  app/views/notices/setup/contact-type.njk
  test/services/notices/setup/contact-type.service.test.js
  test/services/notices/setup/submit-contact-type.service.test.js
  test/validators/notices/setup/contact-type.validator.test.js
Labels: enhancement

#2226 Fix communications notifications
  app/presenters/licences/view-licence-communications.presenter.js
  app/presenters/notifications/view-notification.presenter.js
  app/services/licences/fetch-communications.service.js
  app/services/notifications/fetch-notification.service.js
  test/presenters/licences/view-licence-communications.presenter.test.js
  test/services/licences/fetch-communications.service.test.js
  test/services/notifications/fetch-notification.service.test.js
Labels: enhancement

#2230 Add link to select recipients page
  app/presenters/notices/setup/select-recipients.presenter.js
  app/views/notices/setup/select-recipients.njk
  test/presenters/notices/setup/select-recipients.presenter.test.js
  test/services/notices/setup/select-recipients.service.test.js
  test/services/notices/setup/submit-select-recipients.service.test.js
Labels: enhancement

#2196 Add Gotenberg services
  app/requests/gotenberg.request.js
  app/requests/gotenberg/generate-return-form.request.js
  app/views/notices/pdfs/preview-return-forms.njk
  test/requests/gotenberg.request.test.js
  test/requests/gotenberg/generate-return-form.request.test.js
Labels: enhancement, do not merge

#2231 Ad-hoc notice - enter postcode
  app/controllers/notices-setup.controller.js
  app/presenters/address/postcode.presenter.js
  app/presenters/notices/setup/contact-type.presenter.js
  app/services/address/postcode.service.js
  app/services/address/submit-postcode.service.js
  app/services/notices/setup/submit-contact-type.service.js
  test/controllers/notices-setup.controller.test.js
  test/presenters/address/postcode.presenter.test.js
  test/presenters/notices/setup/contact-type.presenter.test.js
  test/services/address/postcode.service.test.js
  test/services/address/submit-postcode.service.test.js
  test/services/notices/setup/contact-type.service.test.js
  test/services/notices/setup/submit-contact-type.service.test.js
Labels: enhancement

#2234 Add user_data column to users view
  db/migrations/public/20250805100104_alter-users-view.js
  test/models/charge-version-note.model.test.js
  test/models/group.model.test.js
  test/models/return-version.model.test.js
  test/models/role.model.test.js
  test/models/user-group.model.test.js
  test/models/user-role.model.test.js
  test/services/idm/fetch-user-roles-and-groups.service.test.js
  test/support/helpers/user.helper.js
Labels: housekeeping

#2241 Update notices setup recipients to use additional recipients
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/select-recipients.presenter.js
  app/services/notices/setup/check.service.js
  app/services/notices/setup/recipients.service.js
  app/services/notices/setup/submit-contact-type.service.js
  app/views/notices/setup/check.njk
  test/controllers/notices-setup.controller.test.js
  test/presenters/notices/setup/select-recipients.presenter.test.js
  test/services/notices/setup/check.service.test.js
  test/services/notices/setup/recipients.service.test.js
  test/services/notices/setup/select-recipients.service.test.js
  test/services/notices/setup/submit-contact-type.service.test.js
  test/services/notices/setup/submit-select-recipients.service.test.js
Labels: enhancement

#2192 Add basic notice setup return form PDF
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/prepare-return-forms.presenter.js
  app/routes/notices-setup.routes.js
  app/services/notices/setup/prepare-return-forms.service.js
  app/services/notices/setup/preview-return-forms.service.js
  test/controllers/notices-setup.controller.test.js
  test/presenters/notices/setup/prepare-return-forms.presenter.test.js
  test/services/notices/setup/prepare-return-forms.service.test.js
  test/services/notices/setup/preview-return-forms.service.test.js
Labels: enhancement

#2246 Update notice setup return form PDF
  app/presenters/notices/setup/prepare-return-forms.presenter.js
  app/views/notices/pdfs/includes/custom.css
  app/views/notices/pdfs/includes/reset.css
  app/views/notices/pdfs/layout/footer.njk
  app/views/notices/pdfs/layout/header.njk
  app/views/notices/pdfs/layout/logo.html
  app/views/notices/pdfs/layout/page-layout.njk
  app/views/notices/pdfs/pages/cover.njk
  app/views/notices/pdfs/pages/guidance.njk
  app/views/notices/pdfs/preview-return-forms.njk
  test/presenters/notices/setup/prepare-return-forms.presenter.test.js
  test/services/notices/setup/prepare-return-forms.service.test.js
  test/services/notices/setup/preview-return-forms.service.test.js
Labels: enhancement

#2255 Update bill run cancel views to 'template' standard
  app/views/bill-runs/cancel.njk
Labels: housekeeping

#2258 Fix bill run check page back link
  app/presenters/bill-runs/setup/check/base-check.presenter.js
Labels: bug

#2253 Add billing acc. transaction file ref update job
  app/controllers/jobs.controller.js
  app/requests/charging-module/view-customer-files.request.js
  app/routes/jobs.routes.js
  app/services/jobs/customer-files/process-customer-files.service.js
  app/services/jobs/licence-updates/process-licence-updates.service.js
  db/migrations/legacy/20221108003007_crm-v2-invoice-accounts.js
  test/controllers/jobs.controller.test.js
  test/requests/charging-module/view-customer-files.request.test.js
  test/services/jobs/customer-files/process-customer-files.service.test.js
  test/services/jobs/licence-updates/process-licence-updates.service.test.js
Labels: enhancement

#2263 Update recipients download to use Notify addr pres
  app/presenters/notices/setup/abstraction-alert-download-recipients.presenter.js
  app/presenters/notices/setup/abstraction-alert-notifications.presenter.js
  app/presenters/notices/setup/download-recipients.presenter.js
  app/services/notices/setup/batch-notifications.service.js
  app/services/notices/setup/download-recipients.service.js
  app/services/notices/setup/preview/preview.service.js
  test/presenters/notices/setup/abstraction-alert-download-recipients.presenter.test.js
  test/presenters/notices/setup/abstraction-alert-notifications.presenter.test.js
  test/presenters/notices/setup/download-recipients.presenter.test.js
  test/services/notices/setup/download-recipients.service.test.js
Labels: housekeeping

#2245 Ad-hoc notice - select address
  app/controllers/address.controller.js
  app/presenters/notices/setup/contact-type.presenter.js
  app/services/address/submit-postcode.service.js
  app/services/address/submit-select.service.js
  app/services/notices/setup/add-additional-recipient.service.js
  app/services/notices/setup/initiate-session.service.js
  app/services/notices/setup/submit-contact-type.service.js
  app/views/notices/setup/contact-type.njk
  test/controllers/address.controller.test.js
  test/presenters/notices/setup/contact-type.presenter.test.js
  test/services/address/submit-postcode.service.test.js
  test/services/address/submit-select.service.test.js
  test/services/notices/setup/add-additional-recipient.service.test.js
  test/services/notices/setup/contact-type.service.test.js
  test/services/notices/setup/initiate-session.service.test.js
  test/services/notices/setup/submit-contact-type.service.test.js
  test/support/helpers/address.helper.js
Labels: enhancement

#2271 Fix not using company in view billing account
  app/presenters/billing-accounts/view-billing-account.presenter.js
  app/services/billing-accounts/fetch-view-billing-account.service.js
  test/fixtures/billing-accounts.fixtures.js
  test/presenters/billing-accounts/view-billing-account.presenter.test.js
  test/services/billing-accounts/fetch-view-billing-account.service.test.js
Labels: bug

#2270 Update return forms PDF to use region and nald area code
  app/lib/static-lookups.lib.js
  app/presenters/notices/setup/prepare-return-forms.presenter.js
  app/services/notices/setup/fetch-returns-due-by-licence-ref.service.js
  test/presenters/notices/setup/prepare-return-forms.presenter.test.js
  test/services/notices/setup/fetch-returns-due-by-licence-ref.service.test.js
  test/services/notices/setup/prepare-return-forms.service.test.js
  test/services/notices/setup/preview-return-forms.service.test.js
Labels: enhancement

#2262 View return version page standardisation
  app/views/return-versions/view.njk
Labels: housekeeping

#2277 Update the notice 'PreviewService' to use the common 'RecipientsService'
  app/services/notices/setup/preview/preview.service.js
Labels: enhancement

#2280 Update bill run errored view to 'template' standard
  app/presenters/bill-runs/errored-bill-run.presenter.js
  app/services/bill-runs/view-bill-run.service.js
  app/views/bill-runs/errored.njk
  test/presenters/bill-runs/errored-bill-run.presenter.test.js
  test/services/bill-runs/view-bill-run.service.test.js
Labels: housekeeping

#2282 View templates standardise - page title macro
  app/presenters/return-versions/setup/start-date.presenter.js
  app/views/macros/page-heading.njk
  app/views/return-versions/setup/start-date.njk
  test/presenters/return-versions/setup/start-date.presenter.test.js
  test/services/return-versions/setup/start-date.service.test.js
  test/services/return-versions/setup/submit-start-date.service.test.js
Labels: housekeeping

#2284 Update reason page to use new header macro
  app/presenters/return-versions/setup/reason.presenter.js
  app/views/return-versions/setup/reason.njk
  test/presenters/return-versions/setup/reason.presenter.test.js
  test/services/return-versions/setup/reason.service.test.js
  test/services/return-versions/setup/submit-reason.service.test.js
Labels: housekeeping

#2288 View templates standardise - points view
  app/presenters/return-versions/setup/points.presenter.js
  app/views/return-versions/setup/points.njk
  test/presenters/return-versions/setup/points.presenter.test.js
  test/services/return-versions/setup/points.service.test.js
  test/services/return-versions/setup/submit-points.service.test.js
Labels: housekeeping

#2289 View templates standardise - abstraction period view
  app/presenters/return-versions/setup/abstraction-period.presenter.js
  app/views/return-versions/setup/abstraction-period.njk
  test/presenters/return-versions/setup/abstraction-period.presenter.test.js
  test/services/return-versions/setup/abstraction-period.service.test.js
  test/services/return-versions/setup/submit-abstraction-period.service.test.js
Labels: housekeeping

#2273 Submit international address for ad-hoc notice
  app/controllers/address.controller.js
  app/presenters/address/international.presenter.js
  app/services/address/submit-international.service.js
  app/services/address/submit-postcode.service.js
  app/services/notices/setup/add-additional-recipient.service.js
  app/services/notices/setup/submit-contact-type.service.js
  app/views/address/international.njk
  test/controllers/address.controller.test.js
  test/presenters/address/international.presenter.test.js
  test/services/address/international.service.test.js
  test/services/address/submit-international.service.test.js
  test/services/address/submit-postcode.service.test.js
  test/services/notices/setup/add-additional-recipient.service.test.js
  test/services/notices/setup/submit-contact-type.service.test.js
Labels: enhancement

#2233 Change top menu to profile details
  .env.example
  app/controllers/users.controller.js
  app/plugins/router.plugin.js
  app/plugins/views.plugin.js
  app/routes/users.routes.js
  app/services/users/submit-profile-details.service.js
  app/services/users/view-profile-details.service.js
  app/validators/users/profile-details.validator.js
  app/views/users/profile-details.njk
  config/feature-flags.config.js
  test/controllers/users.controller.test.js
  test/services/users/submit-profile-details.service.test.js
  test/services/users/view-profile-details.service.test.js
  test/validators/users/profile-details.validator.test.js
Labels: enhancement

#2299 Add dynamic meter readings to the return forms PDF
  app/lib/general.lib.js
  app/presenters/notices/setup/prepare-return-forms.presenter.js
  app/views/notices/pdfs/pages/data-collection.njk
  app/views/notices/pdfs/preview-return-forms.njk
  test/lib/general.lib.test.js
  test/presenters/notices/setup/prepare-return-forms.presenter.test.js
  test/services/notices/setup/prepare-return-forms.service.test.js
  test/services/notices/setup/preview-return-forms.service.test.js
Labels: enhancement

#2309 Add dynamic meter readings to the return forms PDF for days
  app/presenters/notices/setup/prepare-return-forms.presenter.js
  app/views/notices/pdfs/pages/data-collection.njk
  test/presenters/notices/setup/prepare-return-forms.presenter.test.js
Labels: enhancement

#2308 Add additional recipient - use route to save details
  app/controllers/address.controller.js
  app/controllers/notices-setup.controller.js
  app/routes/notices-setup.routes.js
  app/services/address/submit-select.service.js
  app/services/notices/setup/add-recipient.service.js
  app/services/notices/setup/initiate-session.service.js
  test/controllers/address.controller.test.js
  test/controllers/notices-setup.controller.test.js
  test/services/address/submit-international.service.test.js
  test/services/address/submit-manual.service.test.js
  test/services/address/submit-select.service.test.js
  test/services/notices/setup/add-recipient.service.test.js
  test/services/notices/setup/initiate-session.service.test.js
Labels: enhancement

#2311 Add the return forms preview page
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/check.presenter.js
  app/presenters/notices/setup/preview/check-return-forms.presenter.js
  app/routes/notices-setup.routes.js
  app/services/notices/setup/preview-return-forms.service.js
  app/services/notices/setup/preview/check-return-forms.service.js
  app/views/notices/setup/preview/check-return-forms.njk
  test/controllers/notices-setup.controller.test.js
  test/presenters/notices/setup/check.presenter.test.js
  test/presenters/notices/setup/preview/check-return-forms.presenter.test.js
  test/services/notices/setup/preview/check-return-forms.service.test.js
Labels: enhancement

#2320 Update the standard layout to provide the error summary, back link and page heading html.
  app/views/layout.njk
Labels: enhancement

#2321 Address lookup - handle null premises and street address
  app/services/address/submit-select.service.js
  test/services/address/submit-select.service.test.js
Labels: enhancement

#2330 Add Notify service to our health info page
  app/controllers/health.controller.js
  app/requests/notify/view-health.request.js
  app/services/health/info.service.js
  app/views/health/info.njk
  test/requests/notify/view-health.request.test.js
  test/services/health/info.service.test.js
Labels: enhancement

#2332 Delete redundant /check endpoints
  app/controllers/check.controller.js
  app/routes/check.routes.js
  app/services/check/address/generate-notify-address.service.js
  app/services/check/address/legacy/contact.js
  app/services/check/address/legacy/crm-contact-list.js
  app/services/check/address/legacy/notify-helpers.js
  app/services/check/address/validate-address.service.js
  test/controllers/check.controller.test.js
Labels: housekeeping

#2334 Ensure stubbed global notifier is deleted in tests
  test/lib/general.lib.test.js
  test/plugins/error-pages.plugin.test.js
  test/services/bill-runs/cancel/delete-bill-run.service.test.js
  test/services/bill-runs/handle-errored-bill-run.service.test.js
  test/services/bill-runs/match/fetch-return-logs-for-licence.service.test.js
  test/services/bill-runs/match/match-and-allocate.service.test.js
  test/services/bill-runs/reissue/fetch-bills-to-be-reissued.service.test.js
  test/services/bill-runs/send/update-invoice-numbers.service.test.js
  test/services/data/tear-down/tear-down.service.test.js
  test/services/jobs/clean/clean-empty-bill-runs.service.test.js
  test/services/jobs/clean/clean-empty-void-return-logs.service.test.js
  test/services/jobs/clean/clean-expired-sessions.service.test.js
  test/services/jobs/clean/process-clean.service.test.js
  test/services/jobs/customer-files/process-customer-files.service.test.js
  test/services/jobs/export/schema-export.service.test.js
  test/services/jobs/licence-updates/process-licence-updates.service.test.js
  test/services/jobs/return-logs/process-return-logs.service.test.js
  test/services/jobs/time-limited/process-time-limited-licences.service.test.js
  test/services/licences/supplementary/process-billing-flag.service.test.js
  test/services/notices/setup/submit-check.service.test.js
  test/services/plugins/error-pages.service.test.js
Labels: housekeeping
