Repository DEFRA/water-abstraction-system, pull requests merged in 2025-07, with the labels that each got.

#2143 Update notice setup returns paper forms
  app/presenters/notices/setup/returns-for-paper-forms.presenter.js
  app/services/notices/setup/fetch-returns-due-by-licence-ref.service.js
  app/services/notices/setup/submit-licence.service.js
  test/presenters/notices/setup/returns-for-paper-forms.presenter.test.js
  test/services/notices/setup/fetch-returns-due-by-licence-ref.service.test.js
  test/services/notices/setup/returns-for-paper-forms.service.test.js
  test/services/notices/setup/submit-returns-for-paper-forms.service.test.js
  test/support/helpers/return-log.helper.js
Labels: enhancement

#2156 Update notice setup returns paper forms change link
  app/presenters/notices/setup/check-notice-type.presenter.js
  app/views/notices/setup/check-notice-type.njk
  test/presenters/notices/setup/check-notice-type.presenter.test.js
  test/services/notices/setup/check-notice-type.service.test.js
Labels: enhancement

#2158 Remove the return version migration job
  app/controllers/jobs.controller.js
  app/routes/jobs.routes.js
  app/services/jobs/return-version-migration/fetch-water-undertakers.service.js
  app/services/jobs/return-version-migration/generate-return-requirements-data.service.js
  app/services/jobs/return-version-migration/generate-return-version.service.js
  app/services/jobs/return-version-migration/process-return-version-migration.service.js
  test/controllers/jobs.controller.test.js
Labels: housekeeping

#2159 Update notice setup licence navigation
  app/presenters/notices/setup/licence.presenter.js
  app/services/notices/setup/licence.service.js
  app/services/notices/setup/submit-licence.service.js
  app/views/notices/setup/licence.njk
  test/presenters/notices/setup/licence.presenter.test.js
  test/services/notices/setup/licence.service.test.js
  test/services/notices/setup/submit-licence.service.test.js
Labels: enhancement

#2169 Address lookup requests
  app/requests/address-lookup/lookup-postcode.request.js
  app/requests/address-lookup/lookup-uprn.request.js
  test/requests/address-lookup/lookup-postcode.request.test.js
  test/requests/address-lookup/lookup-uprn.request.test.js
Labels: enhancement

#2170 View postcode page updates
  app/controllers/address.controller.js
  app/routes/address.routes.js
  app/services/address/postcode.service.js
  app/services/address/submit-postcode.service.js
  app/validators/address/postcode.validator.js
  app/views/address/os-places-declaration.njk
  app/views/address/postcode.njk
  package-lock.json
  package.json
  test/services/address/postcode.service.test.js
  test/services/address/submit-postcode.service.test.js
  test/validators/address/postcode.validator.test.js
Labels: enhancement

#2168 Add view select page
  app/controllers/address.controller.js
  app/presenters/address/select.presenter.js
  app/services/address/select.service.js
  app/views/address/postcode.njk
  app/views/address/select.njk
  test/controllers/address.controller.test.js
  test/presenters/address/select.presenter.test.js
  test/services/address/select.service.test.js
Labels: enhancement

#2171 Set role for seeded external users
  db/seeds/09-users.seed.js
Labels: housekeeping

#2173 Update notice setup returns paper forms
  app/services/notices/setup/fetch-returns-due-by-licence-ref.service.js
  test/services/notices/setup/fetch-returns-due-by-licence-ref.service.test.js
  test/services/notices/setup/submit-licence.service.test.js
Labels: enhancement

#2166 Setup scaffolding for manual address page
  app/controllers/address.controller.js
  app/presenters/address/manual.presenter.js
  app/routes/address.routes.js
  app/services/address/manual.service.js
  app/services/address/submit-manual.service.js
  app/validators/address/manual.validator.js
  app/views/address/manual.njk
  test/controllers/address.controller.test.js
  test/presenters/address/manual.presenter.test.js
  test/services/address/manual.service.test.js
  test/services/address/submit-manual.service.test.js
  test/validators/address/manual.validator.test.js
  test/validators/address/postcode.validator.test.js
Labels: enhancement

#2176 Update Address lookup requests to convention
  app/requests/address-facade.request.js
  app/requests/address-facade/lookup-postcode.request.js
  app/requests/address-facade/lookup-uprn.request.js
  app/requests/address-lookup/lookup-postcode.request.js
  app/requests/address-lookup/lookup-uprn.request.js
  app/services/address/select.service.js
  app/services/address/submit-select.service.js
  test/requests/address-facade.request.test.js
  test/requests/address-facade/lookup-postcode.request.test.js
  test/requests/address-facade/lookup-uprn.request.test.js
  test/requests/address-lookup/lookup-postcode.request.test.js
  test/requests/address-lookup/lookup-uprn.request.test.js
  test/services/address/select.service.test.js
  test/services/address/submit-select.service.test.js
Labels: housekeeping

#2181 Update notice setup journey
  app/controllers/notices-setup.controller.js
  app/lib/notify-templates.lib.js
  app/presenters/monitoring-stations/view.presenter.js
  app/presenters/notices/setup/check.presenter.js
  app/presenters/notices/setup/notifications.presenter.js
  app/routes/notices-setup.routes.js
  app/services/notices/setup/batch-notifications.service.js
  app/services/notices/setup/determine-notice-type.service.js
  app/services/notices/setup/initiate-session.service.js
  app/services/notices/setup/preview.service.js
  app/services/notices/setup/submit-notice-type.service.js
  test/controllers/notices-setup.controller.test.js
  test/presenters/monitoring-stations/view.presenter.test.js
  test/presenters/notices/setup/check.presenter.test.js
  test/presenters/notices/setup/notifications.presenter.test.js
  test/requests/notify/notify-email.request.test.js
  test/requests/notify/notify-letter.request.test.js
  test/requests/notify/notify-preview.request.test.js
  test/services/monitoring-stations/view.service.test.js
  test/services/notices/setup/batch-notifications.service.test.js
  test/services/notices/setup/check.service.test.js
  test/services/notices/setup/determine-notice-type.service.test.js
  test/services/notices/setup/initiate-session.service.test.js
  test/services/notices/setup/preview.service.test.js
  test/services/notices/setup/submit-notice-type.service.test.js
Labels: enhancement

#2180 Add submit manual address service
  app/presenters/address/manual.presenter.js
  app/services/address/submit-manual.service.js
  app/services/address/submit-select.service.js
  app/validators/address/manual.validator.js
  app/views/address/manual.njk
  test/presenters/address/manual.presenter.test.js
  test/services/address/manual.service.test.js
  test/services/address/submit-manual.service.test.js
  test/services/address/submit-select.service.test.js
  test/validators/address/manual.validator.test.js
Labels: enhancement

#2131 Tag a licence - Check page
  app/controllers/licence-monitoring-station-setup.controller.js
  app/lib/static-lookups.lib.js
  app/presenters/licence-monitoring-station/setup/check.presenter.js
  app/presenters/licence-monitoring-station/setup/full-condition.presenter.js
  app/routes/licence-monitoring-station-setup.routes.js
  app/services/licence-monitoring-station/setup/check.service.js
  app/services/licence-monitoring-station/setup/fetch-full-condition.service.js
  app/services/licence-monitoring-station/setup/submit-check.service.js
  app/services/licence-monitoring-station/setup/submit-full-condition.service.js
  app/services/licence-monitoring-station/setup/submit-licence-number.service.js
  app/validators/licence-monitoring-station/setup/full-condition.validator.js
  app/views/licence-monitoring-station/setup/check.njk
  app/views/licence-monitoring-station/setup/full-condition.njk
  test/presenters/licence-monitoring-station/setup/check.presenter.test.js
  test/presenters/licence-monitoring-station/setup/full-condition.presenter.test.js
  test/services/licence-monitoring-station/setup/abstraction-period.service.test.js
  test/services/licence-monitoring-station/setup/check.service.test.js
  test/services/licence-monitoring-station/setup/fetch-full-condition.service.test.js
  test/services/licence-monitoring-station/setup/full-condition.service.test.js
  test/services/licence-monitoring-station/setup/submit-abstraction-period.service.test.js
  test/services/licence-monitoring-station/setup/submit-check.service.test.js
  test/services/licence-monitoring-station/setup/submit-full-condition.service.test.js
  test/services/licence-monitoring-station/setup/submit-licence-number.service.test.js
  test/validators/licence-monitoring-station/setup/full-condition.validator.test.js
Labels: enhancement

#2177 Add Gotenberg to health check
  .github/workflows/ci.yml
  app/services/health/info.service.js
  app/views/info.njk
  config/request.config.js
  config/services.config.js
  test/services/health/info.service.test.js
Labels: enhancement

#2186 Refactor return version set up journey views
  app/views/macros/licence-reference-page-heading.njk
  app/views/return-versions/setup/abstraction-period.njk
  app/views/return-versions/setup/additional-submission-options.njk
  app/views/return-versions/setup/agreements-exceptions.njk
  app/views/return-versions/setup/approved.njk
  app/views/return-versions/setup/cancel.njk
  app/views/return-versions/setup/check.njk
  app/views/return-versions/setup/existing.njk
  app/views/return-versions/setup/frequency-collected.njk
  app/views/return-versions/setup/frequency-reported.njk
  app/views/return-versions/setup/method.njk
  app/views/return-versions/setup/no-returns-required.njk
  app/views/return-versions/setup/note.njk
  app/views/return-versions/setup/points.njk
  app/views/return-versions/setup/purpose.njk
  app/views/return-versions/setup/reason.njk
  app/views/return-versions/setup/remove.njk
  app/views/return-versions/setup/returns-cycle.njk
  app/views/return-versions/setup/site-description.njk
  app/views/return-versions/setup/start-date.njk
Labels: housekeeping

#2189 Update missing 'activeNavBar'
  app/services/notices/setup/check-notice-type.service.js
  app/services/notices/setup/notice-type.service.js
  app/services/notices/setup/return-forms.service.js
  app/services/notices/setup/submit-notice-type.service.js
  app/services/notices/setup/submit-return-forms.service.js
  test/services/notices/setup/check-notice-type.service.test.js
  test/services/notices/setup/notice-type.service.test.js
  test/services/notices/setup/returns-for-paper-forms.service.test.js
  test/services/notices/setup/submit-notice-type.service.test.js
  test/services/notices/setup/submit-returns-for-paper-forms.service.test.js
Labels: enhancement

#2193 Add /check end points to verify Notify address fix
  app/controllers/check.controller.js
  app/routes/check.routes.js
  app/services/check/address/determine-notify-address.js
  app/services/check/address/generate-notify-address.service.js
  app/services/check/address/legacy/contact.js
  app/services/check/address/legacy/crm-contact-list.js
  app/services/check/address/legacy/notify-helpers.js
  app/services/check/address/validate-address.service.js
Labels: housekeeping

#2201 Fix caption on "Check the recipient previews" page
  app/presenters/notices/setup/preview/check-alert.presenter.js
  test/presenters/notices/setup/preview/check-alert.presenter.test.js
  test/services/notices/setup/preview/check-alert.service.test.js
Labels: bug

#2202 View international address page
  app/lib/static-lookups.lib.js
  app/presenters/address/international.presenter.js
  app/services/address/international.service.js
  app/validators/address/addressLine.validator.js
  app/validators/address/international.validator.js
  app/validators/address/manual.validator.js
  app/validators/helpers/notify-address-line.validator.js
  app/views/address/international.njk
  test/presenters/address/international.presenter.test.js
  test/services/address/international.service.test.js
  test/services/address/submit-international.service.test.js
  test/validators/address/international.validator.test.js
  test/validators/address/manual.validator.test.js
Labels: enhancement

#2214 Select how to contact recipient view page
  app/presenters/notices/setup/contact-type.presenter.js
  app/services/notices/setup/contact-type.service.js
  app/services/notices/setup/submit-contact-type.service.js
  app/views/notices/setup/contact-type.njk
  test/presenters/notices/setup/contact-type.presenter.test.js
  test/services/notices/setup/contact-type.service.test.js
Labels: enhancement

#2218 Scaffold notices setup select recipients page
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/select-recipients.presenter.js
  app/routes/notices-setup.routes.js
  app/services/notices/setup/select-recipients.service.js
  app/services/notices/setup/submit-select-recipients.service.js
  app/validators/notices/setup/select-recipients.validator.js
  app/views/notices/setup/select-recipients.njk
  test/controllers/notices-setup.controller.test.js
  test/presenters/notices/setup/select-recipients.presenter.test.js
  test/services/notices/setup/select-recipients.service.test.js
  test/services/notices/setup/submit-select-recipients.service.test.js
  test/validators/notices/setup/select-recipients.validator.test.js
Labels: enhancement

#2222 Update notices setup recipients
  app/presenters/notices/setup/check.presenter.js
  app/presenters/notices/setup/contact.presenter.js
  app/services/notices/setup/check.service.js
  app/services/notices/setup/recipients.service.js
  app/services/notices/setup/submit-check.service.js
  test/presenters/notices/setup/contact.presenter.test.js
  test/services/notices/setup/check.service.test.js
  test/services/notices/setup/recipients.service.test.js
Labels: enhancement

#2224 Update notices setup select recipients to handle selected recipients
  app/presenters/notices/setup/select-recipients.presenter.js
  app/services/notices/setup/submit-select-recipients.service.js
  test/presenters/notices/setup/select-recipients.presenter.test.js
  test/services/notices/setup/submit-select-recipients.service.test.js
Labels: enhancement
