Repository DEFRA/water-abstraction-system, pull requests merged in 2025-10, with the labels that each got.

#2466 Add preview return form to the communications tab
  app/controllers/notifications.controller.js
  app/presenters/licences/view-licence-communications.presenter.js
  app/presenters/notifications/view-notification.presenter.js
  app/routes/notifications.routes.js
  app/services/notifications/download-notification.service.js
  app/services/notifications/fetch-notification-download.service.js
  app/services/notifications/fetch-notification.service.js
  app/views/licences/tabs/communications.njk
  app/views/notifications/view.njk
  test/controllers/notifications.controller.test.js
  test/fixtures/notifications.fixture.js
  test/presenters/licences/view-licence-communications.presenter.test.js
  test/presenters/notifications/view-notification.presenter.test.js
  test/services/notifications/download-notification.service.test.js
  test/services/notifications/fetch-notification-download.service.test.js
  test/services/notifications/fetch-notification.service.test.js
  test/services/notifications/view-notification.service.test.js
Labels: enhancement

#2473 Update licence page to template standard
  app/presenters/licences/view-licence.presenter.js
  app/views/licences/view.njk
  test/presenters/licences/view-licence.presenter.test.js
  test/services/licences/view-licence.service.test.js
Labels: enhancement

#2474 Refactor the batch process to have a service for each notification type
  app/presenters/notices/setup/notify-update.presenter.js
  app/services/notices/setup/batch-notifications.service.js
  app/services/notices/setup/batch/send-email.service.js
  app/services/notices/setup/batch/send-letter.service.js
  app/services/notices/setup/batch/send-return-form.service.js
  test/fixtures/notify-response.fixture.js
  test/services/notices/setup/batch-notifications.service.test.js
  test/services/notices/setup/batch/send-email.service.test.js
  test/services/notices/setup/batch/send-letter.service.test.js
  test/services/notices/setup/batch/send-return-form.service.test.js
Labels: enhancement

#2470 Add `return_requirement_id` to returns
  app/models/return-log.model.js
  app/models/return-requirement.model.js
  app/services/return-logs/generate-return-log.service.js
  db/migrations/legacy/20221108006001_returns-returns.js
  db/migrations/public/20251002093242_alter-return-logs-view.js
  test/models/return-log.model.test.js
  test/models/return-requirement.model.test.js
  test/services/return-logs/generate-return-log.service.test.js
Labels: enhancement

#2012 View notice page presenter and view
  .env.example
  app/controllers/notices.controller.js
  app/models/event.model.js
  app/presenters/notices/index-notices.presenter.js
  app/presenters/notices/setup/confirmation.presenter.js
  app/presenters/notices/view-notice.presenter.js
  app/presenters/notices/view.presenter.js
  app/routes/notices.routes.js
  app/services/notices/fetch-notice.service.js
  app/services/notices/submit-view-notice.service.js
  app/services/notices/view-notice.service.js
  app/services/notices/view.service.js
  app/validators/notices/view.validator.js
  app/views/notices/setup/confirmation.njk
  app/views/notices/view.njk
  config/feature-flags.config.js
  test/controllers/notices.controller.test.js
  test/presenters/bill-runs/review/review-charge-element.presenter.test.js
  test/presenters/notices/index-notices.presenter.test.js
  test/presenters/notices/setup/confirmation.presenter.test.js
  test/presenters/notices/view-notice.presenter.test.js
  test/presenters/notices/view.presenter.test.js
  test/services/billing-accounts/change-address.service.test.js
  test/services/notices/fetch-notice.service.test.js
  test/services/notices/index-notices.service.test.js
  test/services/notices/setup/confirmation.service.test.js
  test/services/notices/submit-index-notices.service.test.js
  test/services/notices/submit-view-notice.service.test.js
  test/services/notices/view-notice.service.test.js
  test/services/notices/view.service.test.js
Labels: enhancement

#2481 Refactor notice setup returns period
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/returns-period/returns-period.presenter.js
  app/services/notices/setup/returns-period/submit-returns-period.service.js
  app/validators/notices/setup/returns-periods.validator.js
  app/views/notices/setup/returns-period.njk
  app/views/notices/setup/view-returns-period.njk
  test/presenters/notices/setup/returns-period/returns-period.presenter.test.js
  test/services/notices/setup/returns-period/returns-period.service.test.js
  test/services/notices/setup/returns-period/submit-returns-period.services.test.js
  test/validators/notices/setup/returns-period.validator.test.js
Labels: enhancement, housekeeping

#2478 Update model unit tests
  test/models/licence-supplementary-year.model.test.js
  test/models/licence-version-purpose-condition-type.model.test.js
  test/models/primary-purpose.model.test.js
  test/models/purpose.model.test.js
  test/models/region.model.test.js
  test/models/return-requirement-purpose.model.test.js
  test/models/return-submission-line.model.test.js
  test/models/review-charge-element-return.model.test.js
  test/models/review-charge-element.model.test.js
  test/models/review-charge-reference.model.test.js
  test/models/review-charge-version.model.test.js
  test/models/review-licence.model.test.js
  test/models/review-return.model.test.js
  test/models/scheduled-notification.model.test.js
  test/models/source.model.test.js
  test/models/transaction.model.test.js
  test/models/workflow.model.test.js
Labels: housekeeping

#2487 Migration - Add `overall_status` and `status_counts` columns to `events`
  app/models/event.model.js
  db/migrations/legacy/20221108007004_water-events.js
  db/migrations/public/20251007105036_alter-events-view.js
  test/services/jobs/notification-status/process-notification-status.service.test.js
  test/services/notices/setup/batch-notifications.service.test.js
  test/services/notices/setup/create-notice.service.test.js
  test/services/notices/setup/submit-check.service.test.js
  test/services/notices/setup/update-event.service.test.js
Labels: enhancement

#2484 Update notice type journey entry point
  app/controllers/notices-setup.controller.js
  app/controllers/notices.controller.js
  app/presenters/notices/index-notices.presenter.js
  app/presenters/notices/setup/licence.presenter.js
  app/presenters/notices/setup/returns-period/returns-period.presenter.js
  app/services/notices/index-notices.service.js
  app/services/notices/setup/initiate-session.service.js
  app/services/notices/submit-index-notices.service.js
  app/views/notices/index.njk
  test/presenters/notices/index-notices.presenter.test.js
  test/presenters/notices/setup/licence.presenter.test.js
  test/presenters/notices/setup/returns-period/returns-period.presenter.test.js
  test/services/notices/index-notices.service.test.js
  test/services/notices/setup/initiate-session.service.test.js
  test/services/notices/setup/licence.service.test.js
  test/services/notices/setup/returns-period/returns-period.service.test.js
  test/services/notices/setup/returns-period/submit-returns-period.services.test.js
  test/services/notices/setup/submit-licence.service.test.js
  test/services/notices/submit-index-notices.service.test.js
Labels: enhancement

#2492 Set quarterly flag when creating return logs
  app/services/return-logs/generate-return-log.service.js
  db/migrations/legacy/20221108006001_returns-returns.js
  db/migrations/public/20251008100115_alter-return-logs-view.js
  test/fixtures/return-requirements.fixture.js
  test/services/return-logs/generate-return-log.service.test.js
Labels: enhancement

#2490 Refactor 'return-forms' to 'paper-return' page
  app/controllers/notices-setup.controller.js
  app/presenters/notices/setup/paper-return.presenter.js
  app/routes/notices-setup.routes.js
  app/services/notices/setup/fetch-returns-due-by-licence-ref.service.js
  app/services/notices/setup/paper-return.service.js
  app/services/notices/setup/submit-notice-type.service.js
  app/services/notices/setup/submit-paper-return.service.js
  app/validators/notices/setup/paper-return.validator.js
  app/views/notices/setup/check-notice-type.njk
  app/views/notices/setup/paper-return.njk
  test/controllers/notices-setup.controller.test.js
  test/presenters/notices/setup/paper-return.presenter.test.js
  test/services/notices/setup/paper-return.service.test.js
  test/services/notices/setup/submit-notice-type.service.test.js
  test/services/notices/setup/submit-paper-return.service.test.js
  test/validators/notices/setup/paper-return.validator.test.js
Labels: enhancement
