Repository DEFRA/water-abstraction-system, pull requests merged in 2025-09, with the labels that each got.

#2322 Update download recipients to handle additional and selected recipients
  app/services/notices/setup/check.service.js
  app/services/notices/setup/download-recipients.service.js
  app/services/notices/setup/fetch-download-recipients.service.js
  app/services/notices/setup/fetch-recipients.service.js
  app/services/notices/setup/fetch-returns-recipients.service.js
  app/services/notices/setup/preview-return-forms.service.js
  app/services/notices/setup/preview/preview.service.js
  app/services/notices/setup/recipients.service.js
  app/services/notices/setup/select-recipients.service.js
  app/services/notices/setup/submit-check.service.js
  app/services/notices/setup/submit-select-recipients.service.js
  test/services/notices/setup/check.service.test.js
  test/services/notices/setup/fetch-download-recipients.service.test.js
  test/services/notices/setup/fetch-recipients.service.test.js
  test/services/notices/setup/fetch-returns-recipients.service.test.js
  test/services/notices/setup/preview-return-forms.service.test.js
  test/services/notices/setup/preview/preview.service.test.js
  test/services/notices/setup/recipients.service.test.js
  test/services/notices/setup/select-recipients.service.test.js
  test/services/notices/setup/submit-check.service.test.js
  test/services/notices/setup/submit-select-recipients.service.test.js
Labels: enhancement

#2344 Add request service to send a precompiled file to Notify
  app/requests/notify/create-precompiled-file.request.js
  test/requests/notify/create-precompiled-file.request.test.js
Labels: enhancement

#2346 Returns tab - No due date
  app/presenters/licences/view-licence-returns.presenter.js
  app/services/licences/fetch-licence-returns.service.js
  test/presenters/licences/view-licence-returns.presenter.test.js
  test/services/licences/fetch-licence-returns.service.test.js
Labels: enhancement

#2347 Update notifications 4 auto-populated created_at
  db/migrations/legacy/20221108007033_water-scheduled-notification.js
  test/support/helpers/notification.helper.js
  test/support/helpers/scheduled-notification.helper.js
Labels: housekeeping

#2348 Add recipient download specific variables to additional contacts
  app/services/notices/setup/add-recipient.service.js
  app/services/notices/setup/submit-contact-type.service.js
  test/services/notices/setup/add-recipient.service.test.js
  test/services/notices/setup/submit-contact-type.service.test.js
Labels: enhancement

#2350 Remove 'allRecipients' flag from recipients service
  app/presenters/notices/setup/select-recipients.presenter.js
  app/services/notices/setup/check.service.js
  app/services/notices/setup/download-recipients.service.js
  app/services/notices/setup/fetch-recipients.service.js
  app/services/notices/setup/recipients.service.js
  app/services/notices/setup/select-recipients.service.js
  app/services/notices/setup/submit-select-recipients.service.js
  test/presenters/notices/setup/select-recipients.presenter.test.js
  test/services/notices/setup/recipients.service.test.js
Labels: enhancement

#2349 View return log - fix status when no due date
  app/presenters/return-logs/base-return-logs.presenter.js
  test/presenters/return-logs/base-return-logs.presenter.test.js
Labels: enhancement

#2356 Amend error in layout and add new error formatter
  app/presenters/base.presenter.js
  app/views/layout.njk
  test/presenters/base.presenter.test.js
Labels: housekeeping

#2358 Refactor view notice page to template standard
  app/controllers/notices.controller.js
  app/presenters/notices/index-notices.presenter.js
  app/services/notices/index-notices.service.js
  app/services/notices/submit-index-notices.service.js
  app/views/notices/index.njk
  test/controllers/notices.controller.test.js
  test/presenters/notices/index-notices.presenter.test.js
  test/services/notices/index-notices.service.test.js
  test/services/notices/submit-index-notices.service.test.js
Labels: housekeeping

#2362 Refactor expected session object for address lookup
  app/controllers/notices-setup.controller.js
  app/presenters/address/base-address.presenter.js
  app/presenters/address/international.presenter.js
  app/presenters/address/manual.presenter.js
  app/presenters/address/postcode.presenter.js
  app/presenters/address/select.presenter.js
  app/presenters/notices/setup/check-notice-type.presenter.js
  app/routes/notices-setup.routes.js
  app/services/address/international.service.js
  app/services/address/manual.service.js
  app/services/address/postcode.service.js
  app/services/address/select.service.js
  app/services/address/submit-international.service.js
  app/services/address/submit-manual.service.js
  app/services/address/submit-postcode.service.js
  app/services/address/submit-select.service.js
  app/services/notices/setup/add-recipient.service.js
  app/services/notices/setup/initiate-session.service.js
  app/services/notices/setup/submit-check-notice-type.service.js
  app/views/address/international.njk
  app/views/address/manual.njk
  app/views/address/postcode.njk
  app/views/address/select.njk
  app/views/notices/setup/check-notice-type.njk
  test/controllers/address.controller.test.js
  test/controllers/notices-setup.controller.test.js
  test/presenters/address/base-address.presenter.test.js
  test/presenters/address/international.presenter.test.js
  test/presenters/address/manual.presenter.test.js
  test/presenters/address/postcode.presenter.test.js
  test/presenters/address/select.presenter.test.js
  test/presenters/notices/setup/check-notice-type.presenter.test.js
  test/presenters/return-logs/base-return-logs.presenter.test.js
  test/services/address/international.service.test.js
  test/services/address/manual.service.test.js
  test/services/address/postcode.service.test.js
  test/services/address/select.service.test.js
  test/services/address/submit-international.service.test.js
  test/services/address/submit-manual.service.test.js
  test/services/address/submit-postcode.service.test.js
  test/services/address/submit-select.service.test.js
  test/services/notices/setup/add-recipient.service.test.js
  test/services/notices/setup/check-notice-type.service.test.js
  test/services/notices/setup/initiate-session.service.test.js
  test/services/notices/setup/submit-check-notice-type.service.test.js
Labels: housekeeping

#2364 Update flash notification to support the updated layout
  app/lib/general.lib.js
  app/views/layout.njk
  app/views/monitoring-stations/view.njk
  app/views/notices/setup/abstraction-alerts/check-licence-matches.njk
  app/views/notices/setup/check-notice-type.njk
  app/views/notices/setup/check.njk
  app/views/return-logs/setup/check.njk
  app/views/return-versions/setup/check.njk
  app/views/users/profile-details.njk
  test/lib/general.lib.test.js
  test/services/licence-monitoring-station/setup/submit-check.service.test.js
  test/services/licence-monitoring-station/submit-remove.service.test.js
  test/services/notices/setup/abstraction-alerts/remove-threshold.service.test.js
  test/services/notices/setup/add-recipient.service.test.js
  test/services/notices/setup/submit-contact-type.service.test.js
  test/services/notices/setup/submit-licence.service.test.js
  test/services/notices/setup/submit-notice-type.service.test.js
  test/services/notices/setup/submit-returns-for-paper-forms.service.test.js
  test/services/notices/setup/submit-select-recipients.service.test.js
  test/services/return-logs/setup/delete-note.service.test.js
  test/services/return-logs/setup/submit-meter-details.service.test.js
  test/services/return-logs/setup/submit-meter-provided.service.test.js
  test/services/return-logs/setup/submit-multiple-entries.service.test.js
  test/services/return-logs/setup/submit-readings.service.test.js
  test/services/return-logs/setup/submit-received.service.test.js
  test/services/return-logs/setup/submit-reported.service.test.js
  test/services/return-logs/setup/submit-start-reading.service.test.js
  test/services/return-logs/setup/submit-units.service.test.js
  test/services/return-logs/setup/submit-volumes.service.test.js
  test/services/return-versions/setup/submit-abstraction-period.service.test.js
  test/services/return-versions/setup/submit-additional-submission-options.service.test.js
  test/services/return-versions/setup/submit-agreements-exceptions.service.test.js
  test/services/return-versions/setup/submit-frequency-collected.service.test.js
  test/services/return-versions/setup/submit-frequency-reported.service.test.js
  test/services/return-versions/setup/submit-no-returns-required.service.test.js
  test/services/return-versions/setup/submit-points.service.test.js
  test/services/return-versions/setup/submit-purpose.service.test.js
  test/services/return-versions/setup/submit-reason.service.test.js
  test/services/return-versions/setup/submit-returns-cycle.service.test.js
  test/services/return-versions/setup/submit-site-description.service.test.js
  test/services/return-versions/setup/submit-start-date.service.test.js
  test/services/users/submit-profile-details.service.test.js
Labels: housekeeping

#2376 Update tests to use generated reference codes
  test/fixtures/notices.fixture.js
  test/presenters/notices/setup/abstraction-alert-notifications.presenter.test.js
  test/presenters/notices/setup/cancel.presenter.test.js
  test/presenters/notices/setup/check.presenter.test.js
  test/presenters/notices/setup/confirmation.presenter.test.js
  test/presenters/notices/setup/notifications.presenter.test.js
  test/presenters/notices/setup/remove-licences.presenter.test.js
  test/presenters/notices/setup/select-recipients.presenter.test.js
  test/requests/notify/create-precompiled-file.request.test.js
  test/services/notices/setup/confirmation.service.test.js
  test/services/notices/setup/create-notice.service.test.js
  test/services/notices/setup/download-recipients.service.test.js
  test/services/notices/setup/select-recipients.service.test.js
  test/services/notices/setup/submit-select-recipients.service.test.js
  test/support/helpers/notification.helper.js
Labels: housekeeping

#2379 Add return forms download csv
  app/presenters/notices/setup/download-letter-recipients.presenter.js
  app/services/notices/setup/determine-notice-type.service.js
  app/services/notices/setup/download-recipients.service.js
  test/presenters/notices/setup/download-letter-recipients.presenter.test.js
  test/presenters/notices/setup/notice-type.presenter.test.js
  test/services/notices/setup/determine-notice-type.service.test.js
  test/services/notices/setup/download-recipients.service.test.js
  test/services/notices/setup/submit-check-notice-type.service.test.js
Labels: enhancement

#2380 Update scaffold view.njk template to use page content
  templates/presenter.js
  templates/presenter.test.js
  templates/submit.service.test.js
  templates/view.njk
Labels: enhancement, housekeeping

#2354 Fix last alert info in view lic. mon. station page
  app/controllers/monitoring-stations.controller.js
  app/presenters/monitoring-stations/licence.presenter.js
  app/presenters/monitoring-stations/view-licence.presenter.js
  app/services/monitoring-stations/fetch-licence-monitoring-stations.service.js
  app/services/monitoring-stations/fetch-licence-tag-details.service.js
  app/services/monitoring-stations/licence.service.js
  app/services/monitoring-stations/view-licence.service.js
  app/views/monitoring-stations/licence.njk
  test/controllers/monitoring-stations.controller.test.js
  test/presenters/monitoring-stations/licence.presenter.test.js
  test/presenters/monitoring-stations/view-licence.presenter.test.js
  test/services/monitoring-stations/fetch-licence-monitoring-stations.service.test.js
  test/services/monitoring-stations/fetch-licence-tag-details.service.test.js
  test/services/monitoring-stations/licence.service.test.js
  test/services/monitoring-stations/view-licence.service.test.js
Labels: bug

#2398 Add logic to create return forms notifications
  app/services/notices/setup/determine-return-forms.service.js
  test/services/notices/setup/determine-return-forms.service.test.js
Labels: enhancement

#2399 Clean up notice logic before adding return forms
  app/presenters/notices/setup/notify-update.presenter.js
  app/services/notices/setup/fetch-returns-due-by-licence-ref.service.js
  app/services/notices/setup/submit-check.service.js
  test/services/notices/setup/fetch-recipients.service.test.js
  test/services/notices/setup/fetch-returns-due-by-licence-ref.service.test.js
Labels: housekeeping

#2400 Add return forms to batch notifications
  app/services/notices/setup/batch-notifications.service.js
  app/services/notices/setup/determine-return-forms.service.js
  test/services/notices/setup/batch-notifications.service.test.js
  test/services/notices/setup/determine-return-forms.service.test.js
Labels: enhancement

#2401 Set return logs `updatedAt` when received or submitted
  app/services/return-logs/setup/submit-check.service.js
  test/services/return-logs/setup/submit-check.service.test.js
Labels: bug

#2411 Fix WAA being sent to old/removed contacts
  app/services/notices/setup/fetch-abstraction-alert-recipients.service.js
  test/services/notices/setup/fetch-abstraction-alert-recipients.service.test.js
Labels: bug

#2406 Add presenter to format the return forms data into a notification
  app/presenters/notices/setup/prepare-return-forms.presenter.js
  app/presenters/notices/setup/return-forms-notification.presenter.js
  app/services/notices/setup/determine-return-forms.service.js
  app/services/notices/setup/fetch-returns-due-by-licence-ref.service.js
  test/fixtures/return-logs.fixture.js
  test/presenters/notices/setup/prepare-return-forms.presenter.test.js
  test/presenters/notices/setup/return-forms-notification.presenter.test.js
  test/services/notices/setup/determine-return-forms.service.test.js
  test/services/notices/setup/fetch-returns-due-by-licence-ref.service.test.js
  test/services/notices/setup/prepare-return-forms.service.test.js
  test/services/notices/setup/preview-return-forms.service.test.js
Labels: enhancement

#2415 Fix notification-status job for accepted letters
  .github/workflows/ci.yml
  app/presenters/jobs/notifications/notify-status.presenter.js
  app/services/jobs/notification-status/fetch-notifications.service.js
  test/presenters/jobs/notifications/notify-status.presenter.test.js
  test/services/jobs/notification-status/fetch-notifications.service.test.js
Labels: bug

#2416 Fix missing notifications in licence comms tab
  app/presenters/licences/view-licence-communications.presenter.js
  app/services/licences/fetch-communications.service.js
  app/services/licences/view-licence-communications.service.js
  test/presenters/licences/view-licence-communications.presenter.test.js
  test/services/licences/fetch-communications.service.test.js
Labels: bug

#2414 Update the notification model to convert 'licences' to json
  app/models/notification.model.js
  app/presenters/notices/setup/abstraction-alert-notifications.presenter.js
  app/presenters/notices/setup/notifications.presenter.js
  app/presenters/notices/setup/return-forms-notification.presenter.js
  test/presenters/notices/setup/abstraction-alert-notifications.presenter.test.js
  test/presenters/notices/setup/notifications.presenter.test.js
  test/presenters/notices/setup/return-forms-notification.presenter.test.js
  test/services/licences/fetch-communications.service.test.js
  test/services/notices/setup/determine-return-forms.service.test.js
Labels: enhancement

#2422 Add new today() helper to GeneralLib
  app/lib/general.lib.js
  app/presenters/base.presenter.js
  app/presenters/licences/view-licence.presenter.js
  app/presenters/notices/setup/returns-period/returns-period.presenter.js
  app/presenters/return-logs/setup/received.presenter.js
  app/services/jobs/licence-updates/fetch-licence-updates.service.js
  app/services/jobs/notification-status/fetch-notifications.service.js
  app/services/return-logs/setup/submit-received.service.js
  test/lib/general.lib.test.js
  test/lib/return-cycle-dates.lib.test.js
  test/presenters/licences/view-licence-summary.presenter.test.js
  test/presenters/licences/view-licence.presenter.test.js
  test/presenters/return-logs/setup/received.presenter.test.js
  test/presenters/return-logs/view-return-log.presenter.test.js
  test/services/jobs/clean/clean-expired-sessions.service.test.js
  test/services/jobs/licence-updates/fetch-licence-updates.service.test.js
  test/services/jobs/notification-status/fetch-notifications.service.test.js
  test/services/return-logs/create-return-logs.service.test.js
  test/services/return-logs/generate-return-log.service.test.js
  test/services/return-logs/setup/submit-received.service.test.js
  test/validators/notices/index.validator.test.js
  test/validators/return-logs/setup/received-date.validator.test.js
Labels: housekeeping

#2418 Allow ended 'Not due yet' returns to be submitted
  app/presenters/return-logs/view-return-log.presenter.js
  test/presenters/return-logs/view-return-log.presenter.test.js
Labels: enhancement

#2423 Fix date filter in view notices excluding records
  app/services/notices/fetch-notices.service.js
  test/services/notices/fetch-notices.service.test.js
Labels: bug

#2431 Prevent selecting default abstraction period outside of return period
  app/presenters/return-logs/setup/period-used.presenter.js
  app/views/return-logs/setup/period-used.njk
  test/presenters/return-logs/setup/period-used.presenter.test.js
  test/services/return-logs/setup/period-used.service.test.js
  test/services/return-logs/setup/submit-period-used.service.test.js
Labels: bug

#2433 Return logs - Persist zero quantities
  app/services/return-logs/setup/create-return-lines.service.js
  app/services/return-logs/setup/initiate-session.service.js
  test/services/return-logs/setup/create-return-lines.service.test.js
  test/services/return-logs/setup/initiate-session.service.test.js
Labels: bug

#2442 Refactor 'end' process in setup notice journey - create notifications before batching
  app/models/event.model.js
  app/presenters/notices/setup/create-notice.presenter.js
  app/services/notices/setup/batch-notifications.service.js
  app/services/notices/setup/determine-notifications.service.js
  app/services/notices/setup/submit-check.service.js
  test/presenters/notices/setup/create-notice.presenter.test.js
  test/services/notices/setup/batch-notifications.service.test.js
  test/services/notices/setup/determine-notifications.service.test.js
  test/services/notices/setup/submit-check.service.test.js
Labels: enhancement

#2443 Refactor the reference code to only be used by the batch notification service
  app/presenters/notices/setup/abstraction-alert-notifications.presenter.js
  app/presenters/notices/setup/notifications.presenter.js
  app/presenters/notices/setup/preview/preview.presenter.js
  app/presenters/notices/setup/return-forms-notification.presenter.js
  app/services/notices/setup/batch-notifications.service.js
  app/services/notices/setup/determine-return-forms.service.js
  app/services/notices/setup/preview/preview.service.js
  app/services/notices/setup/submit-check.service.js
  test/presenters/notices/setup/abstraction-alert-notifications.presenter.test.js
  test/presenters/notices/setup/notifications.presenter.test.js
  test/presenters/notices/setup/preview/preview.presenter.test.js
  test/presenters/notices/setup/return-forms-notification.presenter.test.js
  test/services/notices/setup/batch-notifications.service.test.js
  test/services/notices/setup/determine-notifications.service.test.js
  test/services/notices/setup/determine-return-forms.service.test.js
Labels: enhancement

#2447 Fix digitise user role seeding and update tests
  test/models/role.model.test.js
  test/models/user-role.model.test.js
  test/models/user.model.test.js
  test/services/idm/fetch-user-roles-and-groups.service.test.js
  test/support/database.js
  test/support/helpers/user-role.helper.js
Labels: bug

#2446 Add migration to add a template id column to notifications
  db/migrations/legacy/20221108007033_water-scheduled-notification.js
  db/migrations/public/20250925101514_alter-notifcations.js
  test/services/jobs/notification-status/process-notification-status.service.test.js
  test/services/jobs/notification-status/update-notifications.service.test.js
  test/services/notices/setup/batch-notifications.service.test.js
  test/services/notices/setup/create-notifications.service.test.js
Labels: enhancement

#2440 Prevent empty return submissions
  app/controllers/return-logs-setup.controller.js
  app/presenters/base.presenter.js
  app/presenters/return-logs/setup/check.presenter.js
  app/services/return-logs/setup/submit-check.service.js
  app/validators/return-logs/setup/check.validator.js
  app/views/return-logs/setup/check.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/check.presenter.test.js
  test/services/return-logs/setup/check.service.test.js
  test/services/return-logs/setup/submit-check.service.test.js
  test/validators/return-logs/setup/check.validator.test.js
Labels: bug

#2283 Migrate Manage page
  .env.example
  app/controllers/manage.controller.js
  app/plugins/router.plugin.js
  app/plugins/views.plugin.js
  app/presenters/manage/manage.presenter.js
  app/routes/manage.routes.js
  app/services/manage/view-manage.service.js
  app/views/includes/nav-bar.njk
  app/views/manage/manage.njk
  config/feature-flags.config.js
  test/controllers/manage.controller.test.js
  test/presenters/manage/manage.presenter.test.js
  test/services/manage/view-manage.service.test.js
Labels: enhancement

#2450 Add migration to add a PDF column to notifications
  db/migrations/legacy/20221108007033_water-scheduled-notification.js
  db/migrations/public/20250925134813_alter-notifications.js
  test/services/jobs/notification-status/process-notification-status.service.test.js
  test/services/jobs/notification-status/update-notifications.service.test.js
  test/services/notices/setup/batch-notifications.service.test.js
  test/services/notices/setup/create-notifications.service.test.js
Labels: enhancement

#2444 Implement new OPEN return log status
  app/presenters/base.presenter.js
  app/presenters/return-logs/view-return-log.presenter.js
  app/views/macros/return-status-tag.njk
  test/presenters/base.presenter.test.js
  test/presenters/licences/view-licence-returns.presenter.test.js
  test/support/general.js
Labels: enhancement

#2452 Determine relevant lic vers where start date same
  app/services/return-versions/setup/fetch-relevant-licence-version.service.js
  test/services/return-versions/setup/fetch-relevant-licence-version.service.test.js
Labels: bug

#2451 Add an update notifications service
  app/services/notices/setup/record-notify-send-results.service.js
  test/services/notices/setup/record-notify-send-results.service.test.js
Labels: enhancement

#2453 Update create notifications test
  test/services/notices/setup/create-notifications.service.test.js
Labels: enhancement

#2413 Refactor abstraction period pages to new standard
  app/presenters/licence-monitoring-station/setup/abstraction-period.presenter.js
  app/presenters/return-versions/setup/abstraction-period.presenter.js
  app/services/licence-monitoring-station/setup/submit-abstraction-period.service.js
  app/services/return-versions/setup/check/generate-return-version-requirements.service.js
  app/services/return-versions/setup/submit-abstraction-period.service.js
  app/validators/abstraction-period.validator.js
  app/views/licence-monitoring-station/setup/abstraction-period.njk
  app/views/return-versions/setup/abstraction-period.njk
  test/controllers/licence-monitoring-station-setup.controller.test.js
  test/presenters/licence-monitoring-station/setup/abstraction-period.presenter.test.js
  test/presenters/return-versions/setup/abstraction-period.presenter.test.js
  test/services/licence-monitoring-station/setup/abstraction-period.service.test.js
  test/services/licence-monitoring-station/setup/submit-abstraction-period.service.test.js
  test/services/return-versions/setup/abstraction-period.service.test.js
  test/services/return-versions/setup/check/generate-return-version-requirements.service.test.js
  test/services/return-versions/setup/submit-abstraction-period.service.test.js
  test/validators/abstraction-period.validator.test.js
Labels: housekeeping

#2449 Bugs creating return submissions
  app/presenters/return-logs/base-return-logs.presenter.js
  app/presenters/return-logs/setup/check.presenter.js
  app/presenters/return-logs/setup/readings.presenter.js
  app/presenters/return-logs/setup/volumes.presenter.js
  app/services/return-logs/setup/create-return-lines.service.js
  test/presenters/return-logs/setup/check.presenter.test.js
  test/presenters/return-logs/setup/readings.presenter.test.js
  test/presenters/return-logs/setup/volumes.presenter.test.js
  test/services/return-logs/setup/create-return-lines.service.test.js
  test/services/return-logs/setup/readings.service.test.js
  test/services/return-logs/setup/volumes.service.test.js
Labels: bug

#2456 Updated sending notification to save / fetch and update
  app/presenters/notices/setup/return-forms-notification.presenter.js
  app/services/notices/setup/batch-notifications.service.js
  app/services/notices/setup/create-notifications.service.js
  app/services/notices/setup/submit-check.service.js
  test/presenters/notices/setup/return-forms-notification.presenter.test.js
  test/services/notices/setup/batch-notifications.service.test.js
  test/services/notices/setup/determine-return-forms.service.test.js
  test/services/notices/setup/submit-check.service.test.js
Labels: enhancement
