Repository DEFRA/water-abstraction-system, pull requests merged in 2025-01, with the labels that each got.

#1592 Move return-logs-edit into return-logs folder
  app/controllers/return-logs-edit.controller.js
  app/controllers/return-logs-setup.controller.js
  app/plugins/router.plugin.js
  app/routes/return-logs-edit.routes.js
  app/routes/return-logs-setup.routes.js
  app/services/return-logs/setup/initiate-session.service.js
  test/controllers/return-logs-setup.controller.test.js
  test/services/return-logs/setup/initiate-session.service.test.js
Labels: housekeeping

#1600 Move licence-changes to endpoint and split work
  .env.example
  app/controllers/jobs.controller.js
  app/controllers/licences-end-dates.controller.js
  app/models/licence-end-date-change.model.js
  app/models/licence.model.js
  app/plugins/router.plugin.js
  app/routes/jobs.routes.js
  app/routes/licences-end-dates.routes.js
  app/services/data/load/load.service.js
  app/services/data/tear-down/water-schema.service.js
  app/services/jobs/licence-changes/process-licence.service.js
  app/services/licences/end-dates/check-all-licence-end-dates.service.js
  app/services/licences/end-dates/check-licence-end-dates.service.js
  app/services/licences/end-dates/determine-earliest-licence-changed-date.service.js
  app/services/licences/end-dates/fetch-licences.service.js
  app/services/licences/end-dates/process-licence-end-date-changes.service.js
  config/licences.config.js
  db/migrations/legacy/20221108007049_water-licence-end-date-changes.js
  db/migrations/public/20250105170151_create-licence-end-date-changes-view.js
  test/controllers/jobs.controller.test.js
  test/controllers/licences-end-dates.controller.test.js
  test/models/licence-end-date-change.model.test.js
  test/models/licence.model.test.js
  test/services/jobs/licence-changes/process-licence.service.test.js
  test/services/licences/end-dates/check-all-licence-end-dates.service.test.js
  test/services/licences/end-dates/check-licence-end-dates.service.test.js
  test/services/licences/end-dates/determine-earliest-licence-changed-date.service.test.js
  test/services/licences/end-dates/process-licence-end-date-changes.service.test.js
  test/support/helpers/licence-end-date-change.helper.js
Labels: housekeeping

#1532 Migrate abstraction conditions view page
  app/controllers/licences.controller.js
  app/presenters/licences/view-licence-conditions.presenter.js
  app/presenters/licences/view-licence-summary.presenter.js
  app/routes/licence.routes.js
  app/services/licences/fetch-licence-conditions.service.js
  app/services/licences/view-licence-conditions.service.js
  app/views/licences/conditions.njk
  app/views/licences/tabs/summary.njk
  config/feature-flags.config.js
  test/controllers/licences.controller.test.js
  test/fixtures/licences.fixture.js
  test/presenters/licences/view-licence-conditions.presenter.test.js
  test/presenters/licences/view-licence-summary.presenter.test.js
  test/services/licences/fetch-licence-conditions.service.test.js
  test/services/licences/view-licence-conditions.service.test.js
  test/services/licences/view-licence-summary.service.test.js
Labels: enhancement

#1604 Add notification review initial page
  app/controllers/notifications-setup.controller.js
  app/routes/notifications-setup.routes.js
  app/services/notifications/setup/review.service.js
  app/services/notifications/setup/submit-returns-period.service.js
  app/views/notifications/setup/review.njk
  test/controllers/notifications-setup.controller.test.js
  test/services/notifications/setup/review.services.test.js
  test/services/notifications/setup/submit-returns-period.services.test.js
Labels: enhancement

#1602 Return Logs setup received date
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/setup/received.presenter.js
  app/routes/return-logs-setup.routes.js
  app/services/return-logs/setup/received.service.js
  app/services/return-logs/setup/submit-received.service.js
  app/validators/return-logs/setup/received-date.validator.js
  app/views/return-logs/setup/received.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/received.presenter.test.js
  test/services/return-logs/setup/received.service.test.js
  test/services/return-logs/setup/submit-received.service.test.js
  test/validators/return-logs/setup/received-date.validator.test.js
Labels: enhancement

#1608 Fix two-part tariff bill runs time out error
  app/services/bill-runs/two-part-tariff/generate-bill-run.service.js
Labels: bug

#1607 Return Logs setup reported page
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/setup/reported.presenter.js
  app/routes/return-logs-setup.routes.js
  app/services/return-logs/setup/reported.service.js
  app/services/return-logs/setup/submit-reported.service.js
  app/validators/return-logs/setup/reported.validator.js
  app/views/return-logs/setup/reported.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/reported.presenter.test.js
  test/services/return-logs/setup/reported.service.test.js
  test/services/return-logs/setup/submit-reported.service.test.js
  test/validators/return-logs/setup/reported.validator.test.js
Labels: enhancement

#1616 Mark for supplementary billing charge version bug
  app/services/licences/supplementary/determine-charge-version-flags.service.js
  test/services/licences/supplementary/determine-charge-version-flags.service.test.js
Labels: bug

#1612 Return Logs setup units page
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/setup/units.presenter.js
  app/routes/return-logs-setup.routes.js
  app/services/return-logs/setup/submit-units.service.js
  app/services/return-logs/setup/units.service.js
  app/validators/return-logs/setup/units.validator.js
  app/views/return-logs/setup/units.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/units.presenter.test.js
  test/services/return-logs/setup/submit-units.service.test.js
  test/services/return-logs/setup/units.service.test.js
  test/validators/return-logs/setup/units.validator.test.js
Labels: enhancement

#1570 What do you want to do with this return?
  .env.example
  app/controllers/return-logs-setup.controller.js
  app/presenters/bill-runs/review/base-review.presenter.js
  app/presenters/licences/view-licence-returns.presenter.js
  app/presenters/return-logs/setup/start.presenter.js
  app/routes/return-logs-setup.routes.js
  app/services/return-logs/setup/initiate-session.service.js
  app/services/return-logs/setup/start.service.js
  app/services/return-logs/setup/submit-start.service.js
  app/validators/return-logs/setup/start.validator.js
  app/views/return-logs/setup/start.njk
  config/feature-flags.config.js
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/bill-runs/review/base-review.presenter.test.js
  test/presenters/licences/view-licence-returns.presenter.test.js
  test/presenters/return-logs/setup/start.presenter.test.js
  test/services/return-logs/setup/initiate-session.service.test.js
  test/services/return-logs/setup/start.service.test.js
  test/services/return-logs/setup/submit-start.service.test.js
  test/validators/return-logs/setup/start.validator.test.js
Labels: enhancement

#1617 Update controllers to new pageTitle and navBar convention
  app/controllers/bill-licences.controller.js
  app/controllers/bill-runs-review.controller.js
  app/presenters/bill-licences/view-bill-licence.presenter.js
  app/presenters/bill-runs/review/authorised.presenter.js
  app/presenters/bill-runs/review/edit.presenter.js
  app/presenters/bill-runs/review/factors.presenter.js
  app/presenters/bill-runs/review/review-charge-element.presenter.js
  app/presenters/bill-runs/review/review-charge-reference.presenter.js
  app/services/bill-licences/remove-bill-licence.service.js
  app/services/bill-licences/view-bill-licence.service.js
  app/services/bill-runs/review/authorised.service.js
  app/services/bill-runs/review/edit.service.js
  app/services/bill-runs/review/factors.service.js
  app/services/bill-runs/review/remove.service.js
  app/services/bill-runs/review/review-bill-run.service.js
  app/services/bill-runs/review/review-charge-element.service.js
  app/services/bill-runs/review/review-charge-reference.service.js
  app/services/bill-runs/review/review-licence.service.js
  app/services/bill-runs/review/submit-authorised.service.js
  app/services/bill-runs/review/submit-edit.service.js
  app/services/bill-runs/review/submit-factors.service.js
  test/controllers/bill-licences.controller.test.js
  test/presenters/bill-licences/view-bill-licence.presenter.test.js
  test/presenters/bill-runs/review/authorised.presenter.test.js
  test/presenters/bill-runs/review/edit.presenter.test.js
  test/presenters/bill-runs/review/factors.presenter.test.js
  test/presenters/bill-runs/review/review-charge-element.presenter.test.js
  test/presenters/bill-runs/review/review-charge-reference.presenter.test.js
  test/services/bill-licences/remove-bill-licence.service.test.js
  test/services/bill-licences/view-bill-licence.service.test.js
  test/services/bill-runs/review/authorised.service.test.js
  test/services/bill-runs/review/edit.service.test.js
  test/services/bill-runs/review/factors.service.test.js
  test/services/bill-runs/review/remove.service.test.js
  test/services/bill-runs/review/review-charge-element.service.test.js
  test/services/bill-runs/review/review-charge-reference.service.test.js
  test/services/bill-runs/review/review-licence.service.test.js
  test/services/bill-runs/review/submit-authorised.service.test.js
  test/services/bill-runs/review/submit-edit.service.test.js
  test/services/bill-runs/review/submit-factors.service.test.js
Labels: housekeeping

#1620 Update controllers to new pageTitle and navBar convention
  app/controllers/bill-runs-setup.controller.js
  app/controllers/bill-runs.controller.js
  app/presenters/bill-runs/view-cancel-bill-run.presenter.js
  app/presenters/bill-runs/view-send-bill-run.presenter.js
  app/services/bill-runs/cancel/view-cancel-bill-run.service.js
  app/services/bill-runs/index-bill-runs.service.js
  app/services/bill-runs/send/view-send-bill-run.service.js
  app/services/bill-runs/setup/check.service.js
  app/services/bill-runs/setup/no-licences.service.js
  app/services/bill-runs/setup/region.service.js
  app/services/bill-runs/setup/season.service.js
  app/services/bill-runs/setup/submit-check.service.js
  app/services/bill-runs/setup/submit-region.service.js
  app/services/bill-runs/setup/submit-season.service.js
  app/services/bill-runs/setup/submit-type.service.js
  app/services/bill-runs/setup/submit-year.service.js
  app/services/bill-runs/setup/type.service.js
  app/services/bill-runs/setup/year.service.js
  app/services/bill-runs/view-bill-run.service.js
  test/presenters/bill-runs/view-cancel-bill-run.presenter.test.js
  test/presenters/bill-runs/view-send-bill-run.presenter.test.js
  test/services/bill-runs/cancel/view-cancel-bill-run.service.test.js
  test/services/bill-runs/send/view-send-bill-run.service.test.js
  test/services/bill-runs/setup/check.service.test.js
  test/services/bill-runs/setup/no-licences.service.test.js
  test/services/bill-runs/setup/region.service.test.js
  test/services/bill-runs/setup/season.service.test.js
  test/services/bill-runs/setup/submit-check.service.test.js
  test/services/bill-runs/setup/submit-region.service.test.js
  test/services/bill-runs/setup/submit-season.service.test.js
  test/services/bill-runs/setup/submit-type.service.test.js
  test/services/bill-runs/setup/submit-year.service.test.js
  test/services/bill-runs/setup/type.service.test.js
  test/services/bill-runs/setup/year.service.test.js
  test/services/bill-runs/view-bill-run.service.test.js
Labels: housekeeping

#1625 Fix return received validation message
  app/validators/return-logs/setup/received-date.validator.js
  test/validators/return-logs/setup/received-date.validator.test.js
Labels: bug

#1621 Cruikshanks latest changes to the view return log
  app/controllers/return-logs.controller.js
  app/presenters/bill-runs/review/base-review.presenter.js
  app/presenters/licences/view-licence-returns.presenter.js
  app/presenters/return-logs/base-return-logs.presenter.js
  app/presenters/return-logs/view-return-log.presenter.js
  app/services/return-logs/fetch-return-log.service.js
  app/views/macros/return-log-status-tag.njk
  app/views/return-logs/view.njk
Labels: do not merge

#1628 Fix when the "Record receipt" option is displayed
  app/presenters/return-logs/setup/start.presenter.js
  app/services/return-logs/setup/initiate-session.service.js
  app/views/return-logs/setup/start.njk
  test/presenters/return-logs/setup/start.presenter.test.js
  test/services/return-logs/setup/initiate-session.service.test.js
  test/services/return-logs/setup/start.service.test.js
  test/services/return-logs/setup/submit-start.service.test.js
Labels: bug

#1627 Update controllers to new pageTitle and navBar convention
  app/controllers/bills.controller.js
  app/controllers/data.controller.js
  app/controllers/health.controller.js
  app/controllers/licences.controller.js
  app/controllers/monitoring-stations.controller.js
  app/controllers/notifications-setup.controller.js
  app/controllers/return-logs-setup.controller.js
  app/controllers/return-versions-setup.controller.js
  app/controllers/return-versions.controller.js
  app/presenters/bills/view-bill.presenter.js
  app/presenters/licences/supplementary/mark-for-supplementary-billing.presenter.js
  app/services/bills/remove-bill.service.js
  app/services/bills/view-bill.service.js
  app/services/data/deduplicate/submit-deduplicate.service.js
  app/services/health/info.service.js
  app/services/licences/supplementary/mark-for-supplementary-billing.service.js
  app/services/licences/supplementary/marked-for-supplementary-billing.service.js
  test/controllers/bills.controller.test.js
  test/controllers/licences.controller.test.js
  test/presenters/bills/view-bill.presenter.test.js
  test/presenters/licences/supplementary/mark-for-supplementary-billing.presenter.test.js
  test/services/bills/remove-bill.service.test.js
  test/services/bills/view-bill.service.test.js
  test/services/licences/supplementary/mark-for-supplementary-billing.service.test.js
  test/services/licences/supplementary/marked-for-supplementary-billing.service.test.js
Labels: housekeeping

#1626 Tidy up return logs setup journey
  app/presenters/return-logs/setup/meter-provided.presenter.js
  app/presenters/return-logs/setup/received.presenter.js
  app/presenters/return-logs/setup/reported.presenter.js
  app/presenters/return-logs/setup/units.presenter.js
  test/presenters/return-logs/setup/meter-provided.presenter.test.js
  test/presenters/return-logs/setup/received.presenter.test.js
  test/presenters/return-logs/setup/reported.presenter.test.js
  test/presenters/return-logs/setup/units.presenter.test.js
Labels: housekeeping

#1630 Refactor newLine macro
  app/views/licences/conditions.njk
  app/views/licences/purposes.njk
  app/views/macros/new-line-array-items.njk
  app/views/return-versions/setup/check.njk
  app/views/return-versions/view.njk
Labels: enhancement

#1635 Rearrange return log setup routes
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/setup/received.presenter.js
  app/presenters/return-logs/setup/reported.presenter.js
  app/presenters/return-logs/setup/start.presenter.js
  app/views/return-logs/setup/start.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/received.presenter.test.js
  test/presenters/return-logs/setup/reported.presenter.test.js
  test/presenters/return-logs/setup/start.presenter.test.js
  test/services/return-logs/setup/received.service.test.js
  test/services/return-logs/setup/reported.service.test.js
  test/services/return-logs/setup/start.service.test.js
  test/services/return-logs/setup/submit-received.service.test.js
  test/services/return-logs/setup/submit-reported.service.test.js
  test/services/return-logs/setup/submit-start.service.test.js
Labels: housekeeping

#1636 Replace `==` in the views with `===`
  app/views/bill-runs/index.njk
  app/views/bill-runs/review/review-licence.njk
  app/views/bill-runs/setup/region.njk
  app/views/bill-runs/setup/season.njk
  app/views/bill-runs/setup/type.njk
  app/views/bill-runs/view.njk
  app/views/licences/history.njk
  app/views/licences/tabs/bills.njk
  app/views/licences/tabs/communications.njk
  app/views/licences/tabs/set-up.njk
  app/views/return-logs/setup/meter-provided.njk
  app/views/return-logs/setup/received.njk
  app/views/return-logs/setup/reported.njk
  app/views/return-logs/setup/units.njk
  app/views/return-versions/setup/no-returns-required.njk
  app/views/return-versions/setup/start-date.njk
  app/views/return-versions/view.njk
Labels: housekeeping

#1624 Add notification review data to page
  app/presenters/notifications/setup/review.presenter.js
  app/services/notifications/setup/fetch-recipients.service.js
  app/services/notifications/setup/returns-period.service.js
  app/services/notifications/setup/review.service.js
  app/views/notifications/setup/review.njk
  test/fixtures/recipients.fixtures.js
  test/presenters/notifications/setup/review.presenter.test.js
  test/services/licences/fetch-licence-contact-details.service.test.js
  test/services/notifications/setup/fetch-recipients.service.test.js
  test/services/notifications/setup/returns-period.service.test.js
  test/services/notifications/setup/review.service.test.js
  test/services/notifications/setup/review.services.test.js
  test/support/helpers/licence-document-header.helper.js
  test/support/seeders/recipients.seeder.js
Labels: enhancement

#1623 Return Logs setup - Meter details
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/setup/meter-details.presenter.js
  app/routes/return-logs-setup.routes.js
  app/services/bill-runs/review/submit-factors.service.js
  app/services/return-logs/setup/meter-details.service.js
  app/services/return-logs/setup/submit-meter-details.service.js
  app/validators/return-logs/setup/meter-details.validator.js
  app/views/return-logs/setup/meter-details.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/meter-details.presenter.test.js
  test/services/return-logs/setup/meter-details.service.test.js
  test/services/return-logs/setup/submit-meter-details.service.test.js
  test/services/return-logs/setup/submit-meter-provided.service.test.js
  test/validators/return-logs/setup/meter-details.validator.test.js
Labels: enhancement

#1639 Update "What do you want to do with this return?" page
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/setup/reported.presenter.js
  app/presenters/return-logs/setup/start.presenter.js
  app/presenters/return-logs/setup/submission.presenter.js
  app/routes/return-logs-setup.routes.js
  app/services/return-logs/setup/submission.service.js
  app/services/return-logs/setup/submit-submission.service.js
  app/validators/return-logs/setup/submission.validator.js
  app/views/return-logs/setup/start.njk
  app/views/return-logs/setup/submission.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/reported.presenter.test.js
  test/presenters/return-logs/setup/start.presenter.test.js
  test/presenters/return-logs/setup/submission.presenter.test.js
  test/services/return-logs/setup/reported.service.test.js
  test/services/return-logs/setup/start.service.test.js
  test/services/return-logs/setup/submission.service.test.js
  test/services/return-logs/setup/submit-reported.service.test.js
  test/services/return-logs/setup/submit-start.service.test.js
  test/services/return-logs/setup/submit-submission.service.test.js
  test/validators/return-logs/setup/submission.validator.test.js
Labels: enhancement

#1637 Remove duplicate recipients
  app/presenters/notifications/setup/review.presenter.js
  app/services/notifications/setup/dedupe-recipients.service.js
  app/services/notifications/setup/fetch-recipients.service.js
  app/services/notifications/setup/review.service.js
  app/views/notifications/setup/review.njk
  test/fixtures/recipients.fixtures.js
  test/presenters/notifications/setup/review.presenter.test.js
  test/services/notifications/setup/dedupe-recipients.service.test.js
  test/services/notifications/setup/fetch-recipients.service.test.js
  test/services/notifications/setup/review.service.test.js
Labels: enhancement

#1606 Add guidance view on entering multiple readings
  app/controllers/return-logs-setup.controller.js
  app/public/images/example-excel-01-min.png
  app/public/images/example-excel-02-min.png
  app/public/images/example-input-01-min.png
  app/routes/assets.routes.js
  app/routes/return-logs-setup.routes.js
  app/views/return-logs/setup/guidance.njk
  test/controllers/return-logs-setup.controller.test.js
Labels: enhancement

#1644 Fix megalitres content error return logs setup
  app/validators/return-logs/setup/units.validator.js
  app/views/return-logs/setup/units.njk
  test/presenters/return-logs/setup/units.presenter.test.js
  test/validators/return-logs/setup/units.validator.test.js
Labels: bug

#1646 Fix Notifications Returns period
  app/presenters/notifications/setup/returns-period.presenter.js
  test/presenters/notifications/setup/returns-period.presenter.test.js
Labels: bug

#1649 Fix how no abs period data in view rtn vers shown
  app/presenters/base.presenter.js
  app/presenters/return-versions/view.presenter.js
  test/presenters/base.presenter.test.js
  test/presenters/return-versions/view.presenter.test.js
  test/services/return-versions/view.service.test.js
Labels: bug

#1645 Add pagination to notification setup review
  app/controllers/notifications-setup.controller.js
  app/presenters/notifications/setup/review.presenter.js
  app/services/notifications/setup/review.service.js
  app/views/notifications/setup/review.njk
  test/presenters/notifications/setup/review.presenter.test.js
  test/services/notifications/setup/review.service.test.js
Labels: enhancement

#1642 Check return details - build page layout
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/setup/check.presenter.js
  app/routes/return-logs-setup.routes.js
  app/services/return-logs/setup/check.service.js
  app/views/return-logs/setup/check.njk
  app/views/return-logs/setup/guidance.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/check.presenter.test.js
  test/services/return-logs/setup/check.service.test.js
Labels: enhancement

#1655 Add custom serializers to improve app logging
  app/plugins/hapi-pino.plugin.js
  app/services/plugins/hapi-pino-serializers.service.js
  test/services/plugins/hapi-pino-serializers.service.test.js
Labels: housekeeping

#1654 Fix return log views page title size
  app/views/return-logs/setup/meter-details.njk
  app/views/return-logs/setup/meter-provided.njk
  app/views/return-logs/setup/received.njk
  app/views/return-logs/setup/reported.njk
  app/views/return-logs/setup/submission.njk
  app/views/return-logs/setup/units.njk
Labels: housekeeping

#1641 Return Logs setup - Single volume
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/setup/single-volume.presenter.js
  app/routes/return-logs-setup.routes.js
  app/services/return-logs/setup/single-volume.service.js
  app/services/return-logs/setup/submit-single-volume.service.js
  app/validators/return-logs/setup/single-volume.validator.js
  app/views/return-logs/setup/single-volume.njk
  test/controllers/return-logs-setup.controller.test.js
  test/presenters/return-logs/setup/single-volume.presenter.test.js
  test/services/return-logs/setup/single-volume.service.test.js
  test/services/return-logs/setup/submit-single-volume.service.test.js
  test/validators/return-logs/setup/single-volume.validator.test.js
Labels: enhancement

#1661 Add `notes` and `created_by` to `return_submissions`
  db/migrations/legacy/20221108006002_returns-versions.js
  db/migrations/public/20250127153338_alter-return-submissions-view.js
Labels: enhancement

#1663 Refactor licence contact details into CRM presenter
  app/presenters/crm.presenter.js
  app/presenters/licences/view-licence-contact-details.presenter.js
  test/presenters/crm.presenter.test.js
Labels: enhancement

#1653 Fix logging error when deleting a bill run
  app/services/bill-runs/cancel/delete-bill-run.service.js
Labels: bug

#1664 Refactor Notifications contacts
  app/presenters/notifications/setup/review.presenter.js
  app/services/notifications/setup/dedupe-recipients.service.js
  app/services/notifications/setup/determine-recipients.service.js
  app/services/notifications/setup/fetch-recipients.service.js
  app/services/notifications/setup/review.service.js
  test/fixtures/recipients.fixtures.js
  test/presenters/notifications/setup/review.presenter.test.js
  test/services/notifications/setup/dedupe-recipients.service.test.js
  test/services/notifications/setup/determine-recipients.service.test.js
  test/services/notifications/setup/fetch-recipients.service.test.js
  test/services/notifications/setup/review.service.test.js
Labels: enhancement

#1662 Add a note to return submissions
  app/controllers/return-logs-setup.controller.js
  app/presenters/return-logs/setup/note.presenter.js
  app/routes/return-logs-setup.routes.js
  app/services/return-logs/setup/check.service.js
  app/services/return-logs/setup/delete-note.service.js
  app/services/return-logs/setup/note.service.js
  app/services/return-logs/setup/submit-note.service.js
  app/validators/return-logs/setup/note.validator.js
  app/views/return-logs/setup/check.njk
  app/views/return-logs/setup/note.njk
  test/controllers/return-logs-setup.controller.test.js
  test/controllers/return-versions-setup.controller.test.js
  test/presenters/return-logs/setup/note.presenter.test.js
  test/services/return-logs/setup/check.service.test.js
  test/services/return-logs/setup/delete-note.service.test.js
  test/services/return-logs/setup/note.service.test.js
  test/services/return-logs/setup/submit-note.service.test.js
  test/validators/return-logs/setup/note.validator.test.js
Labels: enhancement

#1665 Sort Notifications recipients
  app/presenters/notifications/setup/review.presenter.js
  test/fixtures/recipients.fixtures.js
  test/presenters/notifications/setup/review.presenter.test.js
  test/services/notifications/setup/determine-recipients.service.test.js
Labels: enhancement

#1669 Update Licence entity role to Has Many Relation
  app/models/licence-document-header.model.js
  app/models/licence.model.js
  test/models/licence-document-header.model.test.js
  test/presenters/licences/view-licence.presenter.test.js
  test/services/licences/view-licence.service.test.js
Labels: enhancement

#1484 Create Completed Return Logs page
  app/controllers/return-logs.controller.js
  app/lib/static-lookups.lib.js
  app/models/return-submission.model.js
  app/plugins/router.plugin.js
  app/presenters/base.presenter.js
  app/presenters/bill-runs/review/base-review.presenter.js
  app/presenters/licences/view-licence-returns.presenter.js
  app/presenters/return-logs/base-return-logs.presenter.js
  app/presenters/return-logs/view-return-log.presenter.js
  app/routes/return-logs.routes.js
  app/services/return-logs/fetch-return-log.service.js
  app/services/return-logs/view-return-log.service.js
  app/views/return-logs/view.njk
  client/sass/application.scss
  test/controllers/return-logs.controller.test.js
  test/models/return-submission.model.test.js
  test/presenters/base.presenter.test.js
  test/presenters/bill-runs/review/base-review.presenter.test.js
  test/presenters/licences/view-licence-returns.presenter.test.js
  test/presenters/return-logs/base-return-logs.presenter.test.js
  test/presenters/return-logs/view-return-log.presenter.test.js
  test/services/return-logs/fetch-return-logs.service.test.js
  test/services/return-logs/view-return-log.service.test.js
  test/support/helpers/return-log.helper.js
Labels: enhancement

#1667 Add more contacts to licence contact details
  app/presenters/licences/view-licence-contact-details.presenter.js
  app/services/licences/fetch-licence-contact-details.service.js
  app/services/licences/view-licence-contact-details.service.js
  app/views/licences/licence-contact-details.njk
  test/presenters/licences/view-licence-contact-details.presenter.test.js
  test/services/licences/fetch-licence-contact-details.service.test.js
  test/services/licences/view-licence-contact-details.service.test.js
  test/services/notifications/setup/fetch-recipients.service.test.js
  test/support/seeders/licence-document-header.seeder.js
Labels: enhancement
